---
title: "Visualization Data Science"
author: "David Kane"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This documents provides an overview of our goals and tasks for April/May 2020. Edit it as you need to.

# Students

Maria
Beau
Debi
Rob


# Jobs

These are the possible jobs. There are at least 70 hours worth of work for each of them.

Data Maven: Maintain scripts which creates our data sets, adds them to our package, maintains that as well. Reads [*R Packages*](https://r-pkgs.org/). Creates a **PPBDS** package. (See [here](https://kjhealy.github.io/covdata/) for a nice example of a data-only package.) Someone must do this, but only one person.

Animators: Why not have [animations](https://gganimate.com/articles/gganimate.html) for almost everything? Check out [the ones](https://nickchk.com/causalgraphs.html) by Nick Huntington-Klein. His work is the main inspiration for this project. One showing how loess works. How logistic curve changes as the data changes. How regression lines can be made parallel and then have different slopes. Anscombe Quartet into a [dinosaur](https://blog.revolutionanalytics.com/2017/05/the-datasaurus-dozen.html). Lots of possibilities. Someone must do this. Could have two people on it, maybe even 3. Almost every figure should come with an animation. Why wouldn't it?

Book Builder: Make the book build nicely. Where does it go? How do we view it? How do we print it? Reads [*Bookdown*](https://bookdown.org/yihui/bookdown/). Makes the book look as clean as [Hands-On Machine Learning with R](https://github.com/koalaverse/homlr), which does the nicest job that I have seen in making clean Rmd go to clean html. I like the PDF version of Rafa's book available from Lean Pub. How hard is that to make?


Enhancer: Figure out which of April's cartoons we can use and put them in the book. Maybe collects lots of other cartoons and images. [xkcd](https://cran.r-project.org/package=RXKCD)? Videos [here](https://bookdown.org/yihui/rmarkdown/learnr-videos.html) and use knitr::include_url with embed/id? It is an on-line book, so space is no object!

Writer: There are a lot of words to write, especially new appendix items like Leamer, Tufte and others. See below for a description of changes to the Probability Chapter.



# Animation Resources


https://simplystatistics.org/2017/08/08/code-for-my-educational-gifs/
https://cran.r-project.org/package=TeachingDemos
https://github.com/daranzolin/d3rain
One interesting example at the bottom: https://sarahromanes.github.io/post/gganimate/

# Probability Chapter

Combine Bayes and Probability chapters. There is only enough material here form one chapter. I don't like the mash up of two chapters, from two different original sources. Two approaches: interweave the Bayesian stuff into the probability chapter or the reverse. I like the reverse. The Bayes chapter is nice. It just needs more probability placed into it. Indeed, on some dimensions the probability chapter is overkill, even after I deleted some stuff. Chapter is still called Probability but it becomes an appendix, I think. Should have all political sciency examples.

Maybe this one chapter uses decision trees as its central organizing metaphor. *Bayes Theorem: A Visual Introduction for Beginners* does a nice job of teaching Bayesian inference with decision trees. Works really well! And easy (?) to simulate. Maybe we do that? Fits naturally (?) into list-columns and map functions. A natural (?) way to teach/show unconditional, conditional and marginal probability. Leafs on the tree are the possible outcomes.

Meld the material on functions and purrr into the concepts in the Probability/Bayes Chapters. We are not changing, I think, many of the words in these chapters, most of which are quite good. Instead, we are using these topics as an excuse to provide more lessons in functions/purrr. Also, edit Bayes chapter to make sense after probability chapter. Consider adding in intuition from Bayes for Beginner Book, especially decision trees, which map nicely to our simulation approach. Probabity/Bayes chapter should discuss null model, testing and p-values. This would allow us to add a (simple!) list-column, map function example at the end, very similar to the one we use in class. 


# Bok Proposal

### Visualizing Data Science

There are a dozen or more data science courses at Harvard, scattered across our schools and departments. All seek to draw meaning from data. My project, "Visualizing Data Science," seeks to build a collection of open-source vignettes, each explaining a different aspect of data science in a pedagogically sophisticated way, almost always via the use of visualizations. My textbook, Preceptor's Primer for Bayesian Data Science, is a basic example of what is possible. See, for example, the appendices devoted to mapping and animation.  Working with students from the Bok Center, I hope to create dozens of these lessons, each freely available for use in other Harvard classes and around the world.


David Kane is the Preceptor in Statistical Methods and Mathematics in the Department of Government. His courses, Gov 1005: Data and Gov 1006: Models, are two of the highest-rated lecture courses at the College.






