---
title: "Functions"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tidyverse)
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```


## List-Columns and Map Functions


```{r quiz-1}

# Weave this into the chapter, paragraph for paragraph

quiz(
  question("Which of the following is true about list-columns?",
             answer("List columns, unlike lists, can contain vectors as elements in the list.", 
                    correct = TRUE),
             answer("Lists and list columns are synonyms."),
             answer("List columns can only contain values as elements in the list."),
             answer("R and RStudio are both IDEs"),
             allow_retry = TRUE
    ),
  question("Which of the following map functions is not using an anonymous function? ",
             answer("mutate(new = map_dbl(start, increment()))", 
                    correct = TRUE),
             answer("mutate(new = map_dbl(start, function(x) x + 1))"),
             answer("mutate(new = map_dbl(start, ~ . + 1))"),
             answer("mutate(new = map_dbl(start, ~ (. + 1)))"),
             allow_retry = FALSE
    )
)

# Tester comments

# Is this good enough? 



```

