<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>12.1 Logistic regression | Preceptor’s Primer for Bayesian Data Science</title>
  <meta name="description" content="12.1 Logistic regression | Preceptor’s Primer for Bayesian Data Science" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="12.1 Logistic regression | Preceptor’s Primer for Bayesian Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="davidkane9/PPBDS" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="12.1 Logistic regression | Preceptor’s Primer for Bayesian Data Science" />
  
  
  

<meta name="author" content="David Kane" />


<meta name="date" content="2020-05-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="classification.html"/>
<link rel="next" href="classification-and-regression-trees-cart.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="forward.html"><a href="forward.html"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="warning.html"><a href="warning.html"><i class="fa fa-check"></i>Warning</a></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="part-i.html"><a href="part-i.html"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="1" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>1</b> Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio.html"><a href="r-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="r-rstudio.html"><a href="r-rstudio.html#installing"><i class="fa fa-check"></i><b>1.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="r-rstudio.html"><a href="r-rstudio.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="code.html"><a href="code.html"><i class="fa fa-check"></i><b>1.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="code.html"><a href="code.html#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="1.2.2" data-path="code.html"><a href="code.html#messages"><i class="fa fa-check"></i><b>1.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="1.2.3" data-path="code.html"><a href="code.html#tips-code"><i class="fa fa-check"></i><b>1.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="packages.html"><a href="packages.html#package-installation"><i class="fa fa-check"></i><b>1.3.1</b> Package installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="packages.html"><a href="packages.html#package-loading"><i class="fa fa-check"></i><b>1.3.2</b> Package loading</a></li>
<li class="chapter" data-level="1.3.3" data-path="packages.html"><a href="packages.html#package-use"><i class="fa fa-check"></i><b>1.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="nycflights13.html"><a href="nycflights13.html"><i class="fa fa-check"></i><b>1.4</b> Explore your first datasets</a><ul>
<li class="chapter" data-level="1.4.1" data-path="nycflights13.html"><a href="nycflights13.html#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="nycflights13.html"><a href="nycflights13.html#flights-data-frame"><i class="fa fa-check"></i><b>1.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="1.4.3" data-path="nycflights13.html"><a href="nycflights13.html#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="1.4.4" data-path="nycflights13.html"><a href="nycflights13.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>1.4.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="1.4.5" data-path="nycflights13.html"><a href="nycflights13.html#help-files"><i class="fa fa-check"></i><b>1.4.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a><ul>
<li class="chapter" data-level="1.5.1" data-path="conclusion.html"><a href="conclusion.html#additional-resources"><i class="fa fa-check"></i><b>1.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html"><i class="fa fa-check"></i><b>1.6</b> The grammar of graphics</a><ul>
<li class="chapter" data-level="1.6.1" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#components-of-the-grammar"><i class="fa fa-check"></i><b>1.6.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="1.6.2" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#gapminder"><i class="fa fa-check"></i><b>1.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="1.6.3" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#other-components"><i class="fa fa-check"></i><b>1.6.3</b> Other components</a></li>
<li class="chapter" data-level="1.6.4" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#ggplot2-package"><i class="fa fa-check"></i><b>1.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>1.7</b> Scatterplots</a><ul>
<li class="chapter" data-level="1.7.1" data-path="scatterplots.html"><a href="scatterplots.html#geompoint"><i class="fa fa-check"></i><b>1.7.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="scatterplots.html"><a href="scatterplots.html#overplotting"><i class="fa fa-check"></i><b>1.7.2</b> Overplotting</a></li>
<li class="chapter" data-level="1.7.3" data-path="scatterplots.html"><a href="scatterplots.html#summary"><i class="fa fa-check"></i><b>1.7.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="linegraphs.html"><a href="linegraphs.html"><i class="fa fa-check"></i><b>1.8</b> Linegraphs</a><ul>
<li class="chapter" data-level="1.8.1" data-path="linegraphs.html"><a href="linegraphs.html#geomline"><i class="fa fa-check"></i><b>1.8.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="linegraphs.html"><a href="linegraphs.html#summary-1"><i class="fa fa-check"></i><b>1.8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="histograms.html"><a href="histograms.html"><i class="fa fa-check"></i><b>1.9</b> Histograms</a><ul>
<li class="chapter" data-level="1.9.1" data-path="histograms.html"><a href="histograms.html#geomhistogram"><i class="fa fa-check"></i><b>1.9.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="1.9.2" data-path="histograms.html"><a href="histograms.html#adjustbins"><i class="fa fa-check"></i><b>1.9.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="1.9.3" data-path="histograms.html"><a href="histograms.html#summary-2"><i class="fa fa-check"></i><b>1.9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="facets.html"><a href="facets.html"><i class="fa fa-check"></i><b>1.10</b> Facets</a></li>
<li class="chapter" data-level="1.11" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>1.11</b> Boxplots</a><ul>
<li class="chapter" data-level="1.11.1" data-path="boxplots.html"><a href="boxplots.html#geomboxplot"><i class="fa fa-check"></i><b>1.11.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="boxplots.html"><a href="boxplots.html#summary-3"><i class="fa fa-check"></i><b>1.11.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="geombar.html"><a href="geombar.html"><i class="fa fa-check"></i><b>1.12</b> Barplots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="geombar.html"><a href="geombar.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>1.12.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="1.12.2" data-path="geombar.html"><a href="geombar.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>1.12.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="1.12.3" data-path="geombar.html"><a href="geombar.html#two-categ-barplot"><i class="fa fa-check"></i><b>1.12.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="1.12.4" data-path="geombar.html"><a href="geombar.html#summary-4"><i class="fa fa-check"></i><b>1.12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>1.13</b> Conclusion</a><ul>
<li class="chapter" data-level="1.13.1" data-path="conclusion-1.html"><a href="conclusion-1.html#summary-table"><i class="fa fa-check"></i><b>1.13.1</b> Summary table</a></li>
<li class="chapter" data-level="1.13.2" data-path="conclusion-1.html"><a href="conclusion-1.html#function-argument-specification"><i class="fa fa-check"></i><b>1.13.2</b> Function argument specification</a></li>
<li class="chapter" data-level="1.13.3" data-path="conclusion-1.html"><a href="conclusion-1.html#additional-resources-1"><i class="fa fa-check"></i><b>1.13.3</b> Additional resources</a></li>
<li class="chapter" data-level="1.13.4" data-path="conclusion-1.html"><a href="conclusion-1.html#whats-to-come-3"><i class="fa fa-check"></i><b>1.13.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>2</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="piping.html"><a href="piping.html"><i class="fa fa-check"></i><b>2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.2" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="2.3" data-path="summarize.html"><a href="summarize.html"><i class="fa fa-check"></i><b>2.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="2.4" data-path="groupby.html"><a href="groupby.html"><i class="fa fa-check"></i><b>2.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="groupby.html"><a href="groupby.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>2.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>2.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="2.6" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>2.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="2.7" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>2.7</b> Factors</a><ul>
<li class="chapter" data-level="2.7.1" data-path="factors.html"><a href="factors.html#the-forcats-package"><i class="fa fa-check"></i><b>2.7.1</b> The <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="2.7.2" data-path="factors.html"><a href="factors.html#dropping-unused-levels"><i class="fa fa-check"></i><b>2.7.2</b> Dropping unused levels</a></li>
<li class="chapter" data-level="2.7.3" data-path="factors.html"><a href="factors.html#reorder-factors"><i class="fa fa-check"></i><b>2.7.3</b> Change order of the levels, principled</a></li>
<li class="chapter" data-level="2.7.4" data-path="factors.html"><a href="factors.html#change-order-of-the-levels-because-i-said-so"><i class="fa fa-check"></i><b>2.7.4</b> Change order of the levels, “because I said so”</a></li>
<li class="chapter" data-level="2.7.5" data-path="factors.html"><a href="factors.html#recode-the-levels"><i class="fa fa-check"></i><b>2.7.5</b> Recode the levels</a></li>
<li class="chapter" data-level="2.7.6" data-path="factors.html"><a href="factors.html#grow-a-factor"><i class="fa fa-check"></i><b>2.7.6</b> Grow a factor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="character-vectors.html"><a href="character-vectors.html"><i class="fa fa-check"></i><b>2.8</b> Character Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="character-vectors.html"><a href="character-vectors.html#manipulating-character-vectors"><i class="fa fa-check"></i><b>2.8.1</b> Manipulating character vectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-resources"><i class="fa fa-check"></i><b>2.8.2</b> Regular expressions resources</a></li>
<li class="chapter" data-level="2.8.3" data-path="character-vectors.html"><a href="character-vectors.html#character-encoding-resources"><i class="fa fa-check"></i><b>2.8.3</b> Character encoding resources</a></li>
<li class="chapter" data-level="2.8.4" data-path="character-vectors.html"><a href="character-vectors.html#character-vectors-that-live-in-a-data-frame"><i class="fa fa-check"></i><b>2.8.4</b> Character vectors that live in a data frame</a></li>
<li class="chapter" data-level="2.8.5" data-path="character-vectors.html"><a href="character-vectors.html#regex-free-string-manipulation-with-stringr-and-tidyr"><i class="fa fa-check"></i><b>2.8.5</b> Regex-free string manipulation with stringr and tidyr</a></li>
<li class="chapter" data-level="2.8.6" data-path="character-vectors.html"><a href="character-vectors.html#detect-or-filter-on-a-target-string"><i class="fa fa-check"></i><b>2.8.6</b> Detect or filter on a target string</a></li>
<li class="chapter" data-level="2.8.7" data-path="character-vectors.html"><a href="character-vectors.html#string-splitting-by-delimiter"><i class="fa fa-check"></i><b>2.8.7</b> String splitting by delimiter</a></li>
<li class="chapter" data-level="2.8.8" data-path="character-vectors.html"><a href="character-vectors.html#substring-extraction-and-replacement-by-position"><i class="fa fa-check"></i><b>2.8.8</b> Substring extraction (and replacement) by position</a></li>
<li class="chapter" data-level="2.8.9" data-path="character-vectors.html"><a href="character-vectors.html#collapse-a-vector"><i class="fa fa-check"></i><b>2.8.9</b> Collapse a vector</a></li>
<li class="chapter" data-level="2.8.10" data-path="character-vectors.html"><a href="character-vectors.html#catenate-vectors"><i class="fa fa-check"></i><b>2.8.10</b> Create a character vector by catenating multiple vectors</a></li>
<li class="chapter" data-level="2.8.11" data-path="character-vectors.html"><a href="character-vectors.html#substring-replacement"><i class="fa fa-check"></i><b>2.8.11</b> Substring replacement</a></li>
<li class="chapter" data-level="2.8.12" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-with-stringr"><i class="fa fa-check"></i><b>2.8.12</b> Regular expressions with stringr</a></li>
<li class="chapter" data-level="2.8.13" data-path="character-vectors.html"><a href="character-vectors.html#characters-with-special-meaning"><i class="fa fa-check"></i><b>2.8.13</b> Characters with special meaning</a></li>
<li class="chapter" data-level="2.8.14" data-path="character-vectors.html"><a href="character-vectors.html#character-classes"><i class="fa fa-check"></i><b>2.8.14</b> Character classes</a></li>
<li class="chapter" data-level="2.8.15" data-path="character-vectors.html"><a href="character-vectors.html#quantifiers"><i class="fa fa-check"></i><b>2.8.15</b> Quantifiers</a></li>
<li class="chapter" data-level="2.8.16" data-path="character-vectors.html"><a href="character-vectors.html#escaping"><i class="fa fa-check"></i><b>2.8.16</b> Escaping</a></li>
<li class="chapter" data-level="2.8.17" data-path="character-vectors.html"><a href="character-vectors.html#groups-and-backreferences"><i class="fa fa-check"></i><b>2.8.17</b> Groups and backreferences</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="combining-data.html"><a href="combining-data.html"><i class="fa fa-check"></i><b>2.9</b> Combining Data</a><ul>
<li class="chapter" data-level="2.9.1" data-path="combining-data.html"><a href="combining-data.html#bind"><i class="fa fa-check"></i><b>2.9.1</b> Bind</a></li>
<li class="chapter" data-level="2.9.2" data-path="combining-data.html"><a href="combining-data.html#joins-in-dplyr"><i class="fa fa-check"></i><b>2.9.2</b> Joins in dplyr</a></li>
<li class="chapter" data-level="2.9.3" data-path="combining-data.html"><a href="combining-data.html#joining"><i class="fa fa-check"></i><b>2.9.3</b> Joining</a></li>
<li class="chapter" data-level="2.9.4" data-path="combining-data.html"><a href="combining-data.html#matching-key-variable-names"><i class="fa fa-check"></i><b>2.9.4</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="2.9.5" data-path="combining-data.html"><a href="combining-data.html#diff-key"><i class="fa fa-check"></i><b>2.9.5</b> Different “key” variable names</a></li>
<li class="chapter" data-level="2.9.6" data-path="combining-data.html"><a href="combining-data.html#multiple-key-variables"><i class="fa fa-check"></i><b>2.9.6</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="2.9.7" data-path="combining-data.html"><a href="combining-data.html#normal-forms"><i class="fa fa-check"></i><b>2.9.7</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="other-verbs.html"><a href="other-verbs.html"><i class="fa fa-check"></i><b>2.10</b> Other Verbs</a><ul>
<li class="chapter" data-level="2.10.1" data-path="other-verbs.html"><a href="other-verbs.html#select"><i class="fa fa-check"></i><b>2.10.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="other-verbs.html"><a href="other-verbs.html#rename"><i class="fa fa-check"></i><b>2.10.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="2.10.3" data-path="other-verbs.html"><a href="other-verbs.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>2.10.3</b> <code>top_n</code> values of a variable</a></li>
<li class="chapter" data-level="2.10.4" data-path="other-verbs.html"><a href="other-verbs.html#slice-and-pull-and"><i class="fa fa-check"></i><b>2.10.4</b> <code>slice</code> and <code>pull</code> and <code>[]</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="conclusion-2.html"><a href="conclusion-2.html"><i class="fa fa-check"></i><b>2.11</b> Conclusion</a><ul>
<li class="chapter" data-level="2.11.1" data-path="conclusion-2.html"><a href="conclusion-2.html#summary-table-1"><i class="fa fa-check"></i><b>2.11.1</b> Summary table</a></li>
<li class="chapter" data-level="2.11.2" data-path="conclusion-2.html"><a href="conclusion-2.html#additional-resources-2"><i class="fa fa-check"></i><b>2.11.2</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>2.12</b> Tidy</a></li>
<li class="chapter" data-level="2.13" data-path="csv.html"><a href="csv.html"><i class="fa fa-check"></i><b>2.13</b> Importing data</a></li>
<li class="chapter" data-level="2.14" data-path="web-scraping.html"><a href="web-scraping.html"><i class="fa fa-check"></i><b>2.14</b> Web scraping</a><ul>
<li class="chapter" data-level="2.14.1" data-path="web-scraping.html"><a href="web-scraping.html#html"><i class="fa fa-check"></i><b>2.14.1</b> HTML</a></li>
<li class="chapter" data-level="2.14.2" data-path="web-scraping.html"><a href="web-scraping.html#the-rvest-package"><i class="fa fa-check"></i><b>2.14.2</b> The rvest package</a></li>
<li class="chapter" data-level="2.14.3" data-path="web-scraping.html"><a href="web-scraping.html#css-selectors"><i class="fa fa-check"></i><b>2.14.3</b> CSS selectors</a></li>
<li class="chapter" data-level="2.14.4" data-path="web-scraping.html"><a href="web-scraping.html#json"><i class="fa fa-check"></i><b>2.14.4</b> JSON</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html"><i class="fa fa-check"></i><b>2.15</b> “Tidy” data</a><ul>
<li class="chapter" data-level="2.15.1" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#tidy-definition"><i class="fa fa-check"></i><b>2.15.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="2.15.2" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>2.15.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="2.15.3" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#nycflights13-package-1"><i class="fa fa-check"></i><b>2.15.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="case-study-tidy.html"><a href="case-study-tidy.html"><i class="fa fa-check"></i><b>2.16</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="2.17" data-path="tidyverse-package.html"><a href="tidyverse-package.html"><i class="fa fa-check"></i><b>2.17</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="2.18" data-path="conclusion-3.html"><a href="conclusion-3.html"><i class="fa fa-check"></i><b>2.18</b> Conclusion</a><ul>
<li class="chapter" data-level="2.18.1" data-path="conclusion-3.html"><a href="conclusion-3.html#additional-resources-3"><i class="fa fa-check"></i><b>2.18.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rubin-causal-model.html"><a href="rubin-causal-model.html"><i class="fa fa-check"></i><b>3</b> Rubin Causal Model</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html"><i class="fa fa-check"></i><b>3.1</b> What is a causal effect?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#everything-is-a-missing-data-problem"><i class="fa fa-check"></i><b>3.1.1</b> Everything is a missing data problem</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#potential-outcomes-introduction-to-the-rubin-table"><i class="fa fa-check"></i><b>3.1.2</b> Potential outcomes: introduction to the Rubin Table</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#estimands"><i class="fa fa-check"></i><b>3.1.3</b> Estimands</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#the-infinite-rubin-table-many-kinds-of-missing-data"><i class="fa fa-check"></i><b>3.1.4</b> The infinite Rubin Table: many kinds of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html"><i class="fa fa-check"></i><b>3.2</b> How do we fill in the missing values?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#average-treatment-effect"><i class="fa fa-check"></i><b>3.2.1</b> Average treatment effect</a></li>
<li class="chapter" data-level="3.2.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#the-assignment-mechanism"><i class="fa fa-check"></i><b>3.2.2</b> The assignment mechanism</a></li>
<li class="chapter" data-level="3.2.3" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#uncertainty-and-permutation-tests"><i class="fa fa-check"></i><b>3.2.3</b> Uncertainty and permutation tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#everything-is-a-missing-data-problem-revisited-internal-and-external-validity"><i class="fa fa-check"></i><b>3.2.4</b> Everything is a missing data problem revisited: Internal and external validity</a></li>
<li class="chapter" data-level="3.2.5" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#more-complex-models-for-causal-inference"><i class="fa fa-check"></i><b>3.2.5</b> More complex models for causal inference</a></li>
<li class="chapter" data-level="3.2.6" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#causal-inference-and-prediction"><i class="fa fa-check"></i><b>3.2.6</b> Causal inference and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html"><i class="fa fa-check"></i><b>3.3</b> Other issues with causal inference</a><ul>
<li class="chapter" data-level="3.3.1" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#no-causation-without-manipulation"><i class="fa fa-check"></i><b>3.3.1</b> No causation without manipulation</a></li>
<li class="chapter" data-level="3.3.2" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#stable-unit-treatment-value-assumption-sutva"><i class="fa fa-check"></i><b>3.3.2</b> Stable unit treatment value assumption (SUTVA)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="conclusion-4.html"><a href="conclusion-4.html"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
<li class="chapter" data-level="3.5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a><ul>
<li class="chapter" data-level="4.1" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="part-1.html"><a href="part-1.html#get-something-that-works"><i class="fa fa-check"></i><b>4.1.1</b> Get something that works</a></li>
<li class="chapter" data-level="4.1.2" data-path="part-1.html"><a href="part-1.html#skateboard-perfectly-formed-rear-view-mirror"><i class="fa fa-check"></i><b>4.1.2</b> Skateboard &gt;&gt; perfectly formed rear-view mirror</a></li>
<li class="chapter" data-level="4.1.3" data-path="part-1.html"><a href="part-1.html#turn-the-working-interactive-code-into-a-function"><i class="fa fa-check"></i><b>4.1.3</b> Turn the working interactive code into a function</a></li>
<li class="chapter" data-level="4.1.4" data-path="part-1.html"><a href="part-1.html#test-your-function"><i class="fa fa-check"></i><b>4.1.4</b> Test your function</a></li>
<li class="chapter" data-level="4.1.5" data-path="part-1.html"><a href="part-1.html#check-the-validity-of-arguments"><i class="fa fa-check"></i><b>4.1.5</b> Check the validity of arguments</a></li>
<li class="chapter" data-level="4.1.6" data-path="part-1.html"><a href="part-1.html#wrap-up-and-whats-next"><i class="fa fa-check"></i><b>4.1.6</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i><b>4.2</b> Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="part-2.html"><a href="part-2.html#load-the-gapminder-data"><i class="fa fa-check"></i><b>4.2.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.2.2" data-path="part-2.html"><a href="part-2.html#restore-our-max-minus-min-function"><i class="fa fa-check"></i><b>4.2.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.2.3" data-path="part-2.html"><a href="part-2.html#generalize-our-function-to-other-quantiles"><i class="fa fa-check"></i><b>4.2.3</b> Generalize our function to other quantiles</a></li>
<li class="chapter" data-level="4.2.4" data-path="part-2.html"><a href="part-2.html#get-something-that-works-again"><i class="fa fa-check"></i><b>4.2.4</b> Get something that works, again</a></li>
<li class="chapter" data-level="4.2.5" data-path="part-2.html"><a href="part-2.html#turn-the-working-interactive-code-into-a-function-again"><i class="fa fa-check"></i><b>4.2.5</b> Turn the working interactive code into a function, again</a></li>
<li class="chapter" data-level="4.2.6" data-path="part-2.html"><a href="part-2.html#argument-names-freedom-and-conventions"><i class="fa fa-check"></i><b>4.2.6</b> Argument names: freedom and conventions</a></li>
<li class="chapter" data-level="4.2.7" data-path="part-2.html"><a href="part-2.html#what-a-function-returns"><i class="fa fa-check"></i><b>4.2.7</b> What a function returns</a></li>
<li class="chapter" data-level="4.2.8" data-path="part-2.html"><a href="part-2.html#default-values-freedom-to-not-specify-the-arguments"><i class="fa fa-check"></i><b>4.2.8</b> Default values: freedom to NOT specify the arguments</a></li>
<li class="chapter" data-level="4.2.9" data-path="part-2.html"><a href="part-2.html#wrap-up-and-whats-next-1"><i class="fa fa-check"></i><b>4.2.9</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i><b>4.3</b> Part 3</a><ul>
<li class="chapter" data-level="4.3.1" data-path="part-3.html"><a href="part-3.html#load-the-gapminder-data-1"><i class="fa fa-check"></i><b>4.3.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.3.2" data-path="part-3.html"><a href="part-3.html#restore-our-max-minus-min-function-1"><i class="fa fa-check"></i><b>4.3.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.3.3" data-path="part-3.html"><a href="part-3.html#be-proactive-about-nas"><i class="fa fa-check"></i><b>4.3.3</b> Be proactive about <code>NA</code>s</a></li>
<li class="chapter" data-level="4.3.4" data-path="part-3.html"><a href="part-3.html#the-useful-but-mysterious-...-argument"><i class="fa fa-check"></i><b>4.3.4</b> The useful but mysterious <code>...</code> argument</a></li>
<li class="chapter" data-level="4.3.5" data-path="part-3.html"><a href="part-3.html#use-testthat-for-formal-unit-tests"><i class="fa fa-check"></i><b>4.3.5</b> Use testthat for formal unit tests</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html"><i class="fa fa-check"></i><b>4.4</b> List columns and <code>map_*</code> functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#what-are-list-columns"><i class="fa fa-check"></i><b>4.4.1</b> What are list columns?</a></li>
<li class="chapter" data-level="4.4.2" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#creating-list-columns-with-mutate"><i class="fa fa-check"></i><b>4.4.2</b> Creating list columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="4.4.3" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#map_-functions"><i class="fa fa-check"></i><b>4.4.3</b> <code>map_*</code> functions</a></li>
<li class="chapter" data-level="4.4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#using-map_-functions-to-create-list-columns"><i class="fa fa-check"></i><b>4.4.4</b> Using <code>map_*</code> functions to create list columns</a></li>
<li class="chapter" data-level="4.4.5" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#practice-with-map_-functions-and-list-columns"><i class="fa fa-check"></i><b>4.4.5</b> Practice with <code>map_*</code> functions and list columns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii.html"><a href="part-ii.html"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html"><i class="fa fa-check"></i><b>5.1</b> Defining probability</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#intro-questions"><i class="fa fa-check"></i><b>5.1.1</b> Intro Questions</a></li>
<li class="chapter" data-level="5.1.2" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-1"><i class="fa fa-check"></i><b>5.1.2</b> Probability</a></li>
<li class="chapter" data-level="5.1.3" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#disjoint-or-mutually-exclusive-outcomes"><i class="fa fa-check"></i><b>5.1.3</b> Disjoint or mutually exclusive outcomes</a></li>
<li class="chapter" data-level="5.1.4" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilities-when-events-are-not-disjoint"><i class="fa fa-check"></i><b>5.1.4</b> Probabilities when events are not disjoint</a></li>
<li class="chapter" data-level="5.1.5" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-distributions"><i class="fa fa-check"></i><b>5.1.5</b> Probability distributions</a></li>
<li class="chapter" data-level="5.1.6" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#complement-of-an-event"><i class="fa fa-check"></i><b>5.1.6</b> Complement of an event</a></li>
<li class="chapter" data-level="5.1.7" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilityIndependence"><i class="fa fa-check"></i><b>5.1.7</b> Independence</a></li>
<li class="chapter" data-level="5.1.8" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#conditionalProbabilitySection"><i class="fa fa-check"></i><b>5.1.8</b> Conditional probability</a></li>
<li class="chapter" data-level="5.1.9" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#marginalAndJointProbabilities"><i class="fa fa-check"></i><b>5.1.9</b> Marginal and joint probabilities</a></li>
<li class="chapter" data-level="5.1.10" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#defining-conditional-probability"><i class="fa fa-check"></i><b>5.1.10</b> Defining conditional probability</a></li>
<li class="chapter" data-level="5.1.11" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#smallpox-in-boston-1721"><i class="fa fa-check"></i><b>5.1.11</b> Smallpox in Boston, 1721</a></li>
<li class="chapter" data-level="5.1.12" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#general-multiplication-rule"><i class="fa fa-check"></i><b>5.1.12</b> General multiplication rule</a></li>
<li class="chapter" data-level="5.1.13" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#tree-diagrams"><i class="fa fa-check"></i><b>5.1.13</b> Tree diagrams</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html"><i class="fa fa-check"></i><b>5.2</b> Random variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#expectation"><i class="fa fa-check"></i><b>5.2.1</b> Expectation</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Variability in random variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.3</b> Linear combinations of random variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.4</b> Variability in linear combinations of random variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>5.3</b> Statistical Background</a><ul>
<li class="chapter" data-level="5.3.1" data-path="appendixA.html"><a href="appendixA.html#appendix-stat-terms"><i class="fa fa-check"></i><b>5.3.1</b> Basic statistical terms</a></li>
<li class="chapter" data-level="5.3.2" data-path="appendixA.html"><a href="appendixA.html#appendix-normal-curve"><i class="fa fa-check"></i><b>5.3.2</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bayess-theorem.html"><a href="bayess-theorem.html"><i class="fa fa-check"></i><b>5.4</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.5" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>5.5</b> Conditional probability</a></li>
<li class="chapter" data-level="5.6" data-path="conjoint-probability.html"><a href="conjoint-probability.html"><i class="fa fa-check"></i><b>5.6</b> Conjoint probability</a></li>
<li class="chapter" data-level="5.7" data-path="the-cookie-problem.html"><a href="the-cookie-problem.html"><i class="fa fa-check"></i><b>5.7</b> The cookie problem</a></li>
<li class="chapter" data-level="5.8" data-path="bayess-theorem-1.html"><a href="bayess-theorem-1.html"><i class="fa fa-check"></i><b>5.8</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.9" data-path="the-diachronic-interpretation.html"><a href="the-diachronic-interpretation.html"><i class="fa fa-check"></i><b>5.9</b> The diachronic interpretation</a></li>
<li class="chapter" data-level="5.10" data-path="the-mm-problem.html"><a href="the-mm-problem.html"><i class="fa fa-check"></i><b>5.10</b> The M&amp;M problem</a></li>
<li class="chapter" data-level="5.11" data-path="the-monty-hall-problem.html"><a href="the-monty-hall-problem.html"><i class="fa fa-check"></i><b>5.11</b> The Monty Hall problem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling</a><ul>
<li class="chapter" data-level="" data-path="sampling.html"><a href="sampling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="sampling-activity.html"><a href="sampling-activity.html"><i class="fa fa-check"></i><b>6.1</b> Sampling urn activity</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sampling-activity.html"><a href="sampling-activity.html#what-proportion-of-this-urns-balls-are-red"><i class="fa fa-check"></i><b>6.1.1</b> What proportion of this urn’s balls are red?</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling-activity.html"><a href="sampling-activity.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling-activity.html"><a href="sampling-activity.html#student-shovels"><i class="fa fa-check"></i><b>6.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling-activity.html"><a href="sampling-activity.html#what-did-we-just-do"><i class="fa fa-check"></i><b>6.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html"><i class="fa fa-check"></i><b>6.2</b> Virtual sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-simulation.html"><a href="sampling-simulation.html#shovel-1000-times"><i class="fa fa-check"></i><b>6.2.3</b> Using the virtual shovel 1,000 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-simulation.html"><a href="sampling-simulation.html#different-shovels"><i class="fa fa-check"></i><b>6.2.4</b> Using different shovels</a></li>
<li class="chapter" data-level="6.2.5" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-many-shovels-at-once"><i class="fa fa-check"></i><b>6.2.5</b> Using many shovels at once</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-framework.html"><a href="sampling-framework.html"><i class="fa fa-check"></i><b>6.3</b> Sampling framework</a><ul>
<li class="chapter" data-level="6.3.1" data-path="sampling-framework.html"><a href="sampling-framework.html#terminology-and-notation"><i class="fa fa-check"></i><b>6.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="6.3.2" data-path="sampling-framework.html"><a href="sampling-framework.html#sampling-definitions"><i class="fa fa-check"></i><b>6.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="6.3.3" data-path="sampling-framework.html"><a href="sampling-framework.html#moral-of-the-story"><i class="fa fa-check"></i><b>6.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sampling-case-study.html"><a href="sampling-case-study.html"><i class="fa fa-check"></i><b>6.4</b> Case study: Polls</a><ul>
<li class="chapter" data-level="6.4.1" data-path="sampling-case-study.html"><a href="sampling-case-study.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>6.4.1</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="conclusion-5.html"><a href="conclusion-5.html"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> One Parameter</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html"><i class="fa fa-check"></i><b>7.1</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.1.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.1.2" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-once"><i class="fa fa-check"></i><b>7.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.1.3" data-path="resampling-tactile.html"><a href="resampling-tactile.html#student-resamples"><i class="fa fa-check"></i><b>7.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.1.4" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-did-we-just-do-1"><i class="fa fa-check"></i><b>7.1.4</b> What did we just do?</a></li>
<li class="chapter" data-level="7.1.5" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-simulation"><i class="fa fa-check"></i><b>7.1.5</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.1.6" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>7.1.6</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.1.7" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.1.7</b> Virtually resampling 1,000 times</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ci-build-up.html"><a href="ci-build-up.html"><i class="fa fa-check"></i><b>7.2</b> Measuring uncertainty with confidence intervals</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ci-build-up.html"><a href="ci-build-up.html#percentile-method"><i class="fa fa-check"></i><b>7.2.1</b> Percentile method</a></li>
<li class="chapter" data-level="7.2.2" data-path="ci-build-up.html"><a href="ci-build-up.html#se-method"><i class="fa fa-check"></i><b>7.2.2</b> Standard error method</a></li>
<li class="chapter" data-level="7.2.3" data-path="ci-build-up.html"><a href="ci-build-up.html#one-prop-ci"><i class="fa fa-check"></i><b>7.2.3</b> Interpreting confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ci-width.html"><a href="ci-width.html"><i class="fa fa-check"></i><b>7.3</b> Width of confidence intervals</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ci-width.html"><a href="ci-width.html#impact-of-confidence-level"><i class="fa fa-check"></i><b>7.3.1</b> Impact of confidence level</a></li>
<li class="chapter" data-level="7.3.2" data-path="ci-width.html"><a href="ci-width.html#fitting-multiple-models-using-map"><i class="fa fa-check"></i><b>7.3.2</b> Fitting multiple models using <code>map()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="ci-width.html"><a href="ci-width.html#impact-of-sample-size"><i class="fa fa-check"></i><b>7.3.3</b> Impact of sample size</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-lm-and-tidy-as-a-shortcut.html"><a href="using-lm-and-tidy-as-a-shortcut.html"><i class="fa fa-check"></i><b>7.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html"><i class="fa fa-check"></i><b>7.5</b> Case study: Is yawning contagious?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#mythbusters-study-data"><i class="fa fa-check"></i><b>7.5.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#sampling-scenario"><i class="fa fa-check"></i><b>7.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="7.5.3" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#ci-build"><i class="fa fa-check"></i><b>7.5.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="7.5.4" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#using-lm-and-tidy-as-a-shortcut-1"><i class="fa fa-check"></i><b>7.5.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ci-conclusion.html"><a href="ci-conclusion.html"><i class="fa fa-check"></i><b>7.6</b> Conclusion</a><ul>
<li class="chapter" data-level="7.6.1" data-path="ci-conclusion.html"><a href="ci-conclusion.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>7.6.1</b> Comparing bootstrap and sampling distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="two-parameters.html"><a href="two-parameters.html"><i class="fa fa-check"></i><b>8</b> Two Parameters</a></li>
<li class="chapter" data-level="" data-path="part-iii.html"><a href="part-iii.html"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="9" data-path="n-parameters.html"><a href="n-parameters.html"><i class="fa fa-check"></i><b>9</b> N Parameters</a></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Continuous Response I</a><ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="10.1" data-path="model1.html"><a href="model1.html"><i class="fa fa-check"></i><b>10.1</b> Teaching evaluations: one numerical explanatory variable</a><ul>
<li class="chapter" data-level="10.1.1" data-path="model1.html"><a href="model1.html#model1EDA"><i class="fa fa-check"></i><b>10.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.1.2" data-path="model1.html"><a href="model1.html#model1table"><i class="fa fa-check"></i><b>10.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="model1.html"><a href="model1.html#interpreting-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Interpreting regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html"><i class="fa fa-check"></i><b>10.2</b> Uncertainty in simple linear regressions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#using-lm-and-tidy-as-a-shortcut-2"><i class="fa fa-check"></i><b>10.2.1</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#model1points"><i class="fa fa-check"></i><b>10.2.2</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="model2.html"><a href="model2.html"><i class="fa fa-check"></i><b>10.3</b> Life expectancy: one categorical explanatory variable</a><ul>
<li class="chapter" data-level="10.3.1" data-path="model2.html"><a href="model2.html#model2EDA"><i class="fa fa-check"></i><b>10.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="model2.html"><a href="model2.html#model2table"><i class="fa fa-check"></i><b>10.3.2</b> Linear regression</a></li>
<li class="chapter" data-level="10.3.3" data-path="model2.html"><a href="model2.html#model2points"><i class="fa fa-check"></i><b>10.3.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html"><i class="fa fa-check"></i><b>10.4</b> Case study: 2018 gubernatorial forecasts</a><ul>
<li class="chapter" data-level="10.4.1" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html#fitting-multiple-models-using-map-1"><i class="fa fa-check"></i><b>10.4.1</b> Fitting multiple models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="leastsquares.html"><a href="leastsquares.html"><i class="fa fa-check"></i><b>10.5</b> Appendix: Best-fitting line</a></li>
<li class="chapter" data-level="10.6" data-path="conclusion-6.html"><a href="conclusion-6.html"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>11</b> Continuous Response II</a><ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="11.1" data-path="model4.html"><a href="model4.html"><i class="fa fa-check"></i><b>11.1</b> Teaching evaluations revisited: one numerical and one categorical explanatory variable</a><ul>
<li class="chapter" data-level="11.1.1" data-path="model4.html"><a href="model4.html#model4EDA"><i class="fa fa-check"></i><b>11.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.1.2" data-path="model4.html"><a href="model4.html#model4interactiontable"><i class="fa fa-check"></i><b>11.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="11.1.3" data-path="model4.html"><a href="model4.html#interpreting-regression-coefficients-with-interactions"><i class="fa fa-check"></i><b>11.1.3</b> Interpreting regression coefficients with interactions</a></li>
<li class="chapter" data-level="11.1.4" data-path="model4.html"><a href="model4.html#model4table"><i class="fa fa-check"></i><b>11.1.4</b> Parallel slopes model</a></li>
<li class="chapter" data-level="11.1.5" data-path="model4.html"><a href="model4.html#model4points"><i class="fa fa-check"></i><b>11.1.5</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="model3.html"><a href="model3.html"><i class="fa fa-check"></i><b>11.2</b> Credit card debt: two numerical explanatory variables</a><ul>
<li class="chapter" data-level="11.2.1" data-path="model3.html"><a href="model3.html#model3EDA"><i class="fa fa-check"></i><b>11.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.2.2" data-path="model3.html"><a href="model3.html#model3table"><i class="fa fa-check"></i><b>11.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="11.2.3" data-path="model3.html"><a href="model3.html#model3points"><i class="fa fa-check"></i><b>11.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html"><i class="fa fa-check"></i><b>11.3</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="11.3.1" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>11.3.1</b> Exploratory data analysis: Part I</a></li>
<li class="chapter" data-level="11.3.2" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-II"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory data analysis: Part II</a></li>
<li class="chapter" data-level="11.3.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-regression"><i class="fa fa-check"></i><b>11.3.3</b> Regression modeling</a></li>
<li class="chapter" data-level="11.3.4" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>11.3.4</b> Making predictions</a></li>
<li class="chapter" data-level="11.3.5" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#fitting-many-models-using-map"><i class="fa fa-check"></i><b>11.3.5</b> Fitting many models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="other-topics.html"><a href="other-topics.html"><i class="fa fa-check"></i><b>11.4</b> Other topics</a><ul>
<li class="chapter" data-level="11.4.1" data-path="other-topics.html"><a href="other-topics.html#model-selection"><i class="fa fa-check"></i><b>11.4.1</b> Model selection</a></li>
<li class="chapter" data-level="11.4.2" data-path="other-topics.html"><a href="other-topics.html#correlationcoefficient2"><i class="fa fa-check"></i><b>11.4.2</b> Correlation coefficient</a></li>
<li class="chapter" data-level="11.4.3" data-path="other-topics.html"><a href="other-topics.html#simpsonsparadox"><i class="fa fa-check"></i><b>11.4.3</b> Simpson’s Paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>12</b> Discrete Response</a><ul>
<li class="chapter" data-level="" data-path="classification.html"><a href="classification.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> What is logistic regression?</a></li>
<li class="chapter" data-level="12.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#house-elections-exploratory-data-analysis"><i class="fa fa-check"></i><b>12.1.2</b> House elections: exploratory data analysis</a></li>
<li class="chapter" data-level="12.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.3</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.4" data-path="logistic-regression.html"><a href="logistic-regression.html#observedfitted-values-and-residuals"><i class="fa fa-check"></i><b>12.1.4</b> Observed/fitted values and residuals</a></li>
<li class="chapter" data-level="12.1.5" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.5</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.1.6" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-and-one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.6</b> One numerical and one categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.7" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-many-models-using-map-1"><i class="fa fa-check"></i><b>12.1.7</b> Fitting many models using <code>map()</code></a></li>
<li class="chapter" data-level="12.1.8" data-path="logistic-regression.html"><a href="logistic-regression.html#professional-models"><i class="fa fa-check"></i><b>12.1.8</b> Professional models</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html"><i class="fa fa-check"></i><b>12.2</b> Classification and regression trees (CART)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#what-is-cart"><i class="fa fa-check"></i><b>12.2.1</b> What is CART?</a></li>
<li class="chapter" data-level="12.2.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-categorical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.2</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.2.3" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-numerical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.3</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.2.4" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#multiple-explanatory-variables"><i class="fa fa-check"></i><b>12.2.4</b> Multiple explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>12.3</b> Random forests</a><ul>
<li class="chapter" data-level="12.3.1" data-path="random-forests.html"><a href="random-forests.html#what-are-random-forests"><i class="fa fa-check"></i><b>12.3.1</b> What are random forests?</a></li>
<li class="chapter" data-level="12.3.2" data-path="random-forests.html"><a href="random-forests.html#fitting-random-forests"><i class="fa fa-check"></i><b>12.3.2</b> Fitting random forests</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html"><i class="fa fa-check"></i><b>12.4</b> Comparing the three approaches</a><ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#is-accuracy-the-right-measure"><i class="fa fa-check"></i><b>12.4.1</b> Is accuracy the right measure?</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#modeling-for-prediction-vs.-explanation"><i class="fa fa-check"></i><b>12.4.2</b> Modeling for prediction vs. explanation</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#out-of-sample-predictions"><i class="fa fa-check"></i><b>12.4.3</b> Out-of-sample predictions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="productivity.html"><a href="productivity.html"><i class="fa fa-check"></i><b>A</b> Productivity</a><ul>
<li class="chapter" data-level="A.1" data-path="set-up.html"><a href="set-up.html"><i class="fa fa-check"></i><b>A.1</b> Set Up</a><ul>
<li class="chapter" data-level="A.1.1" data-path="set-up.html"><a href="set-up.html#terminal-on-mac"><i class="fa fa-check"></i><b>A.1.1</b> Accessing the terminal on a Mac</a></li>
<li class="chapter" data-level="A.1.2" data-path="set-up.html"><a href="set-up.html#installing-git-on-the-mac"><i class="fa fa-check"></i><b>A.1.2</b> Installing Git on the Mac</a></li>
<li class="chapter" data-level="A.1.3" data-path="set-up.html"><a href="set-up.html#installing-git-and-git-bash-on-windows"><i class="fa fa-check"></i><b>A.1.3</b> Installing Git and Git Bash on Windows</a></li>
<li class="chapter" data-level="A.1.4" data-path="set-up.html"><a href="set-up.html#terminal-on-windows"><i class="fa fa-check"></i><b>A.1.4</b> Accessing the terminal on Windows</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i><b>A.2</b> Organizing with Unix</a><ul>
<li class="chapter" data-level="A.2.1" data-path="unix.html"><a href="unix.html#naming-convention"><i class="fa fa-check"></i><b>A.2.1</b> Naming convention</a></li>
<li class="chapter" data-level="A.2.2" data-path="unix.html"><a href="unix.html#the-terminal"><i class="fa fa-check"></i><b>A.2.2</b> The terminal</a></li>
<li class="chapter" data-level="A.2.3" data-path="unix.html"><a href="unix.html#filesystem"><i class="fa fa-check"></i><b>A.2.3</b> The filesystem</a></li>
<li class="chapter" data-level="A.2.4" data-path="unix.html"><a href="unix.html#directories-and-subdirectories"><i class="fa fa-check"></i><b>A.2.4</b> Directories and subdirectories</a></li>
<li class="chapter" data-level="A.2.5" data-path="unix.html"><a href="unix.html#the-home-directory"><i class="fa fa-check"></i><b>A.2.5</b> The home directory</a></li>
<li class="chapter" data-level="A.2.6" data-path="unix.html"><a href="unix.html#working-directory"><i class="fa fa-check"></i><b>A.2.6</b> Working directory</a></li>
<li class="chapter" data-level="A.2.7" data-path="unix.html"><a href="unix.html#paths"><i class="fa fa-check"></i><b>A.2.7</b> Paths</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="unix-commands.html"><a href="unix-commands.html"><i class="fa fa-check"></i><b>A.3</b> Unix commands</a><ul>
<li class="chapter" data-level="A.3.1" data-path="unix-commands.html"><a href="unix-commands.html#ls-listing-directory-content"><i class="fa fa-check"></i><b>A.3.1</b> <code>ls</code>: Listing directory content</a></li>
<li class="chapter" data-level="A.3.2" data-path="unix-commands.html"><a href="unix-commands.html#mkdir-and-rmdir-make-and-remove-a-directory"><i class="fa fa-check"></i><b>A.3.2</b> <code>mkdir</code> and <code>rmdir</code>: make and remove a directory</a></li>
<li class="chapter" data-level="A.3.3" data-path="unix-commands.html"><a href="unix-commands.html#cd-navigating-the-filesystem-by-changing-directories"><i class="fa fa-check"></i><b>A.3.3</b> <code>cd</code>: navigating the filesystem by changing directories</a></li>
<li class="chapter" data-level="A.3.4" data-path="unix-commands.html"><a href="unix-commands.html#some-examples"><i class="fa fa-check"></i><b>A.3.4</b> Some examples</a></li>
<li class="chapter" data-level="A.3.5" data-path="unix-commands.html"><a href="unix-commands.html#more-unix-commands"><i class="fa fa-check"></i><b>A.3.5</b> More Unix commands</a></li>
<li class="chapter" data-level="A.3.6" data-path="unix-commands.html"><a href="unix-commands.html#advanced-unix"><i class="fa fa-check"></i><b>A.3.6</b> Advanced Unix</a></li>
<li class="chapter" data-level="A.3.7" data-path="unix-commands.html"><a href="unix-commands.html#file-manipulation-in-r"><i class="fa fa-check"></i><b>A.3.7</b> File manipulation in R</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="git.html"><a href="git.html"><i class="fa fa-check"></i><b>A.4</b> Git and GitHub</a><ul>
<li class="chapter" data-level="A.4.1" data-path="git.html"><a href="git.html#github-accounts"><i class="fa fa-check"></i><b>A.4.1</b> GitHub accounts</a></li>
<li class="chapter" data-level="A.4.2" data-path="git.html"><a href="git.html#github-repos"><i class="fa fa-check"></i><b>A.4.2</b> GitHub repositories</a></li>
<li class="chapter" data-level="A.4.3" data-path="git.html"><a href="git.html#git-overview"><i class="fa fa-check"></i><b>A.4.3</b> Overview of Git</a></li>
<li class="chapter" data-level="A.4.4" data-path="git.html"><a href="git.html#rstudio-git"><i class="fa fa-check"></i><b>A.4.4</b> Using Git and GitHub in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>A.5</b> R</a><ul>
<li class="chapter" data-level="A.5.1" data-path="r.html"><a href="r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.5.1</b> RStudio projects</a></li>
<li class="chapter" data-level="A.5.2" data-path="r.html"><a href="r.html#r-markdown"><i class="fa fa-check"></i><b>A.5.2</b> R markdown</a></li>
<li class="chapter" data-level="A.5.3" data-path="r.html"><a href="r.html#help-for-r"><i class="fa fa-check"></i><b>A.5.3</b> Help for R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>B</b> Getting Help</a><ul>
<li class="chapter" data-level="B.1" data-path="searching-for-help-with-r-1.html"><a href="searching-for-help-with-r-1.html"><i class="fa fa-check"></i><b>B.1</b> Searching for Help with R</a></li>
<li class="chapter" data-level="B.2" data-path="reproducible-examples-1.html"><a href="reproducible-examples-1.html"><i class="fa fa-check"></i><b>B.2</b> Reproducible Examples</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>C</b> Shiny</a><ul>
<li class="chapter" data-level="C.1" data-path="helpful-resources.html"><a href="helpful-resources.html"><i class="fa fa-check"></i><b>C.1</b> Helpful Resources</a></li>
<li class="chapter" data-level="C.2" data-path="set-up-and-getting-started.html"><a href="set-up-and-getting-started.html"><i class="fa fa-check"></i><b>C.2</b> Set Up and Getting Started</a></li>
<li class="chapter" data-level="C.3" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html"><i class="fa fa-check"></i><b>C.3</b> Building Your Basic App</a><ul>
<li class="chapter" data-level="C.3.1" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-basic-ui"><i class="fa fa-check"></i><b>C.3.1</b> Setting Up the Basic UI</a></li>
<li class="chapter" data-level="C.3.2" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-server"><i class="fa fa-check"></i><b>C.3.2</b> Setting up the Server</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="organization.html"><a href="organization.html"><i class="fa fa-check"></i><b>C.4</b> Organization</a></li>
<li class="chapter" data-level="C.5" data-path="customizations.html"><a href="customizations.html"><i class="fa fa-check"></i><b>C.5</b> Customizations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="maps.html"><a href="maps.html"><i class="fa fa-check"></i><b>D</b> Maps</a><ul>
<li class="chapter" data-level="D.1" data-path="tidycensus.html"><a href="tidycensus.html"><i class="fa fa-check"></i><b>D.1</b> Tidycensus</a></li>
<li class="chapter" data-level="D.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html"><i class="fa fa-check"></i><b>D.2</b> Conceptual introduction to mapping</a><ul>
<li class="chapter" data-level="D.2.1" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#vector-versus-spatial-data"><i class="fa fa-check"></i><b>D.2.1</b> Vector versus spatial data</a></li>
<li class="chapter" data-level="D.2.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#sf-vs-sp"><i class="fa fa-check"></i><b>D.2.2</b> <strong>sf</strong> vs <strong>sp</strong></a></li>
<li class="chapter" data-level="D.2.3" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#shapefiles"><i class="fa fa-check"></i><b>D.2.3</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html"><i class="fa fa-check"></i><b>D.3</b> Mapping with <strong>tidycensus</strong> and <code>geom_sf()</code></a><ul>
<li class="chapter" data-level="D.3.1" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#making-maps-pretty"><i class="fa fa-check"></i><b>D.3.1</b> Making maps pretty</a></li>
<li class="chapter" data-level="D.3.2" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#adding-back-alaska-and-hawaii"><i class="fa fa-check"></i><b>D.3.2</b> Adding back Alaska and Hawaii</a></li>
</ul></li>
<li class="chapter" data-level="D.4" data-path="faceting-maps.html"><a href="faceting-maps.html"><i class="fa fa-check"></i><b>D.4</b> Faceting maps</a><ul>
<li class="chapter" data-level="D.4.1" data-path="faceting-maps.html"><a href="faceting-maps.html#transforming-and-mapping-the-data"><i class="fa fa-check"></i><b>D.4.1</b> Transforming and mapping the data</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="want-to-explore-further.html"><a href="want-to-explore-further.html"><i class="fa fa-check"></i><b>D.5</b> Want to explore further?</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="animation.html"><a href="animation.html"><i class="fa fa-check"></i><b>E</b> Animation</a><ul>
<li class="chapter" data-level="E.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><i class="fa fa-check"></i><b>E.1</b> gganimate: How to Create Plots with Beautiful Animation in R</a><ul>
<li class="chapter" data-level="E.1.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#prerequisites"><i class="fa fa-check"></i><b>E.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="E.1.2" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#demo-dataset"><i class="fa fa-check"></i><b>E.1.2</b> Demo dataset</a></li>
<li class="chapter" data-level="E.1.3" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#static-plot"><i class="fa fa-check"></i><b>E.1.3</b> Static plot</a></li>
<li class="chapter" data-level="E.1.4" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-through-distinct-states-in-time"><i class="fa fa-check"></i><b>E.1.4</b> Transition through distinct states in time</a></li>
<li class="chapter" data-level="E.1.5" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#reveal-data-along-a-given-dimension"><i class="fa fa-check"></i><b>E.1.5</b> Reveal data along a given dimension</a></li>
<li class="chapter" data-level="E.1.6" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-between-several-distinct-stages-of-the-data"><i class="fa fa-check"></i><b>E.1.6</b> Transition between several distinct stages of the data</a></li>
<li class="chapter" data-level="E.1.7" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#read-more"><i class="fa fa-check"></i><b>E.1.7</b> Read more</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="how-to-save-your-animation.html"><a href="how-to-save-your-animation.html"><i class="fa fa-check"></i><b>E.2</b> How to save your animation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preceptor’s Primer for Bayesian Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression" class="section level2">
<h2><span class="header-section-number">12.1</span> Logistic regression</h2>
<div id="what-is-logistic-regression" class="section level3">
<h3><span class="header-section-number">12.1.1</span> What is logistic regression?</h3>
<p>Figure <a href="logistic-regression.html#fig:OLSlogistic">12.1</a> illustrates a data set with a binary (0 or 1) response (<span class="math inline">\(Y\)</span>) and a single continuous predictor (<span class="math inline">\(X\)</span>). The blue line is a linear regression to model the probability of a success (<span class="math inline">\(Y=1\)</span>) for a given value of <span class="math inline">\(X\)</span>. With a binary response, the linear regression has an obvious problem: it can produce predicted probabilities below 0 and above 1.</p>
<!-- DK: I think this point, about the nonsense of probabilities outside 0,1, should be emphasized in the picture more. -->
<p>The red curve is the <em>logistic regression</em> curve. Note that its characteristic “S” shape always produces predicted probabilities between 0 and 1. Here is the formula for a logistic regression:</p>
<p><span class="math display">\[
\log\left(\frac{p}{1 - p}\right)=\beta_0+\beta_1X 
\]</span></p>
<p>where <span class="math inline">\(p\)</span> is the probability of a “yes” or “success” for a given set of predictors <span class="math inline">\(X\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:OLSlogistic"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/OLSlogistic-1.png" alt="Linear vs. logistic regression models for binary response data." width="60%" />
<p class="caption">
FIGURE 12.1: Linear vs. logistic regression models for binary response data.
</p>
</div>
<!-- DK: How does the math work here? log(p/1-p) seems, to me, to map 0,1 to 0,infinity. -->
<p>The mathematical function <span class="math inline">\(log\left(\frac{p}{1 - p}\right)\)</span> is called the <em>logit function</em> and it transforms variables from the space <span class="math inline">\((0, 1)\)</span> (like probabilities) to <span class="math inline">\((-\infty, \infty)\)</span>. The inverse of that function, the <em>standard logistic function</em>, is <span class="math inline">\(\frac{1}{1 + e^{-x}}\)</span> and transforms variables from the space <span class="math inline">\((-\infty, \infty)\)</span> to <span class="math inline">\((0, 1)\)</span>. From that latter function’s name we get the terminology of <em>logistic regression</em>.</p>
</div>
<div id="house-elections-exploratory-data-analysis" class="section level3">
<h3><span class="header-section-number">12.1.2</span> House elections: exploratory data analysis</h3>
<!-- DK: Perhaps we can use house elections as a running example throughout the book? With regression we tried to forecast vote percentage. Here, we just care about wins and losses. Also provides an occasion to talk about which is best. Also to get into subtle issues like cases which are dropped, like redistricting contests. -->
<p>What affects whether a Democrat or Republican wins a race in the U.S. House of Representatives? This is an example of a binary response: either a Democrat wins (and a Republican loses) or a Republican wins (and a Democrat loses).<a href="#fn16" class="footnote-ref" id="fnref16"><sup>16</sup></a> In this section, we are going to consider several models predicting Democratic victory in House races. First, we will consider a single categorical variable as a predictor, the region in which a district lies: Midwest, Northeast, South, or West. Second, we will consider a single continuous variable: year. Finally, we fill fit a model that contains both separately, and than also an interaction between the two.</p>
<!-- DK: Too much cognitive load to create these datasets on the fly. They need to be ready to go. -->
<p>The data on House election results from 1976 to 2018 can be found in the <code>house_results</code> data frame in <strong>politicaldata</strong> package. We’ll create a version of this data frame called <code>house_ch13</code> that creates a new column <code>dem_win</code> that notes for each state if the Democratic candidate in a congressional district received more votes than the other candidates. We’ll also join it with the <code>state_info</code> data frame in the <strong>fivethirtyeight</strong> package to add the <code>region</code> of each state.</p>
<div class="sourceCode" id="cb812"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb812-1"><a href="logistic-regression.html#cb812-1"></a><span class="kw">library</span>(politicaldata)</span>
<span id="cb812-2"><a href="logistic-regression.html#cb812-2"></a></span>
<span id="cb812-3"><a href="logistic-regression.html#cb812-3"></a>house_ch13 &lt;-<span class="st"> </span>house_results <span class="op">%&gt;%</span></span>
<span id="cb812-4"><a href="logistic-regression.html#cb812-4"></a><span class="st">  </span></span>
<span id="cb812-5"><a href="logistic-regression.html#cb812-5"></a><span class="st">  </span><span class="co"># Create dem_win variable</span></span>
<span id="cb812-6"><a href="logistic-regression.html#cb812-6"></a><span class="st">  </span></span>
<span id="cb812-7"><a href="logistic-regression.html#cb812-7"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">dem =</span> <span class="kw">ifelse</span>(<span class="kw">is.na</span>(dem), <span class="dv">0</span>, dem),</span>
<span id="cb812-8"><a href="logistic-regression.html#cb812-8"></a>         <span class="dt">other =</span> <span class="kw">ifelse</span>(<span class="kw">is.na</span>(other), <span class="dv">0</span>, other),</span>
<span id="cb812-9"><a href="logistic-regression.html#cb812-9"></a>         <span class="dt">rep =</span> <span class="kw">ifelse</span>(<span class="kw">is.na</span>(rep), <span class="dv">0</span>, rep),</span>
<span id="cb812-10"><a href="logistic-regression.html#cb812-10"></a>         <span class="dt">dem_win =</span> <span class="kw">ifelse</span>(dem <span class="op">&gt;</span><span class="st"> </span>rep <span class="op">&amp;</span><span class="st"> </span>dem <span class="op">&gt;</span><span class="st"> </span>other, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="op">%&gt;%</span></span>
<span id="cb812-11"><a href="logistic-regression.html#cb812-11"></a><span class="st">  </span></span>
<span id="cb812-12"><a href="logistic-regression.html#cb812-12"></a><span class="st">  </span><span class="co"># Rename to join with state_info</span></span>
<span id="cb812-13"><a href="logistic-regression.html#cb812-13"></a><span class="st">  </span></span>
<span id="cb812-14"><a href="logistic-regression.html#cb812-14"></a><span class="st">  </span><span class="kw">rename</span>(<span class="dt">state_abbrev =</span> state_abb) <span class="op">%&gt;%</span></span>
<span id="cb812-15"><a href="logistic-regression.html#cb812-15"></a><span class="st">  </span><span class="kw">left_join</span>(state_info) <span class="op">%&gt;%</span></span>
<span id="cb812-16"><a href="logistic-regression.html#cb812-16"></a><span class="st">  </span><span class="kw">select</span>(region, state, district, year, dem_win)</span></code></pre></div>
<pre><code>## Joining, by = &quot;state_abbrev&quot;</code></pre>
<!-- DK: We use same dataset from other chapter, we need to modify this. But we won't have looked at everything! So, look at other stuff. Some is obvious, especially our new Y variable. But we can also look at stuff like number of elections per state, per year. Which state had the biggest districting rise and when? Indeed, the data exploration section in each chapter provides an occasion to learn more advanced R tricks. -->
<p>Recall the three common steps in an exploratory data analysis we saw in Subsection <a href="model1.html#model1EDA">10.1.1</a>:</p>
<ol style="list-style-type: decimal">
<li>Looking at the raw data values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>Let’s first look at the raw data values by either looking at <code>house_ch13</code> using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> function from the <strong>dplyr</strong> package:</p>
<div class="sourceCode" id="cb814"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb814-1"><a href="logistic-regression.html#cb814-1"></a><span class="kw">glimpse</span>(house_ch13)</span></code></pre></div>
<pre><code>## Rows: 9,557
## Columns: 5
## $ region   &lt;chr&gt; &quot;West&quot;, &quot;South&quot;, &quot;South&quot;, &quot;South&quot;, &quot;South&quot;, &quot;South&quot;, &quot;South&quot;…
## $ state    &lt;chr&gt; &quot;Alaska&quot;, &quot;Alabama&quot;, &quot;Alabama&quot;, &quot;Alabama&quot;, &quot;Alabama&quot;, &quot;Alaba…
## $ district &lt;chr&gt; &quot;AK-AL&quot;, &quot;AL-01&quot;, &quot;AL-02&quot;, &quot;AL-03&quot;, &quot;AL-04&quot;, &quot;AL-05&quot;, &quot;AL-06…
## $ year     &lt;dbl&gt; 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, 1976, …
## $ dem_win  &lt;dbl&gt; 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, …</code></pre>
<p>Let’s also display a random sample of 5 rows of the 9,557 rows corresponding to different district-years. Remember due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="sourceCode" id="cb816"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb816-1"><a href="logistic-regression.html#cb816-1"></a>house_ch13 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb816-2"><a href="logistic-regression.html#cb816-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dt">size =</span> <span class="dv">5</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-483">TABLE 12.1: </span>A random sample of 5 out of the 4,201 district-years
</caption>
<thead>
<tr>
<th style="text-align:left;">
region
</th>
<th style="text-align:left;">
state
</th>
<th style="text-align:left;">
district
</th>
<th style="text-align:right;">
year
</th>
<th style="text-align:right;">
dem_win
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
West
</td>
<td style="text-align:left;">
California
</td>
<td style="text-align:left;">
CA-50
</td>
<td style="text-align:right;">
2012
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Northeast
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:left;">
NY-27
</td>
<td style="text-align:right;">
1984
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Northeast
</td>
<td style="text-align:left;">
New York
</td>
<td style="text-align:left;">
NY-34
</td>
<td style="text-align:right;">
1978
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
South
</td>
<td style="text-align:left;">
Florida
</td>
<td style="text-align:left;">
FL-06
</td>
<td style="text-align:right;">
2008
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Midwest
</td>
<td style="text-align:left;">
Michigan
</td>
<td style="text-align:left;">
MI-15
</td>
<td style="text-align:right;">
1988
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table>
<p>Now that we’ve looked at the raw values in our <code>house_ch13</code> data frame and got a sense of the data, let’s compute summary statistics. As we’ve done in our exploratory data analyses before, let’s use the <code>skim()</code> function from the <code>skimr</code> package, being sure to only select() the variables of interest in our model:</p>
<div class="sourceCode" id="cb817"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb817-1"><a href="logistic-regression.html#cb817-1"></a>house_ch13 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb817-2"><a href="logistic-regression.html#cb817-2"></a><span class="st">  </span><span class="kw">select</span>(dem_win, region, year) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb817-3"><a href="logistic-regression.html#cb817-3"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-484">TABLE 12.2: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
9557
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
region
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
dem_win
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.54
</td>
<td style="text-align:right;">
0.5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
▇▁▁▁▇
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1997.00
</td>
<td style="text-align:right;">
12.7
</td>
<td style="text-align:right;">
1976
</td>
<td style="text-align:right;">
1986
</td>
<td style="text-align:right;">
1998
</td>
<td style="text-align:right;">
2008
</td>
<td style="text-align:right;">
2018
</td>
<td style="text-align:left;">
▇▆▆▆▇
</td>
</tr>
</tbody>
</table>
<p>Observe that we have no missing data, that we have 9,557 observations, and that the mean of <code>dem_win</code> is 0.54, indicating that Democrats won 54% of the House elections in this period (1976–2018).</p>
<p>Let’s now perform the last of the three common steps in an exploratory data analysis: creating data visualizations.</p>
<p>For our categorical variable, we’ll look at histograms of <code>dem_win</code> faceted by <code>region</code>:</p>
<div class="sourceCode" id="cb818"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb818-1"><a href="logistic-regression.html#cb818-1"></a>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb818-2"><a href="logistic-regression.html#cb818-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> dem_win)) <span class="op">+</span></span>
<span id="cb818-3"><a href="logistic-regression.html#cb818-3"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb818-4"><a href="logistic-regression.html#cb818-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Democratic victory percentage, 1976-2018&quot;</span>, </span>
<span id="cb818-5"><a href="logistic-regression.html#cb818-5"></a>       <span class="dt">y =</span> <span class="st">&quot;Number of districts&quot;</span>,</span>
<span id="cb818-6"><a href="logistic-regression.html#cb818-6"></a>       <span class="dt">title =</span> <span class="st">&quot;Histogram of distribution of Democratic victories by House district&quot;</span>) <span class="op">+</span></span>
<span id="cb818-7"><a href="logistic-regression.html#cb818-7"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>region) <span class="op">+</span></span>
<span id="cb818-8"><a href="logistic-regression.html#cb818-8"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-485-1.png" width="\textwidth" /></p>
<p>Wait! That doesn’t tell us very much, because our outcome variable only takes two values, 0 and 1. Let’s instead <code>group_by(district)</code> and <code>summarize()</code> to get a better sense of the distributions:</p>
<div class="sourceCode" id="cb819"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb819-1"><a href="logistic-regression.html#cb819-1"></a>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb819-2"><a href="logistic-regression.html#cb819-2"></a><span class="st">  </span><span class="kw">group_by</span>(region, district) <span class="op">%&gt;%</span></span>
<span id="cb819-3"><a href="logistic-regression.html#cb819-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">dem_win =</span> <span class="kw">mean</span>(dem_win)) <span class="op">%&gt;%</span></span>
<span id="cb819-4"><a href="logistic-regression.html#cb819-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> dem_win)) <span class="op">+</span></span>
<span id="cb819-5"><a href="logistic-regression.html#cb819-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">bins =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb819-6"><a href="logistic-regression.html#cb819-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Democratic victory percentage, 1976-2018&quot;</span>, </span>
<span id="cb819-7"><a href="logistic-regression.html#cb819-7"></a>       <span class="dt">y =</span> <span class="st">&quot;Number of districts&quot;</span>,</span>
<span id="cb819-8"><a href="logistic-regression.html#cb819-8"></a>       <span class="dt">title =</span> <span class="st">&quot;Histogram of distribution of Democratic victories by House district&quot;</span>) <span class="op">+</span></span>
<span id="cb819-9"><a href="logistic-regression.html#cb819-9"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>region) <span class="op">+</span><span class="st"> </span></span>
<span id="cb819-10"><a href="logistic-regression.html#cb819-10"></a><span class="st">  </span><span class="kw">theme_minimal</span>()</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-486-1.png" width="\textwidth" /></p>
<p>This is much more informative! We can see that the Midwest is highly bimodal, with many districts either electing Democrats for every year in this period or for none. The Northeast and West have many districts that always elect Democrats but few that never do. The South is the only region with a peak in the middle, indicating that there are many districts in the South that elected Democrats for about half the time during 1976-2018.</p>
<p>What happens if we create a scatterplot of our outcome variable <code>dem_win</code> and a continuous predictor, <code>year</code>?</p>
<div class="sourceCode" id="cb820"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb820-1"><a href="logistic-regression.html#cb820-1"></a>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb820-2"><a href="logistic-regression.html#cb820-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> dem_win)) <span class="op">+</span></span>
<span id="cb820-3"><a href="logistic-regression.html#cb820-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb820-4"><a href="logistic-regression.html#cb820-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Democratic Victory&quot;</span>) <span class="op">+</span></span>
<span id="cb820-5"><a href="logistic-regression.html#cb820-5"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-487-1.png" width="\textwidth" /></p>
<!-- DK: The below seems like good stuff, but I don't really understand it. Needs more words. Why is log(p/1-p) an interesting thing. Is it really? -->
<p>This is completely incomprehensible! When dealing with binary data, it is more helpful to construct an <em>empirical logit</em> plot instead of a regular scatterplot. The steps for constructing such a plot are as follows:</p>
<ol style="list-style-type: decimal">
<li><code>group_by</code> your continuous variable.</li>
<li><code>summarize</code> the percentage of successes in your outcome variable.</li>
<li>Calculate the <em>empirical logit</em> for each group, using the logit function: <span class="math inline">\(log\left(\frac{p}{1 - p}\right)\)</span></li>
<li>Plot the results.</li>
</ol>
<p>The logit function exists in base R as <code>qlogis()</code>. Let’s look at the empirical logit plot:</p>
<div class="sourceCode" id="cb822"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb822-1"><a href="logistic-regression.html#cb822-1"></a>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb822-2"><a href="logistic-regression.html#cb822-2"></a><span class="st">  </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span></span>
<span id="cb822-3"><a href="logistic-regression.html#cb822-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">perc_dem_win =</span> <span class="kw">mean</span>(dem_win),</span>
<span id="cb822-4"><a href="logistic-regression.html#cb822-4"></a>            <span class="dt">emplogit =</span> <span class="kw">qlogis</span>(perc_dem_win)) <span class="op">%&gt;%</span></span>
<span id="cb822-5"><a href="logistic-regression.html#cb822-5"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> emplogit)) <span class="op">+</span></span>
<span id="cb822-6"><a href="logistic-regression.html#cb822-6"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb822-7"><a href="logistic-regression.html#cb822-7"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></span>
<span id="cb822-8"><a href="logistic-regression.html#cb822-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Year&quot;</span>,</span>
<span id="cb822-9"><a href="logistic-regression.html#cb822-9"></a>       <span class="dt">y =</span> <span class="st">&quot;Empirical logits&quot;</span>) <span class="op">+</span></span>
<span id="cb822-10"><a href="logistic-regression.html#cb822-10"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-488-1.png" width="\textwidth" /></p>
<p>Now we see that after the logit transformation, there is roughly a linear relationship between our outcome variable and our explanatory variable <code>year</code>. This means that a logistic regression model makes sense. Some of the most visually apparent outliers will be familiar to students of American politics: 1994 (the “Republican Revolution”), 2008 (Obama’s first election), and 2018. Yet in general it appears that over time the Democrats have performed worse in House elections.</p>
<p>We can follow the same steps to look at this relationship within Census regions (Midwest, Northeast, South and West):</p>
<div class="sourceCode" id="cb824"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb824-1"><a href="logistic-regression.html#cb824-1"></a>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb824-2"><a href="logistic-regression.html#cb824-2"></a><span class="st">  </span><span class="kw">group_by</span>(region, year) <span class="op">%&gt;%</span></span>
<span id="cb824-3"><a href="logistic-regression.html#cb824-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">perc_dem_win =</span> <span class="kw">mean</span>(dem_win),</span>
<span id="cb824-4"><a href="logistic-regression.html#cb824-4"></a>            <span class="dt">emplogit =</span> <span class="kw">qlogis</span>(perc_dem_win)) <span class="op">%&gt;%</span></span>
<span id="cb824-5"><a href="logistic-regression.html#cb824-5"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> emplogit)) <span class="op">+</span></span>
<span id="cb824-6"><a href="logistic-regression.html#cb824-6"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb824-7"><a href="logistic-regression.html#cb824-7"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></span>
<span id="cb824-8"><a href="logistic-regression.html#cb824-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Year&quot;</span>,</span>
<span id="cb824-9"><a href="logistic-regression.html#cb824-9"></a>       <span class="dt">y =</span> <span class="st">&quot;Empirical logits&quot;</span>) <span class="op">+</span></span>
<span id="cb824-10"><a href="logistic-regression.html#cb824-10"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>region) <span class="op">+</span></span>
<span id="cb824-11"><a href="logistic-regression.html#cb824-11"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-489-1.png" width="\textwidth" /></p>
<p>We see roughly linear relationships after the logit transformation within-region as well, although the relationship looks more linear in the Midwest and South than in the Northeast and West. We see that the Democratic Party’s overall decline in House races is driven by the South and to a lesser extent the Midwest; Democratic performance has on average improved in the Northeast and West. The sharp negative slope in the South will not be surprising if one is familiar with the collapse of the “Solid South.”</p>
</div>
<div id="one-categorical-explanatory-variable" class="section level3">
<h3><span class="header-section-number">12.1.3</span> One categorical explanatory variable</h3>
<p>Let’s start our modeling by predicting <code>dem_win</code> with a single categorical explanatory variable. We’ll start with a binary variable for whether an observation is in the South and we will progress to the categorical variable <code>region</code>. As we’ll see, the syntax for running a logistic regression in R is very similar to that for running a linear regression. In fact, we’ll follow the same basic steps:</p>
<ol style="list-style-type: decimal">
<li>We first “fit” the logistic regression model using the <code>glm(y ~ x, family, data)</code> function and save it in <code>house_region_model</code>.</li>
<li>We get the regression table by applying the <code>tidy()</code> function from the <strong>broom</strong> package to <code>house_region_model</code>. We’ll print the <code>term</code>, <code>estimate</code>, <code>conf.low</code>, and <code>conf.high</code> columns.</li>
</ol>
<p>Note that the key difference is that instead of using <code>lm()</code>, we are now using <code>glm()</code>. <code>glm()</code> operates very similarly to <code>lm()</code>, but it has an additional argument: <code>family</code>. To run a logistic regression, we use <code>family = binomial</code>.</p>
<p>Let’s create a binary variable for whether an observation is in the South:</p>
<div class="sourceCode" id="cb826"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb826-1"><a href="logistic-regression.html#cb826-1"></a>house_ch13 &lt;-<span class="st"> </span>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb826-2"><a href="logistic-regression.html#cb826-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">south =</span> <span class="dv">1</span> <span class="op">*</span><span class="st"> </span>(region <span class="op">==</span><span class="st"> &quot;South&quot;</span>))</span></code></pre></div>
<p>Next, let’s fit a model and <code>tidy()</code> it:</p>
<div class="sourceCode" id="cb827"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb827-1"><a href="logistic-regression.html#cb827-1"></a>house_south_model &lt;-<span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>south, <span class="dt">family =</span> binomial, <span class="dt">data =</span> house_ch13)</span>
<span id="cb827-2"><a href="logistic-regression.html#cb827-2"></a>house_south_model <span class="op">%&gt;%</span></span>
<span id="cb827-3"><a href="logistic-regression.html#cb827-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb827-4"><a href="logistic-regression.html#cb827-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-493">TABLE 12.3: </span>Logistic regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.230
</td>
</tr>
<tr>
<td style="text-align:left;">
south
</td>
<td style="text-align:right;">
-0.249
</td>
</tr>
</tbody>
</table>
<p>How can we interpret the coefficients? Unlike linear regressions, these coefficients aren’t directly interpretable. Recall our logistic regression model equation:</p>
<p><span class="math display">\[
\log\left(\frac{p}{1 - p}\right)=\beta_0+\beta_1X 
\]</span></p>
<p>A one-unit change in <span class="math inline">\(X\)</span> thus is associated with a one-unit change in <span class="math inline">\(log\left(\frac{p}{1 - p}\right)\)</span>, where <span class="math inline">\(p\)</span> is the predicted probability of success. It is hard to understand intuitively what this means.</p>
<p>However, with only two possible values for the predictors (<code>south</code> = 0 or <code>south</code> = 1), we can directly calculate all the possible values of <span class="math inline">\(p\)</span> this model by using the <em>standard logistic function</em>:</p>
<p><span class="math display">\[
p = \frac{1}{1 + e^{-(\beta_0+\beta_1X)}} 
\]</span></p>
<p>This can easily be done using the <code>plogis()</code> function in R.</p>
<p>Thus, for our example, we have:</p>
<p><span class="math display">\[
p_{dem\_win} = \frac{1}{1 + e^{-(0.230 - 0.249 \times south)}} 
\]</span></p>
<p>Therefore, the predicted probability for an observation in the South is <span class="math inline">\(\frac{1}{1 + e^{-(0.230 - 0.249)}}\)</span> (0.495) and the predicted probability for an observation outside the South is <span class="math inline">\(\frac{1}{1 + e^{-(0.230)}}\)</span> (0.557) a difference of -0.062. Thus, an observation being the South is associated with a -0.062 decrease in the predicted probability of a Democratic victory.</p>
<p>Note that you could also estimate this value through the so-called <strong>“divide by 4” rule</strong>: <span class="math inline">\(-0.249 / 4 \approx 0.062\)</span>. We’ll discuss this further when we talk about interpreting the coefficiences of continuous predictors in logistic regression models.</p>
<p>Let’s now estimate the uncertainty around our coefficients. We’ll start by showing how you can do this through the bootstrap. We’ll begin by loading the <strong>infer</strong> package. We’re going to use the function <code>rep_sample_n()</code> to resample from our data 1,000 times:</p>
<div class="sourceCode" id="cb828"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb828-1"><a href="logistic-regression.html#cb828-1"></a><span class="kw">library</span>(infer)</span>
<span id="cb828-2"><a href="logistic-regression.html#cb828-2"></a></span>
<span id="cb828-3"><a href="logistic-regression.html#cb828-3"></a>x &lt;-<span class="st"> </span>house_ch13 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb828-4"><a href="logistic-regression.html#cb828-4"></a><span class="st">  </span><span class="kw">select</span>(dem_win, south) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb828-5"><a href="logistic-regression.html#cb828-5"></a><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="kw">nrow</span>(house_ch13), <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">1000</span>)</span>
<span id="cb828-6"><a href="logistic-regression.html#cb828-6"></a></span>
<span id="cb828-7"><a href="logistic-regression.html#cb828-7"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 9,557,000 x 3
## # Groups:   replicate [1,000]
##    replicate dem_win south
##        &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1         1       1     1
##  2         1       1     0
##  3         1       1     1
##  4         1       1     0
##  5         1       0     1
##  6         1       0     1
##  7         1       0     0
##  8         1       0     1
##  9         1       0     1
## 10         1       1     0
## # … with 9,556,990 more rows</code></pre>
<p>For each <code>replicate</code>, we have 9557 resamples of <code>dem_win</code> and <code>south</code>.</p>
<p>Next, we are going to <code>nest()</code> our data by <code>replicate</code>:</p>
<div class="sourceCode" id="cb830"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb830-1"><a href="logistic-regression.html#cb830-1"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb830-2"><a href="logistic-regression.html#cb830-2"></a><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb830-3"><a href="logistic-regression.html#cb830-3"></a><span class="st">  </span><span class="kw">nest</span>()</span>
<span id="cb830-4"><a href="logistic-regression.html#cb830-4"></a></span>
<span id="cb830-5"><a href="logistic-regression.html#cb830-5"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
## # Groups:   replicate [1,000]
##    replicate data                
##        &lt;int&gt; &lt;list&gt;              
##  1         1 &lt;tibble [9,557 × 2]&gt;
##  2         2 &lt;tibble [9,557 × 2]&gt;
##  3         3 &lt;tibble [9,557 × 2]&gt;
##  4         4 &lt;tibble [9,557 × 2]&gt;
##  5         5 &lt;tibble [9,557 × 2]&gt;
##  6         6 &lt;tibble [9,557 × 2]&gt;
##  7         7 &lt;tibble [9,557 × 2]&gt;
##  8         8 &lt;tibble [9,557 × 2]&gt;
##  9         9 &lt;tibble [9,557 × 2]&gt;
## 10        10 &lt;tibble [9,557 × 2]&gt;
## # … with 990 more rows</code></pre>
<p>After grouping by <code>replicate</code> and using <code>nest()</code>, we now have a dataset of 1,000 rows and a list column named <code>data</code>. Each element of <code>data</code> is a tibble consisting of one of the resampled datasets we created using <code>rep_sample_n()</code>.</p>
<p>Now, we can use <code>map()</code> to run our logistic regression for each dataset:</p>
<div class="sourceCode" id="cb832"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb832-1"><a href="logistic-regression.html#cb832-1"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb832-2"><a href="logistic-regression.html#cb832-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>south, <span class="dt">family =</span> binomial, <span class="dt">data =</span> .)))</span>
<span id="cb832-3"><a href="logistic-regression.html#cb832-3"></a></span>
<span id="cb832-4"><a href="logistic-regression.html#cb832-4"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 3
## # Groups:   replicate [1,000]
##    replicate data                 mod   
##        &lt;int&gt; &lt;list&gt;               &lt;list&gt;
##  1         1 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  2         2 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  3         3 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  4         4 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  5         5 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  6         6 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  7         7 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  8         8 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
##  9         9 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
## 10        10 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt; 
## # … with 990 more rows</code></pre>
<p>Now we have a new list column, <code>mod</code>, that contains the model objects created by <code>glm()</code>. We will now want to <code>tidy()</code> the object created by <code>glm()</code>:</p>
<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb834-1"><a href="logistic-regression.html#cb834-1"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb834-2"><a href="logistic-regression.html#cb834-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(.)))</span>
<span id="cb834-3"><a href="logistic-regression.html#cb834-3"></a></span>
<span id="cb834-4"><a href="logistic-regression.html#cb834-4"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 4
## # Groups:   replicate [1,000]
##    replicate data                 mod    reg_results     
##        &lt;int&gt; &lt;list&gt;               &lt;list&gt; &lt;list&gt;          
##  1         1 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  2         2 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  3         3 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  4         4 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  5         5 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  6         6 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  7         7 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  8         8 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
##  9         9 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
## 10        10 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;
## # … with 990 more rows</code></pre>
<p><code>tidy()</code> stores the coefficients in the <code>estimate</code> column, with each coefficient named in the <code>term</code> column. Thus, if we <code>filter()</code> by <code>term</code> and <code>pull(estimate)</code>, we can get the logistic regression coefficient for each bootstrap sample:</p>
<div class="sourceCode" id="cb836"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb836-1"><a href="logistic-regression.html#cb836-1"></a>x &lt;-<span class="st"> </span>x <span class="op">%&gt;%</span></span>
<span id="cb836-2"><a href="logistic-regression.html#cb836-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">disp_coef =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;south&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(estimate)))</span>
<span id="cb836-3"><a href="logistic-regression.html#cb836-3"></a></span>
<span id="cb836-4"><a href="logistic-regression.html#cb836-4"></a>x</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 5
## # Groups:   replicate [1,000]
##    replicate data                 mod    reg_results      disp_coef
##        &lt;int&gt; &lt;list&gt;               &lt;list&gt; &lt;list&gt;               &lt;dbl&gt;
##  1         1 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.252
##  2         2 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.289
##  3         3 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.203
##  4         4 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.220
##  5         5 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.209
##  6         6 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.203
##  7         7 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.218
##  8         8 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.313
##  9         9 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.252
## 10        10 &lt;tibble [9,557 × 2]&gt; &lt;glm&gt;  &lt;tibble [2 × 5]&gt;    -0.224
## # … with 990 more rows</code></pre>
<p>Now that we have 1,000 estimates from our bootstrap samples, we can construct a percentile-based confidence interval easily:</p>
<div class="sourceCode" id="cb838"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb838-1"><a href="logistic-regression.html#cb838-1"></a>x <span class="op">%&gt;%</span></span>
<span id="cb838-2"><a href="logistic-regression.html#cb838-2"></a><span class="st"> </span><span class="kw">pull</span>(disp_coef) <span class="op">%&gt;%</span></span>
<span id="cb838-3"><a href="logistic-regression.html#cb838-3"></a><span class="st"> </span><span class="kw">quantile</span>(<span class="kw">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>##   2.5%    50%  97.5% 
## -0.333 -0.249 -0.166</code></pre>
<p>As we’ve seen before, these are very similar to what we observe using <code>tidy(conf.int = TRUE)</code>:</p>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb840-1"><a href="logistic-regression.html#cb840-1"></a>house_south_model <span class="op">%&gt;%</span></span>
<span id="cb840-2"><a href="logistic-regression.html#cb840-2"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb840-3"><a href="logistic-regression.html#cb840-3"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-501">TABLE 12.4: </span>Logistic regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.230
</td>
<td style="text-align:right;">
0.181
</td>
<td style="text-align:right;">
0.280
</td>
</tr>
<tr>
<td style="text-align:left;">
south
</td>
<td style="text-align:right;">
-0.249
</td>
<td style="text-align:right;">
-0.334
</td>
<td style="text-align:right;">
-0.164
</td>
</tr>
</tbody>
</table>
<p>Thus, from now on, we’ll just use <code>tidy(conf.int = TRUE)</code> when working with <code>glm()</code>, just as we did with <code>lm()</code>.</p>
<p>Let’s try running a slightly more complicated version of the above model, where we use <code>region</code> as a predictor instead of <code>south</code>.</p>
<div class="sourceCode" id="cb841"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb841-1"><a href="logistic-regression.html#cb841-1"></a>house_region_model &lt;-<span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>region, <span class="dt">family =</span> binomial, <span class="dt">data =</span> house_ch13)</span>
<span id="cb841-2"><a href="logistic-regression.html#cb841-2"></a>house_region_model <span class="op">%&gt;%</span></span>
<span id="cb841-3"><a href="logistic-regression.html#cb841-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb841-4"><a href="logistic-regression.html#cb841-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-504">TABLE 12.5: </span>Logistic regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-0.076
</td>
<td style="text-align:right;">
-0.157
</td>
<td style="text-align:right;">
0.006
</td>
</tr>
<tr>
<td style="text-align:left;">
regionNortheast
</td>
<td style="text-align:right;">
0.657
</td>
<td style="text-align:right;">
0.534
</td>
<td style="text-align:right;">
0.780
</td>
</tr>
<tr>
<td style="text-align:left;">
regionSouth
</td>
<td style="text-align:right;">
0.056
</td>
<td style="text-align:right;">
-0.050
</td>
<td style="text-align:right;">
0.163
</td>
</tr>
<tr>
<td style="text-align:left;">
regionWest
</td>
<td style="text-align:right;">
0.333
</td>
<td style="text-align:right;">
0.213
</td>
<td style="text-align:right;">
0.453
</td>
</tr>
</tbody>
</table>
<p>The intercept here is the omitted category, the Midwest. We can calculate the predicted probabilities for each category:</p>
<ul>
<li>Midwest: <span class="math inline">\(\frac{1}{1 + e^{-(-0.076)}} = 0.481\)</span></li>
<li>Northeast: <span class="math inline">\(\frac{1}{1 + e^{-(-0.076 + 0.657)}} = 0.641\)</span></li>
<li>South: <span class="math inline">\(\frac{1}{1 + e^{-(-0.076 + 0.056)}} = 0.495\)</span></li>
<li>West: <span class="math inline">\(\frac{1}{1 + e^{-(-0.076 + 0.333)}} = 0.564\)</span></li>
</ul>
<p>We can then interpret the effect of moving from one category to another. For example, the effect of being in the Northeast as opposed to the Midwest is 0.16; the predicted probability of a Democratic victory in the Northeast is 0.16 greater than in the Midwest. Note too that we could have obtained this through the “divide by 4” rule: <span class="math inline">\(0.657 / 4 \approx 0.16\)</span>.</p>
</div>
<div id="observedfitted-values-and-residuals" class="section level3">
<h3><span class="header-section-number">12.1.4</span> Observed/fitted values and residuals</h3>
<p>We have previously defined the following three concepts for a linear regression:</p>
<ol style="list-style-type: decimal">
<li>Observed values <span class="math inline">\(y\)</span>, or the observed value of the outcome variable</li>
<li>Fitted values <span class="math inline">\(\widehat{y}\)</span>, or the value on the regression line for a given <span class="math inline">\(x\)</span> value</li>
<li>Residuals <span class="math inline">\(y - \widehat{y}\)</span>, or the error between the observed value and the fitted value</li>
</ol>
<p>We obtained these values and other values using the <code>augment()</code> function from the <strong>broom</strong> package. Recall too that we used the <code>.se.fit</code> column to construct confidence intervals. We’ll see here how we can apply these same concepts to logistic regression.</p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb842-1"><a href="logistic-regression.html#cb842-1"></a>regression_points &lt;-<span class="st"> </span>house_region_model <span class="op">%&gt;%</span></span>
<span id="cb842-2"><a href="logistic-regression.html#cb842-2"></a><span class="st">  </span><span class="kw">augment</span>() <span class="op">%&gt;%</span></span>
<span id="cb842-3"><a href="logistic-regression.html#cb842-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb842-4"><a href="logistic-regression.html#cb842-4"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb842-5"><a href="logistic-regression.html#cb842-5"></a><span class="st">  </span><span class="kw">select</span>(dem_win, region, .fitted, conf.low, conf.high, .resid)</span>
<span id="cb842-6"><a href="logistic-regression.html#cb842-6"></a>regression_points</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-506">TABLE 12.6: </span>Regression points (First 10 out of 4,201 district-years)
</caption>
<thead>
<tr>
<th style="text-align:right;">
dem_win
</th>
<th style="text-align:left;">
region
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
.resid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
West
</td>
<td style="text-align:right;">
0.257
</td>
<td style="text-align:right;">
0.168
</td>
<td style="text-align:right;">
0.347
</td>
<td style="text-align:right;">
-1.29
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
-0.019
</td>
<td style="text-align:right;">
-0.089
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
</tbody>
</table>
<p>The syntax is the same, but the interpretation has to change, since the <code>.fitted</code>, <code>conf.low</code>, and <code>conf.high</code> columns are all on the logit scale. While we could try to interpret these values, <code>augment()</code> has the argument <code>type.predict = "response"</code> that allow us to present the results in terms of <em>predicted probabilities</em>:</p>
<div class="sourceCode" id="cb843"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb843-1"><a href="logistic-regression.html#cb843-1"></a>regression_points &lt;-<span class="st"> </span>house_region_model <span class="op">%&gt;%</span></span>
<span id="cb843-2"><a href="logistic-regression.html#cb843-2"></a><span class="st">  </span><span class="kw">augment</span>(<span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb843-3"><a href="logistic-regression.html#cb843-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb843-4"><a href="logistic-regression.html#cb843-4"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb843-5"><a href="logistic-regression.html#cb843-5"></a><span class="st">  </span><span class="kw">select</span>(dem_win, region, .fitted, conf.low, conf.high, .resid)</span>
<span id="cb843-6"><a href="logistic-regression.html#cb843-6"></a>regression_points</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-508">TABLE 12.7: </span>Regression points (First 10 out of 4,201 district-years)
</caption>
<thead>
<tr>
<th style="text-align:right;">
dem_win
</th>
<th style="text-align:left;">
region
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
.resid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
West
</td>
<td style="text-align:right;">
0.564
</td>
<td style="text-align:right;">
0.542
</td>
<td style="text-align:right;">
0.586
</td>
<td style="text-align:right;">
-1.29
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-1.17
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
1.19
</td>
</tr>
</tbody>
</table>
<p>Now each of the <code>.fitted</code> values is a <em>predicted probability</em> of a Democratic victory from our model for a particular district and the confidence intervals are confidence intervals around that predicted probability.</p>
<p>You may be wondering how to interpret the residuals. The residuals reported by <code>augment()</code> for a logistic regression are called <em>deviance residuals</em>. A deviance residual can be calculated for each observation using:</p>
<p><span class="math display">\[
\textrm{d}_i = 
\textrm{sign}(Y_i-\hat{p_i})\sqrt{-2 [ Y_i \text{log} \hat{p_i} + (1 - Y_i) \text{log} (1 - \hat{p_i}) ]}
\]</span></p>
<p>where <span class="math inline">\(Y_i\)</span> is the actual outcome and <span class="math inline">\(p_i\)</span> is the predicted probability from the logistic regression model.</p>
<p>The sum of the individual deviance residuals is referred to as the <strong>deviance</strong> or <strong>residual deviance</strong>. The deviance is used to assess the model. As the name suggests, a model with a small deviance is preferred.</p>
<p>However, you can also have <code>augment()</code> report residuals as differences between the observed outcome and the predicted probabilities by using <code>type.residuals = "response"</code>:</p>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb844-1"><a href="logistic-regression.html#cb844-1"></a>regression_points &lt;-<span class="st"> </span>house_region_model <span class="op">%&gt;%</span></span>
<span id="cb844-2"><a href="logistic-regression.html#cb844-2"></a><span class="st">  </span><span class="kw">augment</span>(<span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>,</span>
<span id="cb844-3"><a href="logistic-regression.html#cb844-3"></a>          <span class="dt">type.residuals =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb844-4"><a href="logistic-regression.html#cb844-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb844-5"><a href="logistic-regression.html#cb844-5"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb844-6"><a href="logistic-regression.html#cb844-6"></a><span class="st">  </span><span class="kw">select</span>(dem_win, region, .fitted, conf.low, conf.high, .resid)</span>
<span id="cb844-7"><a href="logistic-regression.html#cb844-7"></a>regression_points</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-510">TABLE 12.8: </span>Regression points (First 10 out of 4,201 district-years)
</caption>
<thead>
<tr>
<th style="text-align:right;">
dem_win
</th>
<th style="text-align:left;">
region
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
.resid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
West
</td>
<td style="text-align:right;">
0.564
</td>
<td style="text-align:right;">
0.542
</td>
<td style="text-align:right;">
0.586
</td>
<td style="text-align:right;">
-0.564
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-0.495
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-0.495
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
-0.495
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.495
</td>
<td style="text-align:right;">
0.478
</td>
<td style="text-align:right;">
0.513
</td>
<td style="text-align:right;">
0.505
</td>
</tr>
</tbody>
</table>
<p>Now, the <code>.resid</code> value is the difference between the actual outcome (<code>dem_win</code>) and the predicted probability.</p>
</div>
<div id="one-numerical-explanatory-variable" class="section level3">
<h3><span class="header-section-number">12.1.5</span> One numerical explanatory variable</h3>
<p>We’ll now predict <code>dem_win</code> with a single numerical explanatory variable, <code>year</code>.</p>
<ol style="list-style-type: decimal">
<li>We first “fit” the logistic regression model using the <code>glm(y ~ x, family, data)</code> function and save it in <code>house_year_model</code>.</li>
<li>We get the regression table by applying the <code>tidy()</code> function from the <strong>broom</strong> package to <code>house_year_model</code>. We’ll print the <code>term</code>, <code>estimate</code>, <code>conf.low</code>, and <code>conf.high</code> columns.</li>
</ol>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="logistic-regression.html#cb845-1"></a>house_year_model &lt;-<span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>year, <span class="dt">family =</span> binomial, <span class="dt">data =</span> house_ch13)</span>
<span id="cb845-2"><a href="logistic-regression.html#cb845-2"></a>house_year_model <span class="op">%&gt;%</span></span>
<span id="cb845-3"><a href="logistic-regression.html#cb845-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb845-4"><a href="logistic-regression.html#cb845-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-513">TABLE 12.9: </span>Logistic regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
34.487
</td>
<td style="text-align:right;">
28.10
</td>
<td style="text-align:right;">
40.888
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
-0.017
</td>
<td style="text-align:right;">
-0.02
</td>
<td style="text-align:right;">
-0.014
</td>
</tr>
</tbody>
</table>
<p>How do we interpret the coefficients in this model? Since the <code>year</code> coefficient is negative, that means that each additional year is associated with a reduction in the chances of a Democratic victory.</p>
<p>If we wanted to learn the predicted probabilities for any given value of <code>year</code>, we can plug in our values of <code>year</code> into the standard logistic function, like so:</p>
<p><span class="math display">\[
p_{dem\_win} = \frac{1}{1 + e^{-(34.487 - 0.017 \times year)}} 
\]</span></p>
<p>Note that since this is not a linear function, a one-unit change in <code>year</code> will be associated with various one-unit changes in <code>dem_win</code>, depending on what <code>year</code> you are starting from. Recall the figure we used to start the chapter:</p>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-514-1.png" width="\textwidth" /></p>
<p>A linear regression line (in blue) has a constant slope, which means that no matter what <span class="math inline">\(x\)</span> you start with, the effect of going from <span class="math inline">\(x\)</span> to <span class="math inline">\(x + 1\)</span> on <span class="math inline">\(y\)</span> is the same number.</p>
<p>However, take a look at the logistic regression curve (in red). The value of the slope for very high or very low values of <span class="math inline">\(x\)</span> is smaller (approaching 0 as <span class="math inline">\(x\)</span> tends to negative or positive infinity), while the slope in the middle of the curve is highest. The steepest part of the curve corresponds to that part of the curve where the predicted probability equals 0.5. That is, the effect of a one-unit change in <span class="math inline">\(x\)</span> is the highest when the predicted probability for that <span class="math inline">\(x\)</span> is close to 0.5 and smallest when the predicted probability for that <span class="math inline">\(x\)</span> is close to 0 or 1.</p>
<p>You can always use R to calculate the predicted probabilities for any value of <span class="math inline">\(x\)</span> and thus calculate the effect of moving from a particular <span class="math inline">\(x\)</span> to <span class="math inline">\(x + 1\)</span>. But this can get complicated. In particular, once you start employing logistic regression with multiple predictors, the effect of a one-unit change in a predictor <span class="math inline">\(x\)</span> depends not only on <span class="math inline">\(x\)</span>, but on the values of all the other predictors in your model! You can always plug in all the coefficients and values of your predictors into the logistic function to calculate predicted probabilities, but if you don’t do that, how can you interpret the coefficients?</p>
<p>Here is where we can use the <em>divide by 4 rule</em> that we discussed before. A logistic regression coefficient divided by 4 is the effect of that variable at the steepest part of the logistic regression curve, which, as we saw, corresponds to where the predicted probability is 0.5.</p>
<p>Therefore, you can divide a logistic regression coefficient by 4 to get an upper bound on the effect a one-unit change in that predictor will have on the predicted probability of your outcome. In this case, the approximation tells us that each additional year is associated with about a <span class="math inline">\(-0.004\)</span> decrease in the predicted probability of a Democratic victory. Since the predicted probability of a Democratic victory in this model never strays far from 0.5, this is a pretty good approximation.<a href="#fn17" class="footnote-ref" id="fnref17"><sup>17</sup></a></p>
<p>While <code>house_region_model</code> and <code>house_year_model</code> both tell us something interesting, we could learn more with an <em>interaction model</em> that includes both of our predictors.</p>
</div>
<div id="one-numerical-and-one-categorical-explanatory-variable" class="section level3">
<h3><span class="header-section-number">12.1.6</span> One numerical and one categorical explanatory variable</h3>
<p>We’ll now predict <code>dem_win</code> with a two variable, <code>region</code> and <code>year</code>, as well as the interaction between the two</p>
<ol style="list-style-type: decimal">
<li>We first “fit” the logistic regression model using the <code>glm(y ~ x1 * x2, family, data)</code> function and save it in <code>house_interact_model</code>.</li>
<li>We get the regression table by applying the <code>tidy()</code> function from the <strong>broom</strong> package to <code>house_interact_model</code>. We’ll print the <code>term</code>, <code>estimate</code>, <code>conf.low</code>, and <code>conf.high</code> columns.</li>
</ol>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb846-1"><a href="logistic-regression.html#cb846-1"></a>house_interact_model &lt;-<span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>region <span class="op">*</span><span class="st"> </span>year, <span class="dt">family =</span> binomial <span class="dt">data =</span> house_ch13)</span>
<span id="cb846-2"><a href="logistic-regression.html#cb846-2"></a>house_interact_model <span class="op">%&gt;%</span></span>
<span id="cb846-3"><a href="logistic-regression.html#cb846-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb846-4"><a href="logistic-regression.html#cb846-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-517">TABLE 12.10: </span>Logistic regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
36.395
</td>
<td style="text-align:right;">
23.504
</td>
<td style="text-align:right;">
49.361
</td>
</tr>
<tr>
<td style="text-align:left;">
regionNortheast
</td>
<td style="text-align:right;">
-56.548
</td>
<td style="text-align:right;">
-76.099
</td>
<td style="text-align:right;">
-37.066
</td>
</tr>
<tr>
<td style="text-align:left;">
regionSouth
</td>
<td style="text-align:right;">
61.388
</td>
<td style="text-align:right;">
43.926
</td>
<td style="text-align:right;">
78.877
</td>
</tr>
<tr>
<td style="text-align:left;">
regionWest
</td>
<td style="text-align:right;">
-51.520
</td>
<td style="text-align:right;">
-70.633
</td>
<td style="text-align:right;">
-32.457
</td>
</tr>
<tr>
<td style="text-align:left;">
year
</td>
<td style="text-align:right;">
-0.018
</td>
<td style="text-align:right;">
-0.025
</td>
<td style="text-align:right;">
-0.012
</td>
</tr>
<tr>
<td style="text-align:left;">
regionNortheast:year
</td>
<td style="text-align:right;">
0.029
</td>
<td style="text-align:right;">
0.019
</td>
<td style="text-align:right;">
0.038
</td>
</tr>
<tr>
<td style="text-align:left;">
regionSouth:year
</td>
<td style="text-align:right;">
-0.031
</td>
<td style="text-align:right;">
-0.039
</td>
<td style="text-align:right;">
-0.022
</td>
</tr>
<tr>
<td style="text-align:left;">
regionWest:year
</td>
<td style="text-align:right;">
0.026
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
0.036
</td>
</tr>
</tbody>
</table>
<p>Now we can see how the effect of <code>year</code> varies by <code>region</code>. While the passage of time is associated with more Democratic victories in the Northeast and the West, <code>year</code> is associated with declining Democratic fortunes in the Midwest (<code>year</code>) and the South (<code>regionSouth:year</code>).</p>
<p>Looking at predicted probabilities can also put this model in perspective. Let’s use <code>augment()</code> to generate the predictions. Remember that <code>type.predict = "response"</code> and <code>type.residuals = "response"</code> put the fitted values and the residuals on the probability scale.</p>
<div class="sourceCode" id="cb847"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb847-1"><a href="logistic-regression.html#cb847-1"></a>regression_points &lt;-<span class="st"> </span>house_interact_model <span class="op">%&gt;%</span></span>
<span id="cb847-2"><a href="logistic-regression.html#cb847-2"></a><span class="st">  </span><span class="kw">augment</span>(<span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>,</span>
<span id="cb847-3"><a href="logistic-regression.html#cb847-3"></a>          <span class="dt">type.residuals =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb847-4"><a href="logistic-regression.html#cb847-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb847-5"><a href="logistic-regression.html#cb847-5"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb847-6"><a href="logistic-regression.html#cb847-6"></a><span class="st">  </span><span class="kw">select</span>(dem_win, region, .fitted, conf.low, conf.high, .resid)</span>
<span id="cb847-7"><a href="logistic-regression.html#cb847-7"></a>regression_points</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-519">TABLE 12.11: </span>Regression points (First 10 out of 4,201 district-years)
</caption>
<thead>
<tr>
<th style="text-align:right;">
dem_win
</th>
<th style="text-align:left;">
region
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
.resid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
West
</td>
<td style="text-align:right;">
0.522
</td>
<td style="text-align:right;">
0.477
</td>
<td style="text-align:right;">
0.567
</td>
<td style="text-align:right;">
-0.522
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
-0.739
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
-0.739
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
-0.739
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
South
</td>
<td style="text-align:right;">
0.739
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
0.768
</td>
<td style="text-align:right;">
0.261
</td>
</tr>
</tbody>
</table>
<p>We can also use <code>augment</code> to make predictions for years that aren’t in our data. What would our model predict for the 2020 elections? We use the <code>newdata</code> argument in <code>augment()</code> to make these predictions.</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb848-1"><a href="logistic-regression.html#cb848-1"></a>house_interact_model <span class="op">%&gt;%</span></span>
<span id="cb848-2"><a href="logistic-regression.html#cb848-2"></a><span class="st">  </span><span class="kw">augment</span>(<span class="dt">newdata =</span> <span class="kw">tibble</span>(<span class="dt">year =</span> <span class="kw">rep</span>(<span class="dv">2020</span>, <span class="dv">4</span>),</span>
<span id="cb848-3"><a href="logistic-regression.html#cb848-3"></a>                           <span class="dt">region =</span> <span class="kw">c</span>(<span class="st">&quot;Midwest&quot;</span>, <span class="st">&quot;Northeast&quot;</span>, <span class="st">&quot;South&quot;</span>, <span class="st">&quot;West&quot;</span>)),</span>
<span id="cb848-4"><a href="logistic-regression.html#cb848-4"></a>          <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb848-5"><a href="logistic-regression.html#cb848-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb848-6"><a href="logistic-regression.html#cb848-6"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit)</span></code></pre></div>
<pre><code>## # A tibble: 4 x 6
##    year region    .fitted .se.fit conf.low conf.high
##   &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1  2020 Midwest     0.374  0.0211    0.332     0.416
## 2  2020 Northeast   0.697  0.0218    0.654     0.741
## 3  2020 South       0.248  0.0142    0.219     0.276
## 4  2020 West        0.605  0.0217    0.562     0.648</code></pre>
<p>These can easily be plotted using <code>ggplot()</code>:</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb850-1"><a href="logistic-regression.html#cb850-1"></a>house_interact_model <span class="op">%&gt;%</span></span>
<span id="cb850-2"><a href="logistic-regression.html#cb850-2"></a><span class="st">  </span><span class="kw">augment</span>(<span class="dt">newdata =</span> <span class="kw">tibble</span>(<span class="dt">year =</span> <span class="kw">rep</span>(<span class="dv">2020</span>, <span class="dv">4</span>),</span>
<span id="cb850-3"><a href="logistic-regression.html#cb850-3"></a>                           <span class="dt">region =</span> <span class="kw">c</span>(<span class="st">&quot;Midwest&quot;</span>, <span class="st">&quot;Northeast&quot;</span>, <span class="st">&quot;South&quot;</span>, <span class="st">&quot;West&quot;</span>)),</span>
<span id="cb850-4"><a href="logistic-regression.html#cb850-4"></a>          <span class="dt">type.predict =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb850-5"><a href="logistic-regression.html#cb850-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb850-6"><a href="logistic-regression.html#cb850-6"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb850-7"><a href="logistic-regression.html#cb850-7"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">y =</span> .fitted,</span>
<span id="cb850-8"><a href="logistic-regression.html#cb850-8"></a>             <span class="dt">ymin =</span> conf.low,</span>
<span id="cb850-9"><a href="logistic-regression.html#cb850-9"></a>             <span class="dt">ymax =</span> conf.high,</span>
<span id="cb850-10"><a href="logistic-regression.html#cb850-10"></a>             <span class="dt">x =</span> region)) <span class="op">+</span></span>
<span id="cb850-11"><a href="logistic-regression.html#cb850-11"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb850-12"><a href="logistic-regression.html#cb850-12"></a><span class="st">  </span><span class="kw">geom_errorbar</span>() <span class="op">+</span></span>
<span id="cb850-13"><a href="logistic-regression.html#cb850-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Predicted probability of a Democratic victory (2020)&quot;</span>,</span>
<span id="cb850-14"><a href="logistic-regression.html#cb850-14"></a>       <span class="dt">x =</span> <span class="st">&quot;&quot;</span>) <span class="op">+</span></span>
<span id="cb850-15"><a href="logistic-regression.html#cb850-15"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-521-1.png" width="\textwidth" /></p>
</div>
<div id="fitting-many-models-using-map-1" class="section level3">
<h3><span class="header-section-number">12.1.7</span> Fitting many models using <code>map()</code></h3>
<p>While it is interesting to see how Democrats perform by region over time, it would also be interesting to see how each state has changed in its partisan voting from 1976–2018. Have any seen particularly large increases (or decreases) in the probability of a Democratic candidate winning?</p>
<p>The code to do this is very similar to the code we used for the gubernatorial forecasts in Chapter <a href="regression.html#regression">10</a> and the Seattle house prices in Chapter <a href="multiple-regression.html#multiple-regression">11</a>. However, we will use <code>glm()</code> instead of <code>lm()</code>.</p>
<p>First, we’ll filter to the states that have at least 50 district-years in the dataset. Next, let’s use <code>map()</code> to learn about these districts:</p>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="logistic-regression.html#cb851-1"></a>infreq_states &lt;-<span class="st"> </span>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb851-2"><a href="logistic-regression.html#cb851-2"></a><span class="st">  </span><span class="kw">count</span>(state) <span class="op">%&gt;%</span></span>
<span id="cb851-3"><a href="logistic-regression.html#cb851-3"></a><span class="st">  </span><span class="kw">filter</span>(n <span class="op">&lt;</span><span class="st"> </span><span class="dv">50</span>) <span class="op">%&gt;%</span></span>
<span id="cb851-4"><a href="logistic-regression.html#cb851-4"></a><span class="st">  </span><span class="kw">pull</span>(state)</span>
<span id="cb851-5"><a href="logistic-regression.html#cb851-5"></a></span>
<span id="cb851-6"><a href="logistic-regression.html#cb851-6"></a>house_state_model &lt;-<span class="st"> </span>house_ch13 <span class="op">%&gt;%</span></span>
<span id="cb851-7"><a href="logistic-regression.html#cb851-7"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="st"> </span>state <span class="op">%in%</span><span class="st">  </span>infreq_states) <span class="op">%&gt;%</span></span>
<span id="cb851-8"><a href="logistic-regression.html#cb851-8"></a><span class="st">  </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span></span>
<span id="cb851-9"><a href="logistic-regression.html#cb851-9"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb851-10"><a href="logistic-regression.html#cb851-10"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">glm</span>(dem_win <span class="op">~</span><span class="st"> </span>year, <span class="dt">family =</span> binomial, <span class="dt">data =</span> .)),</span>
<span id="cb851-11"><a href="logistic-regression.html#cb851-11"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(., <span class="dt">conf.int =</span> <span class="ot">TRUE</span>)),</span>
<span id="cb851-12"><a href="logistic-regression.html#cb851-12"></a>         <span class="dt">year_coef =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;year&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(estimate)),</span>
<span id="cb851-13"><a href="logistic-regression.html#cb851-13"></a>         <span class="dt">year_low =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;year&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(conf.low)),</span>
<span id="cb851-14"><a href="logistic-regression.html#cb851-14"></a>         <span class="dt">year_high =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;year&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(conf.high)))</span>
<span id="cb851-15"><a href="logistic-regression.html#cb851-15"></a></span>
<span id="cb851-16"><a href="logistic-regression.html#cb851-16"></a><span class="kw">glimpse</span>(house_state_model)</span></code></pre></div>
<pre><code>## Rows: 38
## Columns: 7
## Groups: state [38]
## $ state       &lt;chr&gt; &quot;Alabama&quot;, &quot;Arkansas&quot;, &quot;Arizona&quot;, &quot;California&quot;, &quot;Colorado…
## $ data        &lt;list&gt; [&lt;tbl_df[154 x 5]&gt;, &lt;tbl_df[88 x 5]&gt;, &lt;tbl_df[143 x 5]&gt;,…
## $ mod         &lt;list&gt; [&lt;134.3621, -0.0675, -3.85, -3.85, 1.35, 1.35, 1.35, -3.…
## $ reg_results &lt;list&gt; [&lt;tbl_df[2 x 7]&gt;, &lt;tbl_df[2 x 7]&gt;, &lt;tbl_df[2 x 7]&gt;, &lt;tbl…
## $ year_coef   &lt;dbl&gt; -0.06747, -0.05540, 0.02080, 0.01670, -0.00268, 0.04724, …
## $ year_low    &lt;dbl&gt; -0.09811, -0.09382, -0.00711, 0.00683, -0.02954, 0.01515,…
## $ year_high   &lt;dbl&gt; -0.039188, -0.020154, 0.049793, 0.026642, 0.024115, 0.081…</code></pre>
<p>The easiest way to see the results of these models is to plot the coefficients:</p>
<div class="sourceCode" id="cb853"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb853-1"><a href="logistic-regression.html#cb853-1"></a>house_state_model <span class="op">%&gt;%</span></span>
<span id="cb853-2"><a href="logistic-regression.html#cb853-2"></a><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span></span>
<span id="cb853-3"><a href="logistic-regression.html#cb853-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">state =</span> <span class="kw">fct_reorder</span>(state, year_coef)) <span class="op">%&gt;%</span></span>
<span id="cb853-4"><a href="logistic-regression.html#cb853-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> state, <span class="dt">y =</span> year_coef, <span class="dt">ymin =</span> year_low, <span class="dt">ymax =</span> year_high)) <span class="op">+</span></span>
<span id="cb853-5"><a href="logistic-regression.html#cb853-5"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb853-6"><a href="logistic-regression.html#cb853-6"></a><span class="st">  </span><span class="kw">geom_errorbar</span>() <span class="op">+</span></span>
<span id="cb853-7"><a href="logistic-regression.html#cb853-7"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb853-8"><a href="logistic-regression.html#cb853-8"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb853-9"><a href="logistic-regression.html#cb853-9"></a>       <span class="dt">y =</span> <span class="st">&quot;Coefficients of </span><span class="ch">\&quot;</span><span class="st">year</span><span class="ch">\&quot;</span><span class="st">&quot;</span>,</span>
<span id="cb853-10"><a href="logistic-regression.html#cb853-10"></a>       <span class="dt">title =</span> <span class="st">&quot;Predicting Democratic victories in the U.S. House over time by state&quot;</span>,</span>
<span id="cb853-11"><a href="logistic-regression.html#cb853-11"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Logistic regression coefficients for year plotted by state&quot;</span>) <span class="op">+</span></span>
<span id="cb853-12"><a href="logistic-regression.html#cb853-12"></a><span class="st">  </span><span class="kw">coord_flip</span>()</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-523-1.png" width="\textwidth" /></p>
<p>Consistent with the account we saw when looking at the effect of <code>year</code> overall, there are more states where the odds of a Democratic victory have been decreasing by year than ones where they have been increasing.</p>
</div>
<div id="professional-models" class="section level3">
<h3><span class="header-section-number">12.1.8</span> Professional models</h3>
<p>So far, we have been fitting linear regressions and logistic regressions using <code>lm()</code> and <code>glm()</code>. While these functions are well-known and easy to use, what if we wanted to fit another model? We’d have to learn a new function, which may have new syntax. It’d be much easier if we could use the same syntax for every model we fit.</p>
<p>A collection of packages that helps address this issue is called <strong>tidymodels</strong>:</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb854-1"><a href="logistic-regression.html#cb854-1"></a><span class="kw">library</span>(tidymodels)</span></code></pre></div>
<p><strong>tidymodels</strong> includes many packages, but we’ll start by showing how to use <strong>parsnip</strong> to fit a logistic regression.</p>
<p>First, in the <strong>tidymodels</strong> workflow, we have to save the <em>model specification</em>. We do that using two functions: <code>logistic_reg()</code> and <code>set_engine()</code>.</p>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="logistic-regression.html#cb855-1"></a>logistic_mod &lt;-<span class="st"> </span><span class="kw">logistic_reg</span>() <span class="op">%&gt;%</span></span>
<span id="cb855-2"><a href="logistic-regression.html#cb855-2"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;glm&quot;</span>)</span></code></pre></div>
<p><code>logistic_reg()</code> says that we want to fit a logistic regression, and <code>set_engine("glm")</code> specifies that we want to do it using <code>glm()</code>. Behind the scenes, <strong>parsnip</strong> uses many other packages to fit its models, but by unifying the syntax, it means that you don’t have to memorize how a lot of different functions work.</p>
<p>Note that our new object, <code>logistic_mod</code>, doesn’t contain our data or a formula. In order actually to fit our model, we need to feed <code>logistic_mod</code> to a function called <code>fit()</code>. <code>fit()</code> is the general purpose function in <strong>parsnip</strong> for fitting any model specification. It takes as its first argument the model specification, but otherwise it operates similarly to <code>lm()</code> and <code>glm()</code>:</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb856-1"><a href="logistic-regression.html#cb856-1"></a>logistic_fit &lt;-<span class="st"> </span><span class="kw">fit</span>(logistic_mod,</span>
<span id="cb856-2"><a href="logistic-regression.html#cb856-2"></a>                    <span class="kw">factor</span>(dem_win) <span class="op">~</span><span class="st"> </span>region <span class="op">*</span><span class="st"> </span>year,</span>
<span id="cb856-3"><a href="logistic-regression.html#cb856-3"></a>                    <span class="dt">data =</span> house_ch13)</span></code></pre></div>
<p>(We have to wrap <code>dem_win</code> in <code>factor()</code>, because <code>fit()</code> is more careful than <code>glm()</code> in requiring that classification models actually have categorical outcomes.)</p>
<p>One we have fit the model, how can we use it? The <code>glm</code> object is still stored in <code>logistic_fit$fit</code>, so we can access that and use <code>tidy()</code>, just like we did before:</p>
<div class="sourceCode" id="cb857"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb857-1"><a href="logistic-regression.html#cb857-1"></a>logistic_fit<span class="op">$</span>fit <span class="op">%&gt;%</span></span>
<span id="cb857-2"><a href="logistic-regression.html#cb857-2"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb857-3"><a href="logistic-regression.html#cb857-3"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 8 x 4
##   term                 estimate conf.low conf.high
##   &lt;chr&gt;                   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)           36.4     23.5      49.4   
## 2 regionNortheast      -56.5    -76.1     -37.1   
## 3 regionSouth           61.4     43.9      78.9   
## 4 regionWest           -51.5    -70.6     -32.5   
## 5 year                  -0.0183  -0.0248   -0.0118
## 6 regionNortheast:year   0.0287   0.0189    0.0385
## 7 regionSouth:year      -0.0307  -0.0394   -0.0219
## 8 regionWest:year        0.0260   0.0164    0.0355</code></pre>
<p>As you can see, this generates the same results as when we used <code>glm()</code> directly.</p>
<p>We’ll use <strong>tidymodels</strong> when introducing CART and random forests in this chapter and machine learning in the next chapter. While the models will change, the basic code structure will be very similar to how we fit the logistic regression above.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="16">
<li id="fn16"><p>It is rare that third party candidates mount serious bids in U.S. House elections, so it isn’t a much of an oversimplication to think of the variable as binary.<a href="logistic-regression.html#fnref16" class="footnote-back">↩︎</a></p></li>
<li id="fn17"><p>Indeed, it is almost identical to the coefficient you would obtain in a linear regression–try it out!<a href="logistic-regression.html#fnref17" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="classification.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="classification-and-regression-trees-cart.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
