<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10.1 Teaching evaluations: one numerical explanatory variable | Preceptor’s Primer for Bayesian Data Science</title>
  <meta name="description" content="10.1 Teaching evaluations: one numerical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="10.1 Teaching evaluations: one numerical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="davidkane9/PPBDS" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10.1 Teaching evaluations: one numerical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  
  
  

<meta name="author" content="David Kane" />


<meta name="date" content="2020-05-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regression.html"/>
<link rel="next" href="uncertainty-in-simple-linear-regressions.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="forward.html"><a href="forward.html"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="warning.html"><a href="warning.html"><i class="fa fa-check"></i>Warning</a></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="part-i.html"><a href="part-i.html"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="1" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>1</b> Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio.html"><a href="r-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="r-rstudio.html"><a href="r-rstudio.html#installing"><i class="fa fa-check"></i><b>1.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="r-rstudio.html"><a href="r-rstudio.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="code.html"><a href="code.html"><i class="fa fa-check"></i><b>1.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="code.html"><a href="code.html#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="1.2.2" data-path="code.html"><a href="code.html#messages"><i class="fa fa-check"></i><b>1.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="1.2.3" data-path="code.html"><a href="code.html#tips-code"><i class="fa fa-check"></i><b>1.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="packages.html"><a href="packages.html#package-installation"><i class="fa fa-check"></i><b>1.3.1</b> Package installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="packages.html"><a href="packages.html#package-loading"><i class="fa fa-check"></i><b>1.3.2</b> Package loading</a></li>
<li class="chapter" data-level="1.3.3" data-path="packages.html"><a href="packages.html#package-use"><i class="fa fa-check"></i><b>1.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="nycflights13.html"><a href="nycflights13.html"><i class="fa fa-check"></i><b>1.4</b> Explore your first datasets</a><ul>
<li class="chapter" data-level="1.4.1" data-path="nycflights13.html"><a href="nycflights13.html#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="nycflights13.html"><a href="nycflights13.html#flights-data-frame"><i class="fa fa-check"></i><b>1.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="1.4.3" data-path="nycflights13.html"><a href="nycflights13.html#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="1.4.4" data-path="nycflights13.html"><a href="nycflights13.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>1.4.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="1.4.5" data-path="nycflights13.html"><a href="nycflights13.html#help-files"><i class="fa fa-check"></i><b>1.4.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a><ul>
<li class="chapter" data-level="1.5.1" data-path="conclusion.html"><a href="conclusion.html#additional-resources"><i class="fa fa-check"></i><b>1.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html"><i class="fa fa-check"></i><b>1.6</b> The grammar of graphics</a><ul>
<li class="chapter" data-level="1.6.1" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#components-of-the-grammar"><i class="fa fa-check"></i><b>1.6.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="1.6.2" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#gapminder"><i class="fa fa-check"></i><b>1.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="1.6.3" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#other-components"><i class="fa fa-check"></i><b>1.6.3</b> Other components</a></li>
<li class="chapter" data-level="1.6.4" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#ggplot2-package"><i class="fa fa-check"></i><b>1.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>1.7</b> Scatterplots</a><ul>
<li class="chapter" data-level="1.7.1" data-path="scatterplots.html"><a href="scatterplots.html#geompoint"><i class="fa fa-check"></i><b>1.7.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="scatterplots.html"><a href="scatterplots.html#overplotting"><i class="fa fa-check"></i><b>1.7.2</b> Overplotting</a></li>
<li class="chapter" data-level="1.7.3" data-path="scatterplots.html"><a href="scatterplots.html#summary"><i class="fa fa-check"></i><b>1.7.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="linegraphs.html"><a href="linegraphs.html"><i class="fa fa-check"></i><b>1.8</b> Linegraphs</a><ul>
<li class="chapter" data-level="1.8.1" data-path="linegraphs.html"><a href="linegraphs.html#geomline"><i class="fa fa-check"></i><b>1.8.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="linegraphs.html"><a href="linegraphs.html#summary-1"><i class="fa fa-check"></i><b>1.8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="histograms.html"><a href="histograms.html"><i class="fa fa-check"></i><b>1.9</b> Histograms</a><ul>
<li class="chapter" data-level="1.9.1" data-path="histograms.html"><a href="histograms.html#geomhistogram"><i class="fa fa-check"></i><b>1.9.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="1.9.2" data-path="histograms.html"><a href="histograms.html#adjustbins"><i class="fa fa-check"></i><b>1.9.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="1.9.3" data-path="histograms.html"><a href="histograms.html#summary-2"><i class="fa fa-check"></i><b>1.9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="facets.html"><a href="facets.html"><i class="fa fa-check"></i><b>1.10</b> Facets</a></li>
<li class="chapter" data-level="1.11" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>1.11</b> Boxplots</a><ul>
<li class="chapter" data-level="1.11.1" data-path="boxplots.html"><a href="boxplots.html#geomboxplot"><i class="fa fa-check"></i><b>1.11.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="boxplots.html"><a href="boxplots.html#summary-3"><i class="fa fa-check"></i><b>1.11.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="geombar.html"><a href="geombar.html"><i class="fa fa-check"></i><b>1.12</b> Barplots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="geombar.html"><a href="geombar.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>1.12.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="1.12.2" data-path="geombar.html"><a href="geombar.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>1.12.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="1.12.3" data-path="geombar.html"><a href="geombar.html#two-categ-barplot"><i class="fa fa-check"></i><b>1.12.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="1.12.4" data-path="geombar.html"><a href="geombar.html#summary-4"><i class="fa fa-check"></i><b>1.12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>1.13</b> Conclusion</a><ul>
<li class="chapter" data-level="1.13.1" data-path="conclusion-1.html"><a href="conclusion-1.html#summary-table"><i class="fa fa-check"></i><b>1.13.1</b> Summary table</a></li>
<li class="chapter" data-level="1.13.2" data-path="conclusion-1.html"><a href="conclusion-1.html#function-argument-specification"><i class="fa fa-check"></i><b>1.13.2</b> Function argument specification</a></li>
<li class="chapter" data-level="1.13.3" data-path="conclusion-1.html"><a href="conclusion-1.html#additional-resources-1"><i class="fa fa-check"></i><b>1.13.3</b> Additional resources</a></li>
<li class="chapter" data-level="1.13.4" data-path="conclusion-1.html"><a href="conclusion-1.html#whats-to-come-3"><i class="fa fa-check"></i><b>1.13.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>2</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="piping.html"><a href="piping.html"><i class="fa fa-check"></i><b>2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.2" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="2.3" data-path="summarize.html"><a href="summarize.html"><i class="fa fa-check"></i><b>2.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="2.4" data-path="groupby.html"><a href="groupby.html"><i class="fa fa-check"></i><b>2.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="groupby.html"><a href="groupby.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>2.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>2.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="2.6" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>2.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="2.7" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>2.7</b> Factors</a><ul>
<li class="chapter" data-level="2.7.1" data-path="factors.html"><a href="factors.html#the-forcats-package"><i class="fa fa-check"></i><b>2.7.1</b> The <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="2.7.2" data-path="factors.html"><a href="factors.html#dropping-unused-levels"><i class="fa fa-check"></i><b>2.7.2</b> Dropping unused levels</a></li>
<li class="chapter" data-level="2.7.3" data-path="factors.html"><a href="factors.html#reorder-factors"><i class="fa fa-check"></i><b>2.7.3</b> Change order of the levels, principled</a></li>
<li class="chapter" data-level="2.7.4" data-path="factors.html"><a href="factors.html#change-order-of-the-levels-because-i-said-so"><i class="fa fa-check"></i><b>2.7.4</b> Change order of the levels, “because I said so”</a></li>
<li class="chapter" data-level="2.7.5" data-path="factors.html"><a href="factors.html#recode-the-levels"><i class="fa fa-check"></i><b>2.7.5</b> Recode the levels</a></li>
<li class="chapter" data-level="2.7.6" data-path="factors.html"><a href="factors.html#grow-a-factor"><i class="fa fa-check"></i><b>2.7.6</b> Grow a factor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="character-vectors.html"><a href="character-vectors.html"><i class="fa fa-check"></i><b>2.8</b> Character Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="character-vectors.html"><a href="character-vectors.html#manipulating-character-vectors"><i class="fa fa-check"></i><b>2.8.1</b> Manipulating character vectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-resources"><i class="fa fa-check"></i><b>2.8.2</b> Regular expressions resources</a></li>
<li class="chapter" data-level="2.8.3" data-path="character-vectors.html"><a href="character-vectors.html#character-encoding-resources"><i class="fa fa-check"></i><b>2.8.3</b> Character encoding resources</a></li>
<li class="chapter" data-level="2.8.4" data-path="character-vectors.html"><a href="character-vectors.html#character-vectors-that-live-in-a-data-frame"><i class="fa fa-check"></i><b>2.8.4</b> Character vectors that live in a data frame</a></li>
<li class="chapter" data-level="2.8.5" data-path="character-vectors.html"><a href="character-vectors.html#regex-free-string-manipulation-with-stringr-and-tidyr"><i class="fa fa-check"></i><b>2.8.5</b> Regex-free string manipulation with stringr and tidyr</a></li>
<li class="chapter" data-level="2.8.6" data-path="character-vectors.html"><a href="character-vectors.html#detect-or-filter-on-a-target-string"><i class="fa fa-check"></i><b>2.8.6</b> Detect or filter on a target string</a></li>
<li class="chapter" data-level="2.8.7" data-path="character-vectors.html"><a href="character-vectors.html#string-splitting-by-delimiter"><i class="fa fa-check"></i><b>2.8.7</b> String splitting by delimiter</a></li>
<li class="chapter" data-level="2.8.8" data-path="character-vectors.html"><a href="character-vectors.html#substring-extraction-and-replacement-by-position"><i class="fa fa-check"></i><b>2.8.8</b> Substring extraction (and replacement) by position</a></li>
<li class="chapter" data-level="2.8.9" data-path="character-vectors.html"><a href="character-vectors.html#collapse-a-vector"><i class="fa fa-check"></i><b>2.8.9</b> Collapse a vector</a></li>
<li class="chapter" data-level="2.8.10" data-path="character-vectors.html"><a href="character-vectors.html#catenate-vectors"><i class="fa fa-check"></i><b>2.8.10</b> Create a character vector by catenating multiple vectors</a></li>
<li class="chapter" data-level="2.8.11" data-path="character-vectors.html"><a href="character-vectors.html#substring-replacement"><i class="fa fa-check"></i><b>2.8.11</b> Substring replacement</a></li>
<li class="chapter" data-level="2.8.12" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-with-stringr"><i class="fa fa-check"></i><b>2.8.12</b> Regular expressions with stringr</a></li>
<li class="chapter" data-level="2.8.13" data-path="character-vectors.html"><a href="character-vectors.html#characters-with-special-meaning"><i class="fa fa-check"></i><b>2.8.13</b> Characters with special meaning</a></li>
<li class="chapter" data-level="2.8.14" data-path="character-vectors.html"><a href="character-vectors.html#character-classes"><i class="fa fa-check"></i><b>2.8.14</b> Character classes</a></li>
<li class="chapter" data-level="2.8.15" data-path="character-vectors.html"><a href="character-vectors.html#quantifiers"><i class="fa fa-check"></i><b>2.8.15</b> Quantifiers</a></li>
<li class="chapter" data-level="2.8.16" data-path="character-vectors.html"><a href="character-vectors.html#escaping"><i class="fa fa-check"></i><b>2.8.16</b> Escaping</a></li>
<li class="chapter" data-level="2.8.17" data-path="character-vectors.html"><a href="character-vectors.html#groups-and-backreferences"><i class="fa fa-check"></i><b>2.8.17</b> Groups and backreferences</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="combining-data.html"><a href="combining-data.html"><i class="fa fa-check"></i><b>2.9</b> Combining Data</a><ul>
<li class="chapter" data-level="2.9.1" data-path="combining-data.html"><a href="combining-data.html#bind"><i class="fa fa-check"></i><b>2.9.1</b> Bind</a></li>
<li class="chapter" data-level="2.9.2" data-path="combining-data.html"><a href="combining-data.html#joins-in-dplyr"><i class="fa fa-check"></i><b>2.9.2</b> Joins in dplyr</a></li>
<li class="chapter" data-level="2.9.3" data-path="combining-data.html"><a href="combining-data.html#joining"><i class="fa fa-check"></i><b>2.9.3</b> Joining</a></li>
<li class="chapter" data-level="2.9.4" data-path="combining-data.html"><a href="combining-data.html#matching-key-variable-names"><i class="fa fa-check"></i><b>2.9.4</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="2.9.5" data-path="combining-data.html"><a href="combining-data.html#diff-key"><i class="fa fa-check"></i><b>2.9.5</b> Different “key” variable names</a></li>
<li class="chapter" data-level="2.9.6" data-path="combining-data.html"><a href="combining-data.html#multiple-key-variables"><i class="fa fa-check"></i><b>2.9.6</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="2.9.7" data-path="combining-data.html"><a href="combining-data.html#normal-forms"><i class="fa fa-check"></i><b>2.9.7</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="other-verbs.html"><a href="other-verbs.html"><i class="fa fa-check"></i><b>2.10</b> Other Verbs</a><ul>
<li class="chapter" data-level="2.10.1" data-path="other-verbs.html"><a href="other-verbs.html#select"><i class="fa fa-check"></i><b>2.10.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="other-verbs.html"><a href="other-verbs.html#rename"><i class="fa fa-check"></i><b>2.10.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="2.10.3" data-path="other-verbs.html"><a href="other-verbs.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>2.10.3</b> <code>top_n</code> values of a variable</a></li>
<li class="chapter" data-level="2.10.4" data-path="other-verbs.html"><a href="other-verbs.html#slice-and-pull-and"><i class="fa fa-check"></i><b>2.10.4</b> <code>slice</code> and <code>pull</code> and <code>[]</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="conclusion-2.html"><a href="conclusion-2.html"><i class="fa fa-check"></i><b>2.11</b> Conclusion</a><ul>
<li class="chapter" data-level="2.11.1" data-path="conclusion-2.html"><a href="conclusion-2.html#summary-table-1"><i class="fa fa-check"></i><b>2.11.1</b> Summary table</a></li>
<li class="chapter" data-level="2.11.2" data-path="conclusion-2.html"><a href="conclusion-2.html#additional-resources-2"><i class="fa fa-check"></i><b>2.11.2</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>2.12</b> Tidy</a></li>
<li class="chapter" data-level="2.13" data-path="csv.html"><a href="csv.html"><i class="fa fa-check"></i><b>2.13</b> Importing data</a></li>
<li class="chapter" data-level="2.14" data-path="web-scraping.html"><a href="web-scraping.html"><i class="fa fa-check"></i><b>2.14</b> Web scraping</a><ul>
<li class="chapter" data-level="2.14.1" data-path="web-scraping.html"><a href="web-scraping.html#html"><i class="fa fa-check"></i><b>2.14.1</b> HTML</a></li>
<li class="chapter" data-level="2.14.2" data-path="web-scraping.html"><a href="web-scraping.html#the-rvest-package"><i class="fa fa-check"></i><b>2.14.2</b> The rvest package</a></li>
<li class="chapter" data-level="2.14.3" data-path="web-scraping.html"><a href="web-scraping.html#css-selectors"><i class="fa fa-check"></i><b>2.14.3</b> CSS selectors</a></li>
<li class="chapter" data-level="2.14.4" data-path="web-scraping.html"><a href="web-scraping.html#json"><i class="fa fa-check"></i><b>2.14.4</b> JSON</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html"><i class="fa fa-check"></i><b>2.15</b> “Tidy” data</a><ul>
<li class="chapter" data-level="2.15.1" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#tidy-definition"><i class="fa fa-check"></i><b>2.15.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="2.15.2" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>2.15.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="2.15.3" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#nycflights13-package-1"><i class="fa fa-check"></i><b>2.15.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="case-study-tidy.html"><a href="case-study-tidy.html"><i class="fa fa-check"></i><b>2.16</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="2.17" data-path="tidyverse-package.html"><a href="tidyverse-package.html"><i class="fa fa-check"></i><b>2.17</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="2.18" data-path="conclusion-3.html"><a href="conclusion-3.html"><i class="fa fa-check"></i><b>2.18</b> Conclusion</a><ul>
<li class="chapter" data-level="2.18.1" data-path="conclusion-3.html"><a href="conclusion-3.html#additional-resources-3"><i class="fa fa-check"></i><b>2.18.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rubin-causal-model.html"><a href="rubin-causal-model.html"><i class="fa fa-check"></i><b>3</b> Rubin Causal Model</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html"><i class="fa fa-check"></i><b>3.1</b> What is a causal effect?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#everything-is-a-missing-data-problem"><i class="fa fa-check"></i><b>3.1.1</b> Everything is a missing data problem</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#potential-outcomes-introduction-to-the-rubin-table"><i class="fa fa-check"></i><b>3.1.2</b> Potential outcomes: introduction to the Rubin Table</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#estimands"><i class="fa fa-check"></i><b>3.1.3</b> Estimands</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#the-infinite-rubin-table-many-kinds-of-missing-data"><i class="fa fa-check"></i><b>3.1.4</b> The infinite Rubin Table: many kinds of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html"><i class="fa fa-check"></i><b>3.2</b> How do we fill in the missing values?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#average-treatment-effect"><i class="fa fa-check"></i><b>3.2.1</b> Average treatment effect</a></li>
<li class="chapter" data-level="3.2.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#the-assignment-mechanism"><i class="fa fa-check"></i><b>3.2.2</b> The assignment mechanism</a></li>
<li class="chapter" data-level="3.2.3" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#uncertainty-and-permutation-tests"><i class="fa fa-check"></i><b>3.2.3</b> Uncertainty and permutation tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#everything-is-a-missing-data-problem-revisited-internal-and-external-validity"><i class="fa fa-check"></i><b>3.2.4</b> Everything is a missing data problem revisited: Internal and external validity</a></li>
<li class="chapter" data-level="3.2.5" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#more-complex-models-for-causal-inference"><i class="fa fa-check"></i><b>3.2.5</b> More complex models for causal inference</a></li>
<li class="chapter" data-level="3.2.6" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#causal-inference-and-prediction"><i class="fa fa-check"></i><b>3.2.6</b> Causal inference and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html"><i class="fa fa-check"></i><b>3.3</b> Other issues with causal inference</a><ul>
<li class="chapter" data-level="3.3.1" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#no-causation-without-manipulation"><i class="fa fa-check"></i><b>3.3.1</b> No causation without manipulation</a></li>
<li class="chapter" data-level="3.3.2" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#stable-unit-treatment-value-assumption-sutva"><i class="fa fa-check"></i><b>3.3.2</b> Stable unit treatment value assumption (SUTVA)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="conclusion-4.html"><a href="conclusion-4.html"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
<li class="chapter" data-level="3.5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a><ul>
<li class="chapter" data-level="4.1" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="part-1.html"><a href="part-1.html#get-something-that-works"><i class="fa fa-check"></i><b>4.1.1</b> Get something that works</a></li>
<li class="chapter" data-level="4.1.2" data-path="part-1.html"><a href="part-1.html#skateboard-perfectly-formed-rear-view-mirror"><i class="fa fa-check"></i><b>4.1.2</b> Skateboard &gt;&gt; perfectly formed rear-view mirror</a></li>
<li class="chapter" data-level="4.1.3" data-path="part-1.html"><a href="part-1.html#turn-the-working-interactive-code-into-a-function"><i class="fa fa-check"></i><b>4.1.3</b> Turn the working interactive code into a function</a></li>
<li class="chapter" data-level="4.1.4" data-path="part-1.html"><a href="part-1.html#test-your-function"><i class="fa fa-check"></i><b>4.1.4</b> Test your function</a></li>
<li class="chapter" data-level="4.1.5" data-path="part-1.html"><a href="part-1.html#check-the-validity-of-arguments"><i class="fa fa-check"></i><b>4.1.5</b> Check the validity of arguments</a></li>
<li class="chapter" data-level="4.1.6" data-path="part-1.html"><a href="part-1.html#wrap-up-and-whats-next"><i class="fa fa-check"></i><b>4.1.6</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i><b>4.2</b> Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="part-2.html"><a href="part-2.html#load-the-gapminder-data"><i class="fa fa-check"></i><b>4.2.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.2.2" data-path="part-2.html"><a href="part-2.html#restore-our-max-minus-min-function"><i class="fa fa-check"></i><b>4.2.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.2.3" data-path="part-2.html"><a href="part-2.html#generalize-our-function-to-other-quantiles"><i class="fa fa-check"></i><b>4.2.3</b> Generalize our function to other quantiles</a></li>
<li class="chapter" data-level="4.2.4" data-path="part-2.html"><a href="part-2.html#get-something-that-works-again"><i class="fa fa-check"></i><b>4.2.4</b> Get something that works, again</a></li>
<li class="chapter" data-level="4.2.5" data-path="part-2.html"><a href="part-2.html#turn-the-working-interactive-code-into-a-function-again"><i class="fa fa-check"></i><b>4.2.5</b> Turn the working interactive code into a function, again</a></li>
<li class="chapter" data-level="4.2.6" data-path="part-2.html"><a href="part-2.html#argument-names-freedom-and-conventions"><i class="fa fa-check"></i><b>4.2.6</b> Argument names: freedom and conventions</a></li>
<li class="chapter" data-level="4.2.7" data-path="part-2.html"><a href="part-2.html#what-a-function-returns"><i class="fa fa-check"></i><b>4.2.7</b> What a function returns</a></li>
<li class="chapter" data-level="4.2.8" data-path="part-2.html"><a href="part-2.html#default-values-freedom-to-not-specify-the-arguments"><i class="fa fa-check"></i><b>4.2.8</b> Default values: freedom to NOT specify the arguments</a></li>
<li class="chapter" data-level="4.2.9" data-path="part-2.html"><a href="part-2.html#wrap-up-and-whats-next-1"><i class="fa fa-check"></i><b>4.2.9</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i><b>4.3</b> Part 3</a><ul>
<li class="chapter" data-level="4.3.1" data-path="part-3.html"><a href="part-3.html#load-the-gapminder-data-1"><i class="fa fa-check"></i><b>4.3.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.3.2" data-path="part-3.html"><a href="part-3.html#restore-our-max-minus-min-function-1"><i class="fa fa-check"></i><b>4.3.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.3.3" data-path="part-3.html"><a href="part-3.html#be-proactive-about-nas"><i class="fa fa-check"></i><b>4.3.3</b> Be proactive about <code>NA</code>s</a></li>
<li class="chapter" data-level="4.3.4" data-path="part-3.html"><a href="part-3.html#the-useful-but-mysterious-...-argument"><i class="fa fa-check"></i><b>4.3.4</b> The useful but mysterious <code>...</code> argument</a></li>
<li class="chapter" data-level="4.3.5" data-path="part-3.html"><a href="part-3.html#use-testthat-for-formal-unit-tests"><i class="fa fa-check"></i><b>4.3.5</b> Use testthat for formal unit tests</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html"><i class="fa fa-check"></i><b>4.4</b> List columns and <code>map_*</code> functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#what-are-list-columns"><i class="fa fa-check"></i><b>4.4.1</b> What are list columns?</a></li>
<li class="chapter" data-level="4.4.2" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#creating-list-columns-with-mutate"><i class="fa fa-check"></i><b>4.4.2</b> Creating list columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="4.4.3" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#map_-functions"><i class="fa fa-check"></i><b>4.4.3</b> <code>map_*</code> functions</a></li>
<li class="chapter" data-level="4.4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#using-map_-functions-to-create-list-columns"><i class="fa fa-check"></i><b>4.4.4</b> Using <code>map_*</code> functions to create list columns</a></li>
<li class="chapter" data-level="4.4.5" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#practice-with-map_-functions-and-list-columns"><i class="fa fa-check"></i><b>4.4.5</b> Practice with <code>map_*</code> functions and list columns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii.html"><a href="part-ii.html"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html"><i class="fa fa-check"></i><b>5.1</b> Defining probability</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#intro-questions"><i class="fa fa-check"></i><b>5.1.1</b> Intro Questions</a></li>
<li class="chapter" data-level="5.1.2" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-1"><i class="fa fa-check"></i><b>5.1.2</b> Probability</a></li>
<li class="chapter" data-level="5.1.3" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#disjoint-or-mutually-exclusive-outcomes"><i class="fa fa-check"></i><b>5.1.3</b> Disjoint or mutually exclusive outcomes</a></li>
<li class="chapter" data-level="5.1.4" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilities-when-events-are-not-disjoint"><i class="fa fa-check"></i><b>5.1.4</b> Probabilities when events are not disjoint</a></li>
<li class="chapter" data-level="5.1.5" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-distributions"><i class="fa fa-check"></i><b>5.1.5</b> Probability distributions</a></li>
<li class="chapter" data-level="5.1.6" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#complement-of-an-event"><i class="fa fa-check"></i><b>5.1.6</b> Complement of an event</a></li>
<li class="chapter" data-level="5.1.7" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilityIndependence"><i class="fa fa-check"></i><b>5.1.7</b> Independence</a></li>
<li class="chapter" data-level="5.1.8" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#conditionalProbabilitySection"><i class="fa fa-check"></i><b>5.1.8</b> Conditional probability</a></li>
<li class="chapter" data-level="5.1.9" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#marginalAndJointProbabilities"><i class="fa fa-check"></i><b>5.1.9</b> Marginal and joint probabilities</a></li>
<li class="chapter" data-level="5.1.10" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#defining-conditional-probability"><i class="fa fa-check"></i><b>5.1.10</b> Defining conditional probability</a></li>
<li class="chapter" data-level="5.1.11" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#smallpox-in-boston-1721"><i class="fa fa-check"></i><b>5.1.11</b> Smallpox in Boston, 1721</a></li>
<li class="chapter" data-level="5.1.12" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#general-multiplication-rule"><i class="fa fa-check"></i><b>5.1.12</b> General multiplication rule</a></li>
<li class="chapter" data-level="5.1.13" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#tree-diagrams"><i class="fa fa-check"></i><b>5.1.13</b> Tree diagrams</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html"><i class="fa fa-check"></i><b>5.2</b> Random variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#expectation"><i class="fa fa-check"></i><b>5.2.1</b> Expectation</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Variability in random variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.3</b> Linear combinations of random variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.4</b> Variability in linear combinations of random variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>5.3</b> Statistical Background</a><ul>
<li class="chapter" data-level="5.3.1" data-path="appendixA.html"><a href="appendixA.html#appendix-stat-terms"><i class="fa fa-check"></i><b>5.3.1</b> Basic statistical terms</a></li>
<li class="chapter" data-level="5.3.2" data-path="appendixA.html"><a href="appendixA.html#appendix-normal-curve"><i class="fa fa-check"></i><b>5.3.2</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bayess-theorem.html"><a href="bayess-theorem.html"><i class="fa fa-check"></i><b>5.4</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.5" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>5.5</b> Conditional probability</a></li>
<li class="chapter" data-level="5.6" data-path="conjoint-probability.html"><a href="conjoint-probability.html"><i class="fa fa-check"></i><b>5.6</b> Conjoint probability</a></li>
<li class="chapter" data-level="5.7" data-path="the-cookie-problem.html"><a href="the-cookie-problem.html"><i class="fa fa-check"></i><b>5.7</b> The cookie problem</a></li>
<li class="chapter" data-level="5.8" data-path="bayess-theorem-1.html"><a href="bayess-theorem-1.html"><i class="fa fa-check"></i><b>5.8</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.9" data-path="the-diachronic-interpretation.html"><a href="the-diachronic-interpretation.html"><i class="fa fa-check"></i><b>5.9</b> The diachronic interpretation</a></li>
<li class="chapter" data-level="5.10" data-path="the-mm-problem.html"><a href="the-mm-problem.html"><i class="fa fa-check"></i><b>5.10</b> The M&amp;M problem</a></li>
<li class="chapter" data-level="5.11" data-path="the-monty-hall-problem.html"><a href="the-monty-hall-problem.html"><i class="fa fa-check"></i><b>5.11</b> The Monty Hall problem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling</a><ul>
<li class="chapter" data-level="" data-path="sampling.html"><a href="sampling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="sampling-activity.html"><a href="sampling-activity.html"><i class="fa fa-check"></i><b>6.1</b> Sampling urn activity</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sampling-activity.html"><a href="sampling-activity.html#what-proportion-of-this-urns-balls-are-red"><i class="fa fa-check"></i><b>6.1.1</b> What proportion of this urn’s balls are red?</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling-activity.html"><a href="sampling-activity.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling-activity.html"><a href="sampling-activity.html#student-shovels"><i class="fa fa-check"></i><b>6.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling-activity.html"><a href="sampling-activity.html#what-did-we-just-do"><i class="fa fa-check"></i><b>6.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html"><i class="fa fa-check"></i><b>6.2</b> Virtual sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-simulation.html"><a href="sampling-simulation.html#shovel-1000-times"><i class="fa fa-check"></i><b>6.2.3</b> Using the virtual shovel 1,000 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-simulation.html"><a href="sampling-simulation.html#different-shovels"><i class="fa fa-check"></i><b>6.2.4</b> Using different shovels</a></li>
<li class="chapter" data-level="6.2.5" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-many-shovels-at-once"><i class="fa fa-check"></i><b>6.2.5</b> Using many shovels at once</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-framework.html"><a href="sampling-framework.html"><i class="fa fa-check"></i><b>6.3</b> Sampling framework</a><ul>
<li class="chapter" data-level="6.3.1" data-path="sampling-framework.html"><a href="sampling-framework.html#terminology-and-notation"><i class="fa fa-check"></i><b>6.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="6.3.2" data-path="sampling-framework.html"><a href="sampling-framework.html#sampling-definitions"><i class="fa fa-check"></i><b>6.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="6.3.3" data-path="sampling-framework.html"><a href="sampling-framework.html#moral-of-the-story"><i class="fa fa-check"></i><b>6.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sampling-case-study.html"><a href="sampling-case-study.html"><i class="fa fa-check"></i><b>6.4</b> Case study: Polls</a><ul>
<li class="chapter" data-level="6.4.1" data-path="sampling-case-study.html"><a href="sampling-case-study.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>6.4.1</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="conclusion-5.html"><a href="conclusion-5.html"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> One Parameter</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html"><i class="fa fa-check"></i><b>7.1</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.1.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.1.2" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-once"><i class="fa fa-check"></i><b>7.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.1.3" data-path="resampling-tactile.html"><a href="resampling-tactile.html#student-resamples"><i class="fa fa-check"></i><b>7.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.1.4" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-did-we-just-do-1"><i class="fa fa-check"></i><b>7.1.4</b> What did we just do?</a></li>
<li class="chapter" data-level="7.1.5" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-simulation"><i class="fa fa-check"></i><b>7.1.5</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.1.6" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>7.1.6</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.1.7" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.1.7</b> Virtually resampling 1,000 times</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ci-build-up.html"><a href="ci-build-up.html"><i class="fa fa-check"></i><b>7.2</b> Measuring uncertainty with confidence intervals</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ci-build-up.html"><a href="ci-build-up.html#percentile-method"><i class="fa fa-check"></i><b>7.2.1</b> Percentile method</a></li>
<li class="chapter" data-level="7.2.2" data-path="ci-build-up.html"><a href="ci-build-up.html#se-method"><i class="fa fa-check"></i><b>7.2.2</b> Standard error method</a></li>
<li class="chapter" data-level="7.2.3" data-path="ci-build-up.html"><a href="ci-build-up.html#one-prop-ci"><i class="fa fa-check"></i><b>7.2.3</b> Interpreting confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ci-width.html"><a href="ci-width.html"><i class="fa fa-check"></i><b>7.3</b> Width of confidence intervals</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ci-width.html"><a href="ci-width.html#impact-of-confidence-level"><i class="fa fa-check"></i><b>7.3.1</b> Impact of confidence level</a></li>
<li class="chapter" data-level="7.3.2" data-path="ci-width.html"><a href="ci-width.html#fitting-multiple-models-using-map"><i class="fa fa-check"></i><b>7.3.2</b> Fitting multiple models using <code>map()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="ci-width.html"><a href="ci-width.html#impact-of-sample-size"><i class="fa fa-check"></i><b>7.3.3</b> Impact of sample size</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-lm-and-tidy-as-a-shortcut.html"><a href="using-lm-and-tidy-as-a-shortcut.html"><i class="fa fa-check"></i><b>7.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html"><i class="fa fa-check"></i><b>7.5</b> Case study: Is yawning contagious?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#mythbusters-study-data"><i class="fa fa-check"></i><b>7.5.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#sampling-scenario"><i class="fa fa-check"></i><b>7.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="7.5.3" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#ci-build"><i class="fa fa-check"></i><b>7.5.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="7.5.4" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#using-lm-and-tidy-as-a-shortcut-1"><i class="fa fa-check"></i><b>7.5.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ci-conclusion.html"><a href="ci-conclusion.html"><i class="fa fa-check"></i><b>7.6</b> Conclusion</a><ul>
<li class="chapter" data-level="7.6.1" data-path="ci-conclusion.html"><a href="ci-conclusion.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>7.6.1</b> Comparing bootstrap and sampling distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="two-parameters.html"><a href="two-parameters.html"><i class="fa fa-check"></i><b>8</b> Two Parameters</a></li>
<li class="chapter" data-level="" data-path="part-iii.html"><a href="part-iii.html"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="9" data-path="n-parameters.html"><a href="n-parameters.html"><i class="fa fa-check"></i><b>9</b> N Parameters</a></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Continuous Response I</a><ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="10.1" data-path="model1.html"><a href="model1.html"><i class="fa fa-check"></i><b>10.1</b> Teaching evaluations: one numerical explanatory variable</a><ul>
<li class="chapter" data-level="10.1.1" data-path="model1.html"><a href="model1.html#model1EDA"><i class="fa fa-check"></i><b>10.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.1.2" data-path="model1.html"><a href="model1.html#model1table"><i class="fa fa-check"></i><b>10.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="model1.html"><a href="model1.html#interpreting-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Interpreting regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html"><i class="fa fa-check"></i><b>10.2</b> Uncertainty in simple linear regressions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#using-lm-and-tidy-as-a-shortcut-2"><i class="fa fa-check"></i><b>10.2.1</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#model1points"><i class="fa fa-check"></i><b>10.2.2</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="model2.html"><a href="model2.html"><i class="fa fa-check"></i><b>10.3</b> Life expectancy: one categorical explanatory variable</a><ul>
<li class="chapter" data-level="10.3.1" data-path="model2.html"><a href="model2.html#model2EDA"><i class="fa fa-check"></i><b>10.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="model2.html"><a href="model2.html#model2table"><i class="fa fa-check"></i><b>10.3.2</b> Linear regression</a></li>
<li class="chapter" data-level="10.3.3" data-path="model2.html"><a href="model2.html#model2points"><i class="fa fa-check"></i><b>10.3.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html"><i class="fa fa-check"></i><b>10.4</b> Case study: 2018 gubernatorial forecasts</a><ul>
<li class="chapter" data-level="10.4.1" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html#fitting-multiple-models-using-map-1"><i class="fa fa-check"></i><b>10.4.1</b> Fitting multiple models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="leastsquares.html"><a href="leastsquares.html"><i class="fa fa-check"></i><b>10.5</b> Appendix: Best-fitting line</a></li>
<li class="chapter" data-level="10.6" data-path="conclusion-6.html"><a href="conclusion-6.html"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>11</b> Continuous Response II</a><ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="11.1" data-path="model4.html"><a href="model4.html"><i class="fa fa-check"></i><b>11.1</b> Teaching evaluations revisited: one numerical and one categorical explanatory variable</a><ul>
<li class="chapter" data-level="11.1.1" data-path="model4.html"><a href="model4.html#model4EDA"><i class="fa fa-check"></i><b>11.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.1.2" data-path="model4.html"><a href="model4.html#model4interactiontable"><i class="fa fa-check"></i><b>11.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="11.1.3" data-path="model4.html"><a href="model4.html#interpreting-regression-coefficients-with-interactions"><i class="fa fa-check"></i><b>11.1.3</b> Interpreting regression coefficients with interactions</a></li>
<li class="chapter" data-level="11.1.4" data-path="model4.html"><a href="model4.html#model4table"><i class="fa fa-check"></i><b>11.1.4</b> Parallel slopes model</a></li>
<li class="chapter" data-level="11.1.5" data-path="model4.html"><a href="model4.html#model4points"><i class="fa fa-check"></i><b>11.1.5</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="model3.html"><a href="model3.html"><i class="fa fa-check"></i><b>11.2</b> Credit card debt: two numerical explanatory variables</a><ul>
<li class="chapter" data-level="11.2.1" data-path="model3.html"><a href="model3.html#model3EDA"><i class="fa fa-check"></i><b>11.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.2.2" data-path="model3.html"><a href="model3.html#model3table"><i class="fa fa-check"></i><b>11.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="11.2.3" data-path="model3.html"><a href="model3.html#model3points"><i class="fa fa-check"></i><b>11.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html"><i class="fa fa-check"></i><b>11.3</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="11.3.1" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>11.3.1</b> Exploratory data analysis: Part I</a></li>
<li class="chapter" data-level="11.3.2" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-II"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory data analysis: Part II</a></li>
<li class="chapter" data-level="11.3.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-regression"><i class="fa fa-check"></i><b>11.3.3</b> Regression modeling</a></li>
<li class="chapter" data-level="11.3.4" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>11.3.4</b> Making predictions</a></li>
<li class="chapter" data-level="11.3.5" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#fitting-many-models-using-map"><i class="fa fa-check"></i><b>11.3.5</b> Fitting many models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="other-topics.html"><a href="other-topics.html"><i class="fa fa-check"></i><b>11.4</b> Other topics</a><ul>
<li class="chapter" data-level="11.4.1" data-path="other-topics.html"><a href="other-topics.html#model-selection"><i class="fa fa-check"></i><b>11.4.1</b> Model selection</a></li>
<li class="chapter" data-level="11.4.2" data-path="other-topics.html"><a href="other-topics.html#correlationcoefficient2"><i class="fa fa-check"></i><b>11.4.2</b> Correlation coefficient</a></li>
<li class="chapter" data-level="11.4.3" data-path="other-topics.html"><a href="other-topics.html#simpsonsparadox"><i class="fa fa-check"></i><b>11.4.3</b> Simpson’s Paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>12</b> Discrete Response</a><ul>
<li class="chapter" data-level="" data-path="classification.html"><a href="classification.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> What is logistic regression?</a></li>
<li class="chapter" data-level="12.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#house-elections-exploratory-data-analysis"><i class="fa fa-check"></i><b>12.1.2</b> House elections: exploratory data analysis</a></li>
<li class="chapter" data-level="12.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.3</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.4" data-path="logistic-regression.html"><a href="logistic-regression.html#observedfitted-values-and-residuals"><i class="fa fa-check"></i><b>12.1.4</b> Observed/fitted values and residuals</a></li>
<li class="chapter" data-level="12.1.5" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.5</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.1.6" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-and-one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.6</b> One numerical and one categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.7" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-many-models-using-map-1"><i class="fa fa-check"></i><b>12.1.7</b> Fitting many models using <code>map()</code></a></li>
<li class="chapter" data-level="12.1.8" data-path="logistic-regression.html"><a href="logistic-regression.html#professional-models"><i class="fa fa-check"></i><b>12.1.8</b> Professional models</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html"><i class="fa fa-check"></i><b>12.2</b> Classification and regression trees (CART)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#what-is-cart"><i class="fa fa-check"></i><b>12.2.1</b> What is CART?</a></li>
<li class="chapter" data-level="12.2.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-categorical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.2</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.2.3" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-numerical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.3</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.2.4" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#multiple-explanatory-variables"><i class="fa fa-check"></i><b>12.2.4</b> Multiple explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>12.3</b> Random forests</a><ul>
<li class="chapter" data-level="12.3.1" data-path="random-forests.html"><a href="random-forests.html#what-are-random-forests"><i class="fa fa-check"></i><b>12.3.1</b> What are random forests?</a></li>
<li class="chapter" data-level="12.3.2" data-path="random-forests.html"><a href="random-forests.html#fitting-random-forests"><i class="fa fa-check"></i><b>12.3.2</b> Fitting random forests</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html"><i class="fa fa-check"></i><b>12.4</b> Comparing the three approaches</a><ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#is-accuracy-the-right-measure"><i class="fa fa-check"></i><b>12.4.1</b> Is accuracy the right measure?</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#modeling-for-prediction-vs.-explanation"><i class="fa fa-check"></i><b>12.4.2</b> Modeling for prediction vs. explanation</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#out-of-sample-predictions"><i class="fa fa-check"></i><b>12.4.3</b> Out-of-sample predictions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="productivity.html"><a href="productivity.html"><i class="fa fa-check"></i><b>A</b> Productivity</a><ul>
<li class="chapter" data-level="A.1" data-path="set-up.html"><a href="set-up.html"><i class="fa fa-check"></i><b>A.1</b> Set Up</a><ul>
<li class="chapter" data-level="A.1.1" data-path="set-up.html"><a href="set-up.html#terminal-on-mac"><i class="fa fa-check"></i><b>A.1.1</b> Accessing the terminal on a Mac</a></li>
<li class="chapter" data-level="A.1.2" data-path="set-up.html"><a href="set-up.html#installing-git-on-the-mac"><i class="fa fa-check"></i><b>A.1.2</b> Installing Git on the Mac</a></li>
<li class="chapter" data-level="A.1.3" data-path="set-up.html"><a href="set-up.html#installing-git-and-git-bash-on-windows"><i class="fa fa-check"></i><b>A.1.3</b> Installing Git and Git Bash on Windows</a></li>
<li class="chapter" data-level="A.1.4" data-path="set-up.html"><a href="set-up.html#terminal-on-windows"><i class="fa fa-check"></i><b>A.1.4</b> Accessing the terminal on Windows</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i><b>A.2</b> Organizing with Unix</a><ul>
<li class="chapter" data-level="A.2.1" data-path="unix.html"><a href="unix.html#naming-convention"><i class="fa fa-check"></i><b>A.2.1</b> Naming convention</a></li>
<li class="chapter" data-level="A.2.2" data-path="unix.html"><a href="unix.html#the-terminal"><i class="fa fa-check"></i><b>A.2.2</b> The terminal</a></li>
<li class="chapter" data-level="A.2.3" data-path="unix.html"><a href="unix.html#filesystem"><i class="fa fa-check"></i><b>A.2.3</b> The filesystem</a></li>
<li class="chapter" data-level="A.2.4" data-path="unix.html"><a href="unix.html#directories-and-subdirectories"><i class="fa fa-check"></i><b>A.2.4</b> Directories and subdirectories</a></li>
<li class="chapter" data-level="A.2.5" data-path="unix.html"><a href="unix.html#the-home-directory"><i class="fa fa-check"></i><b>A.2.5</b> The home directory</a></li>
<li class="chapter" data-level="A.2.6" data-path="unix.html"><a href="unix.html#working-directory"><i class="fa fa-check"></i><b>A.2.6</b> Working directory</a></li>
<li class="chapter" data-level="A.2.7" data-path="unix.html"><a href="unix.html#paths"><i class="fa fa-check"></i><b>A.2.7</b> Paths</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="unix-commands.html"><a href="unix-commands.html"><i class="fa fa-check"></i><b>A.3</b> Unix commands</a><ul>
<li class="chapter" data-level="A.3.1" data-path="unix-commands.html"><a href="unix-commands.html#ls-listing-directory-content"><i class="fa fa-check"></i><b>A.3.1</b> <code>ls</code>: Listing directory content</a></li>
<li class="chapter" data-level="A.3.2" data-path="unix-commands.html"><a href="unix-commands.html#mkdir-and-rmdir-make-and-remove-a-directory"><i class="fa fa-check"></i><b>A.3.2</b> <code>mkdir</code> and <code>rmdir</code>: make and remove a directory</a></li>
<li class="chapter" data-level="A.3.3" data-path="unix-commands.html"><a href="unix-commands.html#cd-navigating-the-filesystem-by-changing-directories"><i class="fa fa-check"></i><b>A.3.3</b> <code>cd</code>: navigating the filesystem by changing directories</a></li>
<li class="chapter" data-level="A.3.4" data-path="unix-commands.html"><a href="unix-commands.html#some-examples"><i class="fa fa-check"></i><b>A.3.4</b> Some examples</a></li>
<li class="chapter" data-level="A.3.5" data-path="unix-commands.html"><a href="unix-commands.html#more-unix-commands"><i class="fa fa-check"></i><b>A.3.5</b> More Unix commands</a></li>
<li class="chapter" data-level="A.3.6" data-path="unix-commands.html"><a href="unix-commands.html#advanced-unix"><i class="fa fa-check"></i><b>A.3.6</b> Advanced Unix</a></li>
<li class="chapter" data-level="A.3.7" data-path="unix-commands.html"><a href="unix-commands.html#file-manipulation-in-r"><i class="fa fa-check"></i><b>A.3.7</b> File manipulation in R</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="git.html"><a href="git.html"><i class="fa fa-check"></i><b>A.4</b> Git and GitHub</a><ul>
<li class="chapter" data-level="A.4.1" data-path="git.html"><a href="git.html#github-accounts"><i class="fa fa-check"></i><b>A.4.1</b> GitHub accounts</a></li>
<li class="chapter" data-level="A.4.2" data-path="git.html"><a href="git.html#github-repos"><i class="fa fa-check"></i><b>A.4.2</b> GitHub repositories</a></li>
<li class="chapter" data-level="A.4.3" data-path="git.html"><a href="git.html#git-overview"><i class="fa fa-check"></i><b>A.4.3</b> Overview of Git</a></li>
<li class="chapter" data-level="A.4.4" data-path="git.html"><a href="git.html#rstudio-git"><i class="fa fa-check"></i><b>A.4.4</b> Using Git and GitHub in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>A.5</b> R</a><ul>
<li class="chapter" data-level="A.5.1" data-path="r.html"><a href="r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.5.1</b> RStudio projects</a></li>
<li class="chapter" data-level="A.5.2" data-path="r.html"><a href="r.html#r-markdown"><i class="fa fa-check"></i><b>A.5.2</b> R markdown</a></li>
<li class="chapter" data-level="A.5.3" data-path="r.html"><a href="r.html#help-for-r"><i class="fa fa-check"></i><b>A.5.3</b> Help for R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>B</b> Getting Help</a><ul>
<li class="chapter" data-level="B.1" data-path="searching-for-help-with-r-1.html"><a href="searching-for-help-with-r-1.html"><i class="fa fa-check"></i><b>B.1</b> Searching for Help with R</a></li>
<li class="chapter" data-level="B.2" data-path="reproducible-examples-1.html"><a href="reproducible-examples-1.html"><i class="fa fa-check"></i><b>B.2</b> Reproducible Examples</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>C</b> Shiny</a><ul>
<li class="chapter" data-level="C.1" data-path="helpful-resources.html"><a href="helpful-resources.html"><i class="fa fa-check"></i><b>C.1</b> Helpful Resources</a></li>
<li class="chapter" data-level="C.2" data-path="set-up-and-getting-started.html"><a href="set-up-and-getting-started.html"><i class="fa fa-check"></i><b>C.2</b> Set Up and Getting Started</a></li>
<li class="chapter" data-level="C.3" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html"><i class="fa fa-check"></i><b>C.3</b> Building Your Basic App</a><ul>
<li class="chapter" data-level="C.3.1" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-basic-ui"><i class="fa fa-check"></i><b>C.3.1</b> Setting Up the Basic UI</a></li>
<li class="chapter" data-level="C.3.2" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-server"><i class="fa fa-check"></i><b>C.3.2</b> Setting up the Server</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="organization.html"><a href="organization.html"><i class="fa fa-check"></i><b>C.4</b> Organization</a></li>
<li class="chapter" data-level="C.5" data-path="customizations.html"><a href="customizations.html"><i class="fa fa-check"></i><b>C.5</b> Customizations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="maps.html"><a href="maps.html"><i class="fa fa-check"></i><b>D</b> Maps</a><ul>
<li class="chapter" data-level="D.1" data-path="tidycensus.html"><a href="tidycensus.html"><i class="fa fa-check"></i><b>D.1</b> Tidycensus</a></li>
<li class="chapter" data-level="D.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html"><i class="fa fa-check"></i><b>D.2</b> Conceptual introduction to mapping</a><ul>
<li class="chapter" data-level="D.2.1" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#vector-versus-spatial-data"><i class="fa fa-check"></i><b>D.2.1</b> Vector versus spatial data</a></li>
<li class="chapter" data-level="D.2.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#sf-vs-sp"><i class="fa fa-check"></i><b>D.2.2</b> <strong>sf</strong> vs <strong>sp</strong></a></li>
<li class="chapter" data-level="D.2.3" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#shapefiles"><i class="fa fa-check"></i><b>D.2.3</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html"><i class="fa fa-check"></i><b>D.3</b> Mapping with <strong>tidycensus</strong> and <code>geom_sf()</code></a><ul>
<li class="chapter" data-level="D.3.1" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#making-maps-pretty"><i class="fa fa-check"></i><b>D.3.1</b> Making maps pretty</a></li>
<li class="chapter" data-level="D.3.2" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#adding-back-alaska-and-hawaii"><i class="fa fa-check"></i><b>D.3.2</b> Adding back Alaska and Hawaii</a></li>
</ul></li>
<li class="chapter" data-level="D.4" data-path="faceting-maps.html"><a href="faceting-maps.html"><i class="fa fa-check"></i><b>D.4</b> Faceting maps</a><ul>
<li class="chapter" data-level="D.4.1" data-path="faceting-maps.html"><a href="faceting-maps.html#transforming-and-mapping-the-data"><i class="fa fa-check"></i><b>D.4.1</b> Transforming and mapping the data</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="want-to-explore-further.html"><a href="want-to-explore-further.html"><i class="fa fa-check"></i><b>D.5</b> Want to explore further?</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="animation.html"><a href="animation.html"><i class="fa fa-check"></i><b>E</b> Animation</a><ul>
<li class="chapter" data-level="E.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><i class="fa fa-check"></i><b>E.1</b> gganimate: How to Create Plots with Beautiful Animation in R</a><ul>
<li class="chapter" data-level="E.1.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#prerequisites"><i class="fa fa-check"></i><b>E.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="E.1.2" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#demo-dataset"><i class="fa fa-check"></i><b>E.1.2</b> Demo dataset</a></li>
<li class="chapter" data-level="E.1.3" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#static-plot"><i class="fa fa-check"></i><b>E.1.3</b> Static plot</a></li>
<li class="chapter" data-level="E.1.4" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-through-distinct-states-in-time"><i class="fa fa-check"></i><b>E.1.4</b> Transition through distinct states in time</a></li>
<li class="chapter" data-level="E.1.5" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#reveal-data-along-a-given-dimension"><i class="fa fa-check"></i><b>E.1.5</b> Reveal data along a given dimension</a></li>
<li class="chapter" data-level="E.1.6" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-between-several-distinct-stages-of-the-data"><i class="fa fa-check"></i><b>E.1.6</b> Transition between several distinct stages of the data</a></li>
<li class="chapter" data-level="E.1.7" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#read-more"><i class="fa fa-check"></i><b>E.1.7</b> Read more</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="how-to-save-your-animation.html"><a href="how-to-save-your-animation.html"><i class="fa fa-check"></i><b>E.2</b> How to save your animation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preceptor’s Primer for Bayesian Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model1" class="section level2">
<h2><span class="header-section-number">10.1</span> Teaching evaluations: one numerical explanatory variable</h2>
<!-- DK: I think this is good. I like walking through EDA. Should do that each chapter, maybe showing more tricks each time. But in what order? skim() here then calculate your own simply in 12 and then calculate using new dplyr 1.0.0 tricks like across() in 13. Also, stop replying on moderndive. Just include this data in our package or on line. Indeed, do we need our own package? Or just our own dedicated set of Google sheets? We need our own package, since we will be using a bunch of datasets, some created/cleaned by us. -->
<!-- DK: Next version, can't use these examples. Need political ones. Let's use an updated version of US congress campaigns. This connects to the new introduction. Can use latest data. Can include variables like last election results, allowing us to follow Gelman's version. Can also include spending data, so that we can discuss a causal model. Perhaps in this chapter, we do one model with each, the second going faster. Then, next chapter, put both variables in the regression. This example would also be nice because we could use list columns for the secret trick, estimating models by year and by country region. -->
<!-- DK: I have skimmed the next section, since I plan on cutting it all. -->
<p>Why do some professors and instructors at universities and colleges receive high teaching evaluations scores from students while others receive lower ones? Are there differences in teaching evaluations between instructors of different demographic groups? Could there be an impact due to student biases? These are all questions that are of interest to university/college administrators, as teaching evaluations are among the many criteria considered in determining which instructors and professors get promoted.</p>
<p>Researchers at the University of Texas in Austin, Texas (UT Austin) tried to answer the following research question: what factors explain differences in instructor teaching evaluation scores? To this end, they collected instructor and course information on 463 courses. A full description of the study can be found at <a href="https://www.openintro.org/data/index.php?data=evals">openintro.org</a>.</p>
<p>In this section, we’ll keep things simple for now and try to explain differences in instructor teaching scores as a function of one numerical variable: the instructor’s “beauty” score (we’ll describe how this score was determined shortly). Could it be that instructors with higher “beauty” scores also have higher teaching evaluations? Could it be instead that instructors with higher “beauty” scores tend to have lower teaching evaluations? Or could it be that there is no relationship between “beauty” score and teaching evaluations? We’ll answer these questions by modeling the relationship between teaching scores and “beauty” scores using <em>simple linear regression</em>  where we have:</p>
<ol style="list-style-type: decimal">
<li>A numerical outcome variable <span class="math inline">\(y\)</span> (the instructor’s teaching score) and</li>
<li>A single numerical explanatory variable <span class="math inline">\(x\)</span> (the instructor’s “beauty” score).</li>
</ol>
<div id="model1EDA" class="section level3">
<h3><span class="header-section-number">10.1.1</span> Exploratory data analysis</h3>
<p>The data on the 463 courses at UT Austin can be found in the <code>evals</code> data frame included in the <strong>moderndive</strong> package. However, to keep things simple, let’s <code>select()</code> only the subset of the variables we’ll consider in this chapter, and save this data in a new data frame called <code>evals_ch11</code>:</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb673-1"><a href="model1.html#cb673-1"></a><span class="kw">library</span>(moderndive)</span>
<span id="cb673-2"><a href="model1.html#cb673-2"></a></span>
<span id="cb673-3"><a href="model1.html#cb673-3"></a>evals_ch11 &lt;-<span class="st"> </span>evals <span class="op">%&gt;%</span></span>
<span id="cb673-4"><a href="model1.html#cb673-4"></a><span class="st">  </span><span class="kw">select</span>(ID, score, bty_avg, age)</span></code></pre></div>
<p>A crucial step before doing any kind of analysis or modeling is performing an <em>exploratory data analysis</em>,  or EDA for short. EDA gives you a sense of the distributions of the individual variables in your data, whether any potential relationships exist between variables, whether there are outliers and/or missing values, and (most importantly) how to build your model. Here are three common steps in an EDA:</p>
<!-- DK: Good stuff. We should keep this and follow it, each chapter. -->
<ol style="list-style-type: decimal">
<li>Most crucially, looking at the raw data values.</li>
<li>Computing summary statistics, such as means, medians, and interquartile ranges.</li>
<li>Creating data visualizations.</li>
</ol>
<p>Let’s perform the first common step in an exploratory data analysis: looking at the raw data values. Because this step seems so trivial, unfortunately many data analysts ignore it. However, getting an early sense of what your raw data looks like can often prevent many larger issues down the road.</p>
<p>You can do this by using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> function as introduced in Subsection <a href="nycflights13.html#exploredataframes">1.4.3</a> on exploring data frames:</p>
<!-- DK: Add summary() -->
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="model1.html#cb674-1"></a><span class="kw">glimpse</span>(evals_ch11)</span></code></pre></div>
<pre><code>## Rows: 463
## Columns: 4
## $ ID      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18…
## $ score   &lt;dbl&gt; 4.7, 4.1, 3.9, 4.8, 4.6, 4.3, 2.8, 4.1, 3.4, 4.5, 3.8, 4.5, 4…
## $ bty_avg &lt;dbl&gt; 5.00, 5.00, 5.00, 5.00, 3.00, 3.00, 3.00, 3.33, 3.33, 3.17, 3…
## $ age     &lt;int&gt; 36, 36, 36, 36, 59, 59, 59, 51, 51, 40, 40, 40, 40, 40, 40, 4…</code></pre>
<p>Observe that <code>Observations: 463</code> indicates that there are 463 rows/observations in <code>evals_ch11</code>, where each row corresponds to one observed course at UT Austin. It is important to note that the <em>observational unit</em>  is an individual course and not an individual instructor. Recall from Subsection <a href="nycflights13.html#exploredataframes">1.4.3</a> that the observational unit is the “type of thing” that is being measured by our variables. Since instructors teach more than one course in an academic year, the same instructor will appear more than once in the data. Hence there are fewer than 463 unique instructors being represented in <code>evals_ch11</code>.</p>
<p>A full description of all the variables included in <code>evals</code> can be found at <a href="https://www.openintro.org/data/index.php?data=evals">openintro.org</a> or by reading the associated help file (run <code>?evals</code> in the console). However, let’s fully describe only the 4 variables we selected in <code>evals_ch11</code>:</p>
<ol style="list-style-type: decimal">
<li><code>ID</code>: An identification variable used to distinguish between the 1 through 463 courses in the dataset.</li>
<li><code>score</code>: A numerical variable of the course instructor’s average teaching score, where the average is computed from the evaluation scores from all students in that course. Teaching scores of 1 are lowest and 5 are highest. This is the outcome variable <span class="math inline">\(y\)</span> of interest.</li>
<li><code>bty_avg</code>: A numerical variable of the course instructor’s average “beauty” score, where the average is computed from a separate panel of six students. “Beauty” scores of 1 are lowest and 10 are highest. This is the explanatory variable <span class="math inline">\(x\)</span> of interest.</li>
<li><code>age</code>: A numerical variable of the course instructor’s age.</li>
</ol>
<p>An alternative way to look at the raw data values is by choosing a random sample of the rows in <code>evals_ch11</code> by piping it into the <code>sample_n()</code>  function from the <strong>dplyr</strong> package. Here we set the <code>size</code> argument to be <code>5</code>, indicating that we want a random sample of 5 rows. We display the results below. Note that due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="model1.html#cb676-1"></a>evals_ch11 <span class="op">%&gt;%</span></span>
<span id="cb676-2"><a href="model1.html#cb676-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dt">size =</span> <span class="dv">5</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-356">TABLE 10.1: </span>A random sample of 5 out of the 463 courses at UT Austin
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:right;">
score
</th>
<th style="text-align:right;">
bty_avg
</th>
<th style="text-align:right;">
age
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
166
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
4.33
</td>
<td style="text-align:right;">
63
</td>
</tr>
<tr>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
4.7
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
62
</td>
</tr>
<tr>
<td style="text-align:right;">
135
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:right;">
64
</td>
</tr>
<tr>
<td style="text-align:right;">
73
</td>
<td style="text-align:right;">
4.4
</td>
<td style="text-align:right;">
4.83
</td>
<td style="text-align:right;">
42
</td>
</tr>
<tr>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
4.2
</td>
<td style="text-align:right;">
4.00
</td>
<td style="text-align:right;">
49
</td>
</tr>
</tbody>
</table>
<p>Now that we’ve looked at the raw values in our <code>evals_ch11</code> data frame and got a preliminary sense of the data, let’s move on to the next common step in an exploratory data analysis: computing summary statistics. Let’s start by computing the mean and median of our numerical outcome variable <code>score</code> and our numerical explanatory variable “beauty” score denoted as <code>bty_avg</code>. We’ll do this by using the <code>summarize()</code> function from <code>dplyr</code> along with the <code>mean()</code> and <code>median()</code> summary functions we saw in Section <a href="summarize.html#summarize">2.3</a>.</p>
<div class="sourceCode" id="cb677"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb677-1"><a href="model1.html#cb677-1"></a>evals_ch11 <span class="op">%&gt;%</span></span>
<span id="cb677-2"><a href="model1.html#cb677-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_bty_avg =</span> <span class="kw">mean</span>(bty_avg),</span>
<span id="cb677-3"><a href="model1.html#cb677-3"></a>            <span class="dt">mean_score =</span> <span class="kw">mean</span>(score),</span>
<span id="cb677-4"><a href="model1.html#cb677-4"></a>            <span class="dt">median_bty_avg =</span> <span class="kw">median</span>(bty_avg),</span>
<span id="cb677-5"><a href="model1.html#cb677-5"></a>            <span class="dt">median_score =</span> <span class="kw">median</span>(score))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   mean_bty_avg mean_score median_bty_avg median_score
##          &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;        &lt;dbl&gt;
## 1         4.42       4.17           4.33          4.3</code></pre>
<!-- DK: This is nice. Having motivated the use of skim() once, we can just go straight to using it in other chapters. And/or show other tricks each chapter, like across(). -->
<p>However, what if we want other summary statistics as well, such as the standard deviation (a measure of spread), the minimum and maximum values, and various percentiles?</p>
<p>Typing out all these summary statistic functions in <code>summarize()</code> would be long and tedious. Instead, let’s use the convenient <code>skim()</code> function from the <strong>skimr</strong> package. This function takes in a data frame, “skims” it, and returns commonly used summary statistics. Let’s take our <code>evals_ch11</code> data frame, <code>select()</code> only the outcome and explanatory variables teaching <code>score</code> and <code>bty_avg</code>, and pipe them into the <code>skim()</code> function:</p>
<div class="sourceCode" id="cb679"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb679-1"><a href="model1.html#cb679-1"></a>evals_ch11 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb679-2"><a href="model1.html#cb679-2"></a><span class="st">  </span><span class="kw">select</span>(score, bty_avg) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb679-3"><a href="model1.html#cb679-3"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-358">TABLE 10.2: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
463
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
score
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:right;">
0.54
</td>
<td style="text-align:right;">
2.30
</td>
<td style="text-align:right;">
3.80
</td>
<td style="text-align:right;">
4.30
</td>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
5.00
</td>
<td style="text-align:left;">
▁▁▅▇▇
</td>
</tr>
<tr>
<td style="text-align:left;">
bty_avg
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.42
</td>
<td style="text-align:right;">
1.53
</td>
<td style="text-align:right;">
1.67
</td>
<td style="text-align:right;">
3.17
</td>
<td style="text-align:right;">
4.33
</td>
<td style="text-align:right;">
5.5
</td>
<td style="text-align:right;">
8.17
</td>
<td style="text-align:left;">
▃▇▇▃▂
</td>
</tr>
</tbody>
</table>
<p>For the numerical variables teaching <code>score</code> and <code>bty_avg</code> it returns:</p>
<ul>
<li><code>n_missing</code>: the number of missing values</li>
<li><code>complete_rate</code>: the percentage of non-missing or complete values</li>
<li><code>mean</code>: the average</li>
<li><code>sd</code>: the standard deviation</li>
<li><code>p0</code>: the 0th percentile: the value at which 0% of observations are smaller than it (the <em>minimum</em> value)</li>
<li><code>p25</code>: the 25th percentile: the value at which 25% of observations are smaller than it (the <em>1st quartile</em>)</li>
<li><code>p50</code>: the 50th percentile: the value at which 50% of observations are smaller than it (the <em>2nd</em> quartile and more commonly called the <em>median</em>)</li>
<li><code>p75</code>: the 75th percentile: the value at which 75% of observations are smaller than it (the <em>3rd quartile</em>)</li>
<li><code>p100</code>: the 100th percentile: the value at which 100% of observations are smaller than it (the <em>maximum</em> value)</li>
</ul>
<p>Looking at this output, we can see how the values of both variables are distributed. For example, the mean teaching score was 4.17 out of 5, whereas the mean “beauty” score was 4.42 out of 10. Furthermore, the middle 50% of teaching scores was between 3.80 and 4.6 (the first and third quartiles), whereas the middle 50% of “beauty” scores falls within 3.17 to 5.5 out of 10.</p>
<!-- DK: Keep this. -->
<p>The <code>skim()</code> function only returns what are known as <em>univariate</em>  summary statistics: functions that take a single variable and return some numerical summary of that variable. However, there also exist <em>bivariate</em>  summary statistics: functions that take in two variables and return some summary of those two variables. In particular, when the two variables are numerical, we can compute the  <em>correlation coefficient</em>. Generally speaking, <em>coefficients</em> are quantitative expressions of a specific phenomenon. A <em>correlation coefficient</em> is a quantitative expression of the <em>strength of the linear relationship between two numerical variables</em>. Its value ranges between -1 and 1 where:</p>
<ul>
<li>-1 indicates a perfect <em>negative relationship</em>: As one variable increases, the value of the other variable tends to go down, following a straight line.</li>
<li>0 indicates no relationship: The values of both variables go up/down independently of each other.</li>
<li>+1 indicates a perfect <em>positive relationship</em>: As the value of one variable goes up, the value of the other variable tends to go up as well in a linear fashion.</li>
</ul>
<p>The following figure gives examples of 9 different correlation coefficient values for hypothetical numerical variables <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. For example, observe in the top right plot that for a correlation coefficient of -0.75 there is a negative linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, but it is not as strong as the negative linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> when the correlation coefficient is -0.9 or -1.</p>
<div class="figure"><span id="fig:unnamed-chunk-359"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-359-1.png" alt="Nine different correlation coefficients." width="\textwidth" />
<p class="caption">
FIGURE 10.1: Nine different correlation coefficients.
</p>
</div>
<p>The correlation coefficient can be computed using the <code>cor()</code> summary function within a <code>summarize()</code>:</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="model1.html#cb680-1"></a>evals_ch11 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-2"><a href="model1.html#cb680-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">correlation =</span> <span class="kw">cor</span>(score, bty_avg))</span></code></pre></div>
<p>In our case, the correlation coefficient of 0.187 indicates that the relationship between teaching evaluation score and “beauty” average is “weakly positive.” There is a certain amount of subjectivity in interpreting correlation coefficients, especially those that aren’t close to the extreme values of -1, 0, and 1.</p>
<p>Let’s now perform the last of the steps in an exploratory data analysis: creating data visualizations. Since both the <code>score</code> and <code>bty_avg</code> variables are numerical, a scatterplot is an appropriate graph to visualize this data. Let’s do this using <code>geom_point()</code> and display the result. Furthermore, let’s highlight the six points in the top right of the visualization in a box.</p>
<div class="sourceCode" id="cb681"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb681-1"><a href="model1.html#cb681-1"></a>evals_ch11 <span class="op">%&gt;%</span></span>
<span id="cb681-2"><a href="model1.html#cb681-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bty_avg, <span class="dt">y =</span> score)) <span class="op">+</span></span>
<span id="cb681-3"><a href="model1.html#cb681-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb681-4"><a href="model1.html#cb681-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Beauty Score&quot;</span>, </span>
<span id="cb681-5"><a href="model1.html#cb681-5"></a>       <span class="dt">y =</span> <span class="st">&quot;Teaching Score&quot;</span>,</span>
<span id="cb681-6"><a href="model1.html#cb681-6"></a>       <span class="dt">title =</span> <span class="st">&quot;Scatterplot of relationship of teaching and beauty scores&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-363"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-363-1.png" alt="Instructor evaluation scores at UT Austin." width="\textwidth" />
<p class="caption">
FIGURE 10.2: Instructor evaluation scores at UT Austin.
</p>
</div>
<p>Observe that most “beauty” scores lie between 2 and 8, while most teaching scores lie between 3 and 5. Furthermore, while opinions may vary, it is our opinion that the relationship between teaching score and “beauty” score is “weakly positive.” This is consistent with our earlier computed correlation coefficient of 0.187.</p>
<p>Furthermore, there appear to be six points in the top-right of this plot highlighted in the box. However, this is not actually the case, as this plot suffers from <em>overplotting</em>. Recall from Subsection <a href="scatterplots.html#overplotting">1.7.2</a> that overplotting occurs when several points are stacked directly on top of each other, making it difficult to distinguish them. So while it may appear that there are only six points in the box, there are actually more. This fact is only apparent when using <code>geom_jitter()</code> in place of <code>geom_point()</code>. We display the resulting plot along with the same small box as before.</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="model1.html#cb682-1"></a>evals_ch11 <span class="op">%&gt;%</span></span>
<span id="cb682-2"><a href="model1.html#cb682-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bty_avg, <span class="dt">y =</span> score)) <span class="op">+</span></span>
<span id="cb682-3"><a href="model1.html#cb682-3"></a><span class="st">  </span><span class="kw">geom_jitter</span>() <span class="op">+</span></span>
<span id="cb682-4"><a href="model1.html#cb682-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Beauty Score&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Teaching Score&quot;</span>,</span>
<span id="cb682-5"><a href="model1.html#cb682-5"></a>       <span class="dt">title =</span> <span class="st">&quot;Scatterplot of relationship of teaching and beauty scores&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-365"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-365-1.png" alt="Instructor evaluation scores at UT Austin." width="\textwidth" />
<p class="caption">
FIGURE 10.3: Instructor evaluation scores at UT Austin.
</p>
</div>
<p>It is now apparent that there are 12 points in the area highlighted in the box and not six as originally suggested. Recall from Subsection <a href="scatterplots.html#overplotting">1.7.2</a> on overplotting that jittering adds a little random “nudge” to each of the points to break up these ties. Furthermore, recall that jittering is strictly a visualization tool; it does not alter the original values in the data frame <code>evals_ch11</code>. To keep things simple going forward, however, we’ll only present regular scatterplots rather than their jittered counterparts.</p>
<p>Let’s build on the unjittered scatterplot by adding a “best-fitting” line: of all possible lines we can draw on this scatterplot, it is the line that “best” fits through the cloud of points. We do this by adding a new <code>geom_smooth(method = "lm", se = FALSE)</code> layer to the <code>ggplot()</code> code that created the scatterplot. The <code>method = "lm"</code> argument sets the line to be a “<code>l</code>inear <code>m</code>odel.” The <code>se = FALSE</code>  argument suppresses <em>standard error</em> uncertainty bars. (We defined the concept of <em>standard error</em> in Subsection <a href="sampling-framework.html#sampling-definitions">6.3.2</a>.)</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="model1.html#cb683-1"></a>evals_ch11 <span class="op">%&gt;%</span></span>
<span id="cb683-2"><a href="model1.html#cb683-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> bty_avg, <span class="dt">y =</span> score)) <span class="op">+</span></span>
<span id="cb683-3"><a href="model1.html#cb683-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb683-4"><a href="model1.html#cb683-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Beauty Score&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Teaching Score&quot;</span>,</span>
<span id="cb683-5"><a href="model1.html#cb683-5"></a>       <span class="dt">title =</span> <span class="st">&quot;Relationship between teaching and beauty scores&quot;</span>) <span class="op">+</span><span class="st">  </span></span>
<span id="cb683-6"><a href="model1.html#cb683-6"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-366"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-366-1.png" alt="Regression line." width="\textwidth" />
<p class="caption">
FIGURE 10.4: Regression line.
</p>
</div>
<p>The line in the resulting figure is called a “regression line.” The regression line  is a visual summary of the relationship between two numerical variables, in our case the outcome variable <code>score</code> and the explanatory variable <code>bty_avg</code>. The positive slope of the blue line is consistent with our earlier observed correlation coefficient of 0.187 suggesting that there is a positive relationship between these two variables: as instructors have higher “beauty” scores, so also do they receive higher teaching evaluations. We’ll see later, however, that while the correlation coefficient and the slope of a regression line always have the same sign (positive or negative), they typically do not have the same value.</p>
<p>Furthermore, a regression line is “best-fitting” in that it minimizes some mathematical criteria. We present these mathematical criteria in Section <a href="leastsquares.html#leastsquares">10.5</a>, but we suggest you read this subsection only after first reading the rest of this section on regression with one numerical explanatory variable.</p>
</div>
<div id="model1table" class="section level3">
<h3><span class="header-section-number">10.1.2</span> Simple linear regression</h3>
<!-- DK: Make this with just one decimal. Indeed, can we make that consistent everywhere? Also, bty_avg should be renamed beauty. We don't really care if it is an average. -->
<p>You may recall from secondary/high school algebra that the equation of a line is <span class="math inline">\(y = a + b\cdot x\)</span>. (Note that the <span class="math inline">\(\cdot\)</span> symbol is equivalent to the <span class="math inline">\(\times\)</span> “multiply by” mathematical symbol. We’ll use the <span class="math inline">\(\cdot\)</span> symbol in the rest of this book as it is more succinct.) It is defined by two coefficients <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The intercept coefficient <span class="math inline">\(a\)</span> is the value of <span class="math inline">\(y\)</span> when <span class="math inline">\(x = 0\)</span>. The slope coefficient <span class="math inline">\(b\)</span> for <span class="math inline">\(x\)</span> is the increase in <span class="math inline">\(y\)</span> for every increase of one in <span class="math inline">\(x\)</span>. This is also called the “rise over run.”</p>
<p>However, when defining a regression line, we use slightly different notation: the equation of the regression line is <span class="math inline">\(\widehat{y} = b_0 + b_1 \cdot x\)</span> . The intercept coefficient is <span class="math inline">\(b_0\)</span>, so <span class="math inline">\(b_0\)</span> is the value of <span class="math inline">\(\widehat{y}\)</span> when <span class="math inline">\(x = 0\)</span>. The slope coefficient for <span class="math inline">\(x\)</span> is <span class="math inline">\(b_1\)</span>, i.e., the increase in <span class="math inline">\(\widehat{y}\)</span> for every increase of one in <span class="math inline">\(x\)</span>. Why do we put a “hat” on top of the <span class="math inline">\(y\)</span>? It’s a form of notation commonly used in regression to indicate that we have a  “fitted value,” or the value of <span class="math inline">\(y\)</span> on the regression line for a given <span class="math inline">\(x\)</span> value. We’ll discuss this more in the upcoming Subsection <a href="uncertainty-in-simple-linear-regressions.html#model1points">10.2.2</a>.</p>
<!-- DK: Is this a good introduction to hat notation? This stikes me as a subtle point that should be wesved throughout the book.  -->
<p>We know that the regression line we plotted has a positive slope <span class="math inline">\(b_1\)</span> corresponding to our explanatory <span class="math inline">\(x\)</span> variable <code>bty_avg</code>. Why? Because instructors with higher <code>bty_avg</code> scores tend to have higher teaching evaluation <code>scores</code>. However, what is the numerical value of the slope <span class="math inline">\(b_1\)</span>? What about the intercept <span class="math inline">\(b_0\)</span>? Let’s not compute these two values by hand, but rather let’s use a computer!</p>
<p>We can obtain the values of the intercept <span class="math inline">\(b_0\)</span> and the slope for <code>btg_avg</code> <span class="math inline">\(b_1\)</span> in two steps:</p>
<ol style="list-style-type: decimal">
<li>“Fit” the linear regression model using the <code>lm()</code> function and save it in <code>score_model</code>. We put the name of the outcome variable on the left-hand side of the <code>~</code> “tilde” sign, while putting the name of the explanatory variable on the right-hand side. This is known as R’s  <em>formula notation</em>.</li>
<li>Apply the <code>tidy()</code>  function from the <strong>broom</strong> package to <code>score_model</code>.</li>
</ol>
<div class="sourceCode" id="cb685"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb685-1"><a href="model1.html#cb685-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb685-2"><a href="model1.html#cb685-2"></a></span>
<span id="cb685-3"><a href="model1.html#cb685-3"></a>score_model &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>bty_avg, <span class="dt">data =</span> evals_ch11)</span>
<span id="cb685-4"><a href="model1.html#cb685-4"></a></span>
<span id="cb685-5"><a href="model1.html#cb685-5"></a><span class="co"># Get regression table:</span></span>
<span id="cb685-6"><a href="model1.html#cb685-6"></a></span>
<span id="cb685-7"><a href="model1.html#cb685-7"></a>score_model <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb685-8"><a href="model1.html#cb685-8"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-369">TABLE 10.3: </span>Linear regression table
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
3.880
</td>
<td style="text-align:right;">
0.076
</td>
<td style="text-align:right;">
50.96
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3.731
</td>
<td style="text-align:right;">
4.030
</td>
</tr>
<tr>
<td style="text-align:left;">
bty_avg
</td>
<td style="text-align:right;">
0.067
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
4.09
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.035
</td>
<td style="text-align:right;">
0.099
</td>
</tr>
</tbody>
</table>
<p>Note that we used the argument <code>conf.int = TRUE</code> in the <code>tidy()</code> function; that will be important for later.</p>
<p>How did this code work? First, we “fit” the linear regression model to the <code>data</code> using the <code>lm()</code>  function and saved this as <code>score_model</code>. When we say “fit”, we mean “find the best fitting line to this data.” <code>lm()</code> stands for “linear model” and is used as follows: <code>lm(y ~ x, data = data_frame_name)</code> where:</p>
<ul>
<li><code>y</code> is the outcome variable, followed by a tilde <code>~</code>. In our case, <code>y</code> is set to <code>score</code>.</li>
<li><code>x</code> is the explanatory variable. In our case, <code>x</code> is set to <code>bty_avg</code>.</li>
<li>The combination of <code>y ~ x</code> is called a <em>model formula</em>. (Note the order of <code>y</code> and <code>x</code>.) In our case, the model formula is <code>score ~ bty_avg</code>.</li>
<li><code>data_frame_name</code> is the name of the data frame that contains the variables <code>y</code> and <code>x</code>. In our case, <code>data_frame_name</code> is the <code>evals_ch11</code> data frame.</li>
</ul>
<p>Second, we take the saved model in <code>score_model</code> and apply the <code>tidy()</code> function from the <strong>broom</strong> package to it to obtain the regression table.</p>
<p>We can also do this with pipes:</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="model1.html#cb686-1"></a>evals_ch11 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb686-2"><a href="model1.html#cb686-2"></a><span class="st">  </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>bty_avg, <span class="dt">data =</span> .) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb686-3"><a href="model1.html#cb686-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb686-4"><a href="model1.html#cb686-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   term        estimate conf.low conf.high
##   &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)   3.88     3.73      4.03  
## 2 bty_avg       0.0666   0.0346    0.0987</code></pre>
<p>Recall from our discussion in Chapter @ref{wrangling} that we can use “.” to refer to the tibble that has been passed in by the proceeding pipe. In this case, that is the <code>eval_ch11</code> tibble. Using “.” to refer to the passed-down tibble will be a trick which we use again and again in the coming chapters.</p>
<p>You may wonder why this code does not work:</p>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="model1.html#cb688-1"></a>evals_ch11 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-2"><a href="model1.html#cb688-2"></a><span class="st">  </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>bty_avg) </span></code></pre></div>
<!-- DK: How can we show the error which happens when this code runs? -->
<p>With most of the functions we have seen, we don’t need the “hack” of referring to the passed-down tibble with a “.”. Things “just work.” Functions like <code>filter()</code> and <code>arrange()</code> just know to work on the tibble which is coming there way. Why doesn’t <code>lm()</code> do that?</p>
<p>The answer is that <code>lm()</code> is, like many parts of R, an old function, created before the Tidyverse came into style. Look at the help page with <code>?lm</code>. As you can see, the first argument is <code>formula</code>. The automatic pass-down trick only works with functions in which the first argument is the data to be used. This is (almost) always the case in Tidyverse functions.</p>
</div>
<div id="interpreting-regression-coefficients" class="section level3">
<h3><span class="header-section-number">10.1.3</span> Interpreting regression coefficients</h3>
<p>In the <code>estimate</code> column are the intercept <span class="math inline">\(b_0\)</span> = 3.88 and the slope <span class="math inline">\(b_1\)</span> = 0.067 for <code>bty_avg</code>. Thus the equation of the regression line follows:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} &amp;= b_0 + b_1 \cdot x\\
\widehat{\text{score}} &amp;= b_0 + b_{\text{bty}\_\text{avg}} \cdot\text{bty}\_\text{avg}\\
&amp;= 3.880 + 0.067\cdot\text{bty}\_\text{avg}
\end{aligned}
\]</span></p>
<!-- DK: "beauty" rather than "bty_avg" would be a better variable name. Don't need to recall that the beauty score is an average. After all, the score is an average also! Also: Need a discussion of potential outcomes and RCM here. Can we manipulate beauty? On one hand, no. On the other hand, yes. Makeup, lighting and so on. Could provide an interesting complex case to discuss. -->
<p>The intercept <span class="math inline">\(b_0\)</span> = 3.88 is the average teaching score <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> for those courses where the instructor had a “beauty” score <code>bty_avg</code> of 0. Or in graphical terms, it’s where the line intersects the <span class="math inline">\(y\)</span> axis when <span class="math inline">\(x\)</span> = 0. Note, however, that while the  intercept of the regression line has a mathematical interpretation, it has no <em>practical</em> interpretation here, since observing a <code>bty_avg</code> of 0 is impossible; it is the average of six panelists’ “beauty” scores ranging from 1 to 10. Furthermore, looking at the scatterplot with the regression line, no instructors had a “beauty” score anywhere near 0.</p>
<!-- DK: Add discussion of "hat". Recall the p hat which we estimated last time. y hat is like that! It is not a variable that we can observe. It is an estimate. (Indeed, it is an estimate of a potential outcome!) This is different form x, which has no hat, because it is real data, something we can see. Side note: not sure if the hat versus no hat distinction works well with b_0/b_1 being things we can't see and need to estimate, but for which we do not use hat notation. -->
<p>Of greater interest is the  slope <span class="math inline">\(b_1\)</span> = <span class="math inline">\(b_{\text{bty_avg}}\)</span> of 0.067. The “bty_avg” subscript indicates that this number summarizes the relationship between the teaching and average beauty score variables. Note that the sign is positive, suggesting a positive relationship between these two variables, meaning teachers with higher <code>bty_avg</code> scores also tend to have higher teaching scores. Recall from earlier that the correlation coefficient is 0.187. They both have the same positive sign, but have a different value. Recall further that the correlation’s interpretation is the “strength of linear association”. The  slope’s interpretation is a little different:</p>
<!-- DK: Let's make sure that these interpretations are highly consistent with Gelman and across the book. -->
<blockquote>
<p>For every increase of 1 unit in <code>bty_avg</code>, there is an <em>associated</em> increase of, <em>on average</em>, 0.067 units of <code>score</code>.</p>
</blockquote>
<p>We say that this associated increase is <em>on average</em> 0.067 units of teaching <code>score</code>, because you might have two instructors whose <code>bty_avg</code> scores differ by 1 unit, but their difference in teaching scores won’t necessarily be exactly 0.067. What the slope of 0.067 is saying is that across all possible courses, the <em>average</em> difference in teaching score between two instructors whose “beauty” scores differ by one is 0.067.</p>
<p>Furthermore, we only state that there is an <em>associated</em> increase and not necessarily a <em>causal</em> increase. For example, perhaps it’s not that higher “beauty” scores directly cause higher teaching scores per se. Instead, the following could hold true: individuals from wealthier backgrounds tend to have stronger educational backgrounds and hence have higher teaching scores, while at the same time these wealthy individuals also tend to have higher “beauty” scores. In other words, just because two variables are strongly associated, it doesn’t necessarily mean that one causes the other. This is summed up in the often quoted phrase, “correlation is not necessarily causation.”</p>
<p>Consider an example: a not-so-great medical doctor goes through medical records and finds that patients who slept with their shoes on tended to wake up more with headaches. So this doctor declares, “Sleeping with shoes on causes headaches!”</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-372"></span>
<img src="images/shutterstock/shoes_headache.png" alt="Does sleeping with shoes on cause headaches?" width="60%" height="60%" />
<p class="caption">
FIGURE 10.5: Does sleeping with shoes on cause headaches?
</p>
</div>
<p>However, there is a good chance that if someone is sleeping with their shoes on, it’s potentially because they are intoxicated from alcohol. Furthermore, higher levels of drinking leads to more hangovers, and hence more headaches. The amount of alcohol consumption here is what’s known as a <em>confounding</em> variable. It lurks behind the scenes, confounding the causal relationship (if any) of “sleeping with shoes on” with “waking up with a headache.” We can summarize this with a <em>causal graph</em> where:</p>
<ul>
<li>Y is a <em>response</em> variable; here it is “waking up with a headache.” </li>
<li>X is a <em>treatment</em> variable whose causal effect we are interested in; here it is “sleeping with shoes on.”</li>
</ul>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-373"></span>
<img src="images/flowchart.009-cropped.png" alt="Causal graph." width="50%" />
<p class="caption">
FIGURE 10.6: Causal graph.
</p>
</div>
<p>To study the relationship between Y and X, we could use a regression model where the outcome variable is set to Y and the explanatory variable is set to be X, as you’ve been doing throughout this chapter. However, the causal graph also includes a third variable with arrows pointing at both X and Y:</p>
<ul>
<li>Z is a <em>confounding</em> variable  that affects both X and Y, thereby “confounding” their relationship. Here the confounding variable is alcohol.</li>
</ul>
<p>Alcohol will cause people to be both more likely to sleep with their shoes on as well as be more likely to wake up with a headache. We can see why this is a problem under the potential outcomes framework: both whether you receive the treatment “sleeping with shoes on” and your potential outcome depend on whether you consumed alcohol, which means that you can’t estimate the treatment effect of “sleeping with shoes on” simply by comparing the observed outcome under treatment and the observed outcome under control. Thus any regression model of the relationship between X and Y should also use Z as an explanatory variable. In other words, our doctor needs to take into account who had been drinking the night before. In the next chapter, we’ll start covering multiple regression models that allow us to incorporate more than one variable in our regression models.</p>
<!-- DK: In the next chapter? Not if we re-organize. -->
<p>Establishing causation is a tricky problem and frequently takes either randomized controlled trials or methods to adjust for the effects of confounding variables. Both these approaches attempt, as best they can, either to take all possible confounding variables into account or negate their impact. This allows researchers to focus only on the relationship of interest: the relationship between the outcome variable Y and the treatment variable X.</p>
<p>As you read news stories, be careful not to fall into the trap of thinking that correlation necessarily implies causation. Check out the <a href="http://www.tylervigen.com/spurious-correlations">Spurious Correlations</a> website for some rather comical examples of variables that are correlated, but are definitely not causally related.</p>
<!--AR: trying to be precise that it is correlation with the treatment and *potential* outcomes that matters, not correlation with the treatment and observed outcomes.  What's a better way to explain this?
DK: Agreed! Indeed, we need to hit the notion of potential outcomes each chapter. Potential outcomes != observed outcomes! Not mentioning RCM for 4 weeks is a mistake. -->
<p>Let’s say, however, that we were confident that there is no confounding: that is, that there are no variables such as socioeconomic background that correlate both with a teacher’s beauty score and the teacher’s potential outcomes. (We shouldn’t be confident in this, but let’s play along for the moment.) Then, we can interpret the slope in terms of the <a href="rubin-causal-model.html#rubin-causal-model">Rubin Causal Model</a>. The slope coefficient on <code>bty_avg</code> of 0.067 then means that the <em>average treatment effect</em> of increasing a teacher’s “beauty” score by 1 is 0.067. In the absence of randomization, however, this is likely not a good interpretation of this regression! Adding additional variables, as we’ll do in Chapter @ref{multiple-regression}, may make it more plausible to interpret the regression causally.</p>
<p>Keeping with the causal interpretation, let’s say that a teacher named Joe had a “beauty” score of 7 and a teaching score of 4. We are curious about how much moving from a “beauty” score of 7 versus “beauty” score of 8 would have affected Joe’s teaching score. Thus, we are comparing the <em>potential outcome</em> for Joe when <code>bty_avg</code> is 7 versus the <em>potential outcome</em> when <code>bty_avg</code> is 8. Only one of these potential outcomes was observed.</p>
<!-- DK: This is good stuff. Belongs in every chapter. -->
<table class="table table-striped" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
Subject
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{bty\_avg = 7}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{bty\_avg = 8}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Joe
</td>
<td style="text-align:left;">
<span class="math inline">\(4\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
</tr>
</tbody>
</table>
<p>We can use our slope coefficient from the linear regression, which is our best estimate of the average treatment effect (ATE), to fill in the missing potential outcome:</p>
<table class="table table-striped" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
Subject
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{bty\_avg = 7}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{bty\_avg = 8}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\widehat{ATE}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Joe
</td>
<td style="text-align:left;">
<span class="math inline">\(4\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4.067\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(0.067\)</span>
</td>
</tr>
</tbody>
</table>
<p>Thus, our best guess of Joe’s potential outcome under the “treatment” of <span class="math inline">\(score = 8\)</span> is <span class="math inline">\(4.067\)</span>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="uncertainty-in-simple-linear-regressions.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
