<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11.1 Teaching evaluations revisited: one numerical and one categorical explanatory variable | Preceptor’s Primer for Bayesian Data Science</title>
  <meta name="description" content="11.1 Teaching evaluations revisited: one numerical and one categorical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="11.1 Teaching evaluations revisited: one numerical and one categorical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="davidkane9/PPBDS" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11.1 Teaching evaluations revisited: one numerical and one categorical explanatory variable | Preceptor’s Primer for Bayesian Data Science" />
  
  
  

<meta name="author" content="David Kane" />


<meta name="date" content="2020-05-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-regression.html"/>
<link rel="next" href="model3.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="forward.html"><a href="forward.html"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="warning.html"><a href="warning.html"><i class="fa fa-check"></i>Warning</a></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="part-i.html"><a href="part-i.html"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="1" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>1</b> Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio.html"><a href="r-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="r-rstudio.html"><a href="r-rstudio.html#installing"><i class="fa fa-check"></i><b>1.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="r-rstudio.html"><a href="r-rstudio.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="code.html"><a href="code.html"><i class="fa fa-check"></i><b>1.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="code.html"><a href="code.html#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="1.2.2" data-path="code.html"><a href="code.html#messages"><i class="fa fa-check"></i><b>1.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="1.2.3" data-path="code.html"><a href="code.html#tips-code"><i class="fa fa-check"></i><b>1.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="packages.html"><a href="packages.html#package-installation"><i class="fa fa-check"></i><b>1.3.1</b> Package installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="packages.html"><a href="packages.html#package-loading"><i class="fa fa-check"></i><b>1.3.2</b> Package loading</a></li>
<li class="chapter" data-level="1.3.3" data-path="packages.html"><a href="packages.html#package-use"><i class="fa fa-check"></i><b>1.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="nycflights13.html"><a href="nycflights13.html"><i class="fa fa-check"></i><b>1.4</b> Explore your first datasets</a><ul>
<li class="chapter" data-level="1.4.1" data-path="nycflights13.html"><a href="nycflights13.html#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="nycflights13.html"><a href="nycflights13.html#flights-data-frame"><i class="fa fa-check"></i><b>1.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="1.4.3" data-path="nycflights13.html"><a href="nycflights13.html#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="1.4.4" data-path="nycflights13.html"><a href="nycflights13.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>1.4.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="1.4.5" data-path="nycflights13.html"><a href="nycflights13.html#help-files"><i class="fa fa-check"></i><b>1.4.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a><ul>
<li class="chapter" data-level="1.5.1" data-path="conclusion.html"><a href="conclusion.html#additional-resources"><i class="fa fa-check"></i><b>1.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html"><i class="fa fa-check"></i><b>1.6</b> The grammar of graphics</a><ul>
<li class="chapter" data-level="1.6.1" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#components-of-the-grammar"><i class="fa fa-check"></i><b>1.6.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="1.6.2" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#gapminder"><i class="fa fa-check"></i><b>1.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="1.6.3" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#other-components"><i class="fa fa-check"></i><b>1.6.3</b> Other components</a></li>
<li class="chapter" data-level="1.6.4" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#ggplot2-package"><i class="fa fa-check"></i><b>1.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>1.7</b> Scatterplots</a><ul>
<li class="chapter" data-level="1.7.1" data-path="scatterplots.html"><a href="scatterplots.html#geompoint"><i class="fa fa-check"></i><b>1.7.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="scatterplots.html"><a href="scatterplots.html#overplotting"><i class="fa fa-check"></i><b>1.7.2</b> Overplotting</a></li>
<li class="chapter" data-level="1.7.3" data-path="scatterplots.html"><a href="scatterplots.html#summary"><i class="fa fa-check"></i><b>1.7.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="linegraphs.html"><a href="linegraphs.html"><i class="fa fa-check"></i><b>1.8</b> Linegraphs</a><ul>
<li class="chapter" data-level="1.8.1" data-path="linegraphs.html"><a href="linegraphs.html#geomline"><i class="fa fa-check"></i><b>1.8.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="linegraphs.html"><a href="linegraphs.html#summary-1"><i class="fa fa-check"></i><b>1.8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="histograms.html"><a href="histograms.html"><i class="fa fa-check"></i><b>1.9</b> Histograms</a><ul>
<li class="chapter" data-level="1.9.1" data-path="histograms.html"><a href="histograms.html#geomhistogram"><i class="fa fa-check"></i><b>1.9.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="1.9.2" data-path="histograms.html"><a href="histograms.html#adjustbins"><i class="fa fa-check"></i><b>1.9.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="1.9.3" data-path="histograms.html"><a href="histograms.html#summary-2"><i class="fa fa-check"></i><b>1.9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="facets.html"><a href="facets.html"><i class="fa fa-check"></i><b>1.10</b> Facets</a></li>
<li class="chapter" data-level="1.11" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>1.11</b> Boxplots</a><ul>
<li class="chapter" data-level="1.11.1" data-path="boxplots.html"><a href="boxplots.html#geomboxplot"><i class="fa fa-check"></i><b>1.11.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="boxplots.html"><a href="boxplots.html#summary-3"><i class="fa fa-check"></i><b>1.11.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="geombar.html"><a href="geombar.html"><i class="fa fa-check"></i><b>1.12</b> Barplots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="geombar.html"><a href="geombar.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>1.12.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="1.12.2" data-path="geombar.html"><a href="geombar.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>1.12.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="1.12.3" data-path="geombar.html"><a href="geombar.html#two-categ-barplot"><i class="fa fa-check"></i><b>1.12.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="1.12.4" data-path="geombar.html"><a href="geombar.html#summary-4"><i class="fa fa-check"></i><b>1.12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>1.13</b> Conclusion</a><ul>
<li class="chapter" data-level="1.13.1" data-path="conclusion-1.html"><a href="conclusion-1.html#summary-table"><i class="fa fa-check"></i><b>1.13.1</b> Summary table</a></li>
<li class="chapter" data-level="1.13.2" data-path="conclusion-1.html"><a href="conclusion-1.html#function-argument-specification"><i class="fa fa-check"></i><b>1.13.2</b> Function argument specification</a></li>
<li class="chapter" data-level="1.13.3" data-path="conclusion-1.html"><a href="conclusion-1.html#additional-resources-1"><i class="fa fa-check"></i><b>1.13.3</b> Additional resources</a></li>
<li class="chapter" data-level="1.13.4" data-path="conclusion-1.html"><a href="conclusion-1.html#whats-to-come-3"><i class="fa fa-check"></i><b>1.13.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>2</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="piping.html"><a href="piping.html"><i class="fa fa-check"></i><b>2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.2" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="2.3" data-path="summarize.html"><a href="summarize.html"><i class="fa fa-check"></i><b>2.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="2.4" data-path="groupby.html"><a href="groupby.html"><i class="fa fa-check"></i><b>2.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="groupby.html"><a href="groupby.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>2.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>2.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="2.6" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>2.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="2.7" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>2.7</b> Factors</a><ul>
<li class="chapter" data-level="2.7.1" data-path="factors.html"><a href="factors.html#the-forcats-package"><i class="fa fa-check"></i><b>2.7.1</b> The <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="2.7.2" data-path="factors.html"><a href="factors.html#dropping-unused-levels"><i class="fa fa-check"></i><b>2.7.2</b> Dropping unused levels</a></li>
<li class="chapter" data-level="2.7.3" data-path="factors.html"><a href="factors.html#reorder-factors"><i class="fa fa-check"></i><b>2.7.3</b> Change order of the levels, principled</a></li>
<li class="chapter" data-level="2.7.4" data-path="factors.html"><a href="factors.html#change-order-of-the-levels-because-i-said-so"><i class="fa fa-check"></i><b>2.7.4</b> Change order of the levels, “because I said so”</a></li>
<li class="chapter" data-level="2.7.5" data-path="factors.html"><a href="factors.html#recode-the-levels"><i class="fa fa-check"></i><b>2.7.5</b> Recode the levels</a></li>
<li class="chapter" data-level="2.7.6" data-path="factors.html"><a href="factors.html#grow-a-factor"><i class="fa fa-check"></i><b>2.7.6</b> Grow a factor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="character-vectors.html"><a href="character-vectors.html"><i class="fa fa-check"></i><b>2.8</b> Character Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="character-vectors.html"><a href="character-vectors.html#manipulating-character-vectors"><i class="fa fa-check"></i><b>2.8.1</b> Manipulating character vectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-resources"><i class="fa fa-check"></i><b>2.8.2</b> Regular expressions resources</a></li>
<li class="chapter" data-level="2.8.3" data-path="character-vectors.html"><a href="character-vectors.html#character-encoding-resources"><i class="fa fa-check"></i><b>2.8.3</b> Character encoding resources</a></li>
<li class="chapter" data-level="2.8.4" data-path="character-vectors.html"><a href="character-vectors.html#character-vectors-that-live-in-a-data-frame"><i class="fa fa-check"></i><b>2.8.4</b> Character vectors that live in a data frame</a></li>
<li class="chapter" data-level="2.8.5" data-path="character-vectors.html"><a href="character-vectors.html#regex-free-string-manipulation-with-stringr-and-tidyr"><i class="fa fa-check"></i><b>2.8.5</b> Regex-free string manipulation with stringr and tidyr</a></li>
<li class="chapter" data-level="2.8.6" data-path="character-vectors.html"><a href="character-vectors.html#detect-or-filter-on-a-target-string"><i class="fa fa-check"></i><b>2.8.6</b> Detect or filter on a target string</a></li>
<li class="chapter" data-level="2.8.7" data-path="character-vectors.html"><a href="character-vectors.html#string-splitting-by-delimiter"><i class="fa fa-check"></i><b>2.8.7</b> String splitting by delimiter</a></li>
<li class="chapter" data-level="2.8.8" data-path="character-vectors.html"><a href="character-vectors.html#substring-extraction-and-replacement-by-position"><i class="fa fa-check"></i><b>2.8.8</b> Substring extraction (and replacement) by position</a></li>
<li class="chapter" data-level="2.8.9" data-path="character-vectors.html"><a href="character-vectors.html#collapse-a-vector"><i class="fa fa-check"></i><b>2.8.9</b> Collapse a vector</a></li>
<li class="chapter" data-level="2.8.10" data-path="character-vectors.html"><a href="character-vectors.html#catenate-vectors"><i class="fa fa-check"></i><b>2.8.10</b> Create a character vector by catenating multiple vectors</a></li>
<li class="chapter" data-level="2.8.11" data-path="character-vectors.html"><a href="character-vectors.html#substring-replacement"><i class="fa fa-check"></i><b>2.8.11</b> Substring replacement</a></li>
<li class="chapter" data-level="2.8.12" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-with-stringr"><i class="fa fa-check"></i><b>2.8.12</b> Regular expressions with stringr</a></li>
<li class="chapter" data-level="2.8.13" data-path="character-vectors.html"><a href="character-vectors.html#characters-with-special-meaning"><i class="fa fa-check"></i><b>2.8.13</b> Characters with special meaning</a></li>
<li class="chapter" data-level="2.8.14" data-path="character-vectors.html"><a href="character-vectors.html#character-classes"><i class="fa fa-check"></i><b>2.8.14</b> Character classes</a></li>
<li class="chapter" data-level="2.8.15" data-path="character-vectors.html"><a href="character-vectors.html#quantifiers"><i class="fa fa-check"></i><b>2.8.15</b> Quantifiers</a></li>
<li class="chapter" data-level="2.8.16" data-path="character-vectors.html"><a href="character-vectors.html#escaping"><i class="fa fa-check"></i><b>2.8.16</b> Escaping</a></li>
<li class="chapter" data-level="2.8.17" data-path="character-vectors.html"><a href="character-vectors.html#groups-and-backreferences"><i class="fa fa-check"></i><b>2.8.17</b> Groups and backreferences</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="combining-data.html"><a href="combining-data.html"><i class="fa fa-check"></i><b>2.9</b> Combining Data</a><ul>
<li class="chapter" data-level="2.9.1" data-path="combining-data.html"><a href="combining-data.html#bind"><i class="fa fa-check"></i><b>2.9.1</b> Bind</a></li>
<li class="chapter" data-level="2.9.2" data-path="combining-data.html"><a href="combining-data.html#joins-in-dplyr"><i class="fa fa-check"></i><b>2.9.2</b> Joins in dplyr</a></li>
<li class="chapter" data-level="2.9.3" data-path="combining-data.html"><a href="combining-data.html#joining"><i class="fa fa-check"></i><b>2.9.3</b> Joining</a></li>
<li class="chapter" data-level="2.9.4" data-path="combining-data.html"><a href="combining-data.html#matching-key-variable-names"><i class="fa fa-check"></i><b>2.9.4</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="2.9.5" data-path="combining-data.html"><a href="combining-data.html#diff-key"><i class="fa fa-check"></i><b>2.9.5</b> Different “key” variable names</a></li>
<li class="chapter" data-level="2.9.6" data-path="combining-data.html"><a href="combining-data.html#multiple-key-variables"><i class="fa fa-check"></i><b>2.9.6</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="2.9.7" data-path="combining-data.html"><a href="combining-data.html#normal-forms"><i class="fa fa-check"></i><b>2.9.7</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="other-verbs.html"><a href="other-verbs.html"><i class="fa fa-check"></i><b>2.10</b> Other Verbs</a><ul>
<li class="chapter" data-level="2.10.1" data-path="other-verbs.html"><a href="other-verbs.html#select"><i class="fa fa-check"></i><b>2.10.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="other-verbs.html"><a href="other-verbs.html#rename"><i class="fa fa-check"></i><b>2.10.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="2.10.3" data-path="other-verbs.html"><a href="other-verbs.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>2.10.3</b> <code>top_n</code> values of a variable</a></li>
<li class="chapter" data-level="2.10.4" data-path="other-verbs.html"><a href="other-verbs.html#slice-and-pull-and"><i class="fa fa-check"></i><b>2.10.4</b> <code>slice</code> and <code>pull</code> and <code>[]</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="conclusion-2.html"><a href="conclusion-2.html"><i class="fa fa-check"></i><b>2.11</b> Conclusion</a><ul>
<li class="chapter" data-level="2.11.1" data-path="conclusion-2.html"><a href="conclusion-2.html#summary-table-1"><i class="fa fa-check"></i><b>2.11.1</b> Summary table</a></li>
<li class="chapter" data-level="2.11.2" data-path="conclusion-2.html"><a href="conclusion-2.html#additional-resources-2"><i class="fa fa-check"></i><b>2.11.2</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>2.12</b> Tidy</a></li>
<li class="chapter" data-level="2.13" data-path="csv.html"><a href="csv.html"><i class="fa fa-check"></i><b>2.13</b> Importing data</a></li>
<li class="chapter" data-level="2.14" data-path="web-scraping.html"><a href="web-scraping.html"><i class="fa fa-check"></i><b>2.14</b> Web scraping</a><ul>
<li class="chapter" data-level="2.14.1" data-path="web-scraping.html"><a href="web-scraping.html#html"><i class="fa fa-check"></i><b>2.14.1</b> HTML</a></li>
<li class="chapter" data-level="2.14.2" data-path="web-scraping.html"><a href="web-scraping.html#the-rvest-package"><i class="fa fa-check"></i><b>2.14.2</b> The rvest package</a></li>
<li class="chapter" data-level="2.14.3" data-path="web-scraping.html"><a href="web-scraping.html#css-selectors"><i class="fa fa-check"></i><b>2.14.3</b> CSS selectors</a></li>
<li class="chapter" data-level="2.14.4" data-path="web-scraping.html"><a href="web-scraping.html#json"><i class="fa fa-check"></i><b>2.14.4</b> JSON</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html"><i class="fa fa-check"></i><b>2.15</b> “Tidy” data</a><ul>
<li class="chapter" data-level="2.15.1" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#tidy-definition"><i class="fa fa-check"></i><b>2.15.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="2.15.2" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>2.15.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="2.15.3" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#nycflights13-package-1"><i class="fa fa-check"></i><b>2.15.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="case-study-tidy.html"><a href="case-study-tidy.html"><i class="fa fa-check"></i><b>2.16</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="2.17" data-path="tidyverse-package.html"><a href="tidyverse-package.html"><i class="fa fa-check"></i><b>2.17</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="2.18" data-path="conclusion-3.html"><a href="conclusion-3.html"><i class="fa fa-check"></i><b>2.18</b> Conclusion</a><ul>
<li class="chapter" data-level="2.18.1" data-path="conclusion-3.html"><a href="conclusion-3.html#additional-resources-3"><i class="fa fa-check"></i><b>2.18.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rubin-causal-model.html"><a href="rubin-causal-model.html"><i class="fa fa-check"></i><b>3</b> Rubin Causal Model</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html"><i class="fa fa-check"></i><b>3.1</b> What is a causal effect?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#everything-is-a-missing-data-problem"><i class="fa fa-check"></i><b>3.1.1</b> Everything is a missing data problem</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#potential-outcomes-introduction-to-the-rubin-table"><i class="fa fa-check"></i><b>3.1.2</b> Potential outcomes: introduction to the Rubin Table</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#estimands"><i class="fa fa-check"></i><b>3.1.3</b> Estimands</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#the-infinite-rubin-table-many-kinds-of-missing-data"><i class="fa fa-check"></i><b>3.1.4</b> The infinite Rubin Table: many kinds of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html"><i class="fa fa-check"></i><b>3.2</b> How do we fill in the missing values?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#average-treatment-effect"><i class="fa fa-check"></i><b>3.2.1</b> Average treatment effect</a></li>
<li class="chapter" data-level="3.2.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#the-assignment-mechanism"><i class="fa fa-check"></i><b>3.2.2</b> The assignment mechanism</a></li>
<li class="chapter" data-level="3.2.3" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#uncertainty-and-permutation-tests"><i class="fa fa-check"></i><b>3.2.3</b> Uncertainty and permutation tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#everything-is-a-missing-data-problem-revisited-internal-and-external-validity"><i class="fa fa-check"></i><b>3.2.4</b> Everything is a missing data problem revisited: Internal and external validity</a></li>
<li class="chapter" data-level="3.2.5" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#more-complex-models-for-causal-inference"><i class="fa fa-check"></i><b>3.2.5</b> More complex models for causal inference</a></li>
<li class="chapter" data-level="3.2.6" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#causal-inference-and-prediction"><i class="fa fa-check"></i><b>3.2.6</b> Causal inference and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html"><i class="fa fa-check"></i><b>3.3</b> Other issues with causal inference</a><ul>
<li class="chapter" data-level="3.3.1" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#no-causation-without-manipulation"><i class="fa fa-check"></i><b>3.3.1</b> No causation without manipulation</a></li>
<li class="chapter" data-level="3.3.2" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#stable-unit-treatment-value-assumption-sutva"><i class="fa fa-check"></i><b>3.3.2</b> Stable unit treatment value assumption (SUTVA)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="conclusion-4.html"><a href="conclusion-4.html"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
<li class="chapter" data-level="3.5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a><ul>
<li class="chapter" data-level="4.1" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="part-1.html"><a href="part-1.html#get-something-that-works"><i class="fa fa-check"></i><b>4.1.1</b> Get something that works</a></li>
<li class="chapter" data-level="4.1.2" data-path="part-1.html"><a href="part-1.html#skateboard-perfectly-formed-rear-view-mirror"><i class="fa fa-check"></i><b>4.1.2</b> Skateboard &gt;&gt; perfectly formed rear-view mirror</a></li>
<li class="chapter" data-level="4.1.3" data-path="part-1.html"><a href="part-1.html#turn-the-working-interactive-code-into-a-function"><i class="fa fa-check"></i><b>4.1.3</b> Turn the working interactive code into a function</a></li>
<li class="chapter" data-level="4.1.4" data-path="part-1.html"><a href="part-1.html#test-your-function"><i class="fa fa-check"></i><b>4.1.4</b> Test your function</a></li>
<li class="chapter" data-level="4.1.5" data-path="part-1.html"><a href="part-1.html#check-the-validity-of-arguments"><i class="fa fa-check"></i><b>4.1.5</b> Check the validity of arguments</a></li>
<li class="chapter" data-level="4.1.6" data-path="part-1.html"><a href="part-1.html#wrap-up-and-whats-next"><i class="fa fa-check"></i><b>4.1.6</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i><b>4.2</b> Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="part-2.html"><a href="part-2.html#load-the-gapminder-data"><i class="fa fa-check"></i><b>4.2.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.2.2" data-path="part-2.html"><a href="part-2.html#restore-our-max-minus-min-function"><i class="fa fa-check"></i><b>4.2.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.2.3" data-path="part-2.html"><a href="part-2.html#generalize-our-function-to-other-quantiles"><i class="fa fa-check"></i><b>4.2.3</b> Generalize our function to other quantiles</a></li>
<li class="chapter" data-level="4.2.4" data-path="part-2.html"><a href="part-2.html#get-something-that-works-again"><i class="fa fa-check"></i><b>4.2.4</b> Get something that works, again</a></li>
<li class="chapter" data-level="4.2.5" data-path="part-2.html"><a href="part-2.html#turn-the-working-interactive-code-into-a-function-again"><i class="fa fa-check"></i><b>4.2.5</b> Turn the working interactive code into a function, again</a></li>
<li class="chapter" data-level="4.2.6" data-path="part-2.html"><a href="part-2.html#argument-names-freedom-and-conventions"><i class="fa fa-check"></i><b>4.2.6</b> Argument names: freedom and conventions</a></li>
<li class="chapter" data-level="4.2.7" data-path="part-2.html"><a href="part-2.html#what-a-function-returns"><i class="fa fa-check"></i><b>4.2.7</b> What a function returns</a></li>
<li class="chapter" data-level="4.2.8" data-path="part-2.html"><a href="part-2.html#default-values-freedom-to-not-specify-the-arguments"><i class="fa fa-check"></i><b>4.2.8</b> Default values: freedom to NOT specify the arguments</a></li>
<li class="chapter" data-level="4.2.9" data-path="part-2.html"><a href="part-2.html#wrap-up-and-whats-next-1"><i class="fa fa-check"></i><b>4.2.9</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i><b>4.3</b> Part 3</a><ul>
<li class="chapter" data-level="4.3.1" data-path="part-3.html"><a href="part-3.html#load-the-gapminder-data-1"><i class="fa fa-check"></i><b>4.3.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.3.2" data-path="part-3.html"><a href="part-3.html#restore-our-max-minus-min-function-1"><i class="fa fa-check"></i><b>4.3.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.3.3" data-path="part-3.html"><a href="part-3.html#be-proactive-about-nas"><i class="fa fa-check"></i><b>4.3.3</b> Be proactive about <code>NA</code>s</a></li>
<li class="chapter" data-level="4.3.4" data-path="part-3.html"><a href="part-3.html#the-useful-but-mysterious-...-argument"><i class="fa fa-check"></i><b>4.3.4</b> The useful but mysterious <code>...</code> argument</a></li>
<li class="chapter" data-level="4.3.5" data-path="part-3.html"><a href="part-3.html#use-testthat-for-formal-unit-tests"><i class="fa fa-check"></i><b>4.3.5</b> Use testthat for formal unit tests</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html"><i class="fa fa-check"></i><b>4.4</b> List columns and <code>map_*</code> functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#what-are-list-columns"><i class="fa fa-check"></i><b>4.4.1</b> What are list columns?</a></li>
<li class="chapter" data-level="4.4.2" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#creating-list-columns-with-mutate"><i class="fa fa-check"></i><b>4.4.2</b> Creating list columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="4.4.3" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#map_-functions"><i class="fa fa-check"></i><b>4.4.3</b> <code>map_*</code> functions</a></li>
<li class="chapter" data-level="4.4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#using-map_-functions-to-create-list-columns"><i class="fa fa-check"></i><b>4.4.4</b> Using <code>map_*</code> functions to create list columns</a></li>
<li class="chapter" data-level="4.4.5" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#practice-with-map_-functions-and-list-columns"><i class="fa fa-check"></i><b>4.4.5</b> Practice with <code>map_*</code> functions and list columns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii.html"><a href="part-ii.html"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html"><i class="fa fa-check"></i><b>5.1</b> Defining probability</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#intro-questions"><i class="fa fa-check"></i><b>5.1.1</b> Intro Questions</a></li>
<li class="chapter" data-level="5.1.2" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-1"><i class="fa fa-check"></i><b>5.1.2</b> Probability</a></li>
<li class="chapter" data-level="5.1.3" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#disjoint-or-mutually-exclusive-outcomes"><i class="fa fa-check"></i><b>5.1.3</b> Disjoint or mutually exclusive outcomes</a></li>
<li class="chapter" data-level="5.1.4" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilities-when-events-are-not-disjoint"><i class="fa fa-check"></i><b>5.1.4</b> Probabilities when events are not disjoint</a></li>
<li class="chapter" data-level="5.1.5" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-distributions"><i class="fa fa-check"></i><b>5.1.5</b> Probability distributions</a></li>
<li class="chapter" data-level="5.1.6" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#complement-of-an-event"><i class="fa fa-check"></i><b>5.1.6</b> Complement of an event</a></li>
<li class="chapter" data-level="5.1.7" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilityIndependence"><i class="fa fa-check"></i><b>5.1.7</b> Independence</a></li>
<li class="chapter" data-level="5.1.8" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#conditionalProbabilitySection"><i class="fa fa-check"></i><b>5.1.8</b> Conditional probability</a></li>
<li class="chapter" data-level="5.1.9" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#marginalAndJointProbabilities"><i class="fa fa-check"></i><b>5.1.9</b> Marginal and joint probabilities</a></li>
<li class="chapter" data-level="5.1.10" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#defining-conditional-probability"><i class="fa fa-check"></i><b>5.1.10</b> Defining conditional probability</a></li>
<li class="chapter" data-level="5.1.11" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#smallpox-in-boston-1721"><i class="fa fa-check"></i><b>5.1.11</b> Smallpox in Boston, 1721</a></li>
<li class="chapter" data-level="5.1.12" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#general-multiplication-rule"><i class="fa fa-check"></i><b>5.1.12</b> General multiplication rule</a></li>
<li class="chapter" data-level="5.1.13" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#tree-diagrams"><i class="fa fa-check"></i><b>5.1.13</b> Tree diagrams</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html"><i class="fa fa-check"></i><b>5.2</b> Random variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#expectation"><i class="fa fa-check"></i><b>5.2.1</b> Expectation</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Variability in random variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.3</b> Linear combinations of random variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.4</b> Variability in linear combinations of random variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>5.3</b> Statistical Background</a><ul>
<li class="chapter" data-level="5.3.1" data-path="appendixA.html"><a href="appendixA.html#appendix-stat-terms"><i class="fa fa-check"></i><b>5.3.1</b> Basic statistical terms</a></li>
<li class="chapter" data-level="5.3.2" data-path="appendixA.html"><a href="appendixA.html#appendix-normal-curve"><i class="fa fa-check"></i><b>5.3.2</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bayess-theorem.html"><a href="bayess-theorem.html"><i class="fa fa-check"></i><b>5.4</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.5" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>5.5</b> Conditional probability</a></li>
<li class="chapter" data-level="5.6" data-path="conjoint-probability.html"><a href="conjoint-probability.html"><i class="fa fa-check"></i><b>5.6</b> Conjoint probability</a></li>
<li class="chapter" data-level="5.7" data-path="the-cookie-problem.html"><a href="the-cookie-problem.html"><i class="fa fa-check"></i><b>5.7</b> The cookie problem</a></li>
<li class="chapter" data-level="5.8" data-path="bayess-theorem-1.html"><a href="bayess-theorem-1.html"><i class="fa fa-check"></i><b>5.8</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.9" data-path="the-diachronic-interpretation.html"><a href="the-diachronic-interpretation.html"><i class="fa fa-check"></i><b>5.9</b> The diachronic interpretation</a></li>
<li class="chapter" data-level="5.10" data-path="the-mm-problem.html"><a href="the-mm-problem.html"><i class="fa fa-check"></i><b>5.10</b> The M&amp;M problem</a></li>
<li class="chapter" data-level="5.11" data-path="the-monty-hall-problem.html"><a href="the-monty-hall-problem.html"><i class="fa fa-check"></i><b>5.11</b> The Monty Hall problem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling</a><ul>
<li class="chapter" data-level="" data-path="sampling.html"><a href="sampling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="sampling-activity.html"><a href="sampling-activity.html"><i class="fa fa-check"></i><b>6.1</b> Sampling urn activity</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sampling-activity.html"><a href="sampling-activity.html#what-proportion-of-this-urns-balls-are-red"><i class="fa fa-check"></i><b>6.1.1</b> What proportion of this urn’s balls are red?</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling-activity.html"><a href="sampling-activity.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling-activity.html"><a href="sampling-activity.html#student-shovels"><i class="fa fa-check"></i><b>6.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling-activity.html"><a href="sampling-activity.html#what-did-we-just-do"><i class="fa fa-check"></i><b>6.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html"><i class="fa fa-check"></i><b>6.2</b> Virtual sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-simulation.html"><a href="sampling-simulation.html#shovel-1000-times"><i class="fa fa-check"></i><b>6.2.3</b> Using the virtual shovel 1,000 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-simulation.html"><a href="sampling-simulation.html#different-shovels"><i class="fa fa-check"></i><b>6.2.4</b> Using different shovels</a></li>
<li class="chapter" data-level="6.2.5" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-many-shovels-at-once"><i class="fa fa-check"></i><b>6.2.5</b> Using many shovels at once</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-framework.html"><a href="sampling-framework.html"><i class="fa fa-check"></i><b>6.3</b> Sampling framework</a><ul>
<li class="chapter" data-level="6.3.1" data-path="sampling-framework.html"><a href="sampling-framework.html#terminology-and-notation"><i class="fa fa-check"></i><b>6.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="6.3.2" data-path="sampling-framework.html"><a href="sampling-framework.html#sampling-definitions"><i class="fa fa-check"></i><b>6.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="6.3.3" data-path="sampling-framework.html"><a href="sampling-framework.html#moral-of-the-story"><i class="fa fa-check"></i><b>6.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sampling-case-study.html"><a href="sampling-case-study.html"><i class="fa fa-check"></i><b>6.4</b> Case study: Polls</a><ul>
<li class="chapter" data-level="6.4.1" data-path="sampling-case-study.html"><a href="sampling-case-study.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>6.4.1</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="conclusion-5.html"><a href="conclusion-5.html"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> One Parameter</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html"><i class="fa fa-check"></i><b>7.1</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.1.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.1.2" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-once"><i class="fa fa-check"></i><b>7.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.1.3" data-path="resampling-tactile.html"><a href="resampling-tactile.html#student-resamples"><i class="fa fa-check"></i><b>7.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.1.4" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-did-we-just-do-1"><i class="fa fa-check"></i><b>7.1.4</b> What did we just do?</a></li>
<li class="chapter" data-level="7.1.5" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-simulation"><i class="fa fa-check"></i><b>7.1.5</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.1.6" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>7.1.6</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.1.7" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.1.7</b> Virtually resampling 1,000 times</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ci-build-up.html"><a href="ci-build-up.html"><i class="fa fa-check"></i><b>7.2</b> Measuring uncertainty with confidence intervals</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ci-build-up.html"><a href="ci-build-up.html#percentile-method"><i class="fa fa-check"></i><b>7.2.1</b> Percentile method</a></li>
<li class="chapter" data-level="7.2.2" data-path="ci-build-up.html"><a href="ci-build-up.html#se-method"><i class="fa fa-check"></i><b>7.2.2</b> Standard error method</a></li>
<li class="chapter" data-level="7.2.3" data-path="ci-build-up.html"><a href="ci-build-up.html#one-prop-ci"><i class="fa fa-check"></i><b>7.2.3</b> Interpreting confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ci-width.html"><a href="ci-width.html"><i class="fa fa-check"></i><b>7.3</b> Width of confidence intervals</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ci-width.html"><a href="ci-width.html#impact-of-confidence-level"><i class="fa fa-check"></i><b>7.3.1</b> Impact of confidence level</a></li>
<li class="chapter" data-level="7.3.2" data-path="ci-width.html"><a href="ci-width.html#fitting-multiple-models-using-map"><i class="fa fa-check"></i><b>7.3.2</b> Fitting multiple models using <code>map()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="ci-width.html"><a href="ci-width.html#impact-of-sample-size"><i class="fa fa-check"></i><b>7.3.3</b> Impact of sample size</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-lm-and-tidy-as-a-shortcut.html"><a href="using-lm-and-tidy-as-a-shortcut.html"><i class="fa fa-check"></i><b>7.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html"><i class="fa fa-check"></i><b>7.5</b> Case study: Is yawning contagious?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#mythbusters-study-data"><i class="fa fa-check"></i><b>7.5.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#sampling-scenario"><i class="fa fa-check"></i><b>7.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="7.5.3" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#ci-build"><i class="fa fa-check"></i><b>7.5.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="7.5.4" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#using-lm-and-tidy-as-a-shortcut-1"><i class="fa fa-check"></i><b>7.5.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ci-conclusion.html"><a href="ci-conclusion.html"><i class="fa fa-check"></i><b>7.6</b> Conclusion</a><ul>
<li class="chapter" data-level="7.6.1" data-path="ci-conclusion.html"><a href="ci-conclusion.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>7.6.1</b> Comparing bootstrap and sampling distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="two-parameters.html"><a href="two-parameters.html"><i class="fa fa-check"></i><b>8</b> Two Parameters</a></li>
<li class="chapter" data-level="" data-path="part-iii.html"><a href="part-iii.html"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="9" data-path="n-parameters.html"><a href="n-parameters.html"><i class="fa fa-check"></i><b>9</b> N Parameters</a></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Continuous Response I</a><ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="10.1" data-path="model1.html"><a href="model1.html"><i class="fa fa-check"></i><b>10.1</b> Teaching evaluations: one numerical explanatory variable</a><ul>
<li class="chapter" data-level="10.1.1" data-path="model1.html"><a href="model1.html#model1EDA"><i class="fa fa-check"></i><b>10.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.1.2" data-path="model1.html"><a href="model1.html#model1table"><i class="fa fa-check"></i><b>10.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="model1.html"><a href="model1.html#interpreting-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Interpreting regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html"><i class="fa fa-check"></i><b>10.2</b> Uncertainty in simple linear regressions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#using-lm-and-tidy-as-a-shortcut-2"><i class="fa fa-check"></i><b>10.2.1</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#model1points"><i class="fa fa-check"></i><b>10.2.2</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="model2.html"><a href="model2.html"><i class="fa fa-check"></i><b>10.3</b> Life expectancy: one categorical explanatory variable</a><ul>
<li class="chapter" data-level="10.3.1" data-path="model2.html"><a href="model2.html#model2EDA"><i class="fa fa-check"></i><b>10.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="model2.html"><a href="model2.html#model2table"><i class="fa fa-check"></i><b>10.3.2</b> Linear regression</a></li>
<li class="chapter" data-level="10.3.3" data-path="model2.html"><a href="model2.html#model2points"><i class="fa fa-check"></i><b>10.3.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html"><i class="fa fa-check"></i><b>10.4</b> Case study: 2018 gubernatorial forecasts</a><ul>
<li class="chapter" data-level="10.4.1" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html#fitting-multiple-models-using-map-1"><i class="fa fa-check"></i><b>10.4.1</b> Fitting multiple models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="leastsquares.html"><a href="leastsquares.html"><i class="fa fa-check"></i><b>10.5</b> Appendix: Best-fitting line</a></li>
<li class="chapter" data-level="10.6" data-path="conclusion-6.html"><a href="conclusion-6.html"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>11</b> Continuous Response II</a><ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="11.1" data-path="model4.html"><a href="model4.html"><i class="fa fa-check"></i><b>11.1</b> Teaching evaluations revisited: one numerical and one categorical explanatory variable</a><ul>
<li class="chapter" data-level="11.1.1" data-path="model4.html"><a href="model4.html#model4EDA"><i class="fa fa-check"></i><b>11.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.1.2" data-path="model4.html"><a href="model4.html#model4interactiontable"><i class="fa fa-check"></i><b>11.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="11.1.3" data-path="model4.html"><a href="model4.html#interpreting-regression-coefficients-with-interactions"><i class="fa fa-check"></i><b>11.1.3</b> Interpreting regression coefficients with interactions</a></li>
<li class="chapter" data-level="11.1.4" data-path="model4.html"><a href="model4.html#model4table"><i class="fa fa-check"></i><b>11.1.4</b> Parallel slopes model</a></li>
<li class="chapter" data-level="11.1.5" data-path="model4.html"><a href="model4.html#model4points"><i class="fa fa-check"></i><b>11.1.5</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="model3.html"><a href="model3.html"><i class="fa fa-check"></i><b>11.2</b> Credit card debt: two numerical explanatory variables</a><ul>
<li class="chapter" data-level="11.2.1" data-path="model3.html"><a href="model3.html#model3EDA"><i class="fa fa-check"></i><b>11.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.2.2" data-path="model3.html"><a href="model3.html#model3table"><i class="fa fa-check"></i><b>11.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="11.2.3" data-path="model3.html"><a href="model3.html#model3points"><i class="fa fa-check"></i><b>11.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html"><i class="fa fa-check"></i><b>11.3</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="11.3.1" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>11.3.1</b> Exploratory data analysis: Part I</a></li>
<li class="chapter" data-level="11.3.2" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-II"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory data analysis: Part II</a></li>
<li class="chapter" data-level="11.3.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-regression"><i class="fa fa-check"></i><b>11.3.3</b> Regression modeling</a></li>
<li class="chapter" data-level="11.3.4" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>11.3.4</b> Making predictions</a></li>
<li class="chapter" data-level="11.3.5" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#fitting-many-models-using-map"><i class="fa fa-check"></i><b>11.3.5</b> Fitting many models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="other-topics.html"><a href="other-topics.html"><i class="fa fa-check"></i><b>11.4</b> Other topics</a><ul>
<li class="chapter" data-level="11.4.1" data-path="other-topics.html"><a href="other-topics.html#model-selection"><i class="fa fa-check"></i><b>11.4.1</b> Model selection</a></li>
<li class="chapter" data-level="11.4.2" data-path="other-topics.html"><a href="other-topics.html#correlationcoefficient2"><i class="fa fa-check"></i><b>11.4.2</b> Correlation coefficient</a></li>
<li class="chapter" data-level="11.4.3" data-path="other-topics.html"><a href="other-topics.html#simpsonsparadox"><i class="fa fa-check"></i><b>11.4.3</b> Simpson’s Paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>12</b> Discrete Response</a><ul>
<li class="chapter" data-level="" data-path="classification.html"><a href="classification.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> What is logistic regression?</a></li>
<li class="chapter" data-level="12.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#house-elections-exploratory-data-analysis"><i class="fa fa-check"></i><b>12.1.2</b> House elections: exploratory data analysis</a></li>
<li class="chapter" data-level="12.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.3</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.4" data-path="logistic-regression.html"><a href="logistic-regression.html#observedfitted-values-and-residuals"><i class="fa fa-check"></i><b>12.1.4</b> Observed/fitted values and residuals</a></li>
<li class="chapter" data-level="12.1.5" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.5</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.1.6" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-and-one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.6</b> One numerical and one categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.7" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-many-models-using-map-1"><i class="fa fa-check"></i><b>12.1.7</b> Fitting many models using <code>map()</code></a></li>
<li class="chapter" data-level="12.1.8" data-path="logistic-regression.html"><a href="logistic-regression.html#professional-models"><i class="fa fa-check"></i><b>12.1.8</b> Professional models</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html"><i class="fa fa-check"></i><b>12.2</b> Classification and regression trees (CART)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#what-is-cart"><i class="fa fa-check"></i><b>12.2.1</b> What is CART?</a></li>
<li class="chapter" data-level="12.2.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-categorical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.2</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.2.3" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-numerical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.3</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.2.4" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#multiple-explanatory-variables"><i class="fa fa-check"></i><b>12.2.4</b> Multiple explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>12.3</b> Random forests</a><ul>
<li class="chapter" data-level="12.3.1" data-path="random-forests.html"><a href="random-forests.html#what-are-random-forests"><i class="fa fa-check"></i><b>12.3.1</b> What are random forests?</a></li>
<li class="chapter" data-level="12.3.2" data-path="random-forests.html"><a href="random-forests.html#fitting-random-forests"><i class="fa fa-check"></i><b>12.3.2</b> Fitting random forests</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html"><i class="fa fa-check"></i><b>12.4</b> Comparing the three approaches</a><ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#is-accuracy-the-right-measure"><i class="fa fa-check"></i><b>12.4.1</b> Is accuracy the right measure?</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#modeling-for-prediction-vs.-explanation"><i class="fa fa-check"></i><b>12.4.2</b> Modeling for prediction vs. explanation</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#out-of-sample-predictions"><i class="fa fa-check"></i><b>12.4.3</b> Out-of-sample predictions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="productivity.html"><a href="productivity.html"><i class="fa fa-check"></i><b>A</b> Productivity</a><ul>
<li class="chapter" data-level="A.1" data-path="set-up.html"><a href="set-up.html"><i class="fa fa-check"></i><b>A.1</b> Set Up</a><ul>
<li class="chapter" data-level="A.1.1" data-path="set-up.html"><a href="set-up.html#terminal-on-mac"><i class="fa fa-check"></i><b>A.1.1</b> Accessing the terminal on a Mac</a></li>
<li class="chapter" data-level="A.1.2" data-path="set-up.html"><a href="set-up.html#installing-git-on-the-mac"><i class="fa fa-check"></i><b>A.1.2</b> Installing Git on the Mac</a></li>
<li class="chapter" data-level="A.1.3" data-path="set-up.html"><a href="set-up.html#installing-git-and-git-bash-on-windows"><i class="fa fa-check"></i><b>A.1.3</b> Installing Git and Git Bash on Windows</a></li>
<li class="chapter" data-level="A.1.4" data-path="set-up.html"><a href="set-up.html#terminal-on-windows"><i class="fa fa-check"></i><b>A.1.4</b> Accessing the terminal on Windows</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i><b>A.2</b> Organizing with Unix</a><ul>
<li class="chapter" data-level="A.2.1" data-path="unix.html"><a href="unix.html#naming-convention"><i class="fa fa-check"></i><b>A.2.1</b> Naming convention</a></li>
<li class="chapter" data-level="A.2.2" data-path="unix.html"><a href="unix.html#the-terminal"><i class="fa fa-check"></i><b>A.2.2</b> The terminal</a></li>
<li class="chapter" data-level="A.2.3" data-path="unix.html"><a href="unix.html#filesystem"><i class="fa fa-check"></i><b>A.2.3</b> The filesystem</a></li>
<li class="chapter" data-level="A.2.4" data-path="unix.html"><a href="unix.html#directories-and-subdirectories"><i class="fa fa-check"></i><b>A.2.4</b> Directories and subdirectories</a></li>
<li class="chapter" data-level="A.2.5" data-path="unix.html"><a href="unix.html#the-home-directory"><i class="fa fa-check"></i><b>A.2.5</b> The home directory</a></li>
<li class="chapter" data-level="A.2.6" data-path="unix.html"><a href="unix.html#working-directory"><i class="fa fa-check"></i><b>A.2.6</b> Working directory</a></li>
<li class="chapter" data-level="A.2.7" data-path="unix.html"><a href="unix.html#paths"><i class="fa fa-check"></i><b>A.2.7</b> Paths</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="unix-commands.html"><a href="unix-commands.html"><i class="fa fa-check"></i><b>A.3</b> Unix commands</a><ul>
<li class="chapter" data-level="A.3.1" data-path="unix-commands.html"><a href="unix-commands.html#ls-listing-directory-content"><i class="fa fa-check"></i><b>A.3.1</b> <code>ls</code>: Listing directory content</a></li>
<li class="chapter" data-level="A.3.2" data-path="unix-commands.html"><a href="unix-commands.html#mkdir-and-rmdir-make-and-remove-a-directory"><i class="fa fa-check"></i><b>A.3.2</b> <code>mkdir</code> and <code>rmdir</code>: make and remove a directory</a></li>
<li class="chapter" data-level="A.3.3" data-path="unix-commands.html"><a href="unix-commands.html#cd-navigating-the-filesystem-by-changing-directories"><i class="fa fa-check"></i><b>A.3.3</b> <code>cd</code>: navigating the filesystem by changing directories</a></li>
<li class="chapter" data-level="A.3.4" data-path="unix-commands.html"><a href="unix-commands.html#some-examples"><i class="fa fa-check"></i><b>A.3.4</b> Some examples</a></li>
<li class="chapter" data-level="A.3.5" data-path="unix-commands.html"><a href="unix-commands.html#more-unix-commands"><i class="fa fa-check"></i><b>A.3.5</b> More Unix commands</a></li>
<li class="chapter" data-level="A.3.6" data-path="unix-commands.html"><a href="unix-commands.html#advanced-unix"><i class="fa fa-check"></i><b>A.3.6</b> Advanced Unix</a></li>
<li class="chapter" data-level="A.3.7" data-path="unix-commands.html"><a href="unix-commands.html#file-manipulation-in-r"><i class="fa fa-check"></i><b>A.3.7</b> File manipulation in R</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="git.html"><a href="git.html"><i class="fa fa-check"></i><b>A.4</b> Git and GitHub</a><ul>
<li class="chapter" data-level="A.4.1" data-path="git.html"><a href="git.html#github-accounts"><i class="fa fa-check"></i><b>A.4.1</b> GitHub accounts</a></li>
<li class="chapter" data-level="A.4.2" data-path="git.html"><a href="git.html#github-repos"><i class="fa fa-check"></i><b>A.4.2</b> GitHub repositories</a></li>
<li class="chapter" data-level="A.4.3" data-path="git.html"><a href="git.html#git-overview"><i class="fa fa-check"></i><b>A.4.3</b> Overview of Git</a></li>
<li class="chapter" data-level="A.4.4" data-path="git.html"><a href="git.html#rstudio-git"><i class="fa fa-check"></i><b>A.4.4</b> Using Git and GitHub in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>A.5</b> R</a><ul>
<li class="chapter" data-level="A.5.1" data-path="r.html"><a href="r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.5.1</b> RStudio projects</a></li>
<li class="chapter" data-level="A.5.2" data-path="r.html"><a href="r.html#r-markdown"><i class="fa fa-check"></i><b>A.5.2</b> R markdown</a></li>
<li class="chapter" data-level="A.5.3" data-path="r.html"><a href="r.html#help-for-r"><i class="fa fa-check"></i><b>A.5.3</b> Help for R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>B</b> Getting Help</a><ul>
<li class="chapter" data-level="B.1" data-path="searching-for-help-with-r-1.html"><a href="searching-for-help-with-r-1.html"><i class="fa fa-check"></i><b>B.1</b> Searching for Help with R</a></li>
<li class="chapter" data-level="B.2" data-path="reproducible-examples-1.html"><a href="reproducible-examples-1.html"><i class="fa fa-check"></i><b>B.2</b> Reproducible Examples</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>C</b> Shiny</a><ul>
<li class="chapter" data-level="C.1" data-path="helpful-resources.html"><a href="helpful-resources.html"><i class="fa fa-check"></i><b>C.1</b> Helpful Resources</a></li>
<li class="chapter" data-level="C.2" data-path="set-up-and-getting-started.html"><a href="set-up-and-getting-started.html"><i class="fa fa-check"></i><b>C.2</b> Set Up and Getting Started</a></li>
<li class="chapter" data-level="C.3" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html"><i class="fa fa-check"></i><b>C.3</b> Building Your Basic App</a><ul>
<li class="chapter" data-level="C.3.1" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-basic-ui"><i class="fa fa-check"></i><b>C.3.1</b> Setting Up the Basic UI</a></li>
<li class="chapter" data-level="C.3.2" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-server"><i class="fa fa-check"></i><b>C.3.2</b> Setting up the Server</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="organization.html"><a href="organization.html"><i class="fa fa-check"></i><b>C.4</b> Organization</a></li>
<li class="chapter" data-level="C.5" data-path="customizations.html"><a href="customizations.html"><i class="fa fa-check"></i><b>C.5</b> Customizations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="maps.html"><a href="maps.html"><i class="fa fa-check"></i><b>D</b> Maps</a><ul>
<li class="chapter" data-level="D.1" data-path="tidycensus.html"><a href="tidycensus.html"><i class="fa fa-check"></i><b>D.1</b> Tidycensus</a></li>
<li class="chapter" data-level="D.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html"><i class="fa fa-check"></i><b>D.2</b> Conceptual introduction to mapping</a><ul>
<li class="chapter" data-level="D.2.1" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#vector-versus-spatial-data"><i class="fa fa-check"></i><b>D.2.1</b> Vector versus spatial data</a></li>
<li class="chapter" data-level="D.2.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#sf-vs-sp"><i class="fa fa-check"></i><b>D.2.2</b> <strong>sf</strong> vs <strong>sp</strong></a></li>
<li class="chapter" data-level="D.2.3" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#shapefiles"><i class="fa fa-check"></i><b>D.2.3</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html"><i class="fa fa-check"></i><b>D.3</b> Mapping with <strong>tidycensus</strong> and <code>geom_sf()</code></a><ul>
<li class="chapter" data-level="D.3.1" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#making-maps-pretty"><i class="fa fa-check"></i><b>D.3.1</b> Making maps pretty</a></li>
<li class="chapter" data-level="D.3.2" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#adding-back-alaska-and-hawaii"><i class="fa fa-check"></i><b>D.3.2</b> Adding back Alaska and Hawaii</a></li>
</ul></li>
<li class="chapter" data-level="D.4" data-path="faceting-maps.html"><a href="faceting-maps.html"><i class="fa fa-check"></i><b>D.4</b> Faceting maps</a><ul>
<li class="chapter" data-level="D.4.1" data-path="faceting-maps.html"><a href="faceting-maps.html#transforming-and-mapping-the-data"><i class="fa fa-check"></i><b>D.4.1</b> Transforming and mapping the data</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="want-to-explore-further.html"><a href="want-to-explore-further.html"><i class="fa fa-check"></i><b>D.5</b> Want to explore further?</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="animation.html"><a href="animation.html"><i class="fa fa-check"></i><b>E</b> Animation</a><ul>
<li class="chapter" data-level="E.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><i class="fa fa-check"></i><b>E.1</b> gganimate: How to Create Plots with Beautiful Animation in R</a><ul>
<li class="chapter" data-level="E.1.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#prerequisites"><i class="fa fa-check"></i><b>E.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="E.1.2" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#demo-dataset"><i class="fa fa-check"></i><b>E.1.2</b> Demo dataset</a></li>
<li class="chapter" data-level="E.1.3" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#static-plot"><i class="fa fa-check"></i><b>E.1.3</b> Static plot</a></li>
<li class="chapter" data-level="E.1.4" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-through-distinct-states-in-time"><i class="fa fa-check"></i><b>E.1.4</b> Transition through distinct states in time</a></li>
<li class="chapter" data-level="E.1.5" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#reveal-data-along-a-given-dimension"><i class="fa fa-check"></i><b>E.1.5</b> Reveal data along a given dimension</a></li>
<li class="chapter" data-level="E.1.6" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-between-several-distinct-stages-of-the-data"><i class="fa fa-check"></i><b>E.1.6</b> Transition between several distinct stages of the data</a></li>
<li class="chapter" data-level="E.1.7" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#read-more"><i class="fa fa-check"></i><b>E.1.7</b> Read more</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="how-to-save-your-animation.html"><a href="how-to-save-your-animation.html"><i class="fa fa-check"></i><b>E.2</b> How to save your animation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preceptor’s Primer for Bayesian Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model4" class="section level2">
<h2><span class="header-section-number">11.1</span> Teaching evaluations revisited: one numerical and one categorical explanatory variable</h2>
<p>Let’s revisit the instructor evaluation data from UT Austin we introduced in Section <a href="model1.html#model1">10.1</a>. We studied the relationship between teaching evaluation scores as given by students and “beauty” scores. The variable teaching <code>score</code> was the numerical outcome variable <span class="math inline">\(y\)</span>, and the variable “beauty” score (<code>bty_avg</code>) was the numerical explanatory <span class="math inline">\(x\)</span> variable.</p>
<p>In this section, we are going to consider a different model. Our outcome variable will still be teaching score, but we’ll now include two different explanatory variables: age and (binary) gender. Could it be that instructors who are older receive better teaching evaluations from students? Or could it instead be that younger instructors receive better evaluations? Are there differences in evaluations given by students for instructors of different genders? We’ll answer these questions by modeling the relationship between these variables using <em>multiple regression</em>, where we have:</p>
<ol style="list-style-type: decimal">
<li>A numerical outcome variable <span class="math inline">\(y\)</span>, the instructor’s teaching score, and</li>
<li>Two explanatory variables:
<ol style="list-style-type: decimal">
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>, the instructor’s age.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>, the instructor’s (binary) gender.</li>
</ol></li>
</ol>
<p>It is important to note that at the time of this study due to then commonly held beliefs about gender, this variable was often recorded as a binary variable. While the results of a model that oversimplifies gender this way may be imperfect, we still found the results to be pertinent and relevant today.</p>
<div id="model4EDA" class="section level3">
<h3><span class="header-section-number">11.1.1</span> Exploratory data analysis</h3>
<p>Recall that data on the 463 courses at UT Austin can be found in the <code>evals</code> data frame included in the <strong>moderndive</strong> package. However, to keep things simple, let’s <code>select()</code> only the subset of the variables we’ll consider in this chapter, and save this data in a new data frame called <code>evals_ch12</code>. Note that these are different from the variables chosen in Chapter <a href="regression.html#regression">10</a>.</p>
<div class="sourceCode" id="cb739"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb739-1"><a href="model4.html#cb739-1"></a><span class="kw">library</span>(moderndive)</span>
<span id="cb739-2"><a href="model4.html#cb739-2"></a></span>
<span id="cb739-3"><a href="model4.html#cb739-3"></a>evals_ch12 &lt;-<span class="st"> </span>evals <span class="op">%&gt;%</span></span>
<span id="cb739-4"><a href="model4.html#cb739-4"></a><span class="st">  </span><span class="kw">select</span>(ID, score, age, gender)</span></code></pre></div>
<p>Recall the three common steps in an exploratory data analysis we saw in Subsection <a href="model1.html#model1EDA">10.1.1</a>:</p>
<ol style="list-style-type: decimal">
<li>Looking at the raw data values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>Let’s first look at the raw data values by either looking at <code>evals_ch12</code> using RStudio’s spreadsheet viewer or by using the <code>glimpse()</code> function from the <strong>dplyr</strong> package:</p>
<div class="sourceCode" id="cb740"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb740-1"><a href="model4.html#cb740-1"></a><span class="kw">glimpse</span>(evals_ch12)</span></code></pre></div>
<pre><code>## Rows: 463
## Columns: 4
## $ ID     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
## $ score  &lt;dbl&gt; 4.7, 4.1, 3.9, 4.8, 4.6, 4.3, 2.8, 4.1, 3.4, 4.5, 3.8, 4.5, 4.…
## $ age    &lt;int&gt; 36, 36, 36, 36, 59, 59, 59, 51, 51, 40, 40, 40, 40, 40, 40, 40…
## $ gender &lt;fct&gt; female, female, female, female, male, male, male, male, male, …</code></pre>
<p>Let’s also display a random sample of 5 rows of the 463 rows corresponding to different courses in Table <a href="model4.html#tab:model4-data-preview">11.1</a>. Remember due to the random nature of the sampling, you will likely end up with a different subset of 5 rows.</p>
<div class="sourceCode" id="cb742"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb742-1"><a href="model4.html#cb742-1"></a>evals_ch12 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb742-2"><a href="model4.html#cb742-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dt">size =</span> <span class="dv">5</span>)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:model4-data-preview">TABLE 11.1: </span>A random sample of 5 out of the 463 courses at UT Austin
</caption>
<thead>
<tr>
<th style="text-align:right;">
ID
</th>
<th style="text-align:right;">
score
</th>
<th style="text-align:right;">
age
</th>
<th style="text-align:left;">
gender
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
239
</td>
<td style="text-align:right;">
3.1
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:left;">
male
</td>
</tr>
<tr>
<td style="text-align:right;">
87
</td>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:left;">
male
</td>
</tr>
<tr>
<td style="text-align:right;">
108
</td>
<td style="text-align:right;">
5.0
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:left;">
female
</td>
</tr>
<tr>
<td style="text-align:right;">
149
</td>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:left;">
male
</td>
</tr>
<tr>
<td style="text-align:right;">
334
</td>
<td style="text-align:right;">
3.7
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:left;">
male
</td>
</tr>
</tbody>
</table>
<p>Now that we’ve looked at the raw values in our <code>evals_ch12</code> data frame and got a sense of the data, let’s compute summary statistics. As we did in our exploratory data analyses in Sections <a href="model1.html#model1EDA">10.1.1</a> and <a href="model2.html#model2EDA">10.3.1</a> from the previous chapter, let’s use the <code>skim()</code> function from the <strong>skimr</strong> package, being sure to only <code>select()</code> the variables of interest in our model:</p>
<div class="sourceCode" id="cb743"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb743-1"><a href="model4.html#cb743-1"></a>evals_ch12 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb743-2"><a href="model4.html#cb743-2"></a><span class="st">  </span><span class="kw">select</span>(score, age, gender) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb743-3"><a href="model4.html#cb743-3"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-422">TABLE 11.2: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
463
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
factor
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
ordered
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:left;">
top_counts
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
gender
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
FALSE
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
mal: 268, fem: 195
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
score
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:right;">
0.54
</td>
<td style="text-align:right;">
2.3
</td>
<td style="text-align:right;">
3.8
</td>
<td style="text-align:right;">
4.3
</td>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
▁▁▅▇▇
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
48.37
</td>
<td style="text-align:right;">
9.80
</td>
<td style="text-align:right;">
29.0
</td>
<td style="text-align:right;">
42.0
</td>
<td style="text-align:right;">
48.0
</td>
<td style="text-align:right;">
57.0
</td>
<td style="text-align:right;">
73
</td>
<td style="text-align:left;">
▅▆▇▆▁
</td>
</tr>
</tbody>
</table>
<p>Observe that we have no missing data, that there are 268 courses taught by male instructors and 195 courses taught by female instructors, and that the average instructor age is 48.37. Recall that each row represents a particular course and that the same instructor often teaches more than one course. Therefore, the average age of the unique instructors may differ.</p>
<p>Furthermore, let’s compute the correlation coefficient between our two numerical variables: <code>score</code> and <code>age</code>. Recall from Subsection <a href="model1.html#model1EDA">10.1.1</a> that correlation coefficients only exist between numerical variables. We observe that they are “weakly negatively” correlated.</p>
<div class="sourceCode" id="cb744"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb744-1"><a href="model4.html#cb744-1"></a>evals_ch12 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb744-2"><a href="model4.html#cb744-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">correlation =</span> <span class="kw">cor</span>(score, age)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb744-3"><a href="model4.html#cb744-3"></a><span class="st">  </span><span class="kw">round</span>(<span class="dv">3</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb744-4"><a href="model4.html#cb744-4"></a><span class="st">  </span><span class="kw">pull</span>()</span></code></pre></div>
<pre><code>## [1] -0.107</code></pre>
<p>Let’s now perform the last of the three common steps in an exploratory data analysis: creating data visualizations. Given that the outcome variable <code>score</code> and explanatory variable <code>age</code> are both numerical, we’ll use a scatterplot to display their relationship. How can we incorporate the categorical variable <code>gender</code>, however? By mapping the variable <code>gender</code> to the <code>color</code> aesthetic, thereby creating a <em>colored</em> scatterplot. The following code is similar to the code that created the scatterplot of teaching score over “beauty” score last chapter, but with <code>color = gender</code> added to the <code>aes()</code>thetic mapping.</p>
<div class="sourceCode" id="cb746"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb746-1"><a href="model4.html#cb746-1"></a>evals_ch12 <span class="op">%&gt;%</span></span>
<span id="cb746-2"><a href="model4.html#cb746-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> score, <span class="dt">color =</span> gender)) <span class="op">+</span></span>
<span id="cb746-3"><a href="model4.html#cb746-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb746-4"><a href="model4.html#cb746-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Teaching Score&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;Gender&quot;</span>) <span class="op">+</span></span>
<span id="cb746-5"><a href="model4.html#cb746-5"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:numxcatxplot1"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/numxcatxplot1-1.png" alt="Colored scatterplot of relationship of teaching and beauty scores." width="\textwidth" />
<p class="caption">
FIGURE 11.1: Colored scatterplot of relationship of teaching and beauty scores.
</p>
</div>
<p>In the resulting Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>, observe that <code>ggplot()</code> assigns a default in red/blue color scheme to the points and to the lines associated with the two levels of <code>gender</code>: <code>female</code> and <code>male</code>. Furthermore, the <code>geom_smooth(method = "lm", se = FALSE)</code> layer automatically fits a different regression line for each group.</p>
<p>We notice some interesting trends. First, there are almost no women faculty over the age of 60 as evidenced by lack of red dots above <span class="math inline">\(x\)</span> = 60. Second, while both regression lines are negatively sloped with age (i.e., older instructors tend to have lower scores), the slope for age for the female instructors is <em>more</em> negative. In other words, female instructors are paying a harsher penalty for advanced age than the male instructors.</p>
</div>
<div id="model4interactiontable" class="section level3">
<h3><span class="header-section-number">11.1.2</span> Interaction model</h3>
<p>Let’s now quantify the relationship of our outcome variable <span class="math inline">\(y\)</span> and the two explanatory variables using one type of multiple regression model known as an <em>interaction model</em>.  We’ll explain where the term “interaction” comes from at the end of this section.</p>
<p>In particular, we’ll write out the equation of the two regression lines in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a> using the values from a regression table. Before we do this, however, let’s go over a brief refresher of regression when you have a categorical explanatory variable <span class="math inline">\(x\)</span>.</p>
<p>Recall in Subsection <a href="model2.html#model2table">10.3.2</a> we fit a regression model for countries’ life expectancies as a function of which continent the country was in. In other words, we had a numerical outcome variable <span class="math inline">\(y\)</span> = <code>lifeExp</code> and a categorical explanatory variable <span class="math inline">\(x\)</span> = <code>continent</code> which had 5 levels: <code>Africa</code>, <code>Americas</code>, <code>Asia</code>, <code>Europe</code>, and <code>Oceania</code>. Let’s re-display the regression table you saw last chapter:</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-425">TABLE 11.3: </span>Regression table for life expectancy as a function of continent
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
54.8
</td>
<td style="text-align:right;">
52.8
</td>
<td style="text-align:right;">
56.8
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAmericas
</td>
<td style="text-align:right;">
18.8
</td>
<td style="text-align:right;">
15.2
</td>
<td style="text-align:right;">
22.4
</td>
</tr>
<tr>
<td style="text-align:left;">
continentAsia
</td>
<td style="text-align:right;">
15.9
</td>
<td style="text-align:right;">
12.7
</td>
<td style="text-align:right;">
19.2
</td>
</tr>
<tr>
<td style="text-align:left;">
continentEurope
</td>
<td style="text-align:right;">
22.8
</td>
<td style="text-align:right;">
19.5
</td>
<td style="text-align:right;">
26.2
</td>
</tr>
<tr>
<td style="text-align:left;">
continentOceania
</td>
<td style="text-align:right;">
25.9
</td>
<td style="text-align:right;">
15.4
</td>
<td style="text-align:right;">
36.5
</td>
</tr>
</tbody>
</table>
<p>Recall our interpretation of the <code>estimate</code> column. Since <code>Africa</code> was the “baseline for comparison” group, the <code>intercept</code> term corresponds to the mean life expectancy for all countries in Africa of 54.8 years. The other four values of <code>estimate</code> correspond to “offsets” relative to the baseline group. So, for example, the “offset” corresponding to the Americas is +18.8 as compared to the baseline for comparison group Africa. In other words, the average life expectancy for countries in the Americas is 18.8 years <em>higher</em>. Thus the mean life expectancy for all countries in the Americas is 54.8 + 18.8 = 73.6. The same interpretation holds for Asia, Europe, and Oceania.</p>
<p>Going back to our multiple regression model for teaching <code>score</code> using <code>age</code> and <code>gender</code> in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>, we generate the regression table using the same two-step approach from Chapter <a href="regression.html#regression">10</a>: we first “fit” the model using the <code>lm()</code> “linear model” function and then we apply the <code>tidy()</code> function. This time, however, our model formula won’t be of the form <code>y ~ x</code>, but rather of the form <code>y ~ x1 * x2</code>. In other words, our two explanatory variables <code>x1</code> and <code>x2</code> are separated by a <code>*</code> sign:</p>
<div class="sourceCode" id="cb748"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb748-1"><a href="model4.html#cb748-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb748-2"><a href="model4.html#cb748-2"></a></span>
<span id="cb748-3"><a href="model4.html#cb748-3"></a>score_model_interaction &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> evals_ch12)</span>
<span id="cb748-4"><a href="model4.html#cb748-4"></a></span>
<span id="cb748-5"><a href="model4.html#cb748-5"></a><span class="co"># Get regression table:</span></span>
<span id="cb748-6"><a href="model4.html#cb748-6"></a></span>
<span id="cb748-7"><a href="model4.html#cb748-7"></a>score_model_interaction <span class="op">%&gt;%</span></span>
<span id="cb748-8"><a href="model4.html#cb748-8"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb748-9"><a href="model4.html#cb748-9"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:regtable-interaction">TABLE 11.4: </span>Regression table for interaction model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
4.883
</td>
<td style="text-align:right;">
4.480
</td>
<td style="text-align:right;">
5.286
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
-0.018
</td>
<td style="text-align:right;">
-0.026
</td>
<td style="text-align:right;">
-0.009
</td>
</tr>
<tr>
<td style="text-align:left;">
gendermale
</td>
<td style="text-align:right;">
-0.446
</td>
<td style="text-align:right;">
-0.968
</td>
<td style="text-align:right;">
0.076
</td>
</tr>
<tr>
<td style="text-align:left;">
age:gendermale
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.024
</td>
</tr>
</tbody>
</table>
<p>Looking at the regression table output in Table <a href="model4.html#tab:regtable-interaction">11.4</a>, there are four rows of values in the <code>estimate</code> column. While it is not immediately apparent, using these four values we can write out the equations of both lines in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>. First, since the word <code>female</code> comes alphabetically before <code>male</code>, female instructors are the “baseline for comparison” group. Thus, <code>intercept</code> is the intercept <em>for only the female instructors</em>.</p>
<p>This holds similarly for <code>age</code>. It is the slope for age <em>for only the female instructors</em>. Thus, the red regression line in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a> has an intercept of 4.883 and slope for age of -0.018. Remember that for this data, while the intercept has a mathematical interpretation, it has no <em>practical</em> interpretation since instructors can’t have zero age.</p>
<p>What about the intercept and slope for age of the male instructors in the blue line in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>? This is where our notion of “offsets” comes into play once again.</p>
<p>The value for <code>gendermale</code> of -0.446 is not the intercept for the male instructors, but rather the <em>offset</em> in intercept for male instructors relative to female instructors. The intercept for the male instructors is <code>intercept + gendermale</code> = 4.883 + (-0.446) = 4.883 - 0.446 = 4.437.</p>
<p>Similarly, <code>age:gendermale</code> = 0.014 is not the slope for age for the male instructors, but rather the <em>offset</em> in slope for the male instructors. Therefore, the slope for age for the male instructors is <code>age + age:gendermale</code> <span class="math inline">\(= -0.018 + 0.014 = -0.004\)</span>. Thus, the blue regression line in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a> has intercept 4.437 and slope for age of -0.004. Let’s summarize these values in Table <a href="model4.html#tab:interaction-summary">11.5</a> and focus on the two slopes for age:</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:interaction-summary">TABLE 11.5: </span>Comparison of intercepts and slopes for interaction model
</caption>
<thead>
<tr>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Intercept
</th>
<th style="text-align:right;">
Slope for age
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female instructors
</td>
<td style="text-align:right;">
4.883
</td>
<td style="text-align:right;">
-0.018
</td>
</tr>
<tr>
<td style="text-align:left;">
Male instructors
</td>
<td style="text-align:right;">
4.437
</td>
<td style="text-align:right;">
-0.004
</td>
</tr>
</tbody>
</table>
<p>Since the slope for age for the female instructors was -0.018, it means that on average, a female instructor who is a year older would have a teaching score that is 0.018 units <strong>lower</strong>. For the male instructors, however, the corresponding associated decrease was on average only 0.004 units. While both slopes for age were negative, the slope for age for the female instructors is <em>more negative</em>. This is consistent with our observation from Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>, that this model is suggesting that age impacts teaching scores for female instructors more than for male instructors.</p>
<p>Note that our regression table included the confidence interval bounds generated from <code>tidy(conf.int = TRUE)</code>. Let’s reassure ourselves that they are similar to what we would get from the bootstrap samples.</p>
<p>The process is somewhat more involved because we have multiple coefficients around which we would like to construct confidence intervals. It begins the same way as we saw in the last chapter:</p>
<div class="sourceCode" id="cb749"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb749-1"><a href="model4.html#cb749-1"></a><span class="kw">library</span>(infer)</span>
<span id="cb749-2"><a href="model4.html#cb749-2"></a></span>
<span id="cb749-3"><a href="model4.html#cb749-3"></a>evals_ch12 <span class="op">%&gt;%</span></span>
<span id="cb749-4"><a href="model4.html#cb749-4"></a><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="kw">nrow</span>(evals_ch12), <span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb749-5"><a href="model4.html#cb749-5"></a><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></span>
<span id="cb749-6"><a href="model4.html#cb749-6"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb749-7"><a href="model4.html#cb749-7"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> .)),</span>
<span id="cb749-8"><a href="model4.html#cb749-8"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(.)))</span></code></pre></div>
<pre><code>## # A tibble: 1,000 x 4
## # Groups:   replicate [1,000]
##    replicate data               mod    reg_results     
##        &lt;int&gt; &lt;list&gt;             &lt;list&gt; &lt;list&gt;          
##  1         1 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  2         2 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  3         3 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  4         4 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  5         5 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  6         6 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  7         7 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  8         8 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
##  9         9 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
## 10        10 &lt;tibble [463 × 4]&gt; &lt;lm&gt;   &lt;tibble [4 × 5]&gt;
## # … with 990 more rows</code></pre>
<p>Now we could use <code>map_dbl()</code> within our <code>mutate()</code> in order to extract each of the estimates from our model. However, as you add more predictors to a regression, that gets more and more unwieldy. Instead, let’s take advantage of <code>unnest()</code> to reshape our data so that the unit of analysis is a replicate-term:</p>
<div class="sourceCode" id="cb751"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb751-1"><a href="model4.html#cb751-1"></a>evals_ch12 <span class="op">%&gt;%</span></span>
<span id="cb751-2"><a href="model4.html#cb751-2"></a><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="kw">nrow</span>(evals_ch12), <span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb751-3"><a href="model4.html#cb751-3"></a><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></span>
<span id="cb751-4"><a href="model4.html#cb751-4"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb751-5"><a href="model4.html#cb751-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> .)),</span>
<span id="cb751-6"><a href="model4.html#cb751-6"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(.))) <span class="op">%&gt;%</span></span>
<span id="cb751-7"><a href="model4.html#cb751-7"></a><span class="st">  </span><span class="kw">unnest</span>(reg_results)</span></code></pre></div>
<pre><code>## # A tibble: 4,000 x 8
## # Groups:   replicate [1,000]
##    replicate data         mod   term      estimate std.error statistic   p.value
##        &lt;int&gt; &lt;list&gt;       &lt;lis&gt; &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1         1 &lt;tibble [46… &lt;lm&gt;  (Interce…   5.12     0.212       24.2  7.33e- 84
##  2         1 &lt;tibble [46… &lt;lm&gt;  age        -0.0215   0.00448     -4.81 2.05e-  6
##  3         1 &lt;tibble [46… &lt;lm&gt;  genderma…  -0.831    0.269       -3.09 2.14e-  3
##  4         1 &lt;tibble [46… &lt;lm&gt;  age:gend…   0.0203   0.00553      3.67 2.71e-  4
##  5         2 &lt;tibble [46… &lt;lm&gt;  (Interce…   5.18     0.178       29.1  2.93e-106
##  6         2 &lt;tibble [46… &lt;lm&gt;  age        -0.0240   0.00395     -6.07 2.64e-  9
##  7         2 &lt;tibble [46… &lt;lm&gt;  genderma…  -0.962    0.240       -4.01 6.95e-  5
##  8         2 &lt;tibble [46… &lt;lm&gt;  age:gend…   0.0245   0.00502      4.89 1.39e-  6
##  9         3 &lt;tibble [46… &lt;lm&gt;  (Interce…   5.02     0.248       20.3  8.52e- 66
## 10         3 &lt;tibble [46… &lt;lm&gt;  age        -0.0204   0.00517     -3.96 8.86e-  5
## # … with 3,990 more rows</code></pre>
<p>Now we have 4,000 rows, which are 1,000 replicates apiece for each of the <code>term</code>s in our regression.</p>
<p>It is now a simple matter to <code>group_by(term)</code> and <code>summarize()</code> to create our confidence intervals:</p>
<div class="sourceCode" id="cb753"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb753-1"><a href="model4.html#cb753-1"></a>evals_ch12 <span class="op">%&gt;%</span></span>
<span id="cb753-2"><a href="model4.html#cb753-2"></a><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="kw">nrow</span>(evals_ch12), <span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb753-3"><a href="model4.html#cb753-3"></a><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></span>
<span id="cb753-4"><a href="model4.html#cb753-4"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb753-5"><a href="model4.html#cb753-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>age <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> .)),</span>
<span id="cb753-6"><a href="model4.html#cb753-6"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(.))) <span class="op">%&gt;%</span></span>
<span id="cb753-7"><a href="model4.html#cb753-7"></a><span class="st">  </span><span class="kw">unnest</span>(reg_results) <span class="op">%&gt;%</span></span>
<span id="cb753-8"><a href="model4.html#cb753-8"></a><span class="st">  </span><span class="kw">group_by</span>(term) <span class="op">%&gt;%</span></span>
<span id="cb753-9"><a href="model4.html#cb753-9"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">conf.low =</span> <span class="kw">quantile</span>(estimate, <span class="fl">0.025</span>),</span>
<span id="cb753-10"><a href="model4.html#cb753-10"></a>            <span class="dt">conf.high =</span> <span class="kw">quantile</span>(estimate, <span class="fl">0.975</span>))</span></code></pre></div>
<pre><code>## # A tibble: 4 x 3
##   term           conf.low conf.high
##   &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)     4.49      5.26   
## 2 age            -0.0256   -0.00881
## 3 age:gendermale  0.00270   0.0233 
## 4 gendermale     -0.931     0.0478</code></pre>
<p>For comparison, let’s take another look at the results from <code>tidy(conf.int = TRUE)</code> which we saw before:</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-430">TABLE 11.6: </span>Regression table for interaction model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
4.883
</td>
<td style="text-align:right;">
4.480
</td>
<td style="text-align:right;">
5.286
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
-0.018
</td>
<td style="text-align:right;">
-0.026
</td>
<td style="text-align:right;">
-0.009
</td>
</tr>
<tr>
<td style="text-align:left;">
gendermale
</td>
<td style="text-align:right;">
-0.446
</td>
<td style="text-align:right;">
-0.968
</td>
<td style="text-align:right;">
0.076
</td>
</tr>
<tr>
<td style="text-align:left;">
age:gendermale
</td>
<td style="text-align:right;">
0.014
</td>
<td style="text-align:right;">
0.003
</td>
<td style="text-align:right;">
0.024
</td>
</tr>
</tbody>
</table>
<p>They are very similar, so we will keep using <code>tidy(conf.int = TRUE)</code> to save time.</p>
<p>Let’s now write the equation for our regression lines, which we can use to compute our fitted values <span class="math inline">\(\widehat{y} = \widehat{\text{score}}\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= b_0 + b_{\text{age}} \cdot \text{age} + b_{\text{male}} \cdot \mathbb{1}_{\text{is male}}(x) + b_{\text{age,male}} \cdot \text{age} \cdot \mathbb{1}_{\text{is male}}\\
&amp;= 4.883 -0.018 \cdot \text{age} - 0.446 \cdot \mathbb{1}_{\text{is male}}(x) + 0.014 \cdot \text{age} \cdot \mathbb{1}_{\text{is male}}
\end{aligned}
\]</span></p>
<p>Whoa! That’s even more daunting than the equation you saw for the life expectancy as a function of continent in Subsection <a href="model2.html#model2table">10.3.2</a>! However, if you recall what an “indicator function” does, the equation simplifies greatly. In the previous equation, we have one indicator function of interest:</p>
<p><span class="math display">\[
\mathbb{1}_{\text{is male}}(x) = \left\{
\begin{array}{ll}
1 &amp; \text{if } \text{instructor } x \text{ is male} \\
0 &amp; \text{otherwise}\end{array}
\right.
\]</span></p>
<p>Second, let’s match coefficients in the previous equation with values in the <code>estimate</code> column in our regression table in Table <a href="model4.html#tab:regtable-interaction">11.4</a>:</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(b_0\)</span> is the <code>intercept</code> = 4.883 for the female instructors</li>
<li><span class="math inline">\(b_{\text{age}}\)</span> is the slope for <code>age</code> = -0.018 for the female instructors</li>
<li><span class="math inline">\(b_{\text{male}}\)</span> is the offset in intercept = -0.446 for the male instructors</li>
<li><span class="math inline">\(b_{\text{age,male}}\)</span> is the offset in slope for age = 0.014 for the male instructors</li>
</ol>
<p>Let’s put this all together and compute the fitted value <span class="math inline">\(\widehat{y} = \widehat{\text{score}}\)</span> for female instructors. Since for female instructors <span class="math inline">\(\mathbb{1}_{\text{is male}}(x)\)</span> = 0, the previous equation becomes</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= 4.883 - 0.018   \cdot \text{age} - 0.446 \cdot 0 + 0.014 \cdot \text{age} \cdot 0\\
&amp;= 4.883 - 0.018    \cdot \text{age} - 0 + 0\\
&amp;= 4.883 - 0.018    \cdot \text{age}\\
\end{aligned}
\]</span></p>
<p>which is the equation of the red regression line in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a> corresponding to the female instructors in Table <a href="model4.html#tab:interaction-summary">11.5</a>. Correspondingly, since for male instructors <span class="math inline">\(\mathbb{1}_{\text{is male}}(x)\)</span> = 1, the previous equation becomes</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= 4.883 - 0.018   \cdot \text{age} - 0.446 + 0.014 \cdot \text{age}\\
&amp;= (4.883 - 0.446) + (- 0.018 + 0.014) * \text{age}\\
&amp;= 4.437 - 0.004    \cdot \text{age}\\
\end{aligned}
\]</span></p>
<p>which is the equation of the blue regression line in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a> corresponding to the male instructors in Table <a href="model4.html#tab:interaction-summary">11.5</a>.</p>
<p>Phew! That was a lot of arithmetic! Don’t fret, however, this is as hard as modeling will get in this book. If you’re still a little unsure about using indicator functions and using categorical explanatory variables in a regression model, we <em>highly</em> suggest you re-read Subsection <a href="model2.html#model2table">10.3.2</a>. This involves only a single categorical explanatory variable and thus is much simpler.</p>
</div>
<div id="interpreting-regression-coefficients-with-interactions" class="section level3">
<h3><span class="header-section-number">11.1.3</span> Interpreting regression coefficients with interactions</h3>
<p>Before we end this section, we explain why we refer to this type of model as an “interaction model.” The <span class="math inline">\(b_{\text{age,male}}\)</span> term in the equation for the fitted value <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> is what’s known in statistical modeling as an “interaction effect.” The interaction term corresponds to the <code>age:gendermale</code> = 0.014 in the final row of the regression table in Table <a href="model4.html#tab:regtable-interaction">11.4</a>.<br />
We say there is an interaction effect if the associated effect of one variable <em>depends on the value of another variable</em>. That is to say, the two variables are “interacting” with each other. Here, the associated effect of the variable age <em>depends</em> on the value of the other variable gender. The difference in slopes for age of +0.014 of male instructors relative to female instructors shows this. </p>
<p>Another way of thinking about interaction effects on teaching scores is as follows. For a given instructor at UT Austin, there might be an associated effect of their age <em>by itself</em>, there might be an associated effect of their gender <em>by itself</em>, but when age and gender are considered <em>together</em> there might be an <em>additional effect</em> above and beyond the two individual effects.</p>
<p>Can we interpret these coefficients using the <a href="rubin-causal-model.html#rubin-causal-model">Rubin Causal Model</a>? In order to interpet a multiple regression causally, you first need to decide what you are considering as the treatment variable. Let’s say that we are conceptualizing gender as the treatment variable. Back in the simple linear regression context, we noted that you cannot interpret the regression coefficient as the average treatment effect if there are any confounding variables – variables that are correlated both with the treatment variable and the potential outcomes. Multiple regression allows for consideration of confounding variables, but only in the situation where you have included <em>all</em> confounders can you justify a causal interpretation of the regression.</p>
<p>For our teaching score model, then, we can interpret the effect of gender causally <strong>only if</strong> <em>other than age measured in years</em> there are no variables that correlate with a teacher’s gender and the teacher’s potential outcomes. So if age is the only confounding variable, we can interpret the model causally. This is a heroic assumption, but let’s say it’s right and we saw the following observed outcomes:</p>
<table class="table table-striped" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
Subject
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = F}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = M}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Alice
</td>
<td style="text-align:left;">
<span class="math inline">\(4\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Bob
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.75\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;border-right:1px solid;">
Charlie
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4.1\)</span>
</td>
</tr>
</tbody>
</table>
<!-- AR: problems with using potential outcome tables with regressions like
this: a) heterogenous treatment effects lead to difficult-to-calculate
confidence intervals, given what we've shown the students before, b) this only
takes into account the uncertainty around the estimate of the ATE, since
predictive intervals aren't causal quantities.  But this was my best attempt.
-->
<p>Now, following what we saw in the last chapter, we’ll want to fill in the missing potential outcomes by using our estimate of the ATE. But in an interaction model, this is is more complicated, because we have <strong>heterogeneous treatment effects</strong>. That means that we don’t just have one estimate of the ATE, but rather we have an estimate of the ATE for <em>each age.</em> So we need to know the age of each instructor:</p>
<table class="table table-striped" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
Subject
</th>
<th style="text-align:left;">
age
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = F}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = M}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Alice
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(30\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Bob
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(45\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.75\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Charlie
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(60\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(?\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4.1\)</span>
</td>
</tr>
</tbody>
</table>
<p>We could use the regression equation to get the point estimate of the ATE for each age:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{ATE}} &amp;= - 0.446 \cdot \mathbb{1}_{\text{is male}}(x) + 0.014 \cdot \text{age} \cdot \mathbb{1}_{\text{is male}}
\end{aligned}
\]</span></p>
<p>But that still does not give us an estimate of the uncertainty around that interval.</p>
<!-- AR: we could teach the students how to use a covariance matrix to calculate this quantity, but this chapter is very long and I fear this is already pretty confusing, so I'm presenting an easy way to get the answer -->
<p>Thankfully, there is an easy way to get that using <code>lm()</code> and <code>tidy()</code>. Recall that our coefficient on <code>gendermale</code> reflects the effect for instructors whose age is 0. If we <em>recenter</em> age so 0 is equal to the age we are interested in, then we can use both the coefficient and confidence inteveral around <code>gendermale</code> to get the confidence interval for that age. For example, here is how we would get the coefficient and confidence interval for instructors whose age is 30:</p>
<div class="sourceCode" id="cb755"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb755-1"><a href="model4.html#cb755-1"></a><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(age <span class="op">-</span><span class="st"> </span><span class="dv">30</span>) <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> evals_ch12) <span class="op">%&gt;%</span></span>
<span id="cb755-2"><a href="model4.html#cb755-2"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb755-3"><a href="model4.html#cb755-3"></a><span class="st">  </span><span class="kw">filter</span>(term <span class="op">==</span><span class="st"> &quot;gendermale&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb755-4"><a href="model4.html#cb755-4"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##   term       estimate conf.low conf.high
##   &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 gendermale  -0.0401   -0.252     0.172</code></pre>
<!-- AR: at least this is an excuse to use our `map_*` code for regressions
another time! -->
<p>But there’s no reason to do this just for one age. We can use <code>map_*</code> functions and list columns to get the coefficient on <code>gendermale</code> and the confidence interval for an arbitrary range of ages, say 20 to 90:</p>
<div class="sourceCode" id="cb757"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb757-1"><a href="model4.html#cb757-1"></a>gendermale_coefs &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ages =</span> <span class="dv">20</span><span class="op">:</span><span class="dv">90</span>) <span class="op">%&gt;%</span></span>
<span id="cb757-2"><a href="model4.html#cb757-2"></a><span class="st">  </span></span>
<span id="cb757-3"><a href="model4.html#cb757-3"></a><span class="st">  </span><span class="co"># First, we get our regression results for each age:</span></span>
<span id="cb757-4"><a href="model4.html#cb757-4"></a><span class="st">  </span></span>
<span id="cb757-5"><a href="model4.html#cb757-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(ages, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span><span class="kw">I</span>(age <span class="op">-</span><span class="st"> </span>.) <span class="op">*</span><span class="st"> </span>gender, <span class="dt">data =</span> evals_ch12)),</span>
<span id="cb757-6"><a href="model4.html#cb757-6"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(., <span class="dt">conf.int =</span> <span class="ot">TRUE</span>)),</span>
<span id="cb757-7"><a href="model4.html#cb757-7"></a>         </span>
<span id="cb757-8"><a href="model4.html#cb757-8"></a>         <span class="co"># We only care about the term &quot;gendermale&quot;:</span></span>
<span id="cb757-9"><a href="model4.html#cb757-9"></a>         </span>
<span id="cb757-10"><a href="model4.html#cb757-10"></a>         <span class="dt">reg_gendermale =</span> <span class="kw">map</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;gendermale&quot;</span>)),</span>
<span id="cb757-11"><a href="model4.html#cb757-11"></a>         </span>
<span id="cb757-12"><a href="model4.html#cb757-12"></a>         <span class="co"># Now, let&#39;s get the estimates and CIs:</span></span>
<span id="cb757-13"><a href="model4.html#cb757-13"></a>         </span>
<span id="cb757-14"><a href="model4.html#cb757-14"></a>         <span class="dt">estimate =</span> <span class="kw">map_dbl</span>(reg_gendermale, <span class="op">~</span><span class="st"> </span><span class="kw">pull</span>(., estimate)),</span>
<span id="cb757-15"><a href="model4.html#cb757-15"></a>         <span class="dt">conf.low =</span> <span class="kw">map_dbl</span>(reg_gendermale, <span class="op">~</span><span class="st"> </span><span class="kw">pull</span>(., conf.low)),</span>
<span id="cb757-16"><a href="model4.html#cb757-16"></a>         <span class="dt">conf.high =</span> <span class="kw">map_dbl</span>(reg_gendermale, <span class="op">~</span><span class="st"> </span><span class="kw">pull</span>(., conf.high)))</span>
<span id="cb757-17"><a href="model4.html#cb757-17"></a></span>
<span id="cb757-18"><a href="model4.html#cb757-18"></a>gendermale_coefs</span></code></pre></div>
<pre><code>## # A tibble: 71 x 7
##     ages mod    reg_results      reg_gendermale   estimate conf.low conf.high
##    &lt;int&gt; &lt;list&gt; &lt;list&gt;           &lt;list&gt;              &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1    20 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.175    -0.487     0.136
##  2    21 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.162    -0.463     0.139
##  3    22 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.148    -0.439     0.143
##  4    23 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.135    -0.416     0.146
##  5    24 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.121    -0.392     0.149
##  6    25 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.108    -0.368     0.153
##  7    26 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.0942   -0.345     0.156
##  8    27 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.0807   -0.322     0.160
##  9    28 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.0672   -0.298     0.164
## 10    29 &lt;lm&gt;   &lt;tibble [4 × 7]&gt; &lt;tibble [1 × 7]&gt;  -0.0537   -0.275     0.168
## # … with 61 more rows</code></pre>
<p>Note how closely this code follows code we’ve seen before for using <code>map_*</code> functions to run multiple models, except now we are using <code>I(age - .)</code> in the <code>lm()</code> call to recenter each regression by <code>ages</code>.</p>
<p>The heterogeneous treatment effects are easiest to understand if plotted visually:</p>
<div class="sourceCode" id="cb759"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb759-1"><a href="model4.html#cb759-1"></a>gendermale_coefs <span class="op">%&gt;%</span></span>
<span id="cb759-2"><a href="model4.html#cb759-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> ages, <span class="dt">y =</span> estimate, <span class="dt">ymin =</span> conf.low, <span class="dt">ymax =</span> conf.high)) <span class="op">+</span></span>
<span id="cb759-3"><a href="model4.html#cb759-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb759-4"><a href="model4.html#cb759-4"></a><span class="st">  </span><span class="kw">geom_errorbar</span>() <span class="op">+</span></span>
<span id="cb759-5"><a href="model4.html#cb759-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb759-6"><a href="model4.html#cb759-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>,</span>
<span id="cb759-7"><a href="model4.html#cb759-7"></a>       <span class="dt">y =</span> <span class="st">&quot;Effect of being male on teaching scores&quot;</span>,</span>
<span id="cb759-8"><a href="model4.html#cb759-8"></a>       <span class="dt">title =</span> <span class="st">&quot;Predicting teaching scores with gender and age&quot;</span>,</span>
<span id="cb759-9"><a href="model4.html#cb759-9"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;As age increases, being male is more associated with higher teaching scores&quot;</span>)</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-435-1.png" width="\textwidth" /></p>
<p>Note that our interaction model constrains the heterogeneous treatment effects to be linear with respect to age. If that isn’t a good model of the relationship, our model may make poor predictions.</p>
<p>Finally, let’s extract the values we need for our potential outcomes table:</p>
<div class="sourceCode" id="cb760"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb760-1"><a href="model4.html#cb760-1"></a>gendermale_coefs <span class="op">%&gt;%</span></span>
<span id="cb760-2"><a href="model4.html#cb760-2"></a><span class="st">  </span><span class="kw">filter</span>(ages <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">60</span>)) <span class="op">%&gt;%</span></span>
<span id="cb760-3"><a href="model4.html#cb760-3"></a><span class="st">  </span><span class="kw">select</span>(ages, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 4
##    ages estimate conf.low conf.high
##   &lt;int&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1    30  -0.0401  -0.252      0.172
## 2    45   0.163    0.0579     0.268
## 3    60   0.366    0.192      0.540</code></pre>
<p>Note that we’ll have to reverse the sign on our estimate for Bob and Charlie, because for them, the counterfactual is that <code>gender</code> is <code>"female"</code>.</p>
<table class="table table-striped" style="width: auto !important; ">
<thead>
<tr>
<th style="text-align:left;">
Subject
</th>
<th style="text-align:left;">
age
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = F}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(Y_{gender = M}\)</span>
</th>
<th style="text-align:left;">
<span class="math inline">\(\widehat{ATE}\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
Alice
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(30\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.96\)</span> <span class="math inline">\((3.75,\)</span> <span class="math inline">\(4.17)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-0.04\)</span> <span class="math inline">\((-0.25,\)</span> <span class="math inline">\(0.17)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Bob
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(45\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.59\)</span> <span class="math inline">\((3.48,\)</span> <span class="math inline">\(3.69)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.75\)</span>
</td>
<td style="text-align:left;">
-<span class="math inline">\(0.16\)</span> <span class="math inline">\((-0.27,\)</span> <span class="math inline">\(-0.06)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Charlie
</td>
<td style="text-align:left;border-right:1px solid;">
<span class="math inline">\(60\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(3.73\)</span> <span class="math inline">\((3.56,\)</span> <span class="math inline">\(3.91)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(4.1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(-0.37\)</span> <span class="math inline">\((-0.54,\)</span> <span class="math inline">\(-0.19)\)</span>
</td>
</tr>
</tbody>
</table>
<p>Again, however, one should always think carefully about whether a causal interpretation of a regression model is plausible. Is it really the case that age is only confounder of the relationship between gender and teaching scores? Likely it is not, and therefore we should not interpret the results of this regression causally.</p>
</div>
<div id="model4table" class="section level3">
<h3><span class="header-section-number">11.1.4</span> Parallel slopes model</h3>
<p>When creating regression models with one numerical and one categorical explanatory variable, we are not just limited to interaction models as we just saw. Another type of model we can use is known as a <em>parallel slopes</em> model. Unlike interaction models where the regression lines can have different intercepts and different slopes, parallel slopes models still allow for different intercepts but <em>force</em> all lines to have the same slope. The resulting regression lines are thus parallel. Let’s visualize the best-fitting parallel slopes model to <code>evals_ch12</code>.</p>
<p>Unfortunately, the <code>geom_smooth()</code> function in the <code>ggplot2</code> package does not have a convenient way to plot parallel slopes models. Evgeni Chasnovski thus created a special purpose function called <code>geom_parallel_slopes()</code> that is included in the <strong>moderndive</strong> package. You won’t find <code>geom_parallel_slopes()</code> in the <strong>ggplot2</strong> package, but rather the <strong>moderndive</strong> package. Thus, if you want to be able to use it, you will need to load both the <strong>ggplot2</strong> and <strong>moderndive</strong> packages. Using this function, let’s now plot the parallel slopes model for teaching score. Notice how the code is identical to the code that produced the visualization of the interaction model in Figure <a href="model4.html#fig:numxcatxplot1">11.1</a>, but now the <code>geom_smooth(method = "lm", se = FALSE)</code> layer is replaced with <code>geom_parallel_slopes(se = FALSE)</code>.</p>
<div class="sourceCode" id="cb762"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb762-1"><a href="model4.html#cb762-1"></a><span class="kw">ggplot</span>(evals_ch12, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> score, <span class="dt">color =</span> gender)) <span class="op">+</span></span>
<span id="cb762-2"><a href="model4.html#cb762-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb762-3"><a href="model4.html#cb762-3"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Age&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Teaching Score&quot;</span>, <span class="dt">color =</span> <span class="st">&quot;Gender&quot;</span>) <span class="op">+</span></span>
<span id="cb762-4"><a href="model4.html#cb762-4"></a><span class="st">  </span><span class="kw">geom_parallel_slopes</span>(<span class="dt">se =</span> <span class="ot">FALSE</span>)</span></code></pre></div>
<div class="figure"><span id="fig:numxcatx-parallel"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/numxcatx-parallel-1.png" alt="Parallel slopes model of score with age and gender." width="\textwidth" />
<p class="caption">
FIGURE 11.2: Parallel slopes model of score with age and gender.
</p>
</div>
<p>Observe in Figure <a href="model4.html#fig:numxcatx-parallel">11.2</a> that we now have parallel lines corresponding to the female and male instructors, respectively: here they have the same negative slope. This is telling us that instructors who are older will tend to receive lower teaching scores than instructors who are younger. Furthermore, since the lines are parallel, the associated penalty for being older is assumed to be the same for both female and male instructors.</p>
<p>However, observe also in Figure <a href="model4.html#fig:numxcatx-parallel">11.2</a> that these two lines have different intercepts as evidenced by the fact that the blue line corresponding to the male instructors is higher than the red line corresponding to the female instructors. This is telling us that irrespective of age, female instructors tended to receive lower teaching scores than male instructors.</p>
<p>In order to obtain the precise numerical values of the two intercepts and the single common slope, we once again “fit” the model using the <code>lm()</code> “linear model” function and then apply the <code>tidy()</code> function. However, unlike the interaction model which had a model formula of the form <code>y ~ x1 * x2</code>, our model formula is now of the form <code>y ~ x1 + x2</code>. In other words, our two explanatory variables <code>x1</code> and <code>x2</code> are separated by a <code>+</code> sign:</p>
<div class="sourceCode" id="cb763"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb763-1"><a href="model4.html#cb763-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb763-2"><a href="model4.html#cb763-2"></a></span>
<span id="cb763-3"><a href="model4.html#cb763-3"></a>score_model_parallel_slopes &lt;-<span class="st"> </span><span class="kw">lm</span>(score <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>gender, <span class="dt">data =</span> evals_ch12)</span>
<span id="cb763-4"><a href="model4.html#cb763-4"></a></span>
<span id="cb763-5"><a href="model4.html#cb763-5"></a><span class="co"># Get regression table:</span></span>
<span id="cb763-6"><a href="model4.html#cb763-6"></a></span>
<span id="cb763-7"><a href="model4.html#cb763-7"></a>score_model_parallel_slopes <span class="op">%&gt;%</span></span>
<span id="cb763-8"><a href="model4.html#cb763-8"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb763-9"><a href="model4.html#cb763-9"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:regtable-parallel-slopes">TABLE 11.7: </span>Regression table for parallel slopes model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
4.484
</td>
<td style="text-align:right;">
4.238
</td>
<td style="text-align:right;">
4.730
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
-0.009
</td>
<td style="text-align:right;">
-0.014
</td>
<td style="text-align:right;">
-0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
gendermale
</td>
<td style="text-align:right;">
0.191
</td>
<td style="text-align:right;">
0.087
</td>
<td style="text-align:right;">
0.294
</td>
</tr>
</tbody>
</table>
<p>Similarly to the regression table for the interaction model from Table <a href="model4.html#tab:regtable-interaction">11.4</a>, we have an <code>intercept</code> term corresponding to the intercept for the “baseline for comparison” female instructor group and a <code>gendermale</code> term corresponding to the <em>offset</em> in intercept for the male instructors relative to female instructors. In other words, in Figure <a href="model4.html#fig:numxcatx-parallel">11.2</a> the red regression line corresponding to the female instructors has an intercept of 4.484 while the blue regression line corresponding to the male instructors has an intercept of 4.484 + 0.191 = 4.675. Once again, since there aren’t any instructors of age 0, the intercepts only have a mathematical interpretation but no practical one.</p>
<p>Unlike in Table <a href="model4.html#tab:regtable-interaction">11.4</a>, however, we now only have a single slope for age of -0.009. This is because the model dictates that both the female and male instructors have a common slope for age.  This is telling us that an instructor who is a year older than another instructor received a teaching score that is on average 0.009 units <em>lower</em>. This penalty for being of advanced age applies equally to both female and male instructors.</p>
<p>Let’s summarize these values in Table <a href="model4.html#tab:parallel-slopes-summary">11.8</a>, noting the different intercepts but common slopes:</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:parallel-slopes-summary">TABLE 11.8: </span>Comparison of intercepts and slope for parallel slopes model
</caption>
<thead>
<tr>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Intercept
</th>
<th style="text-align:right;">
Slope for age
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Female instructors
</td>
<td style="text-align:right;">
4.484
</td>
<td style="text-align:right;">
-0.009
</td>
</tr>
<tr>
<td style="text-align:left;">
Male instructors
</td>
<td style="text-align:right;">
4.675
</td>
<td style="text-align:right;">
-0.009
</td>
</tr>
</tbody>
</table>
<p>Let’s now write the equation for our regression lines, which we can use to compute our fitted values <span class="math inline">\(\widehat{y} = \widehat{\text{score}}\)</span>.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= b_0 + b_{\text{age}} \cdot \text{age} + b_{\text{male}} \cdot \mathbb{1}_{\text{is male}}(x)\\
&amp;= 4.484 -0.009 \cdot \text{age} + 0.191 \cdot \mathbb{1}_{\text{is male}}(x) 
\end{aligned}
\]</span></p>
<p>Let’s put this all together and compute the fitted value <span class="math inline">\(\widehat{y} = \widehat{\text{score}}\)</span> for female instructors. Since for female instructors the indicator function <span class="math inline">\(\mathbb{1}_{\text{is male}}(x)\)</span> = 0, the previous equation becomes</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= 4.484 -0.009    \cdot \text{age} + 0.191 \cdot 0\\
&amp;= 4.484 -0.009 \cdot \text{age}
\end{aligned}
\]</span></p>
<p>which is the equation of the red regression line in Figure <a href="model4.html#fig:numxcatx-parallel">11.2</a> corresponding to the female instructors. Correspondingly, since for male instructors the indicator function <span class="math inline">\(\mathbb{1}_{\text{is male}}(x)\)</span> = 1, the previous equation becomes</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} = \widehat{\text{score}} &amp;= 4.484 -0.009    \cdot \text{age} + 0.191 \cdot 1\\
&amp;= (4.484 + 0.191) - 0.009 \cdot \text{age}\\
&amp;= 4.675 -0.009 \cdot \text{age}
\end{aligned}
\]</span></p>
<p>which is the equation of the blue regression line in Figure <a href="model4.html#fig:numxcatx-parallel">11.2</a> corresponding to the male instructors.</p>
<p>Great! We’ve considered both an interaction model and a parallel slopes model for our data. Let’s compare the visualizations for both models side-by-side in Figure <a href="model4.html#fig:numxcatx-comparison">11.3</a>.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:numxcatx-comparison"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/numxcatx-comparison-1.png" alt="Comparison of interaction and parallel slopes models." width="\textwidth" />
<p class="caption">
FIGURE 11.3: Comparison of interaction and parallel slopes models.
</p>
</div>
<p>At this point, you might be asking yourself: “Why would we ever use a parallel slopes model?” Looking at the left-hand plot in Figure <a href="model4.html#fig:numxcatx-comparison">11.3</a>, the two lines definitely do not appear to be parallel, so why would we <em>force</em> them to be parallel? For this data, we agree! It can easily be argued that the interaction model on the left is more appropriate. However, in the upcoming Subsection <a href="other-topics.html#model-selection">11.4.1</a> on model selection, we’ll present an example where it can be argued that the case for a parallel slopes model might be stronger.</p>
</div>
<div id="model4points" class="section level3">
<h3><span class="header-section-number">11.1.5</span> Observed/fitted values and residuals</h3>
<p>For brevity’s sake, in this section we’ll only compute the observed values, fitted values, and residuals for the interaction model which we saved in <code>score_model_interaction</code>.</p>
<p>Say, you have an instructor who identifies as female and is 36 years old. What fitted value <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> would our model yield? Say, you have another instructor who identifies as male and is 59 years old. What would their fitted value <span class="math inline">\(\widehat{y}\)</span> be?</p>
<p>We answer this question visually first for the female instructor by finding the intersection of the red regression line and the vertical line at <span class="math inline">\(x\)</span> = age = 36. We mark this value with a large red dot in Figure <a href="model4.html#fig:fitted-values">11.4</a>. Similarly, we can identify the fitted value <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> for the male instructor by finding the intersection of the blue regression line and the vertical line at <span class="math inline">\(x\)</span> = age = 59. We mark this value with a large blue dot in Figure <a href="model4.html#fig:fitted-values">11.4</a>.</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<div class="figure"><span id="fig:fitted-values"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/fitted-values-1.png" alt="Fitted values for two new professors." width="\textwidth" />
<p class="caption">
FIGURE 11.4: Fitted values for two new professors.
</p>
</div>
<p>What are these two values of <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> precisely? We can use the equations of the two regression lines we computed in Subsection <a href="model4.html#model4interactiontable">11.1.2</a>, which in turn were based on values from the regression table in Table <a href="model4.html#tab:regtable-interaction">11.4</a>:</p>
<ul>
<li>For all female instructors: <span class="math inline">\(\widehat{y} = \widehat{\text{score}} = 4.883 - 0.018 \cdot \text{age}\)</span></li>
<li>For all male instructors: <span class="math inline">\(\widehat{y} = \widehat{\text{score}} = 4.437 - 0.004 \cdot \text{age}\)</span></li>
</ul>
<p>So our fitted values would be: <span class="math inline">\(4.883 - 0.018 \cdot 36 = 4.25\)</span> and <span class="math inline">\(4.437 - 0.004 \cdot 59 = 4.20\)</span>, respectively.</p>
<p>Now what if we want the fitted values not just for these two instructors, but for the instructors of all 463 courses included in the <code>evals_ch12</code> data frame? Doing this by hand would be long and tedious! This is where the <code>augment()</code> function from the <strong>broom</strong> package can help: it will quickly automate the above calculations for all 463 courses. We present a preview of just the first 10 rows out of 463 in Table <a href="model4.html#tab:model4-points-table">11.9</a>. Just like in the last chapter, we’ll use the <code>.se.fit</code> column to construct confidence intervals around our predicted values.</p>
<div class="sourceCode" id="cb766"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb766-1"><a href="model4.html#cb766-1"></a>regression_points &lt;-<span class="st"> </span>score_model_interaction <span class="op">%&gt;%</span></span>
<span id="cb766-2"><a href="model4.html#cb766-2"></a><span class="st">  </span><span class="kw">augment</span>() <span class="op">%&gt;%</span></span>
<span id="cb766-3"><a href="model4.html#cb766-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">conf.low =</span> .fitted <span class="op">-</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit,</span>
<span id="cb766-4"><a href="model4.html#cb766-4"></a>         <span class="dt">conf.high =</span> .fitted <span class="op">+</span><span class="st"> </span><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>.se.fit) <span class="op">%&gt;%</span></span>
<span id="cb766-5"><a href="model4.html#cb766-5"></a><span class="st">  </span><span class="kw">select</span>(score, age, gender, .fitted, conf.low, conf.high, .resid)</span>
<span id="cb766-6"><a href="model4.html#cb766-6"></a>regression_points</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:model4-points-table">TABLE 11.9: </span>Regression points (First 10 out of 463 courses)
</caption>
<thead>
<tr>
<th style="text-align:right;">
score
</th>
<th style="text-align:right;">
age
</th>
<th style="text-align:left;">
gender
</th>
<th style="text-align:right;">
.fitted
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:right;">
.resid
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
4.7
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
4.25
</td>
<td style="text-align:right;">
4.14
</td>
<td style="text-align:right;">
4.36
</td>
<td style="text-align:right;">
0.448
</td>
</tr>
<tr>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
4.25
</td>
<td style="text-align:right;">
4.14
</td>
<td style="text-align:right;">
4.36
</td>
<td style="text-align:right;">
-0.152
</td>
</tr>
<tr>
<td style="text-align:right;">
3.9
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
4.25
</td>
<td style="text-align:right;">
4.14
</td>
<td style="text-align:right;">
4.36
</td>
<td style="text-align:right;">
-0.352
</td>
</tr>
<tr>
<td style="text-align:right;">
4.8
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
4.25
</td>
<td style="text-align:right;">
4.14
</td>
<td style="text-align:right;">
4.36
</td>
<td style="text-align:right;">
0.548
</td>
</tr>
<tr>
<td style="text-align:right;">
4.6
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4.20
</td>
<td style="text-align:right;">
4.12
</td>
<td style="text-align:right;">
4.29
</td>
<td style="text-align:right;">
0.399
</td>
</tr>
<tr>
<td style="text-align:right;">
4.3
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4.20
</td>
<td style="text-align:right;">
4.12
</td>
<td style="text-align:right;">
4.29
</td>
<td style="text-align:right;">
0.099
</td>
</tr>
<tr>
<td style="text-align:right;">
2.8
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4.20
</td>
<td style="text-align:right;">
4.12
</td>
<td style="text-align:right;">
4.29
</td>
<td style="text-align:right;">
-1.401
</td>
</tr>
<tr>
<td style="text-align:right;">
4.1
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4.23
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:right;">
4.30
</td>
<td style="text-align:right;">
-0.133
</td>
</tr>
<tr>
<td style="text-align:right;">
3.4
</td>
<td style="text-align:right;">
51
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
4.23
</td>
<td style="text-align:right;">
4.17
</td>
<td style="text-align:right;">
4.30
</td>
<td style="text-align:right;">
-0.833
</td>
</tr>
<tr>
<td style="text-align:right;">
4.5
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
4.18
</td>
<td style="text-align:right;">
4.09
</td>
<td style="text-align:right;">
4.27
</td>
<td style="text-align:right;">
0.318
</td>
</tr>
</tbody>
</table>
<p>It turns out that the female instructor of age 36 taught the first four courses, while the male instructor taught the next 3. The resulting <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(\widehat{\text{score}}\)</span> fitted values are in the <code>.fitted</code> column. Furthermore, the <code>augment()</code> function also returns the residuals <span class="math inline">\(y-\widehat{y}\)</span>. Notice, for example, the first and fourth courses the female instructor of age 36 taught had positive residuals, indicating that the actual teaching scores they received from students were greater than their fitted score of 4.25. On the other hand, the second and third courses this instructor taught had negative residuals, indicating that the actual teaching scores they received from students were less than 4.25.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="multiple-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="model3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
