<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.4 Explore your first datasets | Preceptor’s Primer for Bayesian Data Science</title>
  <meta name="description" content="1.4 Explore your first datasets | Preceptor’s Primer for Bayesian Data Science" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="1.4 Explore your first datasets | Preceptor’s Primer for Bayesian Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="davidkane9/PPBDS" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.4 Explore your first datasets | Preceptor’s Primer for Bayesian Data Science" />
  
  
  

<meta name="author" content="David Kane" />


<meta name="date" content="2020-05-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="packages.html"/>
<link rel="next" href="conclusion.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="forward.html"><a href="forward.html"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="warning.html"><a href="warning.html"><i class="fa fa-check"></i>Warning</a></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="part-i.html"><a href="part-i.html"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="1" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>1</b> Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio.html"><a href="r-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="r-rstudio.html"><a href="r-rstudio.html#installing"><i class="fa fa-check"></i><b>1.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="r-rstudio.html"><a href="r-rstudio.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="code.html"><a href="code.html"><i class="fa fa-check"></i><b>1.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="code.html"><a href="code.html#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="1.2.2" data-path="code.html"><a href="code.html#messages"><i class="fa fa-check"></i><b>1.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="1.2.3" data-path="code.html"><a href="code.html#tips-code"><i class="fa fa-check"></i><b>1.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="packages.html"><a href="packages.html#package-installation"><i class="fa fa-check"></i><b>1.3.1</b> Package installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="packages.html"><a href="packages.html#package-loading"><i class="fa fa-check"></i><b>1.3.2</b> Package loading</a></li>
<li class="chapter" data-level="1.3.3" data-path="packages.html"><a href="packages.html#package-use"><i class="fa fa-check"></i><b>1.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="nycflights13.html"><a href="nycflights13.html"><i class="fa fa-check"></i><b>1.4</b> Explore your first datasets</a><ul>
<li class="chapter" data-level="1.4.1" data-path="nycflights13.html"><a href="nycflights13.html#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="nycflights13.html"><a href="nycflights13.html#flights-data-frame"><i class="fa fa-check"></i><b>1.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="1.4.3" data-path="nycflights13.html"><a href="nycflights13.html#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="1.4.4" data-path="nycflights13.html"><a href="nycflights13.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>1.4.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="1.4.5" data-path="nycflights13.html"><a href="nycflights13.html#help-files"><i class="fa fa-check"></i><b>1.4.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a><ul>
<li class="chapter" data-level="1.5.1" data-path="conclusion.html"><a href="conclusion.html#additional-resources"><i class="fa fa-check"></i><b>1.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html"><i class="fa fa-check"></i><b>1.6</b> The grammar of graphics</a><ul>
<li class="chapter" data-level="1.6.1" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#components-of-the-grammar"><i class="fa fa-check"></i><b>1.6.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="1.6.2" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#gapminder"><i class="fa fa-check"></i><b>1.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="1.6.3" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#other-components"><i class="fa fa-check"></i><b>1.6.3</b> Other components</a></li>
<li class="chapter" data-level="1.6.4" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#ggplot2-package"><i class="fa fa-check"></i><b>1.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>1.7</b> Scatterplots</a><ul>
<li class="chapter" data-level="1.7.1" data-path="scatterplots.html"><a href="scatterplots.html#geompoint"><i class="fa fa-check"></i><b>1.7.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="scatterplots.html"><a href="scatterplots.html#overplotting"><i class="fa fa-check"></i><b>1.7.2</b> Overplotting</a></li>
<li class="chapter" data-level="1.7.3" data-path="scatterplots.html"><a href="scatterplots.html#summary"><i class="fa fa-check"></i><b>1.7.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="linegraphs.html"><a href="linegraphs.html"><i class="fa fa-check"></i><b>1.8</b> Linegraphs</a><ul>
<li class="chapter" data-level="1.8.1" data-path="linegraphs.html"><a href="linegraphs.html#geomline"><i class="fa fa-check"></i><b>1.8.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="linegraphs.html"><a href="linegraphs.html#summary-1"><i class="fa fa-check"></i><b>1.8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="histograms.html"><a href="histograms.html"><i class="fa fa-check"></i><b>1.9</b> Histograms</a><ul>
<li class="chapter" data-level="1.9.1" data-path="histograms.html"><a href="histograms.html#geomhistogram"><i class="fa fa-check"></i><b>1.9.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="1.9.2" data-path="histograms.html"><a href="histograms.html#adjustbins"><i class="fa fa-check"></i><b>1.9.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="1.9.3" data-path="histograms.html"><a href="histograms.html#summary-2"><i class="fa fa-check"></i><b>1.9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="facets.html"><a href="facets.html"><i class="fa fa-check"></i><b>1.10</b> Facets</a></li>
<li class="chapter" data-level="1.11" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>1.11</b> Boxplots</a><ul>
<li class="chapter" data-level="1.11.1" data-path="boxplots.html"><a href="boxplots.html#geomboxplot"><i class="fa fa-check"></i><b>1.11.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="boxplots.html"><a href="boxplots.html#summary-3"><i class="fa fa-check"></i><b>1.11.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="geombar.html"><a href="geombar.html"><i class="fa fa-check"></i><b>1.12</b> Barplots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="geombar.html"><a href="geombar.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>1.12.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="1.12.2" data-path="geombar.html"><a href="geombar.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>1.12.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="1.12.3" data-path="geombar.html"><a href="geombar.html#two-categ-barplot"><i class="fa fa-check"></i><b>1.12.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="1.12.4" data-path="geombar.html"><a href="geombar.html#summary-4"><i class="fa fa-check"></i><b>1.12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>1.13</b> Conclusion</a><ul>
<li class="chapter" data-level="1.13.1" data-path="conclusion-1.html"><a href="conclusion-1.html#summary-table"><i class="fa fa-check"></i><b>1.13.1</b> Summary table</a></li>
<li class="chapter" data-level="1.13.2" data-path="conclusion-1.html"><a href="conclusion-1.html#function-argument-specification"><i class="fa fa-check"></i><b>1.13.2</b> Function argument specification</a></li>
<li class="chapter" data-level="1.13.3" data-path="conclusion-1.html"><a href="conclusion-1.html#additional-resources-1"><i class="fa fa-check"></i><b>1.13.3</b> Additional resources</a></li>
<li class="chapter" data-level="1.13.4" data-path="conclusion-1.html"><a href="conclusion-1.html#whats-to-come-3"><i class="fa fa-check"></i><b>1.13.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>2</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="piping.html"><a href="piping.html"><i class="fa fa-check"></i><b>2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.2" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="2.3" data-path="summarize.html"><a href="summarize.html"><i class="fa fa-check"></i><b>2.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="2.4" data-path="groupby.html"><a href="groupby.html"><i class="fa fa-check"></i><b>2.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="groupby.html"><a href="groupby.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>2.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>2.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="2.6" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>2.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="2.7" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>2.7</b> Factors</a><ul>
<li class="chapter" data-level="2.7.1" data-path="factors.html"><a href="factors.html#the-forcats-package"><i class="fa fa-check"></i><b>2.7.1</b> The <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="2.7.2" data-path="factors.html"><a href="factors.html#dropping-unused-levels"><i class="fa fa-check"></i><b>2.7.2</b> Dropping unused levels</a></li>
<li class="chapter" data-level="2.7.3" data-path="factors.html"><a href="factors.html#reorder-factors"><i class="fa fa-check"></i><b>2.7.3</b> Change order of the levels, principled</a></li>
<li class="chapter" data-level="2.7.4" data-path="factors.html"><a href="factors.html#change-order-of-the-levels-because-i-said-so"><i class="fa fa-check"></i><b>2.7.4</b> Change order of the levels, “because I said so”</a></li>
<li class="chapter" data-level="2.7.5" data-path="factors.html"><a href="factors.html#recode-the-levels"><i class="fa fa-check"></i><b>2.7.5</b> Recode the levels</a></li>
<li class="chapter" data-level="2.7.6" data-path="factors.html"><a href="factors.html#grow-a-factor"><i class="fa fa-check"></i><b>2.7.6</b> Grow a factor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="character-vectors.html"><a href="character-vectors.html"><i class="fa fa-check"></i><b>2.8</b> Character Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="character-vectors.html"><a href="character-vectors.html#manipulating-character-vectors"><i class="fa fa-check"></i><b>2.8.1</b> Manipulating character vectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-resources"><i class="fa fa-check"></i><b>2.8.2</b> Regular expressions resources</a></li>
<li class="chapter" data-level="2.8.3" data-path="character-vectors.html"><a href="character-vectors.html#character-encoding-resources"><i class="fa fa-check"></i><b>2.8.3</b> Character encoding resources</a></li>
<li class="chapter" data-level="2.8.4" data-path="character-vectors.html"><a href="character-vectors.html#character-vectors-that-live-in-a-data-frame"><i class="fa fa-check"></i><b>2.8.4</b> Character vectors that live in a data frame</a></li>
<li class="chapter" data-level="2.8.5" data-path="character-vectors.html"><a href="character-vectors.html#regex-free-string-manipulation-with-stringr-and-tidyr"><i class="fa fa-check"></i><b>2.8.5</b> Regex-free string manipulation with stringr and tidyr</a></li>
<li class="chapter" data-level="2.8.6" data-path="character-vectors.html"><a href="character-vectors.html#detect-or-filter-on-a-target-string"><i class="fa fa-check"></i><b>2.8.6</b> Detect or filter on a target string</a></li>
<li class="chapter" data-level="2.8.7" data-path="character-vectors.html"><a href="character-vectors.html#string-splitting-by-delimiter"><i class="fa fa-check"></i><b>2.8.7</b> String splitting by delimiter</a></li>
<li class="chapter" data-level="2.8.8" data-path="character-vectors.html"><a href="character-vectors.html#substring-extraction-and-replacement-by-position"><i class="fa fa-check"></i><b>2.8.8</b> Substring extraction (and replacement) by position</a></li>
<li class="chapter" data-level="2.8.9" data-path="character-vectors.html"><a href="character-vectors.html#collapse-a-vector"><i class="fa fa-check"></i><b>2.8.9</b> Collapse a vector</a></li>
<li class="chapter" data-level="2.8.10" data-path="character-vectors.html"><a href="character-vectors.html#catenate-vectors"><i class="fa fa-check"></i><b>2.8.10</b> Create a character vector by catenating multiple vectors</a></li>
<li class="chapter" data-level="2.8.11" data-path="character-vectors.html"><a href="character-vectors.html#substring-replacement"><i class="fa fa-check"></i><b>2.8.11</b> Substring replacement</a></li>
<li class="chapter" data-level="2.8.12" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-with-stringr"><i class="fa fa-check"></i><b>2.8.12</b> Regular expressions with stringr</a></li>
<li class="chapter" data-level="2.8.13" data-path="character-vectors.html"><a href="character-vectors.html#characters-with-special-meaning"><i class="fa fa-check"></i><b>2.8.13</b> Characters with special meaning</a></li>
<li class="chapter" data-level="2.8.14" data-path="character-vectors.html"><a href="character-vectors.html#character-classes"><i class="fa fa-check"></i><b>2.8.14</b> Character classes</a></li>
<li class="chapter" data-level="2.8.15" data-path="character-vectors.html"><a href="character-vectors.html#quantifiers"><i class="fa fa-check"></i><b>2.8.15</b> Quantifiers</a></li>
<li class="chapter" data-level="2.8.16" data-path="character-vectors.html"><a href="character-vectors.html#escaping"><i class="fa fa-check"></i><b>2.8.16</b> Escaping</a></li>
<li class="chapter" data-level="2.8.17" data-path="character-vectors.html"><a href="character-vectors.html#groups-and-backreferences"><i class="fa fa-check"></i><b>2.8.17</b> Groups and backreferences</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="combining-data.html"><a href="combining-data.html"><i class="fa fa-check"></i><b>2.9</b> Combining Data</a><ul>
<li class="chapter" data-level="2.9.1" data-path="combining-data.html"><a href="combining-data.html#bind"><i class="fa fa-check"></i><b>2.9.1</b> Bind</a></li>
<li class="chapter" data-level="2.9.2" data-path="combining-data.html"><a href="combining-data.html#joins-in-dplyr"><i class="fa fa-check"></i><b>2.9.2</b> Joins in dplyr</a></li>
<li class="chapter" data-level="2.9.3" data-path="combining-data.html"><a href="combining-data.html#joining"><i class="fa fa-check"></i><b>2.9.3</b> Joining</a></li>
<li class="chapter" data-level="2.9.4" data-path="combining-data.html"><a href="combining-data.html#matching-key-variable-names"><i class="fa fa-check"></i><b>2.9.4</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="2.9.5" data-path="combining-data.html"><a href="combining-data.html#diff-key"><i class="fa fa-check"></i><b>2.9.5</b> Different “key” variable names</a></li>
<li class="chapter" data-level="2.9.6" data-path="combining-data.html"><a href="combining-data.html#multiple-key-variables"><i class="fa fa-check"></i><b>2.9.6</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="2.9.7" data-path="combining-data.html"><a href="combining-data.html#normal-forms"><i class="fa fa-check"></i><b>2.9.7</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="other-verbs.html"><a href="other-verbs.html"><i class="fa fa-check"></i><b>2.10</b> Other Verbs</a><ul>
<li class="chapter" data-level="2.10.1" data-path="other-verbs.html"><a href="other-verbs.html#select"><i class="fa fa-check"></i><b>2.10.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="other-verbs.html"><a href="other-verbs.html#rename"><i class="fa fa-check"></i><b>2.10.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="2.10.3" data-path="other-verbs.html"><a href="other-verbs.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>2.10.3</b> <code>top_n</code> values of a variable</a></li>
<li class="chapter" data-level="2.10.4" data-path="other-verbs.html"><a href="other-verbs.html#slice-and-pull-and"><i class="fa fa-check"></i><b>2.10.4</b> <code>slice</code> and <code>pull</code> and <code>[]</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="conclusion-2.html"><a href="conclusion-2.html"><i class="fa fa-check"></i><b>2.11</b> Conclusion</a><ul>
<li class="chapter" data-level="2.11.1" data-path="conclusion-2.html"><a href="conclusion-2.html#summary-table-1"><i class="fa fa-check"></i><b>2.11.1</b> Summary table</a></li>
<li class="chapter" data-level="2.11.2" data-path="conclusion-2.html"><a href="conclusion-2.html#additional-resources-2"><i class="fa fa-check"></i><b>2.11.2</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>2.12</b> Tidy</a></li>
<li class="chapter" data-level="2.13" data-path="csv.html"><a href="csv.html"><i class="fa fa-check"></i><b>2.13</b> Importing data</a></li>
<li class="chapter" data-level="2.14" data-path="web-scraping.html"><a href="web-scraping.html"><i class="fa fa-check"></i><b>2.14</b> Web scraping</a><ul>
<li class="chapter" data-level="2.14.1" data-path="web-scraping.html"><a href="web-scraping.html#html"><i class="fa fa-check"></i><b>2.14.1</b> HTML</a></li>
<li class="chapter" data-level="2.14.2" data-path="web-scraping.html"><a href="web-scraping.html#the-rvest-package"><i class="fa fa-check"></i><b>2.14.2</b> The rvest package</a></li>
<li class="chapter" data-level="2.14.3" data-path="web-scraping.html"><a href="web-scraping.html#css-selectors"><i class="fa fa-check"></i><b>2.14.3</b> CSS selectors</a></li>
<li class="chapter" data-level="2.14.4" data-path="web-scraping.html"><a href="web-scraping.html#json"><i class="fa fa-check"></i><b>2.14.4</b> JSON</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html"><i class="fa fa-check"></i><b>2.15</b> “Tidy” data</a><ul>
<li class="chapter" data-level="2.15.1" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#tidy-definition"><i class="fa fa-check"></i><b>2.15.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="2.15.2" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>2.15.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="2.15.3" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#nycflights13-package-1"><i class="fa fa-check"></i><b>2.15.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="case-study-tidy.html"><a href="case-study-tidy.html"><i class="fa fa-check"></i><b>2.16</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="2.17" data-path="tidyverse-package.html"><a href="tidyverse-package.html"><i class="fa fa-check"></i><b>2.17</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="2.18" data-path="conclusion-3.html"><a href="conclusion-3.html"><i class="fa fa-check"></i><b>2.18</b> Conclusion</a><ul>
<li class="chapter" data-level="2.18.1" data-path="conclusion-3.html"><a href="conclusion-3.html#additional-resources-3"><i class="fa fa-check"></i><b>2.18.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rubin-causal-model.html"><a href="rubin-causal-model.html"><i class="fa fa-check"></i><b>3</b> Rubin Causal Model</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html"><i class="fa fa-check"></i><b>3.1</b> What is a causal effect?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#everything-is-a-missing-data-problem"><i class="fa fa-check"></i><b>3.1.1</b> Everything is a missing data problem</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#potential-outcomes-introduction-to-the-rubin-table"><i class="fa fa-check"></i><b>3.1.2</b> Potential outcomes: introduction to the Rubin Table</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#estimands"><i class="fa fa-check"></i><b>3.1.3</b> Estimands</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#the-infinite-rubin-table-many-kinds-of-missing-data"><i class="fa fa-check"></i><b>3.1.4</b> The infinite Rubin Table: many kinds of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html"><i class="fa fa-check"></i><b>3.2</b> How do we fill in the missing values?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#average-treatment-effect"><i class="fa fa-check"></i><b>3.2.1</b> Average treatment effect</a></li>
<li class="chapter" data-level="3.2.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#the-assignment-mechanism"><i class="fa fa-check"></i><b>3.2.2</b> The assignment mechanism</a></li>
<li class="chapter" data-level="3.2.3" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#uncertainty-and-permutation-tests"><i class="fa fa-check"></i><b>3.2.3</b> Uncertainty and permutation tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#everything-is-a-missing-data-problem-revisited-internal-and-external-validity"><i class="fa fa-check"></i><b>3.2.4</b> Everything is a missing data problem revisited: Internal and external validity</a></li>
<li class="chapter" data-level="3.2.5" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#more-complex-models-for-causal-inference"><i class="fa fa-check"></i><b>3.2.5</b> More complex models for causal inference</a></li>
<li class="chapter" data-level="3.2.6" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#causal-inference-and-prediction"><i class="fa fa-check"></i><b>3.2.6</b> Causal inference and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html"><i class="fa fa-check"></i><b>3.3</b> Other issues with causal inference</a><ul>
<li class="chapter" data-level="3.3.1" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#no-causation-without-manipulation"><i class="fa fa-check"></i><b>3.3.1</b> No causation without manipulation</a></li>
<li class="chapter" data-level="3.3.2" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#stable-unit-treatment-value-assumption-sutva"><i class="fa fa-check"></i><b>3.3.2</b> Stable unit treatment value assumption (SUTVA)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="conclusion-4.html"><a href="conclusion-4.html"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
<li class="chapter" data-level="3.5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a><ul>
<li class="chapter" data-level="4.1" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="part-1.html"><a href="part-1.html#get-something-that-works"><i class="fa fa-check"></i><b>4.1.1</b> Get something that works</a></li>
<li class="chapter" data-level="4.1.2" data-path="part-1.html"><a href="part-1.html#skateboard-perfectly-formed-rear-view-mirror"><i class="fa fa-check"></i><b>4.1.2</b> Skateboard &gt;&gt; perfectly formed rear-view mirror</a></li>
<li class="chapter" data-level="4.1.3" data-path="part-1.html"><a href="part-1.html#turn-the-working-interactive-code-into-a-function"><i class="fa fa-check"></i><b>4.1.3</b> Turn the working interactive code into a function</a></li>
<li class="chapter" data-level="4.1.4" data-path="part-1.html"><a href="part-1.html#test-your-function"><i class="fa fa-check"></i><b>4.1.4</b> Test your function</a></li>
<li class="chapter" data-level="4.1.5" data-path="part-1.html"><a href="part-1.html#check-the-validity-of-arguments"><i class="fa fa-check"></i><b>4.1.5</b> Check the validity of arguments</a></li>
<li class="chapter" data-level="4.1.6" data-path="part-1.html"><a href="part-1.html#wrap-up-and-whats-next"><i class="fa fa-check"></i><b>4.1.6</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i><b>4.2</b> Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="part-2.html"><a href="part-2.html#load-the-gapminder-data"><i class="fa fa-check"></i><b>4.2.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.2.2" data-path="part-2.html"><a href="part-2.html#restore-our-max-minus-min-function"><i class="fa fa-check"></i><b>4.2.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.2.3" data-path="part-2.html"><a href="part-2.html#generalize-our-function-to-other-quantiles"><i class="fa fa-check"></i><b>4.2.3</b> Generalize our function to other quantiles</a></li>
<li class="chapter" data-level="4.2.4" data-path="part-2.html"><a href="part-2.html#get-something-that-works-again"><i class="fa fa-check"></i><b>4.2.4</b> Get something that works, again</a></li>
<li class="chapter" data-level="4.2.5" data-path="part-2.html"><a href="part-2.html#turn-the-working-interactive-code-into-a-function-again"><i class="fa fa-check"></i><b>4.2.5</b> Turn the working interactive code into a function, again</a></li>
<li class="chapter" data-level="4.2.6" data-path="part-2.html"><a href="part-2.html#argument-names-freedom-and-conventions"><i class="fa fa-check"></i><b>4.2.6</b> Argument names: freedom and conventions</a></li>
<li class="chapter" data-level="4.2.7" data-path="part-2.html"><a href="part-2.html#what-a-function-returns"><i class="fa fa-check"></i><b>4.2.7</b> What a function returns</a></li>
<li class="chapter" data-level="4.2.8" data-path="part-2.html"><a href="part-2.html#default-values-freedom-to-not-specify-the-arguments"><i class="fa fa-check"></i><b>4.2.8</b> Default values: freedom to NOT specify the arguments</a></li>
<li class="chapter" data-level="4.2.9" data-path="part-2.html"><a href="part-2.html#wrap-up-and-whats-next-1"><i class="fa fa-check"></i><b>4.2.9</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i><b>4.3</b> Part 3</a><ul>
<li class="chapter" data-level="4.3.1" data-path="part-3.html"><a href="part-3.html#load-the-gapminder-data-1"><i class="fa fa-check"></i><b>4.3.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.3.2" data-path="part-3.html"><a href="part-3.html#restore-our-max-minus-min-function-1"><i class="fa fa-check"></i><b>4.3.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.3.3" data-path="part-3.html"><a href="part-3.html#be-proactive-about-nas"><i class="fa fa-check"></i><b>4.3.3</b> Be proactive about <code>NA</code>s</a></li>
<li class="chapter" data-level="4.3.4" data-path="part-3.html"><a href="part-3.html#the-useful-but-mysterious-...-argument"><i class="fa fa-check"></i><b>4.3.4</b> The useful but mysterious <code>...</code> argument</a></li>
<li class="chapter" data-level="4.3.5" data-path="part-3.html"><a href="part-3.html#use-testthat-for-formal-unit-tests"><i class="fa fa-check"></i><b>4.3.5</b> Use testthat for formal unit tests</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html"><i class="fa fa-check"></i><b>4.4</b> List columns and <code>map_*</code> functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#what-are-list-columns"><i class="fa fa-check"></i><b>4.4.1</b> What are list columns?</a></li>
<li class="chapter" data-level="4.4.2" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#creating-list-columns-with-mutate"><i class="fa fa-check"></i><b>4.4.2</b> Creating list columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="4.4.3" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#map_-functions"><i class="fa fa-check"></i><b>4.4.3</b> <code>map_*</code> functions</a></li>
<li class="chapter" data-level="4.4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#using-map_-functions-to-create-list-columns"><i class="fa fa-check"></i><b>4.4.4</b> Using <code>map_*</code> functions to create list columns</a></li>
<li class="chapter" data-level="4.4.5" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#practice-with-map_-functions-and-list-columns"><i class="fa fa-check"></i><b>4.4.5</b> Practice with <code>map_*</code> functions and list columns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii.html"><a href="part-ii.html"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html"><i class="fa fa-check"></i><b>5.1</b> Defining probability</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#intro-questions"><i class="fa fa-check"></i><b>5.1.1</b> Intro Questions</a></li>
<li class="chapter" data-level="5.1.2" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-1"><i class="fa fa-check"></i><b>5.1.2</b> Probability</a></li>
<li class="chapter" data-level="5.1.3" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#disjoint-or-mutually-exclusive-outcomes"><i class="fa fa-check"></i><b>5.1.3</b> Disjoint or mutually exclusive outcomes</a></li>
<li class="chapter" data-level="5.1.4" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilities-when-events-are-not-disjoint"><i class="fa fa-check"></i><b>5.1.4</b> Probabilities when events are not disjoint</a></li>
<li class="chapter" data-level="5.1.5" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-distributions"><i class="fa fa-check"></i><b>5.1.5</b> Probability distributions</a></li>
<li class="chapter" data-level="5.1.6" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#complement-of-an-event"><i class="fa fa-check"></i><b>5.1.6</b> Complement of an event</a></li>
<li class="chapter" data-level="5.1.7" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilityIndependence"><i class="fa fa-check"></i><b>5.1.7</b> Independence</a></li>
<li class="chapter" data-level="5.1.8" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#conditionalProbabilitySection"><i class="fa fa-check"></i><b>5.1.8</b> Conditional probability</a></li>
<li class="chapter" data-level="5.1.9" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#marginalAndJointProbabilities"><i class="fa fa-check"></i><b>5.1.9</b> Marginal and joint probabilities</a></li>
<li class="chapter" data-level="5.1.10" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#defining-conditional-probability"><i class="fa fa-check"></i><b>5.1.10</b> Defining conditional probability</a></li>
<li class="chapter" data-level="5.1.11" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#smallpox-in-boston-1721"><i class="fa fa-check"></i><b>5.1.11</b> Smallpox in Boston, 1721</a></li>
<li class="chapter" data-level="5.1.12" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#general-multiplication-rule"><i class="fa fa-check"></i><b>5.1.12</b> General multiplication rule</a></li>
<li class="chapter" data-level="5.1.13" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#tree-diagrams"><i class="fa fa-check"></i><b>5.1.13</b> Tree diagrams</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html"><i class="fa fa-check"></i><b>5.2</b> Random variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#expectation"><i class="fa fa-check"></i><b>5.2.1</b> Expectation</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Variability in random variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.3</b> Linear combinations of random variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.4</b> Variability in linear combinations of random variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>5.3</b> Statistical Background</a><ul>
<li class="chapter" data-level="5.3.1" data-path="appendixA.html"><a href="appendixA.html#appendix-stat-terms"><i class="fa fa-check"></i><b>5.3.1</b> Basic statistical terms</a></li>
<li class="chapter" data-level="5.3.2" data-path="appendixA.html"><a href="appendixA.html#appendix-normal-curve"><i class="fa fa-check"></i><b>5.3.2</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bayess-theorem.html"><a href="bayess-theorem.html"><i class="fa fa-check"></i><b>5.4</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.5" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>5.5</b> Conditional probability</a></li>
<li class="chapter" data-level="5.6" data-path="conjoint-probability.html"><a href="conjoint-probability.html"><i class="fa fa-check"></i><b>5.6</b> Conjoint probability</a></li>
<li class="chapter" data-level="5.7" data-path="the-cookie-problem.html"><a href="the-cookie-problem.html"><i class="fa fa-check"></i><b>5.7</b> The cookie problem</a></li>
<li class="chapter" data-level="5.8" data-path="bayess-theorem-1.html"><a href="bayess-theorem-1.html"><i class="fa fa-check"></i><b>5.8</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.9" data-path="the-diachronic-interpretation.html"><a href="the-diachronic-interpretation.html"><i class="fa fa-check"></i><b>5.9</b> The diachronic interpretation</a></li>
<li class="chapter" data-level="5.10" data-path="the-mm-problem.html"><a href="the-mm-problem.html"><i class="fa fa-check"></i><b>5.10</b> The M&amp;M problem</a></li>
<li class="chapter" data-level="5.11" data-path="the-monty-hall-problem.html"><a href="the-monty-hall-problem.html"><i class="fa fa-check"></i><b>5.11</b> The Monty Hall problem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling</a><ul>
<li class="chapter" data-level="" data-path="sampling.html"><a href="sampling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="sampling-activity.html"><a href="sampling-activity.html"><i class="fa fa-check"></i><b>6.1</b> Sampling urn activity</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sampling-activity.html"><a href="sampling-activity.html#what-proportion-of-this-urns-balls-are-red"><i class="fa fa-check"></i><b>6.1.1</b> What proportion of this urn’s balls are red?</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling-activity.html"><a href="sampling-activity.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling-activity.html"><a href="sampling-activity.html#student-shovels"><i class="fa fa-check"></i><b>6.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling-activity.html"><a href="sampling-activity.html#what-did-we-just-do"><i class="fa fa-check"></i><b>6.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html"><i class="fa fa-check"></i><b>6.2</b> Virtual sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-simulation.html"><a href="sampling-simulation.html#shovel-1000-times"><i class="fa fa-check"></i><b>6.2.3</b> Using the virtual shovel 1,000 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-simulation.html"><a href="sampling-simulation.html#different-shovels"><i class="fa fa-check"></i><b>6.2.4</b> Using different shovels</a></li>
<li class="chapter" data-level="6.2.5" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-many-shovels-at-once"><i class="fa fa-check"></i><b>6.2.5</b> Using many shovels at once</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-framework.html"><a href="sampling-framework.html"><i class="fa fa-check"></i><b>6.3</b> Sampling framework</a><ul>
<li class="chapter" data-level="6.3.1" data-path="sampling-framework.html"><a href="sampling-framework.html#terminology-and-notation"><i class="fa fa-check"></i><b>6.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="6.3.2" data-path="sampling-framework.html"><a href="sampling-framework.html#sampling-definitions"><i class="fa fa-check"></i><b>6.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="6.3.3" data-path="sampling-framework.html"><a href="sampling-framework.html#moral-of-the-story"><i class="fa fa-check"></i><b>6.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sampling-case-study.html"><a href="sampling-case-study.html"><i class="fa fa-check"></i><b>6.4</b> Case study: Polls</a><ul>
<li class="chapter" data-level="6.4.1" data-path="sampling-case-study.html"><a href="sampling-case-study.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>6.4.1</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="conclusion-5.html"><a href="conclusion-5.html"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> One Parameter</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html"><i class="fa fa-check"></i><b>7.1</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.1.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.1.2" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-once"><i class="fa fa-check"></i><b>7.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.1.3" data-path="resampling-tactile.html"><a href="resampling-tactile.html#student-resamples"><i class="fa fa-check"></i><b>7.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.1.4" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-did-we-just-do-1"><i class="fa fa-check"></i><b>7.1.4</b> What did we just do?</a></li>
<li class="chapter" data-level="7.1.5" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-simulation"><i class="fa fa-check"></i><b>7.1.5</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.1.6" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>7.1.6</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.1.7" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.1.7</b> Virtually resampling 1,000 times</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ci-build-up.html"><a href="ci-build-up.html"><i class="fa fa-check"></i><b>7.2</b> Measuring uncertainty with confidence intervals</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ci-build-up.html"><a href="ci-build-up.html#percentile-method"><i class="fa fa-check"></i><b>7.2.1</b> Percentile method</a></li>
<li class="chapter" data-level="7.2.2" data-path="ci-build-up.html"><a href="ci-build-up.html#se-method"><i class="fa fa-check"></i><b>7.2.2</b> Standard error method</a></li>
<li class="chapter" data-level="7.2.3" data-path="ci-build-up.html"><a href="ci-build-up.html#one-prop-ci"><i class="fa fa-check"></i><b>7.2.3</b> Interpreting confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ci-width.html"><a href="ci-width.html"><i class="fa fa-check"></i><b>7.3</b> Width of confidence intervals</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ci-width.html"><a href="ci-width.html#impact-of-confidence-level"><i class="fa fa-check"></i><b>7.3.1</b> Impact of confidence level</a></li>
<li class="chapter" data-level="7.3.2" data-path="ci-width.html"><a href="ci-width.html#fitting-multiple-models-using-map"><i class="fa fa-check"></i><b>7.3.2</b> Fitting multiple models using <code>map()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="ci-width.html"><a href="ci-width.html#impact-of-sample-size"><i class="fa fa-check"></i><b>7.3.3</b> Impact of sample size</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-lm-and-tidy-as-a-shortcut.html"><a href="using-lm-and-tidy-as-a-shortcut.html"><i class="fa fa-check"></i><b>7.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html"><i class="fa fa-check"></i><b>7.5</b> Case study: Is yawning contagious?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#mythbusters-study-data"><i class="fa fa-check"></i><b>7.5.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#sampling-scenario"><i class="fa fa-check"></i><b>7.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="7.5.3" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#ci-build"><i class="fa fa-check"></i><b>7.5.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="7.5.4" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#using-lm-and-tidy-as-a-shortcut-1"><i class="fa fa-check"></i><b>7.5.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ci-conclusion.html"><a href="ci-conclusion.html"><i class="fa fa-check"></i><b>7.6</b> Conclusion</a><ul>
<li class="chapter" data-level="7.6.1" data-path="ci-conclusion.html"><a href="ci-conclusion.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>7.6.1</b> Comparing bootstrap and sampling distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="two-parameters.html"><a href="two-parameters.html"><i class="fa fa-check"></i><b>8</b> Two Parameters</a></li>
<li class="chapter" data-level="" data-path="part-iii.html"><a href="part-iii.html"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="9" data-path="n-parameters.html"><a href="n-parameters.html"><i class="fa fa-check"></i><b>9</b> N Parameters</a></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Continuous Response I</a><ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="10.1" data-path="model1.html"><a href="model1.html"><i class="fa fa-check"></i><b>10.1</b> Teaching evaluations: one numerical explanatory variable</a><ul>
<li class="chapter" data-level="10.1.1" data-path="model1.html"><a href="model1.html#model1EDA"><i class="fa fa-check"></i><b>10.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.1.2" data-path="model1.html"><a href="model1.html#model1table"><i class="fa fa-check"></i><b>10.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="model1.html"><a href="model1.html#interpreting-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Interpreting regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html"><i class="fa fa-check"></i><b>10.2</b> Uncertainty in simple linear regressions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#using-lm-and-tidy-as-a-shortcut-2"><i class="fa fa-check"></i><b>10.2.1</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#model1points"><i class="fa fa-check"></i><b>10.2.2</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="model2.html"><a href="model2.html"><i class="fa fa-check"></i><b>10.3</b> Life expectancy: one categorical explanatory variable</a><ul>
<li class="chapter" data-level="10.3.1" data-path="model2.html"><a href="model2.html#model2EDA"><i class="fa fa-check"></i><b>10.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="model2.html"><a href="model2.html#model2table"><i class="fa fa-check"></i><b>10.3.2</b> Linear regression</a></li>
<li class="chapter" data-level="10.3.3" data-path="model2.html"><a href="model2.html#model2points"><i class="fa fa-check"></i><b>10.3.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html"><i class="fa fa-check"></i><b>10.4</b> Case study: 2018 gubernatorial forecasts</a><ul>
<li class="chapter" data-level="10.4.1" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html#fitting-multiple-models-using-map-1"><i class="fa fa-check"></i><b>10.4.1</b> Fitting multiple models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="leastsquares.html"><a href="leastsquares.html"><i class="fa fa-check"></i><b>10.5</b> Appendix: Best-fitting line</a></li>
<li class="chapter" data-level="10.6" data-path="conclusion-6.html"><a href="conclusion-6.html"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>11</b> Continuous Response II</a><ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="11.1" data-path="model4.html"><a href="model4.html"><i class="fa fa-check"></i><b>11.1</b> Teaching evaluations revisited: one numerical and one categorical explanatory variable</a><ul>
<li class="chapter" data-level="11.1.1" data-path="model4.html"><a href="model4.html#model4EDA"><i class="fa fa-check"></i><b>11.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.1.2" data-path="model4.html"><a href="model4.html#model4interactiontable"><i class="fa fa-check"></i><b>11.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="11.1.3" data-path="model4.html"><a href="model4.html#interpreting-regression-coefficients-with-interactions"><i class="fa fa-check"></i><b>11.1.3</b> Interpreting regression coefficients with interactions</a></li>
<li class="chapter" data-level="11.1.4" data-path="model4.html"><a href="model4.html#model4table"><i class="fa fa-check"></i><b>11.1.4</b> Parallel slopes model</a></li>
<li class="chapter" data-level="11.1.5" data-path="model4.html"><a href="model4.html#model4points"><i class="fa fa-check"></i><b>11.1.5</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="model3.html"><a href="model3.html"><i class="fa fa-check"></i><b>11.2</b> Credit card debt: two numerical explanatory variables</a><ul>
<li class="chapter" data-level="11.2.1" data-path="model3.html"><a href="model3.html#model3EDA"><i class="fa fa-check"></i><b>11.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.2.2" data-path="model3.html"><a href="model3.html#model3table"><i class="fa fa-check"></i><b>11.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="11.2.3" data-path="model3.html"><a href="model3.html#model3points"><i class="fa fa-check"></i><b>11.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html"><i class="fa fa-check"></i><b>11.3</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="11.3.1" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>11.3.1</b> Exploratory data analysis: Part I</a></li>
<li class="chapter" data-level="11.3.2" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-II"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory data analysis: Part II</a></li>
<li class="chapter" data-level="11.3.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-regression"><i class="fa fa-check"></i><b>11.3.3</b> Regression modeling</a></li>
<li class="chapter" data-level="11.3.4" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>11.3.4</b> Making predictions</a></li>
<li class="chapter" data-level="11.3.5" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#fitting-many-models-using-map"><i class="fa fa-check"></i><b>11.3.5</b> Fitting many models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="other-topics.html"><a href="other-topics.html"><i class="fa fa-check"></i><b>11.4</b> Other topics</a><ul>
<li class="chapter" data-level="11.4.1" data-path="other-topics.html"><a href="other-topics.html#model-selection"><i class="fa fa-check"></i><b>11.4.1</b> Model selection</a></li>
<li class="chapter" data-level="11.4.2" data-path="other-topics.html"><a href="other-topics.html#correlationcoefficient2"><i class="fa fa-check"></i><b>11.4.2</b> Correlation coefficient</a></li>
<li class="chapter" data-level="11.4.3" data-path="other-topics.html"><a href="other-topics.html#simpsonsparadox"><i class="fa fa-check"></i><b>11.4.3</b> Simpson’s Paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>12</b> Discrete Response</a><ul>
<li class="chapter" data-level="" data-path="classification.html"><a href="classification.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> What is logistic regression?</a></li>
<li class="chapter" data-level="12.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#house-elections-exploratory-data-analysis"><i class="fa fa-check"></i><b>12.1.2</b> House elections: exploratory data analysis</a></li>
<li class="chapter" data-level="12.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.3</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.4" data-path="logistic-regression.html"><a href="logistic-regression.html#observedfitted-values-and-residuals"><i class="fa fa-check"></i><b>12.1.4</b> Observed/fitted values and residuals</a></li>
<li class="chapter" data-level="12.1.5" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.5</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.1.6" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-and-one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.6</b> One numerical and one categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.7" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-many-models-using-map-1"><i class="fa fa-check"></i><b>12.1.7</b> Fitting many models using <code>map()</code></a></li>
<li class="chapter" data-level="12.1.8" data-path="logistic-regression.html"><a href="logistic-regression.html#professional-models"><i class="fa fa-check"></i><b>12.1.8</b> Professional models</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html"><i class="fa fa-check"></i><b>12.2</b> Classification and regression trees (CART)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#what-is-cart"><i class="fa fa-check"></i><b>12.2.1</b> What is CART?</a></li>
<li class="chapter" data-level="12.2.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-categorical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.2</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.2.3" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-numerical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.3</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.2.4" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#multiple-explanatory-variables"><i class="fa fa-check"></i><b>12.2.4</b> Multiple explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>12.3</b> Random forests</a><ul>
<li class="chapter" data-level="12.3.1" data-path="random-forests.html"><a href="random-forests.html#what-are-random-forests"><i class="fa fa-check"></i><b>12.3.1</b> What are random forests?</a></li>
<li class="chapter" data-level="12.3.2" data-path="random-forests.html"><a href="random-forests.html#fitting-random-forests"><i class="fa fa-check"></i><b>12.3.2</b> Fitting random forests</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html"><i class="fa fa-check"></i><b>12.4</b> Comparing the three approaches</a><ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#is-accuracy-the-right-measure"><i class="fa fa-check"></i><b>12.4.1</b> Is accuracy the right measure?</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#modeling-for-prediction-vs.-explanation"><i class="fa fa-check"></i><b>12.4.2</b> Modeling for prediction vs. explanation</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#out-of-sample-predictions"><i class="fa fa-check"></i><b>12.4.3</b> Out-of-sample predictions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="productivity.html"><a href="productivity.html"><i class="fa fa-check"></i><b>A</b> Productivity</a><ul>
<li class="chapter" data-level="A.1" data-path="set-up.html"><a href="set-up.html"><i class="fa fa-check"></i><b>A.1</b> Set Up</a><ul>
<li class="chapter" data-level="A.1.1" data-path="set-up.html"><a href="set-up.html#terminal-on-mac"><i class="fa fa-check"></i><b>A.1.1</b> Accessing the terminal on a Mac</a></li>
<li class="chapter" data-level="A.1.2" data-path="set-up.html"><a href="set-up.html#installing-git-on-the-mac"><i class="fa fa-check"></i><b>A.1.2</b> Installing Git on the Mac</a></li>
<li class="chapter" data-level="A.1.3" data-path="set-up.html"><a href="set-up.html#installing-git-and-git-bash-on-windows"><i class="fa fa-check"></i><b>A.1.3</b> Installing Git and Git Bash on Windows</a></li>
<li class="chapter" data-level="A.1.4" data-path="set-up.html"><a href="set-up.html#terminal-on-windows"><i class="fa fa-check"></i><b>A.1.4</b> Accessing the terminal on Windows</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i><b>A.2</b> Organizing with Unix</a><ul>
<li class="chapter" data-level="A.2.1" data-path="unix.html"><a href="unix.html#naming-convention"><i class="fa fa-check"></i><b>A.2.1</b> Naming convention</a></li>
<li class="chapter" data-level="A.2.2" data-path="unix.html"><a href="unix.html#the-terminal"><i class="fa fa-check"></i><b>A.2.2</b> The terminal</a></li>
<li class="chapter" data-level="A.2.3" data-path="unix.html"><a href="unix.html#filesystem"><i class="fa fa-check"></i><b>A.2.3</b> The filesystem</a></li>
<li class="chapter" data-level="A.2.4" data-path="unix.html"><a href="unix.html#directories-and-subdirectories"><i class="fa fa-check"></i><b>A.2.4</b> Directories and subdirectories</a></li>
<li class="chapter" data-level="A.2.5" data-path="unix.html"><a href="unix.html#the-home-directory"><i class="fa fa-check"></i><b>A.2.5</b> The home directory</a></li>
<li class="chapter" data-level="A.2.6" data-path="unix.html"><a href="unix.html#working-directory"><i class="fa fa-check"></i><b>A.2.6</b> Working directory</a></li>
<li class="chapter" data-level="A.2.7" data-path="unix.html"><a href="unix.html#paths"><i class="fa fa-check"></i><b>A.2.7</b> Paths</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="unix-commands.html"><a href="unix-commands.html"><i class="fa fa-check"></i><b>A.3</b> Unix commands</a><ul>
<li class="chapter" data-level="A.3.1" data-path="unix-commands.html"><a href="unix-commands.html#ls-listing-directory-content"><i class="fa fa-check"></i><b>A.3.1</b> <code>ls</code>: Listing directory content</a></li>
<li class="chapter" data-level="A.3.2" data-path="unix-commands.html"><a href="unix-commands.html#mkdir-and-rmdir-make-and-remove-a-directory"><i class="fa fa-check"></i><b>A.3.2</b> <code>mkdir</code> and <code>rmdir</code>: make and remove a directory</a></li>
<li class="chapter" data-level="A.3.3" data-path="unix-commands.html"><a href="unix-commands.html#cd-navigating-the-filesystem-by-changing-directories"><i class="fa fa-check"></i><b>A.3.3</b> <code>cd</code>: navigating the filesystem by changing directories</a></li>
<li class="chapter" data-level="A.3.4" data-path="unix-commands.html"><a href="unix-commands.html#some-examples"><i class="fa fa-check"></i><b>A.3.4</b> Some examples</a></li>
<li class="chapter" data-level="A.3.5" data-path="unix-commands.html"><a href="unix-commands.html#more-unix-commands"><i class="fa fa-check"></i><b>A.3.5</b> More Unix commands</a></li>
<li class="chapter" data-level="A.3.6" data-path="unix-commands.html"><a href="unix-commands.html#advanced-unix"><i class="fa fa-check"></i><b>A.3.6</b> Advanced Unix</a></li>
<li class="chapter" data-level="A.3.7" data-path="unix-commands.html"><a href="unix-commands.html#file-manipulation-in-r"><i class="fa fa-check"></i><b>A.3.7</b> File manipulation in R</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="git.html"><a href="git.html"><i class="fa fa-check"></i><b>A.4</b> Git and GitHub</a><ul>
<li class="chapter" data-level="A.4.1" data-path="git.html"><a href="git.html#github-accounts"><i class="fa fa-check"></i><b>A.4.1</b> GitHub accounts</a></li>
<li class="chapter" data-level="A.4.2" data-path="git.html"><a href="git.html#github-repos"><i class="fa fa-check"></i><b>A.4.2</b> GitHub repositories</a></li>
<li class="chapter" data-level="A.4.3" data-path="git.html"><a href="git.html#git-overview"><i class="fa fa-check"></i><b>A.4.3</b> Overview of Git</a></li>
<li class="chapter" data-level="A.4.4" data-path="git.html"><a href="git.html#rstudio-git"><i class="fa fa-check"></i><b>A.4.4</b> Using Git and GitHub in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>A.5</b> R</a><ul>
<li class="chapter" data-level="A.5.1" data-path="r.html"><a href="r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.5.1</b> RStudio projects</a></li>
<li class="chapter" data-level="A.5.2" data-path="r.html"><a href="r.html#r-markdown"><i class="fa fa-check"></i><b>A.5.2</b> R markdown</a></li>
<li class="chapter" data-level="A.5.3" data-path="r.html"><a href="r.html#help-for-r"><i class="fa fa-check"></i><b>A.5.3</b> Help for R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>B</b> Getting Help</a><ul>
<li class="chapter" data-level="B.1" data-path="searching-for-help-with-r-1.html"><a href="searching-for-help-with-r-1.html"><i class="fa fa-check"></i><b>B.1</b> Searching for Help with R</a></li>
<li class="chapter" data-level="B.2" data-path="reproducible-examples-1.html"><a href="reproducible-examples-1.html"><i class="fa fa-check"></i><b>B.2</b> Reproducible Examples</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>C</b> Shiny</a><ul>
<li class="chapter" data-level="C.1" data-path="helpful-resources.html"><a href="helpful-resources.html"><i class="fa fa-check"></i><b>C.1</b> Helpful Resources</a></li>
<li class="chapter" data-level="C.2" data-path="set-up-and-getting-started.html"><a href="set-up-and-getting-started.html"><i class="fa fa-check"></i><b>C.2</b> Set Up and Getting Started</a></li>
<li class="chapter" data-level="C.3" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html"><i class="fa fa-check"></i><b>C.3</b> Building Your Basic App</a><ul>
<li class="chapter" data-level="C.3.1" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-basic-ui"><i class="fa fa-check"></i><b>C.3.1</b> Setting Up the Basic UI</a></li>
<li class="chapter" data-level="C.3.2" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-server"><i class="fa fa-check"></i><b>C.3.2</b> Setting up the Server</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="organization.html"><a href="organization.html"><i class="fa fa-check"></i><b>C.4</b> Organization</a></li>
<li class="chapter" data-level="C.5" data-path="customizations.html"><a href="customizations.html"><i class="fa fa-check"></i><b>C.5</b> Customizations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="maps.html"><a href="maps.html"><i class="fa fa-check"></i><b>D</b> Maps</a><ul>
<li class="chapter" data-level="D.1" data-path="tidycensus.html"><a href="tidycensus.html"><i class="fa fa-check"></i><b>D.1</b> Tidycensus</a></li>
<li class="chapter" data-level="D.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html"><i class="fa fa-check"></i><b>D.2</b> Conceptual introduction to mapping</a><ul>
<li class="chapter" data-level="D.2.1" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#vector-versus-spatial-data"><i class="fa fa-check"></i><b>D.2.1</b> Vector versus spatial data</a></li>
<li class="chapter" data-level="D.2.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#sf-vs-sp"><i class="fa fa-check"></i><b>D.2.2</b> <strong>sf</strong> vs <strong>sp</strong></a></li>
<li class="chapter" data-level="D.2.3" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#shapefiles"><i class="fa fa-check"></i><b>D.2.3</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html"><i class="fa fa-check"></i><b>D.3</b> Mapping with <strong>tidycensus</strong> and <code>geom_sf()</code></a><ul>
<li class="chapter" data-level="D.3.1" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#making-maps-pretty"><i class="fa fa-check"></i><b>D.3.1</b> Making maps pretty</a></li>
<li class="chapter" data-level="D.3.2" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#adding-back-alaska-and-hawaii"><i class="fa fa-check"></i><b>D.3.2</b> Adding back Alaska and Hawaii</a></li>
</ul></li>
<li class="chapter" data-level="D.4" data-path="faceting-maps.html"><a href="faceting-maps.html"><i class="fa fa-check"></i><b>D.4</b> Faceting maps</a><ul>
<li class="chapter" data-level="D.4.1" data-path="faceting-maps.html"><a href="faceting-maps.html#transforming-and-mapping-the-data"><i class="fa fa-check"></i><b>D.4.1</b> Transforming and mapping the data</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="want-to-explore-further.html"><a href="want-to-explore-further.html"><i class="fa fa-check"></i><b>D.5</b> Want to explore further?</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="animation.html"><a href="animation.html"><i class="fa fa-check"></i><b>E</b> Animation</a><ul>
<li class="chapter" data-level="E.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><i class="fa fa-check"></i><b>E.1</b> gganimate: How to Create Plots with Beautiful Animation in R</a><ul>
<li class="chapter" data-level="E.1.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#prerequisites"><i class="fa fa-check"></i><b>E.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="E.1.2" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#demo-dataset"><i class="fa fa-check"></i><b>E.1.2</b> Demo dataset</a></li>
<li class="chapter" data-level="E.1.3" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#static-plot"><i class="fa fa-check"></i><b>E.1.3</b> Static plot</a></li>
<li class="chapter" data-level="E.1.4" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-through-distinct-states-in-time"><i class="fa fa-check"></i><b>E.1.4</b> Transition through distinct states in time</a></li>
<li class="chapter" data-level="E.1.5" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#reveal-data-along-a-given-dimension"><i class="fa fa-check"></i><b>E.1.5</b> Reveal data along a given dimension</a></li>
<li class="chapter" data-level="E.1.6" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-between-several-distinct-stages-of-the-data"><i class="fa fa-check"></i><b>E.1.6</b> Transition between several distinct stages of the data</a></li>
<li class="chapter" data-level="E.1.7" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#read-more"><i class="fa fa-check"></i><b>E.1.7</b> Read more</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="how-to-save-your-animation.html"><a href="how-to-save-your-animation.html"><i class="fa fa-check"></i><b>E.2</b> How to save your animation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preceptor’s Primer for Bayesian Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nycflights13" class="section level2">
<h2><span class="header-section-number">1.4</span> Explore your first datasets</h2>
<p>Let’s put everything we’ve learned so far into practice and start exploring some real data! Data comes to us in a variety of formats, from pictures to text to numbers. Throughout this book, we’ll focus on datasets that are saved in “spreadsheet”-type format. This is probably the most common way data are collected and saved in many fields. Remember from Subsection <a href="code.html#programming-concepts">1.2.1</a> that these “spreadsheet”-type datasets are called <em>data frames</em> in R.  We’ll focus on working with data saved as data frames throughout this book. Again, “tibble” is the more modern term for “data frame,” but we will use both interchangeably.</p>
<p>Let’s first load all the packages needed for this chapter, assuming you’ve already installed them. Read Section <a href="packages.html#packages">1.3</a> for information on how to install and load R packages if you haven’t already.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="nycflights13.html#cb4-1"></a><span class="kw">library</span>(nycflights13)</span>
<span id="cb4-2"><a href="nycflights13.html#cb4-2"></a><span class="kw">library</span>(dplyr)</span>
<span id="cb4-3"><a href="nycflights13.html#cb4-3"></a><span class="kw">library</span>(knitr)</span></code></pre></div>
<p>At the beginning of all subsequent chapters in this book, we’ll always have a list of packages that you should have installed and loaded in order to work with that chapter’s R code.</p>
<div id="nycflights13-package" class="section level3">
<h3><span class="header-section-number">1.4.1</span> <code>nycflights13</code> package</h3>
<p>Many of us have flown on airplanes or know someone who has. Air travel has become an ever-present aspect of many people’s lives. If you look at the Departures flight information board at an airport, you will frequently see that some flights are delayed for a variety of reasons. Are there ways that we can understand the reasons that cause flight delays?</p>
<p>We’re going to analyze data related to all domestic flights departing from one of New York City’s three main airports in 2013: Newark Liberty International (EWR), John F. Kennedy International (JFK), and LaGuardia Airport (LGA). We’ll access this data using the <code>nycflights13</code>  R package, which contains five datasets saved in five tibbles:</p>
<ul>
<li><code>flights</code>: Information on all 336,776 flights.</li>
<li><code>airlines</code>: A table matching airline names and their two-letter International Air Transport Association (IATA) airline codes (also known as carrier codes) for 16 airline companies. For example, “DL” is the two-letter code for Delta.</li>
<li><code>planes</code>: Information about each of the 3,322 physical aircraft used.</li>
<li><code>weather</code>: Hourly meteorological data for each of the three NYC airports. This data frame has 26,115 rows, roughly corresponding to the <span class="math inline">\(365 \times 24 \times 3 = 26,280\)</span> possible hourly measurements one can observe at three locations over the course of a year.</li>
<li><code>airports</code>: Names, codes, and locations of the 1,458 domestic destinations.</li>
</ul>
</div>
<div id="flights-data-frame" class="section level3">
<h3><span class="header-section-number">1.4.2</span> <code>flights</code> data frame</h3>
<p>We’ll begin by exploring the <code>flights</code> data frame and get an idea of its structure. Run the following code in your console, either by typing it or by cutting-and-pasting it. It displays the contents of the <code>flights</code> data frame in your console. Note that depending on the size of your monitor, the output may vary slightly.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="nycflights13.html#cb5-1"></a>flights</span></code></pre></div>
<pre><code>## # A tibble: 336,776 x 19
##     year month   day dep_time sched_dep_time dep_delay arr_time sched_arr_time
##    &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;          &lt;int&gt;     &lt;dbl&gt;    &lt;int&gt;          &lt;int&gt;
##  1  2013     1     1      517            515         2      830            819
##  2  2013     1     1      533            529         4      850            830
##  3  2013     1     1      542            540         2      923            850
##  4  2013     1     1      544            545        -1     1004           1022
##  5  2013     1     1      554            600        -6      812            837
##  6  2013     1     1      554            558        -4      740            728
##  7  2013     1     1      555            600        -5      913            854
##  8  2013     1     1      557            600        -3      709            723
##  9  2013     1     1      557            600        -3      838            846
## 10  2013     1     1      558            600        -2      753            745
## # … with 336,766 more rows, and 11 more variables: arr_delay &lt;dbl&gt;,
## #   carrier &lt;chr&gt;, flight &lt;int&gt;, tailnum &lt;chr&gt;, origin &lt;chr&gt;, dest &lt;chr&gt;,
## #   air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;, minute &lt;dbl&gt;, time_hour &lt;dttm&gt;</code></pre>
<p>Let’s unpack this output:</p>
<ul>
<li><code>A tibble: 336,776 x 19</code>: A <code>tibble</code> is a specific kind of data frame in R. This particular data frame has
<ul>
<li><code>336,776</code> rows corresponding to different <em>observations</em>. Here, each observation is a flight.</li>
<li><code>19</code> columns corresponding to 19 <em>variables</em> describing each observation.</li>
</ul></li>
<li><code>year</code>, <code>month</code>, <code>day</code>, <code>dep_time</code>, <code>sched_dep_time</code>, <code>dep_delay</code>, and <code>arr_time</code> are the different columns, in other words, the different variables of this dataset.</li>
<li>We then have a preview of the first 10 rows of observations corresponding to the first 10 flights. R is only showing the first 10 rows, because if it showed all <code>336,776</code> rows, it would overwhelm your screen.</li>
<li><code>... with 336,766 more rows, and 11 more variables:</code> indicating to us that 336,766 more rows of data and 11 more variables could not fit in this screen.</li>
</ul>
<p>Unfortunately, this output does not allow us to explore the data very well, but it does give a nice preview. Let’s look at some different ways to explore data frames.</p>
</div>
<div id="exploredataframes" class="section level3">
<h3><span class="header-section-number">1.4.3</span> Exploring data frames</h3>
<p>There are many ways to get a feel for the data contained in a data frame such as <code>flights</code>. We present three functions that take as their “argument” (their input) the data frame in question. We also include a fourth method for exploring one particular column of a data frame:</p>
<ol style="list-style-type: decimal">
<li>Using the <code>View()</code> function, which brings up RStudio’s built-in data viewer.</li>
<li>Using the <code>glimpse()</code> function, which is included in the <code>dplyr</code> package.</li>
<li>Using the <code>kable()</code> function, which is included in the <code>knitr</code> package.</li>
<li>Using the <code>$</code> “extraction operator,” which is used to view a single variable/column in a data frame.</li>
</ol>
<p><strong>1. <code>View()</code></strong>:</p>
<p>Run <code>View(flights)</code>  in your console in RStudio, either by typing it or cutting-and-pasting it into the console pane. Explore this data frame in the resulting pop up viewer. You should get into the habit of viewing any data frames you encounter. Note the uppercase <code>V</code> in <code>View()</code>. R is case-sensitive, so you’ll get an error message if you run <code>view(flights)</code> instead of <code>View(flights)</code>.</p>
<p>By running <code>View(flights)</code>, we can explore the different <em>variables</em> listed in the columns. Observe that there are many different types of variables. Some of the variables like <code>distance</code>, <code>day</code>, and <code>arr_delay</code> are what we will call <em>quantitative</em> variables.  These variables are numerical in nature. Other variables here are  <em>categorical</em>.</p>
<p>Note that if you look in the leftmost column of the <code>View(flights)</code> output, you will see a column of numbers. These are the row numbers of the dataset. If you glance across a row with the same number, say row 5, you can get an idea of what each row is representing. This will allow you to identify what object is being described in a given row by taking note of the values of the columns in that specific row. This is often called the <em>observational unit</em>. The observational unit in this example is an individual flight departing from New York City in 2013. You can identify the observational unit by determining what “thing” is being measured or described by each of the variables. We’ll talk more about observational units in Subsection <a href="nycflights13.html#identification-vs-measurement-variables">1.4.4</a> on <em>identification</em> and <em>measurement</em> variables.</p>
<p><strong>2. <code>glimpse()</code></strong>:</p>
<p>The second way we’ll cover to explore a data frame is using the <code>glimpse()</code> function  included in the  <code>dplyr</code> package. Thus, you can only use the <code>glimpse()</code> function after you’ve loaded the <code>dplyr</code> package by running <code>library(dplyr)</code>. This function provides us with an alternative perspective for exploring a data frame than the <code>View()</code> function:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="nycflights13.html#cb7-1"></a><span class="kw">glimpse</span>(flights)</span></code></pre></div>
<pre><code>## Rows: 336,776
## Columns: 19
## $ year           &lt;int&gt; 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, …
## $ month          &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ day            &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ dep_time       &lt;int&gt; 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558,…
## $ sched_dep_time &lt;int&gt; 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600,…
## $ dep_delay      &lt;dbl&gt; 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -…
## $ arr_time       &lt;int&gt; 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849…
## $ sched_arr_time &lt;int&gt; 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851…
## $ arr_delay      &lt;dbl&gt; 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -…
## $ carrier        &lt;chr&gt; &quot;UA&quot;, &quot;UA&quot;, &quot;AA&quot;, &quot;B6&quot;, &quot;DL&quot;, &quot;UA&quot;, &quot;B6&quot;, &quot;EV&quot;, &quot;B6&quot;, …
## $ flight         &lt;int&gt; 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, …
## $ tailnum        &lt;chr&gt; &quot;N14228&quot;, &quot;N24211&quot;, &quot;N619AA&quot;, &quot;N804JB&quot;, &quot;N668DN&quot;, &quot;N39…
## $ origin         &lt;chr&gt; &quot;EWR&quot;, &quot;LGA&quot;, &quot;JFK&quot;, &quot;JFK&quot;, &quot;LGA&quot;, &quot;EWR&quot;, &quot;EWR&quot;, &quot;LGA&quot;…
## $ dest           &lt;chr&gt; &quot;IAH&quot;, &quot;IAH&quot;, &quot;MIA&quot;, &quot;BQN&quot;, &quot;ATL&quot;, &quot;ORD&quot;, &quot;FLL&quot;, &quot;IAD&quot;…
## $ air_time       &lt;dbl&gt; 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, …
## $ distance       &lt;dbl&gt; 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733,…
## $ hour           &lt;dbl&gt; 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, …
## $ minute         &lt;dbl&gt; 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, …
## $ time_hour      &lt;dttm&gt; 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-01 …</code></pre>
<p>Observe that <code>glimpse()</code> will give you the first few entries of each variable in a row after the variable name. In addition, the <em>data type</em> (see Subsection <a href="code.html#programming-concepts">1.2.1</a>) of the variable is given immediately after each variable’s name inside <code>&lt; &gt;</code>. Here, <code>int</code> and <code>dbl</code> refer to “integer” and “double”, which are computer coding terminology for quantitative/numerical variables. “Doubles” take up twice the size to store on a computer compared to integers.</p>
<p>In contrast, <code>chr</code> refers to “character”, which is computer terminology for text data. In most forms, text data, such as the <code>carrier</code> or <code>origin</code> of a flight, are categorical variables. The <code>time_hour</code> variable is another data type: <code>dttm</code>. These types of variables represent date and time combinations. However, we won’t work with dates and times in this book; we leave this topic for other data science books like <a href="https://ubc-dsci.github.io/introduction-to-datascience/"><em>Introduction to Data Science</em> by Tiffany-Anne Timbers, Melissa Lee, and Trevor Campbell</a> or <a href="https://r4ds.had.co.nz/dates-and-times.html"><em>R for Data Science</em></a> <span class="citation">(Grolemund and Wickham <a href="#ref-rds2016" role="doc-biblioref">2017</a>)</span>.</p>
<p><strong>3. <code>kable()</code></strong>:</p>
<p>The final way to explore the entirety of a data frame is using the <code>kable()</code>  function from the  <code>knitr</code> package. Let’s explore the different carrier codes for all the airlines in our dataset two ways. Run both of these lines of code in the console:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="nycflights13.html#cb9-1"></a>airlines</span>
<span id="cb9-2"><a href="nycflights13.html#cb9-2"></a><span class="kw">kable</span>(airlines)</span></code></pre></div>
<p>At first glance, it may not appear that there is much difference in the outputs. However, when using tools for producing reproducible reports such as <a href="http://rmarkdown.rstudio.com/lesson-1.html">R Markdown</a>, the latter code produces output that is much more legible and reader-friendly. You’ll see us use this reader-friendly style in many places in the book when we want to print a data frame as a nice table.</p>
<p><strong>4. <code>$</code> operator</strong></p>
<p>Lastly, the <code>$</code> operator  allows us to extract and then explore a single variable within a data frame. For example, run the following in your console</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="nycflights13.html#cb10-1"></a>airlines<span class="op">$</span>name</span></code></pre></div>
<p>We used the <code>$</code> operator to extract only the <code>name</code> variable and return it as a vector of length 16. We’ll only be occasionally exploring data frames using the <code>$</code> operator, instead favoring the <code>View()</code> and <code>glimpse()</code> functions.</p>
</div>
<div id="identification-vs-measurement-variables" class="section level3">
<h3><span class="header-section-number">1.4.4</span> Identification and measurement variables</h3>
<p>There is a subtle difference between the kinds of variables that you will encounter in data frames. There are <em>identification variables</em> and <em>measurement variables</em>. For example, let’s explore the <code>airports</code> data frame by showing the output of <code>glimpse(airports)</code>:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="nycflights13.html#cb11-1"></a><span class="kw">glimpse</span>(airports)</span></code></pre></div>
<pre><code>## Rows: 1,458
## Columns: 8
## $ faa   &lt;chr&gt; &quot;04G&quot;, &quot;06A&quot;, &quot;06C&quot;, &quot;06N&quot;, &quot;09J&quot;, &quot;0A9&quot;, &quot;0G6&quot;, &quot;0G7&quot;, &quot;0P2&quot;, …
## $ name  &lt;chr&gt; &quot;Lansdowne Airport&quot;, &quot;Moton Field Municipal Airport&quot;, &quot;Schaumbu…
## $ lat   &lt;dbl&gt; 41.13047, 32.46057, 41.98934, 41.43191, 31.07447, 36.37122, 41.…
## $ lon   &lt;dbl&gt; -80.61958, -85.68003, -88.10124, -74.39156, -81.42778, -82.1734…
## $ alt   &lt;dbl&gt; 1044, 264, 801, 523, 11, 1593, 730, 492, 1000, 108, 409, 875, 1…
## $ tz    &lt;dbl&gt; -5, -6, -6, -5, -5, -5, -5, -5, -5, -8, -5, -6, -5, -5, -5, -5,…
## $ dst   &lt;chr&gt; &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;U&quot;, &quot;A&quot;, &quot;A&quot;, &quot;U&quot;, &quot;A&quot;…
## $ tzone &lt;chr&gt; &quot;America/New_York&quot;, &quot;America/Chicago&quot;, &quot;America/Chicago&quot;, &quot;Amer…</code></pre>
<p>The variables <code>faa</code> and <code>name</code> are what we will call <em>identification variables</em>, variables that uniquely identify each observational unit. In this case, the identification variables uniquely identify airports. Such variables are mainly used in practice to uniquely identify each row in a data frame. <code>faa</code> gives the unique code provided by the FAA for that airport, while the <code>name</code> variable gives the longer official name of the airport. The remaining variables (<code>lat</code>, <code>lon</code>, <code>alt</code>, <code>tz</code>, <code>dst</code>, <code>tzone</code>) are often called <em>measurement</em> or <em>characteristic</em> variables: variables that describe properties of each observational unit. For example, <code>lat</code> and <code>long</code> describe the latitude and longitude of each airport.</p>
<p>Furthermore, sometimes a single variable might not be enough to uniquely identify each observational unit: combinations of variables might be needed. While it is not an absolute rule, for organizational purposes it is considered good practice to have your identification variables in the leftmost columns of your data frame.</p>
</div>
<div id="help-files" class="section level3">
<h3><span class="header-section-number">1.4.5</span> Help files</h3>
<p>Another nice feature of R are help files, which provide documentation for various functions and datasets. You can bring up help files by adding a <code>?</code>  before the name of a function or data frame and then run this in the console. You will then be presented with a page showing the corresponding documentation if it exists. For example, let’s look at the help file for the <code>flights</code> data frame.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="nycflights13.html#cb13-1"></a>?flights</span></code></pre></div>
<p>The help file should pop up in the Help pane of RStudio. If you have questions about a function or data frame included in an R package, you should get in the habit of consulting the help file right away.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-rds2016">
<p>Grolemund, Garrett, and Hadley Wickham. 2017. <em>R for Data Science</em>. First. Sebastopol, CA: O’Reilly Media. <a href="https://r4ds.had.co.nz/">https://r4ds.had.co.nz/</a>.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="packages.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
