<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11.3 Case study: Seattle house prices | Preceptor’s Primer for Bayesian Data Science</title>
  <meta name="description" content="11.3 Case study: Seattle house prices | Preceptor’s Primer for Bayesian Data Science" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="11.3 Case study: Seattle house prices | Preceptor’s Primer for Bayesian Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="davidkane9/PPBDS" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11.3 Case study: Seattle house prices | Preceptor’s Primer for Bayesian Data Science" />
  
  
  

<meta name="author" content="David Kane" />


<meta name="date" content="2020-05-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="model3.html"/>
<link rel="next" href="other-topics.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Cover</a></li>
<li class="chapter" data-level="" data-path="forward.html"><a href="forward.html"><i class="fa fa-check"></i>Forward</a></li>
<li class="chapter" data-level="" data-path="warning.html"><a href="warning.html"><i class="fa fa-check"></i>Warning</a></li>
<li class="chapter" data-level="" data-path="license.html"><a href="license.html"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="acknowledgements.html"><a href="acknowledgements.html"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="dedication.html"><a href="dedication.html"><i class="fa fa-check"></i>Dedication</a></li>
<li class="chapter" data-level="" data-path="part-i.html"><a href="part-i.html"><i class="fa fa-check"></i>Part I</a></li>
<li class="chapter" data-level="1" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>1</b> Visualization</a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio.html"><a href="r-rstudio.html"><i class="fa fa-check"></i><b>1.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="1.1.1" data-path="r-rstudio.html"><a href="r-rstudio.html#installing"><i class="fa fa-check"></i><b>1.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="r-rstudio.html"><a href="r-rstudio.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="code.html"><a href="code.html"><i class="fa fa-check"></i><b>1.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="1.2.1" data-path="code.html"><a href="code.html#programming-concepts"><i class="fa fa-check"></i><b>1.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="1.2.2" data-path="code.html"><a href="code.html#messages"><i class="fa fa-check"></i><b>1.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="1.2.3" data-path="code.html"><a href="code.html#tips-code"><i class="fa fa-check"></i><b>1.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>1.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="1.3.1" data-path="packages.html"><a href="packages.html#package-installation"><i class="fa fa-check"></i><b>1.3.1</b> Package installation</a></li>
<li class="chapter" data-level="1.3.2" data-path="packages.html"><a href="packages.html#package-loading"><i class="fa fa-check"></i><b>1.3.2</b> Package loading</a></li>
<li class="chapter" data-level="1.3.3" data-path="packages.html"><a href="packages.html#package-use"><i class="fa fa-check"></i><b>1.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="nycflights13.html"><a href="nycflights13.html"><i class="fa fa-check"></i><b>1.4</b> Explore your first datasets</a><ul>
<li class="chapter" data-level="1.4.1" data-path="nycflights13.html"><a href="nycflights13.html#nycflights13-package"><i class="fa fa-check"></i><b>1.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="1.4.2" data-path="nycflights13.html"><a href="nycflights13.html#flights-data-frame"><i class="fa fa-check"></i><b>1.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="1.4.3" data-path="nycflights13.html"><a href="nycflights13.html#exploredataframes"><i class="fa fa-check"></i><b>1.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="1.4.4" data-path="nycflights13.html"><a href="nycflights13.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>1.4.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="1.4.5" data-path="nycflights13.html"><a href="nycflights13.html#help-files"><i class="fa fa-check"></i><b>1.4.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>1.5</b> Conclusion</a><ul>
<li class="chapter" data-level="1.5.1" data-path="conclusion.html"><a href="conclusion.html#additional-resources"><i class="fa fa-check"></i><b>1.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="" data-path="conclusion.html"><a href="conclusion.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html"><i class="fa fa-check"></i><b>1.6</b> The grammar of graphics</a><ul>
<li class="chapter" data-level="1.6.1" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#components-of-the-grammar"><i class="fa fa-check"></i><b>1.6.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="1.6.2" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#gapminder"><i class="fa fa-check"></i><b>1.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="1.6.3" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#other-components"><i class="fa fa-check"></i><b>1.6.3</b> Other components</a></li>
<li class="chapter" data-level="1.6.4" data-path="grammarofgraphics.html"><a href="grammarofgraphics.html#ggplot2-package"><i class="fa fa-check"></i><b>1.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>1.7</b> Scatterplots</a><ul>
<li class="chapter" data-level="1.7.1" data-path="scatterplots.html"><a href="scatterplots.html#geompoint"><i class="fa fa-check"></i><b>1.7.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="1.7.2" data-path="scatterplots.html"><a href="scatterplots.html#overplotting"><i class="fa fa-check"></i><b>1.7.2</b> Overplotting</a></li>
<li class="chapter" data-level="1.7.3" data-path="scatterplots.html"><a href="scatterplots.html#summary"><i class="fa fa-check"></i><b>1.7.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="linegraphs.html"><a href="linegraphs.html"><i class="fa fa-check"></i><b>1.8</b> Linegraphs</a><ul>
<li class="chapter" data-level="1.8.1" data-path="linegraphs.html"><a href="linegraphs.html#geomline"><i class="fa fa-check"></i><b>1.8.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="1.8.2" data-path="linegraphs.html"><a href="linegraphs.html#summary-1"><i class="fa fa-check"></i><b>1.8.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="histograms.html"><a href="histograms.html"><i class="fa fa-check"></i><b>1.9</b> Histograms</a><ul>
<li class="chapter" data-level="1.9.1" data-path="histograms.html"><a href="histograms.html#geomhistogram"><i class="fa fa-check"></i><b>1.9.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="1.9.2" data-path="histograms.html"><a href="histograms.html#adjustbins"><i class="fa fa-check"></i><b>1.9.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="1.9.3" data-path="histograms.html"><a href="histograms.html#summary-2"><i class="fa fa-check"></i><b>1.9.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="facets.html"><a href="facets.html"><i class="fa fa-check"></i><b>1.10</b> Facets</a></li>
<li class="chapter" data-level="1.11" data-path="boxplots.html"><a href="boxplots.html"><i class="fa fa-check"></i><b>1.11</b> Boxplots</a><ul>
<li class="chapter" data-level="1.11.1" data-path="boxplots.html"><a href="boxplots.html#geomboxplot"><i class="fa fa-check"></i><b>1.11.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="1.11.2" data-path="boxplots.html"><a href="boxplots.html#summary-3"><i class="fa fa-check"></i><b>1.11.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="geombar.html"><a href="geombar.html"><i class="fa fa-check"></i><b>1.12</b> Barplots</a><ul>
<li class="chapter" data-level="1.12.1" data-path="geombar.html"><a href="geombar.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>1.12.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="1.12.2" data-path="geombar.html"><a href="geombar.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>1.12.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="1.12.3" data-path="geombar.html"><a href="geombar.html#two-categ-barplot"><i class="fa fa-check"></i><b>1.12.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="1.12.4" data-path="geombar.html"><a href="geombar.html#summary-4"><i class="fa fa-check"></i><b>1.12.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.13" data-path="conclusion-1.html"><a href="conclusion-1.html"><i class="fa fa-check"></i><b>1.13</b> Conclusion</a><ul>
<li class="chapter" data-level="1.13.1" data-path="conclusion-1.html"><a href="conclusion-1.html#summary-table"><i class="fa fa-check"></i><b>1.13.1</b> Summary table</a></li>
<li class="chapter" data-level="1.13.2" data-path="conclusion-1.html"><a href="conclusion-1.html#function-argument-specification"><i class="fa fa-check"></i><b>1.13.2</b> Function argument specification</a></li>
<li class="chapter" data-level="1.13.3" data-path="conclusion-1.html"><a href="conclusion-1.html#additional-resources-1"><i class="fa fa-check"></i><b>1.13.3</b> Additional resources</a></li>
<li class="chapter" data-level="1.13.4" data-path="conclusion-1.html"><a href="conclusion-1.html#whats-to-come-3"><i class="fa fa-check"></i><b>1.13.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>2</b> Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="piping.html"><a href="piping.html"><i class="fa fa-check"></i><b>2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="2.2" data-path="filter.html"><a href="filter.html"><i class="fa fa-check"></i><b>2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="2.3" data-path="summarize.html"><a href="summarize.html"><i class="fa fa-check"></i><b>2.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="2.4" data-path="groupby.html"><a href="groupby.html"><i class="fa fa-check"></i><b>2.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="2.4.1" data-path="groupby.html"><a href="groupby.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>2.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="mutate.html"><a href="mutate.html"><i class="fa fa-check"></i><b>2.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="2.6" data-path="arrange.html"><a href="arrange.html"><i class="fa fa-check"></i><b>2.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="2.7" data-path="factors.html"><a href="factors.html"><i class="fa fa-check"></i><b>2.7</b> Factors</a><ul>
<li class="chapter" data-level="2.7.1" data-path="factors.html"><a href="factors.html#the-forcats-package"><i class="fa fa-check"></i><b>2.7.1</b> The <strong>forcats</strong> package</a></li>
<li class="chapter" data-level="2.7.2" data-path="factors.html"><a href="factors.html#dropping-unused-levels"><i class="fa fa-check"></i><b>2.7.2</b> Dropping unused levels</a></li>
<li class="chapter" data-level="2.7.3" data-path="factors.html"><a href="factors.html#reorder-factors"><i class="fa fa-check"></i><b>2.7.3</b> Change order of the levels, principled</a></li>
<li class="chapter" data-level="2.7.4" data-path="factors.html"><a href="factors.html#change-order-of-the-levels-because-i-said-so"><i class="fa fa-check"></i><b>2.7.4</b> Change order of the levels, “because I said so”</a></li>
<li class="chapter" data-level="2.7.5" data-path="factors.html"><a href="factors.html#recode-the-levels"><i class="fa fa-check"></i><b>2.7.5</b> Recode the levels</a></li>
<li class="chapter" data-level="2.7.6" data-path="factors.html"><a href="factors.html#grow-a-factor"><i class="fa fa-check"></i><b>2.7.6</b> Grow a factor</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="character-vectors.html"><a href="character-vectors.html"><i class="fa fa-check"></i><b>2.8</b> Character Vectors</a><ul>
<li class="chapter" data-level="2.8.1" data-path="character-vectors.html"><a href="character-vectors.html#manipulating-character-vectors"><i class="fa fa-check"></i><b>2.8.1</b> Manipulating character vectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-resources"><i class="fa fa-check"></i><b>2.8.2</b> Regular expressions resources</a></li>
<li class="chapter" data-level="2.8.3" data-path="character-vectors.html"><a href="character-vectors.html#character-encoding-resources"><i class="fa fa-check"></i><b>2.8.3</b> Character encoding resources</a></li>
<li class="chapter" data-level="2.8.4" data-path="character-vectors.html"><a href="character-vectors.html#character-vectors-that-live-in-a-data-frame"><i class="fa fa-check"></i><b>2.8.4</b> Character vectors that live in a data frame</a></li>
<li class="chapter" data-level="2.8.5" data-path="character-vectors.html"><a href="character-vectors.html#regex-free-string-manipulation-with-stringr-and-tidyr"><i class="fa fa-check"></i><b>2.8.5</b> Regex-free string manipulation with stringr and tidyr</a></li>
<li class="chapter" data-level="2.8.6" data-path="character-vectors.html"><a href="character-vectors.html#detect-or-filter-on-a-target-string"><i class="fa fa-check"></i><b>2.8.6</b> Detect or filter on a target string</a></li>
<li class="chapter" data-level="2.8.7" data-path="character-vectors.html"><a href="character-vectors.html#string-splitting-by-delimiter"><i class="fa fa-check"></i><b>2.8.7</b> String splitting by delimiter</a></li>
<li class="chapter" data-level="2.8.8" data-path="character-vectors.html"><a href="character-vectors.html#substring-extraction-and-replacement-by-position"><i class="fa fa-check"></i><b>2.8.8</b> Substring extraction (and replacement) by position</a></li>
<li class="chapter" data-level="2.8.9" data-path="character-vectors.html"><a href="character-vectors.html#collapse-a-vector"><i class="fa fa-check"></i><b>2.8.9</b> Collapse a vector</a></li>
<li class="chapter" data-level="2.8.10" data-path="character-vectors.html"><a href="character-vectors.html#catenate-vectors"><i class="fa fa-check"></i><b>2.8.10</b> Create a character vector by catenating multiple vectors</a></li>
<li class="chapter" data-level="2.8.11" data-path="character-vectors.html"><a href="character-vectors.html#substring-replacement"><i class="fa fa-check"></i><b>2.8.11</b> Substring replacement</a></li>
<li class="chapter" data-level="2.8.12" data-path="character-vectors.html"><a href="character-vectors.html#regular-expressions-with-stringr"><i class="fa fa-check"></i><b>2.8.12</b> Regular expressions with stringr</a></li>
<li class="chapter" data-level="2.8.13" data-path="character-vectors.html"><a href="character-vectors.html#characters-with-special-meaning"><i class="fa fa-check"></i><b>2.8.13</b> Characters with special meaning</a></li>
<li class="chapter" data-level="2.8.14" data-path="character-vectors.html"><a href="character-vectors.html#character-classes"><i class="fa fa-check"></i><b>2.8.14</b> Character classes</a></li>
<li class="chapter" data-level="2.8.15" data-path="character-vectors.html"><a href="character-vectors.html#quantifiers"><i class="fa fa-check"></i><b>2.8.15</b> Quantifiers</a></li>
<li class="chapter" data-level="2.8.16" data-path="character-vectors.html"><a href="character-vectors.html#escaping"><i class="fa fa-check"></i><b>2.8.16</b> Escaping</a></li>
<li class="chapter" data-level="2.8.17" data-path="character-vectors.html"><a href="character-vectors.html#groups-and-backreferences"><i class="fa fa-check"></i><b>2.8.17</b> Groups and backreferences</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="combining-data.html"><a href="combining-data.html"><i class="fa fa-check"></i><b>2.9</b> Combining Data</a><ul>
<li class="chapter" data-level="2.9.1" data-path="combining-data.html"><a href="combining-data.html#bind"><i class="fa fa-check"></i><b>2.9.1</b> Bind</a></li>
<li class="chapter" data-level="2.9.2" data-path="combining-data.html"><a href="combining-data.html#joins-in-dplyr"><i class="fa fa-check"></i><b>2.9.2</b> Joins in dplyr</a></li>
<li class="chapter" data-level="2.9.3" data-path="combining-data.html"><a href="combining-data.html#joining"><i class="fa fa-check"></i><b>2.9.3</b> Joining</a></li>
<li class="chapter" data-level="2.9.4" data-path="combining-data.html"><a href="combining-data.html#matching-key-variable-names"><i class="fa fa-check"></i><b>2.9.4</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="2.9.5" data-path="combining-data.html"><a href="combining-data.html#diff-key"><i class="fa fa-check"></i><b>2.9.5</b> Different “key” variable names</a></li>
<li class="chapter" data-level="2.9.6" data-path="combining-data.html"><a href="combining-data.html#multiple-key-variables"><i class="fa fa-check"></i><b>2.9.6</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="2.9.7" data-path="combining-data.html"><a href="combining-data.html#normal-forms"><i class="fa fa-check"></i><b>2.9.7</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="other-verbs.html"><a href="other-verbs.html"><i class="fa fa-check"></i><b>2.10</b> Other Verbs</a><ul>
<li class="chapter" data-level="2.10.1" data-path="other-verbs.html"><a href="other-verbs.html#select"><i class="fa fa-check"></i><b>2.10.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="2.10.2" data-path="other-verbs.html"><a href="other-verbs.html#rename"><i class="fa fa-check"></i><b>2.10.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="2.10.3" data-path="other-verbs.html"><a href="other-verbs.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>2.10.3</b> <code>top_n</code> values of a variable</a></li>
<li class="chapter" data-level="2.10.4" data-path="other-verbs.html"><a href="other-verbs.html#slice-and-pull-and"><i class="fa fa-check"></i><b>2.10.4</b> <code>slice</code> and <code>pull</code> and <code>[]</code></a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="conclusion-2.html"><a href="conclusion-2.html"><i class="fa fa-check"></i><b>2.11</b> Conclusion</a><ul>
<li class="chapter" data-level="2.11.1" data-path="conclusion-2.html"><a href="conclusion-2.html#summary-table-1"><i class="fa fa-check"></i><b>2.11.1</b> Summary table</a></li>
<li class="chapter" data-level="2.11.2" data-path="conclusion-2.html"><a href="conclusion-2.html#additional-resources-2"><i class="fa fa-check"></i><b>2.11.2</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>2.12</b> Tidy</a></li>
<li class="chapter" data-level="2.13" data-path="csv.html"><a href="csv.html"><i class="fa fa-check"></i><b>2.13</b> Importing data</a></li>
<li class="chapter" data-level="2.14" data-path="web-scraping.html"><a href="web-scraping.html"><i class="fa fa-check"></i><b>2.14</b> Web scraping</a><ul>
<li class="chapter" data-level="2.14.1" data-path="web-scraping.html"><a href="web-scraping.html#html"><i class="fa fa-check"></i><b>2.14.1</b> HTML</a></li>
<li class="chapter" data-level="2.14.2" data-path="web-scraping.html"><a href="web-scraping.html#the-rvest-package"><i class="fa fa-check"></i><b>2.14.2</b> The rvest package</a></li>
<li class="chapter" data-level="2.14.3" data-path="web-scraping.html"><a href="web-scraping.html#css-selectors"><i class="fa fa-check"></i><b>2.14.3</b> CSS selectors</a></li>
<li class="chapter" data-level="2.14.4" data-path="web-scraping.html"><a href="web-scraping.html#json"><i class="fa fa-check"></i><b>2.14.4</b> JSON</a></li>
</ul></li>
<li class="chapter" data-level="2.15" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html"><i class="fa fa-check"></i><b>2.15</b> “Tidy” data</a><ul>
<li class="chapter" data-level="2.15.1" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#tidy-definition"><i class="fa fa-check"></i><b>2.15.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="2.15.2" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>2.15.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="2.15.3" data-path="tidy-data-ex.html"><a href="tidy-data-ex.html#nycflights13-package-1"><i class="fa fa-check"></i><b>2.15.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="2.16" data-path="case-study-tidy.html"><a href="case-study-tidy.html"><i class="fa fa-check"></i><b>2.16</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="2.17" data-path="tidyverse-package.html"><a href="tidyverse-package.html"><i class="fa fa-check"></i><b>2.17</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="2.18" data-path="conclusion-3.html"><a href="conclusion-3.html"><i class="fa fa-check"></i><b>2.18</b> Conclusion</a><ul>
<li class="chapter" data-level="2.18.1" data-path="conclusion-3.html"><a href="conclusion-3.html#additional-resources-3"><i class="fa fa-check"></i><b>2.18.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="rubin-causal-model.html"><a href="rubin-causal-model.html"><i class="fa fa-check"></i><b>3</b> Rubin Causal Model</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html"><i class="fa fa-check"></i><b>3.1</b> What is a causal effect?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#everything-is-a-missing-data-problem"><i class="fa fa-check"></i><b>3.1.1</b> Everything is a missing data problem</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#potential-outcomes-introduction-to-the-rubin-table"><i class="fa fa-check"></i><b>3.1.2</b> Potential outcomes: introduction to the Rubin Table</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#estimands"><i class="fa fa-check"></i><b>3.1.3</b> Estimands</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-causal-effect.html"><a href="what-is-a-causal-effect.html#the-infinite-rubin-table-many-kinds-of-missing-data"><i class="fa fa-check"></i><b>3.1.4</b> The infinite Rubin Table: many kinds of missing data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html"><i class="fa fa-check"></i><b>3.2</b> How do we fill in the missing values?</a><ul>
<li class="chapter" data-level="3.2.1" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#average-treatment-effect"><i class="fa fa-check"></i><b>3.2.1</b> Average treatment effect</a></li>
<li class="chapter" data-level="3.2.2" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#the-assignment-mechanism"><i class="fa fa-check"></i><b>3.2.2</b> The assignment mechanism</a></li>
<li class="chapter" data-level="3.2.3" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#uncertainty-and-permutation-tests"><i class="fa fa-check"></i><b>3.2.3</b> Uncertainty and permutation tests</a></li>
<li class="chapter" data-level="3.2.4" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#everything-is-a-missing-data-problem-revisited-internal-and-external-validity"><i class="fa fa-check"></i><b>3.2.4</b> Everything is a missing data problem revisited: Internal and external validity</a></li>
<li class="chapter" data-level="3.2.5" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#more-complex-models-for-causal-inference"><i class="fa fa-check"></i><b>3.2.5</b> More complex models for causal inference</a></li>
<li class="chapter" data-level="3.2.6" data-path="how-do-we-fill-in-the-missing-values.html"><a href="how-do-we-fill-in-the-missing-values.html#causal-inference-and-prediction"><i class="fa fa-check"></i><b>3.2.6</b> Causal inference and prediction</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html"><i class="fa fa-check"></i><b>3.3</b> Other issues with causal inference</a><ul>
<li class="chapter" data-level="3.3.1" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#no-causation-without-manipulation"><i class="fa fa-check"></i><b>3.3.1</b> No causation without manipulation</a></li>
<li class="chapter" data-level="3.3.2" data-path="other-issues-with-causal-inference.html"><a href="other-issues-with-causal-inference.html#stable-unit-treatment-value-assumption-sutva"><i class="fa fa-check"></i><b>3.3.2</b> Stable unit treatment value assumption (SUTVA)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="conclusion-4.html"><a href="conclusion-4.html"><i class="fa fa-check"></i><b>3.4</b> Conclusion</a></li>
<li class="chapter" data-level="3.5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="functions.html"><a href="functions.html"><i class="fa fa-check"></i><b>4</b> Functions</a><ul>
<li class="chapter" data-level="4.1" data-path="part-1.html"><a href="part-1.html"><i class="fa fa-check"></i><b>4.1</b> Part 1</a><ul>
<li class="chapter" data-level="4.1.1" data-path="part-1.html"><a href="part-1.html#get-something-that-works"><i class="fa fa-check"></i><b>4.1.1</b> Get something that works</a></li>
<li class="chapter" data-level="4.1.2" data-path="part-1.html"><a href="part-1.html#skateboard-perfectly-formed-rear-view-mirror"><i class="fa fa-check"></i><b>4.1.2</b> Skateboard &gt;&gt; perfectly formed rear-view mirror</a></li>
<li class="chapter" data-level="4.1.3" data-path="part-1.html"><a href="part-1.html#turn-the-working-interactive-code-into-a-function"><i class="fa fa-check"></i><b>4.1.3</b> Turn the working interactive code into a function</a></li>
<li class="chapter" data-level="4.1.4" data-path="part-1.html"><a href="part-1.html#test-your-function"><i class="fa fa-check"></i><b>4.1.4</b> Test your function</a></li>
<li class="chapter" data-level="4.1.5" data-path="part-1.html"><a href="part-1.html#check-the-validity-of-arguments"><i class="fa fa-check"></i><b>4.1.5</b> Check the validity of arguments</a></li>
<li class="chapter" data-level="4.1.6" data-path="part-1.html"><a href="part-1.html#wrap-up-and-whats-next"><i class="fa fa-check"></i><b>4.1.6</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="part-2.html"><a href="part-2.html"><i class="fa fa-check"></i><b>4.2</b> Part 2</a><ul>
<li class="chapter" data-level="4.2.1" data-path="part-2.html"><a href="part-2.html#load-the-gapminder-data"><i class="fa fa-check"></i><b>4.2.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.2.2" data-path="part-2.html"><a href="part-2.html#restore-our-max-minus-min-function"><i class="fa fa-check"></i><b>4.2.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.2.3" data-path="part-2.html"><a href="part-2.html#generalize-our-function-to-other-quantiles"><i class="fa fa-check"></i><b>4.2.3</b> Generalize our function to other quantiles</a></li>
<li class="chapter" data-level="4.2.4" data-path="part-2.html"><a href="part-2.html#get-something-that-works-again"><i class="fa fa-check"></i><b>4.2.4</b> Get something that works, again</a></li>
<li class="chapter" data-level="4.2.5" data-path="part-2.html"><a href="part-2.html#turn-the-working-interactive-code-into-a-function-again"><i class="fa fa-check"></i><b>4.2.5</b> Turn the working interactive code into a function, again</a></li>
<li class="chapter" data-level="4.2.6" data-path="part-2.html"><a href="part-2.html#argument-names-freedom-and-conventions"><i class="fa fa-check"></i><b>4.2.6</b> Argument names: freedom and conventions</a></li>
<li class="chapter" data-level="4.2.7" data-path="part-2.html"><a href="part-2.html#what-a-function-returns"><i class="fa fa-check"></i><b>4.2.7</b> What a function returns</a></li>
<li class="chapter" data-level="4.2.8" data-path="part-2.html"><a href="part-2.html#default-values-freedom-to-not-specify-the-arguments"><i class="fa fa-check"></i><b>4.2.8</b> Default values: freedom to NOT specify the arguments</a></li>
<li class="chapter" data-level="4.2.9" data-path="part-2.html"><a href="part-2.html#wrap-up-and-whats-next-1"><i class="fa fa-check"></i><b>4.2.9</b> Wrap-up and what’s next?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="part-3.html"><a href="part-3.html"><i class="fa fa-check"></i><b>4.3</b> Part 3</a><ul>
<li class="chapter" data-level="4.3.1" data-path="part-3.html"><a href="part-3.html#load-the-gapminder-data-1"><i class="fa fa-check"></i><b>4.3.1</b> Load the Gapminder data</a></li>
<li class="chapter" data-level="4.3.2" data-path="part-3.html"><a href="part-3.html#restore-our-max-minus-min-function-1"><i class="fa fa-check"></i><b>4.3.2</b> Restore our max minus min function</a></li>
<li class="chapter" data-level="4.3.3" data-path="part-3.html"><a href="part-3.html#be-proactive-about-nas"><i class="fa fa-check"></i><b>4.3.3</b> Be proactive about <code>NA</code>s</a></li>
<li class="chapter" data-level="4.3.4" data-path="part-3.html"><a href="part-3.html#the-useful-but-mysterious-...-argument"><i class="fa fa-check"></i><b>4.3.4</b> The useful but mysterious <code>...</code> argument</a></li>
<li class="chapter" data-level="4.3.5" data-path="part-3.html"><a href="part-3.html#use-testthat-for-formal-unit-tests"><i class="fa fa-check"></i><b>4.3.5</b> Use testthat for formal unit tests</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html"><i class="fa fa-check"></i><b>4.4</b> List columns and <code>map_*</code> functions</a><ul>
<li class="chapter" data-level="4.4.1" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#what-are-list-columns"><i class="fa fa-check"></i><b>4.4.1</b> What are list columns?</a></li>
<li class="chapter" data-level="4.4.2" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#creating-list-columns-with-mutate"><i class="fa fa-check"></i><b>4.4.2</b> Creating list columns with <code>mutate()</code></a></li>
<li class="chapter" data-level="4.4.3" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#map_-functions"><i class="fa fa-check"></i><b>4.4.3</b> <code>map_*</code> functions</a></li>
<li class="chapter" data-level="4.4.4" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#using-map_-functions-to-create-list-columns"><i class="fa fa-check"></i><b>4.4.4</b> Using <code>map_*</code> functions to create list columns</a></li>
<li class="chapter" data-level="4.4.5" data-path="list-columns-and-map-functions.html"><a href="list-columns-and-map-functions.html#practice-with-map_-functions-and-list-columns"><i class="fa fa-check"></i><b>4.4.5</b> Practice with <code>map_*</code> functions and list columns</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="part-ii.html"><a href="part-ii.html"><i class="fa fa-check"></i>Part II</a></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> Probability</a><ul>
<li class="chapter" data-level="5.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html"><i class="fa fa-check"></i><b>5.1</b> Defining probability</a><ul>
<li class="chapter" data-level="5.1.1" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#intro-questions"><i class="fa fa-check"></i><b>5.1.1</b> Intro Questions</a></li>
<li class="chapter" data-level="5.1.2" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-1"><i class="fa fa-check"></i><b>5.1.2</b> Probability</a></li>
<li class="chapter" data-level="5.1.3" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#disjoint-or-mutually-exclusive-outcomes"><i class="fa fa-check"></i><b>5.1.3</b> Disjoint or mutually exclusive outcomes</a></li>
<li class="chapter" data-level="5.1.4" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilities-when-events-are-not-disjoint"><i class="fa fa-check"></i><b>5.1.4</b> Probabilities when events are not disjoint</a></li>
<li class="chapter" data-level="5.1.5" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probability-distributions"><i class="fa fa-check"></i><b>5.1.5</b> Probability distributions</a></li>
<li class="chapter" data-level="5.1.6" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#complement-of-an-event"><i class="fa fa-check"></i><b>5.1.6</b> Complement of an event</a></li>
<li class="chapter" data-level="5.1.7" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#probabilityIndependence"><i class="fa fa-check"></i><b>5.1.7</b> Independence</a></li>
<li class="chapter" data-level="5.1.8" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#conditionalProbabilitySection"><i class="fa fa-check"></i><b>5.1.8</b> Conditional probability</a></li>
<li class="chapter" data-level="5.1.9" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#marginalAndJointProbabilities"><i class="fa fa-check"></i><b>5.1.9</b> Marginal and joint probabilities</a></li>
<li class="chapter" data-level="5.1.10" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#defining-conditional-probability"><i class="fa fa-check"></i><b>5.1.10</b> Defining conditional probability</a></li>
<li class="chapter" data-level="5.1.11" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#smallpox-in-boston-1721"><i class="fa fa-check"></i><b>5.1.11</b> Smallpox in Boston, 1721</a></li>
<li class="chapter" data-level="5.1.12" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#general-multiplication-rule"><i class="fa fa-check"></i><b>5.1.12</b> General multiplication rule</a></li>
<li class="chapter" data-level="5.1.13" data-path="basicsOfProbability.html"><a href="basicsOfProbability.html#tree-diagrams"><i class="fa fa-check"></i><b>5.1.13</b> Tree diagrams</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html"><i class="fa fa-check"></i><b>5.2</b> Random variables</a><ul>
<li class="chapter" data-level="5.2.1" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#expectation"><i class="fa fa-check"></i><b>5.2.1</b> Expectation</a></li>
<li class="chapter" data-level="5.2.2" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-random-variables"><i class="fa fa-check"></i><b>5.2.2</b> Variability in random variables</a></li>
<li class="chapter" data-level="5.2.3" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.3</b> Linear combinations of random variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="randomVariablesSection.html"><a href="randomVariablesSection.html#variability-in-linear-combinations-of-random-variables"><i class="fa fa-check"></i><b>5.2.4</b> Variability in linear combinations of random variables</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>5.3</b> Statistical Background</a><ul>
<li class="chapter" data-level="5.3.1" data-path="appendixA.html"><a href="appendixA.html#appendix-stat-terms"><i class="fa fa-check"></i><b>5.3.1</b> Basic statistical terms</a></li>
<li class="chapter" data-level="5.3.2" data-path="appendixA.html"><a href="appendixA.html#appendix-normal-curve"><i class="fa fa-check"></i><b>5.3.2</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="bayess-theorem.html"><a href="bayess-theorem.html"><i class="fa fa-check"></i><b>5.4</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.5" data-path="conditional-probability.html"><a href="conditional-probability.html"><i class="fa fa-check"></i><b>5.5</b> Conditional probability</a></li>
<li class="chapter" data-level="5.6" data-path="conjoint-probability.html"><a href="conjoint-probability.html"><i class="fa fa-check"></i><b>5.6</b> Conjoint probability</a></li>
<li class="chapter" data-level="5.7" data-path="the-cookie-problem.html"><a href="the-cookie-problem.html"><i class="fa fa-check"></i><b>5.7</b> The cookie problem</a></li>
<li class="chapter" data-level="5.8" data-path="bayess-theorem-1.html"><a href="bayess-theorem-1.html"><i class="fa fa-check"></i><b>5.8</b> Bayes’s Theorem</a></li>
<li class="chapter" data-level="5.9" data-path="the-diachronic-interpretation.html"><a href="the-diachronic-interpretation.html"><i class="fa fa-check"></i><b>5.9</b> The diachronic interpretation</a></li>
<li class="chapter" data-level="5.10" data-path="the-mm-problem.html"><a href="the-mm-problem.html"><i class="fa fa-check"></i><b>5.10</b> The M&amp;M problem</a></li>
<li class="chapter" data-level="5.11" data-path="the-monty-hall-problem.html"><a href="the-monty-hall-problem.html"><i class="fa fa-check"></i><b>5.11</b> The Monty Hall problem</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling</a><ul>
<li class="chapter" data-level="" data-path="sampling.html"><a href="sampling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="sampling-activity.html"><a href="sampling-activity.html"><i class="fa fa-check"></i><b>6.1</b> Sampling urn activity</a><ul>
<li class="chapter" data-level="6.1.1" data-path="sampling-activity.html"><a href="sampling-activity.html#what-proportion-of-this-urns-balls-are-red"><i class="fa fa-check"></i><b>6.1.1</b> What proportion of this urn’s balls are red?</a></li>
<li class="chapter" data-level="6.1.2" data-path="sampling-activity.html"><a href="sampling-activity.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.1.3" data-path="sampling-activity.html"><a href="sampling-activity.html#student-shovels"><i class="fa fa-check"></i><b>6.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.1.4" data-path="sampling-activity.html"><a href="sampling-activity.html#what-did-we-just-do"><i class="fa fa-check"></i><b>6.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html"><i class="fa fa-check"></i><b>6.2</b> Virtual sampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.2.2" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.2.3" data-path="sampling-simulation.html"><a href="sampling-simulation.html#shovel-1000-times"><i class="fa fa-check"></i><b>6.2.3</b> Using the virtual shovel 1,000 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="sampling-simulation.html"><a href="sampling-simulation.html#different-shovels"><i class="fa fa-check"></i><b>6.2.4</b> Using different shovels</a></li>
<li class="chapter" data-level="6.2.5" data-path="sampling-simulation.html"><a href="sampling-simulation.html#using-many-shovels-at-once"><i class="fa fa-check"></i><b>6.2.5</b> Using many shovels at once</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="sampling-framework.html"><a href="sampling-framework.html"><i class="fa fa-check"></i><b>6.3</b> Sampling framework</a><ul>
<li class="chapter" data-level="6.3.1" data-path="sampling-framework.html"><a href="sampling-framework.html#terminology-and-notation"><i class="fa fa-check"></i><b>6.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="6.3.2" data-path="sampling-framework.html"><a href="sampling-framework.html#sampling-definitions"><i class="fa fa-check"></i><b>6.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="6.3.3" data-path="sampling-framework.html"><a href="sampling-framework.html#moral-of-the-story"><i class="fa fa-check"></i><b>6.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sampling-case-study.html"><a href="sampling-case-study.html"><i class="fa fa-check"></i><b>6.4</b> Case study: Polls</a><ul>
<li class="chapter" data-level="6.4.1" data-path="sampling-case-study.html"><a href="sampling-case-study.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>6.4.1</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="conclusion-5.html"><a href="conclusion-5.html"><i class="fa fa-check"></i><b>6.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="confidence-intervals.html"><a href="confidence-intervals.html"><i class="fa fa-check"></i><b>7</b> One Parameter</a><ul>
<li class="chapter" data-level="" data-path="confidence-intervals.html"><a href="confidence-intervals.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="7.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html"><i class="fa fa-check"></i><b>7.1</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.1.1" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.1.2" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-once"><i class="fa fa-check"></i><b>7.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.1.3" data-path="resampling-tactile.html"><a href="resampling-tactile.html#student-resamples"><i class="fa fa-check"></i><b>7.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.1.4" data-path="resampling-tactile.html"><a href="resampling-tactile.html#what-did-we-just-do-1"><i class="fa fa-check"></i><b>7.1.4</b> What did we just do?</a></li>
<li class="chapter" data-level="7.1.5" data-path="resampling-tactile.html"><a href="resampling-tactile.html#resampling-simulation"><i class="fa fa-check"></i><b>7.1.5</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.1.6" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>7.1.6</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.1.7" data-path="resampling-tactile.html"><a href="resampling-tactile.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.1.7</b> Virtually resampling 1,000 times</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ci-build-up.html"><a href="ci-build-up.html"><i class="fa fa-check"></i><b>7.2</b> Measuring uncertainty with confidence intervals</a><ul>
<li class="chapter" data-level="7.2.1" data-path="ci-build-up.html"><a href="ci-build-up.html#percentile-method"><i class="fa fa-check"></i><b>7.2.1</b> Percentile method</a></li>
<li class="chapter" data-level="7.2.2" data-path="ci-build-up.html"><a href="ci-build-up.html#se-method"><i class="fa fa-check"></i><b>7.2.2</b> Standard error method</a></li>
<li class="chapter" data-level="7.2.3" data-path="ci-build-up.html"><a href="ci-build-up.html#one-prop-ci"><i class="fa fa-check"></i><b>7.2.3</b> Interpreting confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ci-width.html"><a href="ci-width.html"><i class="fa fa-check"></i><b>7.3</b> Width of confidence intervals</a><ul>
<li class="chapter" data-level="7.3.1" data-path="ci-width.html"><a href="ci-width.html#impact-of-confidence-level"><i class="fa fa-check"></i><b>7.3.1</b> Impact of confidence level</a></li>
<li class="chapter" data-level="7.3.2" data-path="ci-width.html"><a href="ci-width.html#fitting-multiple-models-using-map"><i class="fa fa-check"></i><b>7.3.2</b> Fitting multiple models using <code>map()</code></a></li>
<li class="chapter" data-level="7.3.3" data-path="ci-width.html"><a href="ci-width.html#impact-of-sample-size"><i class="fa fa-check"></i><b>7.3.3</b> Impact of sample size</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="using-lm-and-tidy-as-a-shortcut.html"><a href="using-lm-and-tidy-as-a-shortcut.html"><i class="fa fa-check"></i><b>7.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="7.5" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html"><i class="fa fa-check"></i><b>7.5</b> Case study: Is yawning contagious?</a><ul>
<li class="chapter" data-level="7.5.1" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#mythbusters-study-data"><i class="fa fa-check"></i><b>7.5.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="7.5.2" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#sampling-scenario"><i class="fa fa-check"></i><b>7.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="7.5.3" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#ci-build"><i class="fa fa-check"></i><b>7.5.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="7.5.4" data-path="case-study-two-prop-ci.html"><a href="case-study-two-prop-ci.html#using-lm-and-tidy-as-a-shortcut-1"><i class="fa fa-check"></i><b>7.5.4</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ci-conclusion.html"><a href="ci-conclusion.html"><i class="fa fa-check"></i><b>7.6</b> Conclusion</a><ul>
<li class="chapter" data-level="7.6.1" data-path="ci-conclusion.html"><a href="ci-conclusion.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>7.6.1</b> Comparing bootstrap and sampling distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="two-parameters.html"><a href="two-parameters.html"><i class="fa fa-check"></i><b>8</b> Two Parameters</a></li>
<li class="chapter" data-level="" data-path="part-iii.html"><a href="part-iii.html"><i class="fa fa-check"></i>Part III</a></li>
<li class="chapter" data-level="9" data-path="n-parameters.html"><a href="n-parameters.html"><i class="fa fa-check"></i><b>9</b> N Parameters</a></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Continuous Response I</a><ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="10.1" data-path="model1.html"><a href="model1.html"><i class="fa fa-check"></i><b>10.1</b> Teaching evaluations: one numerical explanatory variable</a><ul>
<li class="chapter" data-level="10.1.1" data-path="model1.html"><a href="model1.html#model1EDA"><i class="fa fa-check"></i><b>10.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.1.2" data-path="model1.html"><a href="model1.html#model1table"><i class="fa fa-check"></i><b>10.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="10.1.3" data-path="model1.html"><a href="model1.html#interpreting-regression-coefficients"><i class="fa fa-check"></i><b>10.1.3</b> Interpreting regression coefficients</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html"><i class="fa fa-check"></i><b>10.2</b> Uncertainty in simple linear regressions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#using-lm-and-tidy-as-a-shortcut-2"><i class="fa fa-check"></i><b>10.2.1</b> Using <code>lm()</code> and <code>tidy()</code> as a shortcut</a></li>
<li class="chapter" data-level="10.2.2" data-path="uncertainty-in-simple-linear-regressions.html"><a href="uncertainty-in-simple-linear-regressions.html#model1points"><i class="fa fa-check"></i><b>10.2.2</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="model2.html"><a href="model2.html"><i class="fa fa-check"></i><b>10.3</b> Life expectancy: one categorical explanatory variable</a><ul>
<li class="chapter" data-level="10.3.1" data-path="model2.html"><a href="model2.html#model2EDA"><i class="fa fa-check"></i><b>10.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="10.3.2" data-path="model2.html"><a href="model2.html#model2table"><i class="fa fa-check"></i><b>10.3.2</b> Linear regression</a></li>
<li class="chapter" data-level="10.3.3" data-path="model2.html"><a href="model2.html#model2points"><i class="fa fa-check"></i><b>10.3.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html"><i class="fa fa-check"></i><b>10.4</b> Case study: 2018 gubernatorial forecasts</a><ul>
<li class="chapter" data-level="10.4.1" data-path="case-study-2018-gubernatorial-forecasts.html"><a href="case-study-2018-gubernatorial-forecasts.html#fitting-multiple-models-using-map-1"><i class="fa fa-check"></i><b>10.4.1</b> Fitting multiple models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="leastsquares.html"><a href="leastsquares.html"><i class="fa fa-check"></i><b>10.5</b> Appendix: Best-fitting line</a></li>
<li class="chapter" data-level="10.6" data-path="conclusion-6.html"><a href="conclusion-6.html"><i class="fa fa-check"></i><b>10.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="multiple-regression.html"><a href="multiple-regression.html"><i class="fa fa-check"></i><b>11</b> Continuous Response II</a><ul>
<li class="chapter" data-level="" data-path="multiple-regression.html"><a href="multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="11.1" data-path="model4.html"><a href="model4.html"><i class="fa fa-check"></i><b>11.1</b> Teaching evaluations revisited: one numerical and one categorical explanatory variable</a><ul>
<li class="chapter" data-level="11.1.1" data-path="model4.html"><a href="model4.html#model4EDA"><i class="fa fa-check"></i><b>11.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.1.2" data-path="model4.html"><a href="model4.html#model4interactiontable"><i class="fa fa-check"></i><b>11.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="11.1.3" data-path="model4.html"><a href="model4.html#interpreting-regression-coefficients-with-interactions"><i class="fa fa-check"></i><b>11.1.3</b> Interpreting regression coefficients with interactions</a></li>
<li class="chapter" data-level="11.1.4" data-path="model4.html"><a href="model4.html#model4table"><i class="fa fa-check"></i><b>11.1.4</b> Parallel slopes model</a></li>
<li class="chapter" data-level="11.1.5" data-path="model4.html"><a href="model4.html#model4points"><i class="fa fa-check"></i><b>11.1.5</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="model3.html"><a href="model3.html"><i class="fa fa-check"></i><b>11.2</b> Credit card debt: two numerical explanatory variables</a><ul>
<li class="chapter" data-level="11.2.1" data-path="model3.html"><a href="model3.html#model3EDA"><i class="fa fa-check"></i><b>11.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="11.2.2" data-path="model3.html"><a href="model3.html#model3table"><i class="fa fa-check"></i><b>11.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="11.2.3" data-path="model3.html"><a href="model3.html#model3points"><i class="fa fa-check"></i><b>11.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html"><i class="fa fa-check"></i><b>11.3</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="11.3.1" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>11.3.1</b> Exploratory data analysis: Part I</a></li>
<li class="chapter" data-level="11.3.2" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-EDA-II"><i class="fa fa-check"></i><b>11.3.2</b> Exploratory data analysis: Part II</a></li>
<li class="chapter" data-level="11.3.3" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-regression"><i class="fa fa-check"></i><b>11.3.3</b> Regression modeling</a></li>
<li class="chapter" data-level="11.3.4" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>11.3.4</b> Making predictions</a></li>
<li class="chapter" data-level="11.3.5" data-path="seattle-house-prices.html"><a href="seattle-house-prices.html#fitting-many-models-using-map"><i class="fa fa-check"></i><b>11.3.5</b> Fitting many models using <code>map()</code></a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="other-topics.html"><a href="other-topics.html"><i class="fa fa-check"></i><b>11.4</b> Other topics</a><ul>
<li class="chapter" data-level="11.4.1" data-path="other-topics.html"><a href="other-topics.html#model-selection"><i class="fa fa-check"></i><b>11.4.1</b> Model selection</a></li>
<li class="chapter" data-level="11.4.2" data-path="other-topics.html"><a href="other-topics.html#correlationcoefficient2"><i class="fa fa-check"></i><b>11.4.2</b> Correlation coefficient</a></li>
<li class="chapter" data-level="11.4.3" data-path="other-topics.html"><a href="other-topics.html#simpsonsparadox"><i class="fa fa-check"></i><b>11.4.3</b> Simpson’s Paradox</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>12</b> Discrete Response</a><ul>
<li class="chapter" data-level="" data-path="classification.html"><a href="classification.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12.1</b> Logistic regression</a><ul>
<li class="chapter" data-level="12.1.1" data-path="logistic-regression.html"><a href="logistic-regression.html#what-is-logistic-regression"><i class="fa fa-check"></i><b>12.1.1</b> What is logistic regression?</a></li>
<li class="chapter" data-level="12.1.2" data-path="logistic-regression.html"><a href="logistic-regression.html#house-elections-exploratory-data-analysis"><i class="fa fa-check"></i><b>12.1.2</b> House elections: exploratory data analysis</a></li>
<li class="chapter" data-level="12.1.3" data-path="logistic-regression.html"><a href="logistic-regression.html#one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.3</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.4" data-path="logistic-regression.html"><a href="logistic-regression.html#observedfitted-values-and-residuals"><i class="fa fa-check"></i><b>12.1.4</b> Observed/fitted values and residuals</a></li>
<li class="chapter" data-level="12.1.5" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.5</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.1.6" data-path="logistic-regression.html"><a href="logistic-regression.html#one-numerical-and-one-categorical-explanatory-variable"><i class="fa fa-check"></i><b>12.1.6</b> One numerical and one categorical explanatory variable</a></li>
<li class="chapter" data-level="12.1.7" data-path="logistic-regression.html"><a href="logistic-regression.html#fitting-many-models-using-map-1"><i class="fa fa-check"></i><b>12.1.7</b> Fitting many models using <code>map()</code></a></li>
<li class="chapter" data-level="12.1.8" data-path="logistic-regression.html"><a href="logistic-regression.html#professional-models"><i class="fa fa-check"></i><b>12.1.8</b> Professional models</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html"><i class="fa fa-check"></i><b>12.2</b> Classification and regression trees (CART)</a><ul>
<li class="chapter" data-level="12.2.1" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#what-is-cart"><i class="fa fa-check"></i><b>12.2.1</b> What is CART?</a></li>
<li class="chapter" data-level="12.2.2" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-categorical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.2</b> One categorical explanatory variable</a></li>
<li class="chapter" data-level="12.2.3" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#one-numerical-explanatory-variable-1"><i class="fa fa-check"></i><b>12.2.3</b> One numerical explanatory variable</a></li>
<li class="chapter" data-level="12.2.4" data-path="classification-and-regression-trees-cart.html"><a href="classification-and-regression-trees-cart.html#multiple-explanatory-variables"><i class="fa fa-check"></i><b>12.2.4</b> Multiple explanatory variables</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="random-forests.html"><a href="random-forests.html"><i class="fa fa-check"></i><b>12.3</b> Random forests</a><ul>
<li class="chapter" data-level="12.3.1" data-path="random-forests.html"><a href="random-forests.html#what-are-random-forests"><i class="fa fa-check"></i><b>12.3.1</b> What are random forests?</a></li>
<li class="chapter" data-level="12.3.2" data-path="random-forests.html"><a href="random-forests.html#fitting-random-forests"><i class="fa fa-check"></i><b>12.3.2</b> Fitting random forests</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html"><i class="fa fa-check"></i><b>12.4</b> Comparing the three approaches</a><ul>
<li class="chapter" data-level="12.4.1" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#is-accuracy-the-right-measure"><i class="fa fa-check"></i><b>12.4.1</b> Is accuracy the right measure?</a></li>
<li class="chapter" data-level="12.4.2" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#modeling-for-prediction-vs.-explanation"><i class="fa fa-check"></i><b>12.4.2</b> Modeling for prediction vs. explanation</a></li>
<li class="chapter" data-level="12.4.3" data-path="comparing-the-three-approaches.html"><a href="comparing-the-three-approaches.html#out-of-sample-predictions"><i class="fa fa-check"></i><b>12.4.3</b> Out-of-sample predictions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="productivity.html"><a href="productivity.html"><i class="fa fa-check"></i><b>A</b> Productivity</a><ul>
<li class="chapter" data-level="A.1" data-path="set-up.html"><a href="set-up.html"><i class="fa fa-check"></i><b>A.1</b> Set Up</a><ul>
<li class="chapter" data-level="A.1.1" data-path="set-up.html"><a href="set-up.html#terminal-on-mac"><i class="fa fa-check"></i><b>A.1.1</b> Accessing the terminal on a Mac</a></li>
<li class="chapter" data-level="A.1.2" data-path="set-up.html"><a href="set-up.html#installing-git-on-the-mac"><i class="fa fa-check"></i><b>A.1.2</b> Installing Git on the Mac</a></li>
<li class="chapter" data-level="A.1.3" data-path="set-up.html"><a href="set-up.html#installing-git-and-git-bash-on-windows"><i class="fa fa-check"></i><b>A.1.3</b> Installing Git and Git Bash on Windows</a></li>
<li class="chapter" data-level="A.1.4" data-path="set-up.html"><a href="set-up.html#terminal-on-windows"><i class="fa fa-check"></i><b>A.1.4</b> Accessing the terminal on Windows</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="unix.html"><a href="unix.html"><i class="fa fa-check"></i><b>A.2</b> Organizing with Unix</a><ul>
<li class="chapter" data-level="A.2.1" data-path="unix.html"><a href="unix.html#naming-convention"><i class="fa fa-check"></i><b>A.2.1</b> Naming convention</a></li>
<li class="chapter" data-level="A.2.2" data-path="unix.html"><a href="unix.html#the-terminal"><i class="fa fa-check"></i><b>A.2.2</b> The terminal</a></li>
<li class="chapter" data-level="A.2.3" data-path="unix.html"><a href="unix.html#filesystem"><i class="fa fa-check"></i><b>A.2.3</b> The filesystem</a></li>
<li class="chapter" data-level="A.2.4" data-path="unix.html"><a href="unix.html#directories-and-subdirectories"><i class="fa fa-check"></i><b>A.2.4</b> Directories and subdirectories</a></li>
<li class="chapter" data-level="A.2.5" data-path="unix.html"><a href="unix.html#the-home-directory"><i class="fa fa-check"></i><b>A.2.5</b> The home directory</a></li>
<li class="chapter" data-level="A.2.6" data-path="unix.html"><a href="unix.html#working-directory"><i class="fa fa-check"></i><b>A.2.6</b> Working directory</a></li>
<li class="chapter" data-level="A.2.7" data-path="unix.html"><a href="unix.html#paths"><i class="fa fa-check"></i><b>A.2.7</b> Paths</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="unix-commands.html"><a href="unix-commands.html"><i class="fa fa-check"></i><b>A.3</b> Unix commands</a><ul>
<li class="chapter" data-level="A.3.1" data-path="unix-commands.html"><a href="unix-commands.html#ls-listing-directory-content"><i class="fa fa-check"></i><b>A.3.1</b> <code>ls</code>: Listing directory content</a></li>
<li class="chapter" data-level="A.3.2" data-path="unix-commands.html"><a href="unix-commands.html#mkdir-and-rmdir-make-and-remove-a-directory"><i class="fa fa-check"></i><b>A.3.2</b> <code>mkdir</code> and <code>rmdir</code>: make and remove a directory</a></li>
<li class="chapter" data-level="A.3.3" data-path="unix-commands.html"><a href="unix-commands.html#cd-navigating-the-filesystem-by-changing-directories"><i class="fa fa-check"></i><b>A.3.3</b> <code>cd</code>: navigating the filesystem by changing directories</a></li>
<li class="chapter" data-level="A.3.4" data-path="unix-commands.html"><a href="unix-commands.html#some-examples"><i class="fa fa-check"></i><b>A.3.4</b> Some examples</a></li>
<li class="chapter" data-level="A.3.5" data-path="unix-commands.html"><a href="unix-commands.html#more-unix-commands"><i class="fa fa-check"></i><b>A.3.5</b> More Unix commands</a></li>
<li class="chapter" data-level="A.3.6" data-path="unix-commands.html"><a href="unix-commands.html#advanced-unix"><i class="fa fa-check"></i><b>A.3.6</b> Advanced Unix</a></li>
<li class="chapter" data-level="A.3.7" data-path="unix-commands.html"><a href="unix-commands.html#file-manipulation-in-r"><i class="fa fa-check"></i><b>A.3.7</b> File manipulation in R</a></li>
</ul></li>
<li class="chapter" data-level="A.4" data-path="git.html"><a href="git.html"><i class="fa fa-check"></i><b>A.4</b> Git and GitHub</a><ul>
<li class="chapter" data-level="A.4.1" data-path="git.html"><a href="git.html#github-accounts"><i class="fa fa-check"></i><b>A.4.1</b> GitHub accounts</a></li>
<li class="chapter" data-level="A.4.2" data-path="git.html"><a href="git.html#github-repos"><i class="fa fa-check"></i><b>A.4.2</b> GitHub repositories</a></li>
<li class="chapter" data-level="A.4.3" data-path="git.html"><a href="git.html#git-overview"><i class="fa fa-check"></i><b>A.4.3</b> Overview of Git</a></li>
<li class="chapter" data-level="A.4.4" data-path="git.html"><a href="git.html#rstudio-git"><i class="fa fa-check"></i><b>A.4.4</b> Using Git and GitHub in RStudio</a></li>
</ul></li>
<li class="chapter" data-level="A.5" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>A.5</b> R</a><ul>
<li class="chapter" data-level="A.5.1" data-path="r.html"><a href="r.html#rstudio-projects"><i class="fa fa-check"></i><b>A.5.1</b> RStudio projects</a></li>
<li class="chapter" data-level="A.5.2" data-path="r.html"><a href="r.html#r-markdown"><i class="fa fa-check"></i><b>A.5.2</b> R markdown</a></li>
<li class="chapter" data-level="A.5.3" data-path="r.html"><a href="r.html#help-for-r"><i class="fa fa-check"></i><b>A.5.3</b> Help for R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="B" data-path="getting-help.html"><a href="getting-help.html"><i class="fa fa-check"></i><b>B</b> Getting Help</a><ul>
<li class="chapter" data-level="B.1" data-path="searching-for-help-with-r-1.html"><a href="searching-for-help-with-r-1.html"><i class="fa fa-check"></i><b>B.1</b> Searching for Help with R</a></li>
<li class="chapter" data-level="B.2" data-path="reproducible-examples-1.html"><a href="reproducible-examples-1.html"><i class="fa fa-check"></i><b>B.2</b> Reproducible Examples</a></li>
</ul></li>
<li class="chapter" data-level="C" data-path="shiny.html"><a href="shiny.html"><i class="fa fa-check"></i><b>C</b> Shiny</a><ul>
<li class="chapter" data-level="C.1" data-path="helpful-resources.html"><a href="helpful-resources.html"><i class="fa fa-check"></i><b>C.1</b> Helpful Resources</a></li>
<li class="chapter" data-level="C.2" data-path="set-up-and-getting-started.html"><a href="set-up-and-getting-started.html"><i class="fa fa-check"></i><b>C.2</b> Set Up and Getting Started</a></li>
<li class="chapter" data-level="C.3" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html"><i class="fa fa-check"></i><b>C.3</b> Building Your Basic App</a><ul>
<li class="chapter" data-level="C.3.1" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-basic-ui"><i class="fa fa-check"></i><b>C.3.1</b> Setting Up the Basic UI</a></li>
<li class="chapter" data-level="C.3.2" data-path="building-your-basic-app.html"><a href="building-your-basic-app.html#setting-up-the-server"><i class="fa fa-check"></i><b>C.3.2</b> Setting up the Server</a></li>
</ul></li>
<li class="chapter" data-level="C.4" data-path="organization.html"><a href="organization.html"><i class="fa fa-check"></i><b>C.4</b> Organization</a></li>
<li class="chapter" data-level="C.5" data-path="customizations.html"><a href="customizations.html"><i class="fa fa-check"></i><b>C.5</b> Customizations</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="maps.html"><a href="maps.html"><i class="fa fa-check"></i><b>D</b> Maps</a><ul>
<li class="chapter" data-level="D.1" data-path="tidycensus.html"><a href="tidycensus.html"><i class="fa fa-check"></i><b>D.1</b> Tidycensus</a></li>
<li class="chapter" data-level="D.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html"><i class="fa fa-check"></i><b>D.2</b> Conceptual introduction to mapping</a><ul>
<li class="chapter" data-level="D.2.1" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#vector-versus-spatial-data"><i class="fa fa-check"></i><b>D.2.1</b> Vector versus spatial data</a></li>
<li class="chapter" data-level="D.2.2" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#sf-vs-sp"><i class="fa fa-check"></i><b>D.2.2</b> <strong>sf</strong> vs <strong>sp</strong></a></li>
<li class="chapter" data-level="D.2.3" data-path="conceptual-introduction-to-mapping.html"><a href="conceptual-introduction-to-mapping.html#shapefiles"><i class="fa fa-check"></i><b>D.2.3</b> Shapefiles</a></li>
</ul></li>
<li class="chapter" data-level="D.3" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html"><i class="fa fa-check"></i><b>D.3</b> Mapping with <strong>tidycensus</strong> and <code>geom_sf()</code></a><ul>
<li class="chapter" data-level="D.3.1" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#making-maps-pretty"><i class="fa fa-check"></i><b>D.3.1</b> Making maps pretty</a></li>
<li class="chapter" data-level="D.3.2" data-path="mapping-with-tidycensus-and-geom-sf.html"><a href="mapping-with-tidycensus-and-geom-sf.html#adding-back-alaska-and-hawaii"><i class="fa fa-check"></i><b>D.3.2</b> Adding back Alaska and Hawaii</a></li>
</ul></li>
<li class="chapter" data-level="D.4" data-path="faceting-maps.html"><a href="faceting-maps.html"><i class="fa fa-check"></i><b>D.4</b> Faceting maps</a><ul>
<li class="chapter" data-level="D.4.1" data-path="faceting-maps.html"><a href="faceting-maps.html#transforming-and-mapping-the-data"><i class="fa fa-check"></i><b>D.4.1</b> Transforming and mapping the data</a></li>
</ul></li>
<li class="chapter" data-level="D.5" data-path="want-to-explore-further.html"><a href="want-to-explore-further.html"><i class="fa fa-check"></i><b>D.5</b> Want to explore further?</a></li>
</ul></li>
<li class="chapter" data-level="E" data-path="animation.html"><a href="animation.html"><i class="fa fa-check"></i><b>E</b> Animation</a><ul>
<li class="chapter" data-level="E.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><i class="fa fa-check"></i><b>E.1</b> gganimate: How to Create Plots with Beautiful Animation in R</a><ul>
<li class="chapter" data-level="E.1.1" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#prerequisites"><i class="fa fa-check"></i><b>E.1.1</b> Prerequisites</a></li>
<li class="chapter" data-level="E.1.2" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#demo-dataset"><i class="fa fa-check"></i><b>E.1.2</b> Demo dataset</a></li>
<li class="chapter" data-level="E.1.3" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#static-plot"><i class="fa fa-check"></i><b>E.1.3</b> Static plot</a></li>
<li class="chapter" data-level="E.1.4" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-through-distinct-states-in-time"><i class="fa fa-check"></i><b>E.1.4</b> Transition through distinct states in time</a></li>
<li class="chapter" data-level="E.1.5" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#reveal-data-along-a-given-dimension"><i class="fa fa-check"></i><b>E.1.5</b> Reveal data along a given dimension</a></li>
<li class="chapter" data-level="E.1.6" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#transition-between-several-distinct-stages-of-the-data"><i class="fa fa-check"></i><b>E.1.6</b> Transition between several distinct stages of the data</a></li>
<li class="chapter" data-level="E.1.7" data-path="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html"><a href="gganimate-how-to-create-plots-with-beautiful-animation-in-r.html#read-more"><i class="fa fa-check"></i><b>E.1.7</b> Read more</a></li>
</ul></li>
<li class="chapter" data-level="E.2" data-path="how-to-save-your-animation.html"><a href="how-to-save-your-animation.html"><i class="fa fa-check"></i><b>E.2</b> How to save your animation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Preceptor’s Primer for Bayesian Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="seattle-house-prices" class="section level2">
<h2><span class="header-section-number">11.3</span> Case study: Seattle house prices</h2>
<p><a href="https://www.kaggle.com/">Kaggle.com</a> is a machine learning and predictive modeling competition website that hosts datasets uploaded by companies, governmental organizations, and other individuals. One of their datasets is the <a href="https://www.kaggle.com/harlfoxem/housesalesprediction">“House Sales in King County, USA”</a>. It consists of sale prices of homes sold between May 2014 and May 2015 in King County, Washington, USA, which includes the greater Seattle metropolitan area. This dataset is in the <code>house_prices</code> data frame included in the <strong>moderndive</strong> package.</p>
<p>The dataset consists of 21,613 houses and 21 variables describing these houses (for a full list and description of these variables, see the help file by running <code>?house_prices</code> in the console). In this case study, we’ll create a multiple regression model where:</p>
<ul>
<li>The outcome variable <span class="math inline">\(y\)</span> is the sale <code>price</code> of houses.</li>
<li>Two explanatory variables:
<ol style="list-style-type: decimal">
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>: house size <code>sqft_living</code> as measured in square feet of living space. Note that 1 square foot is about 0.09 square meters.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>: house <code>condition</code>, a categorical variable with five levels where <code>1</code> indicates “poor” and <code>5</code> indicates “excellent.”</li>
</ol></li>
</ul>
<p>Then, we will use <code>map_*</code> functions to run the above model for every year that a house was built.</p>
<div id="house-prices-EDA-I" class="section level3">
<h3><span class="header-section-number">11.3.1</span> Exploratory data analysis: Part I</h3>
<p>As we’ve said numerous times throughout this book, a crucial first step when presented with data is to perform an exploratory data analysis (EDA). Exploratory data analysis can give you a sense of your data, help identify issues with your data, bring to light any outliers, and help inform model construction.</p>
<p>Recall the three common steps in an exploratory data analysis we introduced in Subsection <a href="model1.html#model1EDA">10.1.1</a>:</p>
<ol style="list-style-type: decimal">
<li>Looking at the raw data values.</li>
<li>Computing summary statistics.</li>
<li>Creating data visualizations.</li>
</ol>
<p>First, let’s look at the raw data using <code>View()</code> to bring up RStudio’s spreadsheet viewer and the <code>glimpse()</code> function from the <strong>dplyr</strong> package:</p>
<div class="sourceCode" id="cb778"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb778-1"><a href="seattle-house-prices.html#cb778-1"></a><span class="kw">View</span>(house_prices)</span>
<span id="cb778-2"><a href="seattle-house-prices.html#cb778-2"></a><span class="kw">glimpse</span>(house_prices)</span></code></pre></div>
<pre><code>## Rows: 21,613
## Columns: 21
## $ id            &lt;chr&gt; &quot;7129300520&quot;, &quot;6414100192&quot;, &quot;5631500400&quot;, &quot;2487200875&quot;,…
## $ date          &lt;date&gt; 2014-10-13, 2014-12-09, 2015-02-25, 2014-12-09, 2015-0…
## $ price         &lt;dbl&gt; 221900, 538000, 180000, 604000, 510000, 1225000, 257500…
## $ bedrooms      &lt;int&gt; 3, 3, 2, 4, 3, 4, 3, 3, 3, 3, 3, 2, 3, 3, 5, 4, 3, 4, 2…
## $ bathrooms     &lt;dbl&gt; 1.00, 2.25, 1.00, 3.00, 2.00, 4.50, 2.25, 1.50, 1.00, 2…
## $ sqft_living   &lt;int&gt; 1180, 2570, 770, 1960, 1680, 5420, 1715, 1060, 1780, 18…
## $ sqft_lot      &lt;int&gt; 5650, 7242, 10000, 5000, 8080, 101930, 6819, 9711, 7470…
## $ floors        &lt;dbl&gt; 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 2.0, 1.0, …
## $ waterfront    &lt;lgl&gt; FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,…
## $ view          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0…
## $ condition     &lt;fct&gt; 3, 3, 3, 5, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3, 3, 4, 4…
## $ grade         &lt;fct&gt; 7, 7, 6, 7, 8, 11, 7, 7, 7, 7, 8, 7, 7, 7, 7, 9, 7, 7, …
## $ sqft_above    &lt;int&gt; 1180, 2170, 770, 1050, 1680, 3890, 1715, 1060, 1050, 18…
## $ sqft_basement &lt;int&gt; 0, 400, 0, 910, 0, 1530, 0, 0, 730, 0, 1700, 300, 0, 0,…
## $ yr_built      &lt;int&gt; 1955, 1951, 1933, 1965, 1987, 2001, 1995, 1963, 1960, 2…
## $ yr_renovated  &lt;int&gt; 0, 1991, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ zipcode       &lt;fct&gt; 98178, 98125, 98028, 98136, 98074, 98053, 98003, 98198,…
## $ lat           &lt;dbl&gt; 47.5, 47.7, 47.7, 47.5, 47.6, 47.7, 47.3, 47.4, 47.5, 4…
## $ long          &lt;dbl&gt; -122, -122, -122, -122, -122, -122, -122, -122, -122, -…
## $ sqft_living15 &lt;int&gt; 1340, 1690, 2720, 1360, 1800, 4760, 2238, 1650, 1780, 2…
## $ sqft_lot15    &lt;int&gt; 5650, 7639, 8062, 5000, 7503, 101930, 6819, 9711, 8113,…</code></pre>
<p>Here are some questions you can ask yourself at this stage of an EDA: Which variables are numerical? Which are categorical? For the categorical variables, what are their levels? Besides the variables we’ll be using in our regression model, what other variables do you think would be useful to use in a model for house price?</p>
<p>Observe, for example, that while the <code>condition</code> variable has values <code>1</code> through <code>5</code>, these are saved in R as <code>fct</code> standing for “factors.” This is one of R’s ways of saving categorical variables. So you should think of these as the “labels” <code>1</code> through <code>5</code> and not the numerical values <code>1</code> through <code>5</code>.</p>
<p>Let’s now perform the second step in an EDA: computing summary statistics. Recall from Section <a href="summarize.html#summarize">2.3</a> that <em>summary statistics</em> are single numerical values that summarize a large number of values. Examples of summary statistics include the mean, the median, the standard deviation, and various percentiles.</p>
<p>We could do this using the <code>summarize()</code> function in the <strong>dplyr</strong> package along with R’s built-in <em>summary functions</em>, like <code>mean()</code> and <code>median()</code>. However, recall in Section <a href="mutate.html#mutate">2.5</a>, we saw the following code that computes a variety of summary statistics of the variable <code>gain</code>, which is the amount of time that a flight makes up mid-air:</p>
<div class="sourceCode" id="cb780"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb780-1"><a href="seattle-house-prices.html#cb780-1"></a>gain_summary &lt;-<span class="st"> </span>flights <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb780-2"><a href="seattle-house-prices.html#cb780-2"></a><span class="st">  </span><span class="kw">summarize</span>(</span>
<span id="cb780-3"><a href="seattle-house-prices.html#cb780-3"></a>    <span class="dt">min =</span> <span class="kw">min</span>(gain, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-4"><a href="seattle-house-prices.html#cb780-4"></a>    <span class="dt">q1 =</span> <span class="kw">quantile</span>(gain, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-5"><a href="seattle-house-prices.html#cb780-5"></a>    <span class="dt">median =</span> <span class="kw">quantile</span>(gain, <span class="fl">0.5</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-6"><a href="seattle-house-prices.html#cb780-6"></a>    <span class="dt">q3 =</span> <span class="kw">quantile</span>(gain, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-7"><a href="seattle-house-prices.html#cb780-7"></a>    <span class="dt">max =</span> <span class="kw">max</span>(gain, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-8"><a href="seattle-house-prices.html#cb780-8"></a>    <span class="dt">mean =</span> <span class="kw">mean</span>(gain, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-9"><a href="seattle-house-prices.html#cb780-9"></a>    <span class="dt">sd =</span> <span class="kw">sd</span>(gain, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb780-10"><a href="seattle-house-prices.html#cb780-10"></a>    <span class="dt">missing =</span> <span class="kw">sum</span>(<span class="kw">is.na</span>(gain))</span>
<span id="cb780-11"><a href="seattle-house-prices.html#cb780-11"></a>  )</span></code></pre></div>
<p>To repeat this for all three <code>price</code>, <code>sqft_living</code>, and <code>condition</code> variables would be tedious to code up. So instead, let’s use the convenient <code>skim()</code> function from the <strong>skimr</strong> package we first used in Subsection <a href="model4.html#model4EDA">11.1.1</a>, being sure to only <code>select()</code> the variables of interest for our model:</p>
<!-- DDK: The current output does not include the p75 and p100 columns. Fixable? -->
<div class="sourceCode" id="cb781"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb781-1"><a href="seattle-house-prices.html#cb781-1"></a>house_prices <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb781-2"><a href="seattle-house-prices.html#cb781-2"></a><span class="st">  </span><span class="kw">select</span>(price, sqft_living, condition) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb781-3"><a href="seattle-house-prices.html#cb781-3"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-457">TABLE 11.15: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
21613
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
factor
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
ordered
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:left;">
top_counts
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
condition
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
FALSE
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
3: 14031, 4: 5679, 5: 1701, 2: 172
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
price
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
540088
</td>
<td style="text-align:right;">
367127
</td>
<td style="text-align:right;">
75000
</td>
<td style="text-align:right;">
321950
</td>
<td style="text-align:right;">
450000
</td>
<td style="text-align:right;">
645000
</td>
<td style="text-align:right;">
7700000
</td>
<td style="text-align:left;">
▇▁▁▁▁
</td>
</tr>
<tr>
<td style="text-align:left;">
sqft_living
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2080
</td>
<td style="text-align:right;">
918
</td>
<td style="text-align:right;">
290
</td>
<td style="text-align:right;">
1427
</td>
<td style="text-align:right;">
1910
</td>
<td style="text-align:right;">
2550
</td>
<td style="text-align:right;">
13540
</td>
<td style="text-align:left;">
▇▂▁▁▁
</td>
</tr>
</tbody>
</table>
<p>Observe that the mean <code>price</code> of $540,088 is larger than the median of $450,000. This is because a small number of very expensive houses are inflating the average. In other words, there are “outlier” house prices in our dataset. (This fact will become even more apparent when we create our visualizations next.)</p>
<p>However, the median is not as sensitive to such outlier house prices. This is why news about the real estate market generally report median house prices and not mean/average house prices. We say here that the median is more <em>robust to outliers</em> than the mean. Similarly, while both the standard deviation and interquartile-range (IQR) are both measures of spread and variability, the IQR is more <em>robust to outliers</em>.</p>
<p>Let’s now perform the last of the three common steps in an exploratory data analysis: creating data visualizations. Let’s first create <em>univariate</em> visualizations. These are plots focusing on a single variable at a time. Since <code>price</code> and <code>sqft_living</code> are numerical variables, we can visualize their distributions using a <code>geom_histogram()</code> as seen in Section <a href="histograms.html#histograms">1.9</a> on histograms. On the other hand, since <code>condition</code> is categorical, we can visualize its distribution using a <code>geom_bar()</code>. Recall from Section <a href="geombar.html#geombar">1.12</a> on barplots that since <code>condition</code> is not “pre-counted”, we use a <code>geom_bar()</code> and not a <code>geom_col()</code>.</p>
<div class="sourceCode" id="cb782"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb782-1"><a href="seattle-house-prices.html#cb782-1"></a><span class="co"># Histogram of house price:</span></span>
<span id="cb782-2"><a href="seattle-house-prices.html#cb782-2"></a></span>
<span id="cb782-3"><a href="seattle-house-prices.html#cb782-3"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb782-4"><a href="seattle-house-prices.html#cb782-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> price)) <span class="op">+</span></span>
<span id="cb782-5"><a href="seattle-house-prices.html#cb782-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb782-6"><a href="seattle-house-prices.html#cb782-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;price (USD)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House price&quot;</span>)</span>
<span id="cb782-7"><a href="seattle-house-prices.html#cb782-7"></a></span>
<span id="cb782-8"><a href="seattle-house-prices.html#cb782-8"></a><span class="co"># Histogram of sqft_living</span></span>
<span id="cb782-9"><a href="seattle-house-prices.html#cb782-9"></a></span>
<span id="cb782-10"><a href="seattle-house-prices.html#cb782-10"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb782-11"><a href="seattle-house-prices.html#cb782-11"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sqft_living)) <span class="op">+</span></span>
<span id="cb782-12"><a href="seattle-house-prices.html#cb782-12"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb782-13"><a href="seattle-house-prices.html#cb782-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;living space (square feet)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House size&quot;</span>)</span>
<span id="cb782-14"><a href="seattle-house-prices.html#cb782-14"></a></span>
<span id="cb782-15"><a href="seattle-house-prices.html#cb782-15"></a><span class="co"># Barplot of condition:</span></span>
<span id="cb782-16"><a href="seattle-house-prices.html#cb782-16"></a></span>
<span id="cb782-17"><a href="seattle-house-prices.html#cb782-17"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb782-18"><a href="seattle-house-prices.html#cb782-18"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> condition)) <span class="op">+</span></span>
<span id="cb782-19"><a href="seattle-house-prices.html#cb782-19"></a><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span></span>
<span id="cb782-20"><a href="seattle-house-prices.html#cb782-20"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;condition&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House condition&quot;</span>)</span></code></pre></div>
<p>In Figure <a href="seattle-house-prices.html#fig:house-prices-viz">11.7</a>, we display all three of these visualizations at once.</p>
<div class="figure"><span id="fig:house-prices-viz"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/house-prices-viz-1.png" alt="Exploratory visualizations of Seattle house prices data." width="\textwidth" />
<p class="caption">
FIGURE 11.7: Exploratory visualizations of Seattle house prices data.
</p>
</div>
<p>First, observe in the bottom plot that most houses are of condition “3”, with a few more of conditions “4” and “5”, and almost none that are “1” or “2”.</p>
<p>Next, observe in the histogram for <code>price</code> in the top-left plot that a majority of houses are less than two million dollars. Observe also that the x-axis stretches out to 8 million dollars, even though there does not appear to be any houses close to that price. This is because there are a <em>very small number</em> of houses with prices closer to 8 million. These are the outlier house prices we mentioned earlier. We say that the variable <code>price</code> is <em>right-skewed</em> as exhibited by the long right tail.</p>
<p>Further, observe in the histogram of <code>sqft_living</code> in the middle plot as well that most houses appear to have less than 5000 square feet of living space. For comparison, a football field in the US is about 57,600 square feet, whereas a standard soccer/association football field is about 64,000 square feet. Observe also that this variable is also right-skewed, although not as drastically as the <code>price</code> variable.</p>
<p>For both the <code>price</code> and <code>sqft_living</code> variables, the right-skew makes distinguishing houses at the lower end of the x-axis hard. This is because the scale of the x-axis is compressed by the small number of quite expensive and immensely-sized houses.</p>
<p>So what can we do about this skew? Let’s apply a <em>log10 transformation</em> to these variables. A log transformations allow us to alter the scale of a variable to focus on <em>multiplicative</em> changes instead of <em>additive</em> changes. In other words, they shift the view to be on <em>relative</em> changes instead of <em>absolute</em> changes. Such multiplicative/relative changes are also called changes in <em>orders of magnitude</em>.</p>
<p>Let’s create new log10 transformed versions of the right-skewed variable <code>price</code> and <code>sqft_living</code> using the <code>mutate()</code> function from Section <a href="mutate.html#mutate">2.5</a>, but we’ll give the latter the name <code>log10_size</code>, which is shorter and easier to understand than the name <code>log10_sqft_living</code>.</p>
<div class="sourceCode" id="cb783"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb783-1"><a href="seattle-house-prices.html#cb783-1"></a>house_prices &lt;-<span class="st"> </span>house_prices <span class="op">%&gt;%</span></span>
<span id="cb783-2"><a href="seattle-house-prices.html#cb783-2"></a><span class="st">  </span><span class="kw">mutate</span>(</span>
<span id="cb783-3"><a href="seattle-house-prices.html#cb783-3"></a>    <span class="dt">log10_price =</span> <span class="kw">log10</span>(price),</span>
<span id="cb783-4"><a href="seattle-house-prices.html#cb783-4"></a>    <span class="dt">log10_size =</span> <span class="kw">log10</span>(sqft_living)</span>
<span id="cb783-5"><a href="seattle-house-prices.html#cb783-5"></a>    )</span></code></pre></div>
<p>Let’s display the before and after effects of this transformation on these variables for only the first 10 rows of <code>house_prices</code>:</p>
<div class="sourceCode" id="cb784"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb784-1"><a href="seattle-house-prices.html#cb784-1"></a>house_prices <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb784-2"><a href="seattle-house-prices.html#cb784-2"></a><span class="st">  </span><span class="kw">select</span>(price, log10_price, sqft_living, log10_size)</span></code></pre></div>
<pre><code>## # A tibble: 21,613 x 4
##      price log10_price sqft_living log10_size
##      &lt;dbl&gt;       &lt;dbl&gt;       &lt;int&gt;      &lt;dbl&gt;
##  1  221900        5.35        1180       3.07
##  2  538000        5.73        2570       3.41
##  3  180000        5.26         770       2.89
##  4  604000        5.78        1960       3.29
##  5  510000        5.71        1680       3.23
##  6 1225000        6.09        5420       3.73
##  7  257500        5.41        1715       3.23
##  8  291850        5.47        1060       3.03
##  9  229500        5.36        1780       3.25
## 10  323000        5.51        1890       3.28
## # … with 21,603 more rows</code></pre>
<p>Observe in particular the houses in the sixth and third rows. The house in the sixth row has <code>price</code> $1,225,000, which is just above one million dollars. Since <span class="math inline">\(10^6\)</span> is one million, its <code>log10_price</code> is around 6.09.</p>
<p>Contrast this with all other houses with <code>log10_price</code> less than six, since they all have <code>price</code> less than $1,000,000. The house in the third row is the only house with <code>sqft_living</code> less than 1,000. Since <span class="math inline">\(1,000 = 10^3\)</span>, it’s the lone house with <code>log10_size</code> less than 3.</p>
<p>Let’s now visualize the before and after effects of this transformation for <code>price</code> in Figure <a href="seattle-house-prices.html#fig:log10-price-viz">11.8</a>.</p>
<div class="sourceCode" id="cb786"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb786-1"><a href="seattle-house-prices.html#cb786-1"></a><span class="co"># Before log10 transformation:</span></span>
<span id="cb786-2"><a href="seattle-house-prices.html#cb786-2"></a></span>
<span id="cb786-3"><a href="seattle-house-prices.html#cb786-3"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb786-4"><a href="seattle-house-prices.html#cb786-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> price)) <span class="op">+</span></span>
<span id="cb786-5"><a href="seattle-house-prices.html#cb786-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb786-6"><a href="seattle-house-prices.html#cb786-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;price (USD)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House price: Before&quot;</span>)</span>
<span id="cb786-7"><a href="seattle-house-prices.html#cb786-7"></a></span>
<span id="cb786-8"><a href="seattle-house-prices.html#cb786-8"></a><span class="co"># After log10 transformation:</span></span>
<span id="cb786-9"><a href="seattle-house-prices.html#cb786-9"></a></span>
<span id="cb786-10"><a href="seattle-house-prices.html#cb786-10"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb786-11"><a href="seattle-house-prices.html#cb786-11"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log10_price)) <span class="op">+</span></span>
<span id="cb786-12"><a href="seattle-house-prices.html#cb786-12"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb786-13"><a href="seattle-house-prices.html#cb786-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;log10 price (USD)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House price: After&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:log10-price-viz"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/log10-price-viz-1.png" alt="House price before and after log10 transformation." width="\textwidth" />
<p class="caption">
FIGURE 11.8: House price before and after log10 transformation.
</p>
</div>
<p>Observe that after the transformation, the distribution is much less skewed, and in this case, more symmetric and more bell-shaped. Now you can more easily distinguish the lower priced houses.</p>
<p>Let’s do the same for house size, where the variable <code>sqft_living</code> was log10 transformed to <code>log10_size</code>.</p>
<div class="sourceCode" id="cb787"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb787-1"><a href="seattle-house-prices.html#cb787-1"></a><span class="co"># Before log10 transformation:</span></span>
<span id="cb787-2"><a href="seattle-house-prices.html#cb787-2"></a></span>
<span id="cb787-3"><a href="seattle-house-prices.html#cb787-3"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb787-4"><a href="seattle-house-prices.html#cb787-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> sqft_living)) <span class="op">+</span></span>
<span id="cb787-5"><a href="seattle-house-prices.html#cb787-5"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb787-6"><a href="seattle-house-prices.html#cb787-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;living space (square feet)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House size: Before&quot;</span>)</span>
<span id="cb787-7"><a href="seattle-house-prices.html#cb787-7"></a></span>
<span id="cb787-8"><a href="seattle-house-prices.html#cb787-8"></a><span class="co"># After log10 transformation:</span></span>
<span id="cb787-9"><a href="seattle-house-prices.html#cb787-9"></a></span>
<span id="cb787-10"><a href="seattle-house-prices.html#cb787-10"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb787-11"><a href="seattle-house-prices.html#cb787-11"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log10_size)) <span class="op">+</span></span>
<span id="cb787-12"><a href="seattle-house-prices.html#cb787-12"></a><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></span>
<span id="cb787-13"><a href="seattle-house-prices.html#cb787-13"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;log10 living space (square feet)&quot;</span>, <span class="dt">title =</span> <span class="st">&quot;House size: After&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:log10-size-viz"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/log10-size-viz-1.png" alt="House size before and after log10 transformation." width="\textwidth" />
<p class="caption">
FIGURE 11.9: House size before and after log10 transformation.
</p>
</div>
<p>Observe in Figure <a href="seattle-house-prices.html#fig:log10-size-viz">11.9</a> that the log10 transformation has a similar effect of unskewing the variable. We emphasize that while in these two cases the resulting distributions are more symmetric and bell-shaped, this is not always necessarily the case.</p>
<p>Given the now symmetric nature of <code>log10_price</code> and <code>log10_size</code>, we are going to revise our multiple regression model to use our new variables:</p>
<ol style="list-style-type: decimal">
<li>The outcome variable <span class="math inline">\(y\)</span> is the sale <code>log10_price</code> of houses.</li>
<li>Two explanatory variables:
<ol style="list-style-type: decimal">
<li>A numerical explanatory variable <span class="math inline">\(x_1\)</span>: house size <code>log10_size</code> as measured in log base 10 square feet of living space.</li>
<li>A categorical explanatory variable <span class="math inline">\(x_2\)</span>: house <code>condition</code>, a categorical variable with five levels where <code>1</code> indicates “poor” and <code>5</code> indicates “excellent.”</li>
</ol></li>
</ol>
</div>
<div id="house-prices-EDA-II" class="section level3">
<h3><span class="header-section-number">11.3.2</span> Exploratory data analysis: Part II</h3>
<p>Let’s now continue our EDA by creating <em>multivariate</em> visualizations. Unlike the <em>univariate</em> histograms and barplot in the earlier Figures <a href="seattle-house-prices.html#fig:house-prices-viz">11.7</a>, <a href="seattle-house-prices.html#fig:log10-price-viz">11.8</a>, and <a href="seattle-house-prices.html#fig:log10-size-viz">11.9</a>, <em>multivariate</em> visualizations show relationships between more than one variable. This is an important step of an EDA to perform since the goal of modeling is to explore relationships between variables.</p>
<p>Since our model involves a numerical outcome variable, a numerical explanatory variable, and a categorical explanatory variable, we are in a similar regression modeling situation as in Section <a href="model4.html#model4">11.1</a> where we studied the UT Austin teaching scores dataset. Recall in that case the numerical outcome variable was teaching <code>score</code>, the numerical explanatory variable was instructor <code>age</code>, and the categorical explanatory variable was (binary) <code>gender</code>.</p>
<p>We thus have two choices of models we can fit: either (1) an <em>interaction model</em> where the regression line for each <code>condition</code> level will have both a different slope and a different intercept or (2) a <em>parallel slopes model</em> where the regression line for each <code>condition</code> level will have the same slope but different intercepts.</p>
<p>Recall from Subsection <a href="model4.html#model4table">11.1.4</a> that the <code>geom_parallel_slopes()</code> function is a special purpose function that Evgeni Chasnovski created and included in the <strong>moderndive</strong> package, since the <code>geom_smooth()</code> method in the <strong>ggplot2</strong> package does not have a convenient way to plot parallel slopes models. We plot both resulting models in Figure <a href="seattle-house-prices.html#fig:house-price-parallel-slopes">11.10</a>, with the interaction model on the left.</p>
<div class="sourceCode" id="cb788"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb788-1"><a href="seattle-house-prices.html#cb788-1"></a><span class="co"># Plot interaction model</span></span>
<span id="cb788-2"><a href="seattle-house-prices.html#cb788-2"></a></span>
<span id="cb788-3"><a href="seattle-house-prices.html#cb788-3"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb788-4"><a href="seattle-house-prices.html#cb788-4"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log10_size, <span class="dt">y =</span> log10_price, <span class="dt">col =</span> condition)) <span class="op">+</span></span>
<span id="cb788-5"><a href="seattle-house-prices.html#cb788-5"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.05</span>) <span class="op">+</span></span>
<span id="cb788-6"><a href="seattle-house-prices.html#cb788-6"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb788-7"><a href="seattle-house-prices.html#cb788-7"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;log10 price&quot;</span>, </span>
<span id="cb788-8"><a href="seattle-house-prices.html#cb788-8"></a>       <span class="dt">x =</span> <span class="st">&quot;log10 size&quot;</span>, </span>
<span id="cb788-9"><a href="seattle-house-prices.html#cb788-9"></a>       <span class="dt">title =</span> <span class="st">&quot;House prices in Seattle&quot;</span>)</span>
<span id="cb788-10"><a href="seattle-house-prices.html#cb788-10"></a></span>
<span id="cb788-11"><a href="seattle-house-prices.html#cb788-11"></a><span class="co"># Plot parallel slopes model</span></span>
<span id="cb788-12"><a href="seattle-house-prices.html#cb788-12"></a></span>
<span id="cb788-13"><a href="seattle-house-prices.html#cb788-13"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb788-14"><a href="seattle-house-prices.html#cb788-14"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log10_size, <span class="dt">y =</span> log10_price, <span class="dt">col =</span> condition)) <span class="op">+</span></span>
<span id="cb788-15"><a href="seattle-house-prices.html#cb788-15"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.05</span>) <span class="op">+</span></span>
<span id="cb788-16"><a href="seattle-house-prices.html#cb788-16"></a><span class="st">  </span><span class="kw">geom_parallel_slopes</span>(<span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb788-17"><a href="seattle-house-prices.html#cb788-17"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;log10 price&quot;</span>, </span>
<span id="cb788-18"><a href="seattle-house-prices.html#cb788-18"></a>       <span class="dt">x =</span> <span class="st">&quot;log10 size&quot;</span>, </span>
<span id="cb788-19"><a href="seattle-house-prices.html#cb788-19"></a>       <span class="dt">title =</span> <span class="st">&quot;House prices in Seattle&quot;</span>)</span></code></pre></div>
<div class="figure"><span id="fig:house-price-parallel-slopes"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/house-price-parallel-slopes-1.png" alt="Interaction and parallel slopes models." width="\textwidth" />
<p class="caption">
FIGURE 11.10: Interaction and parallel slopes models.
</p>
</div>
<p>In both cases, we see there is a positive relationship between house price and size, meaning as houses are larger, they tend to be more expensive. Furthermore, in both plots it seems that houses of condition 5 tend to be the most expensive for most house sizes as evidenced by the fact that the line for condition 5 is highest, followed by conditions 4 and 3. As for conditions 1 and 2, this pattern isn’t as clear. Recall from the univariate barplot of <code>condition</code> in Figure <a href="seattle-house-prices.html#fig:house-prices-viz">11.7</a>, there are only a few houses of condition 1 or 2.</p>
<p>Let’s also show a faceted version of just the interaction model in Figure <a href="seattle-house-prices.html#fig:house-price-interaction-2">11.11</a>. It is now much more apparent just how few houses are of condition 1 or 2.</p>
<div class="sourceCode" id="cb789"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb789-1"><a href="seattle-house-prices.html#cb789-1"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb789-2"><a href="seattle-house-prices.html#cb789-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> log10_size, <span class="dt">y =</span> log10_price, <span class="dt">col =</span> condition)) <span class="op">+</span></span>
<span id="cb789-3"><a href="seattle-house-prices.html#cb789-3"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.4</span>) <span class="op">+</span></span>
<span id="cb789-4"><a href="seattle-house-prices.html#cb789-4"></a><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span></span>
<span id="cb789-5"><a href="seattle-house-prices.html#cb789-5"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;log10 price&quot;</span>, </span>
<span id="cb789-6"><a href="seattle-house-prices.html#cb789-6"></a>       <span class="dt">x =</span> <span class="st">&quot;log10 size&quot;</span>, </span>
<span id="cb789-7"><a href="seattle-house-prices.html#cb789-7"></a>       <span class="dt">title =</span> <span class="st">&quot;House prices in Seattle&quot;</span>) <span class="op">+</span></span>
<span id="cb789-8"><a href="seattle-house-prices.html#cb789-8"></a><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>condition)</span></code></pre></div>
<div class="figure"><span id="fig:house-price-interaction-2"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/house-price-interaction-2-1.png" alt="Faceted plot of interaction model." width="\textwidth" />
<p class="caption">
FIGURE 11.11: Faceted plot of interaction model.
</p>
</div>
<p>Which exploratory visualization of the interaction model is better, the one in the left-hand plot of Figure <a href="seattle-house-prices.html#fig:house-price-parallel-slopes">11.10</a> or the faceted version in Figure <a href="seattle-house-prices.html#fig:house-price-interaction-2">11.11</a>? There is no universal right answer. You need to make a choice depending on what you want to convey, and own that choice, with including and discussing both also as an option as needed.</p>
</div>
<div id="house-prices-regression" class="section level3">
<h3><span class="header-section-number">11.3.3</span> Regression modeling</h3>
<p>Which of the two models in Figure <a href="seattle-house-prices.html#fig:house-price-parallel-slopes">11.10</a> is “better”? The interaction model in the left-hand plot or the parallel slopes model in the right-hand plot?</p>
<p>We had a similar discussion in Subsection <a href="other-topics.html#model-selection">11.4.1</a> on <em>model selection</em>. Recall that we stated that we should only favor more complex models if the additional complexity is <em>warranted</em>. In this case, the more complex model is the interaction model since it considers five intercepts and five slopes total. This is in contrast to the parallel slopes model which considers five intercepts but only one common slope.</p>
<p>Is the additional complexity of the interaction model warranted? Looking at the left-hand plot in Figure <a href="seattle-house-prices.html#fig:house-price-parallel-slopes">11.10</a>, we’re of the opinion that it is, as evidenced by the slight x-like pattern to some of the lines. Therefore, we’ll focus the rest of this analysis only on the interaction model. This visual approach is somewhat subjective, however, so feel free to disagree! What are the five different slopes and five different intercepts for the interaction model? We can obtain these values from the regression table. Recall our two-step process for getting the regression table:</p>
<div class="sourceCode" id="cb790"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb790-1"><a href="seattle-house-prices.html#cb790-1"></a><span class="co"># Fit regression model:</span></span>
<span id="cb790-2"><a href="seattle-house-prices.html#cb790-2"></a></span>
<span id="cb790-3"><a href="seattle-house-prices.html#cb790-3"></a>price_interaction &lt;-<span class="st"> </span><span class="kw">lm</span>(log10_price <span class="op">~</span><span class="st"> </span>log10_size <span class="op">*</span><span class="st"> </span>condition, </span>
<span id="cb790-4"><a href="seattle-house-prices.html#cb790-4"></a>                        <span class="dt">data =</span> house_prices)</span>
<span id="cb790-5"><a href="seattle-house-prices.html#cb790-5"></a></span>
<span id="cb790-6"><a href="seattle-house-prices.html#cb790-6"></a><span class="co"># Get regression table:</span></span>
<span id="cb790-7"><a href="seattle-house-prices.html#cb790-7"></a></span>
<span id="cb790-8"><a href="seattle-house-prices.html#cb790-8"></a>price_interaction <span class="op">%&gt;%</span></span>
<span id="cb790-9"><a href="seattle-house-prices.html#cb790-9"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb790-10"><a href="seattle-house-prices.html#cb790-10"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:seattle-interaction">TABLE 11.16: </span>Regression table for interaction model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
3.330
</td>
<td style="text-align:right;">
2.446
</td>
<td style="text-align:right;">
4.215
</td>
</tr>
<tr>
<td style="text-align:left;">
log10_size
</td>
<td style="text-align:right;">
0.690
</td>
<td style="text-align:right;">
0.399
</td>
<td style="text-align:right;">
0.980
</td>
</tr>
<tr>
<td style="text-align:left;">
condition2
</td>
<td style="text-align:right;">
0.047
</td>
<td style="text-align:right;">
-0.930
</td>
<td style="text-align:right;">
1.024
</td>
</tr>
<tr>
<td style="text-align:left;">
condition3
</td>
<td style="text-align:right;">
-0.367
</td>
<td style="text-align:right;">
-1.253
</td>
<td style="text-align:right;">
0.519
</td>
</tr>
<tr>
<td style="text-align:left;">
condition4
</td>
<td style="text-align:right;">
-0.398
</td>
<td style="text-align:right;">
-1.286
</td>
<td style="text-align:right;">
0.490
</td>
</tr>
<tr>
<td style="text-align:left;">
condition5
</td>
<td style="text-align:right;">
-0.883
</td>
<td style="text-align:right;">
-1.779
</td>
<td style="text-align:right;">
0.013
</td>
</tr>
<tr>
<td style="text-align:left;">
log10_size:condition2
</td>
<td style="text-align:right;">
-0.024
</td>
<td style="text-align:right;">
-0.344
</td>
<td style="text-align:right;">
0.295
</td>
</tr>
<tr>
<td style="text-align:left;">
log10_size:condition3
</td>
<td style="text-align:right;">
0.133
</td>
<td style="text-align:right;">
-0.158
</td>
<td style="text-align:right;">
0.424
</td>
</tr>
<tr>
<td style="text-align:left;">
log10_size:condition4
</td>
<td style="text-align:right;">
0.146
</td>
<td style="text-align:right;">
-0.146
</td>
<td style="text-align:right;">
0.437
</td>
</tr>
<tr>
<td style="text-align:left;">
log10_size:condition5
</td>
<td style="text-align:right;">
0.310
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
0.604
</td>
</tr>
</tbody>
</table>
<p>Recall we saw in Subsection <a href="model4.html#model4interactiontable">11.1.2</a> how to interpret a regression table when there are both numerical and categorical explanatory variables. Let’s now do the same for all 10 values in the <code>estimate</code> column of Table <a href="seattle-house-prices.html#tab:seattle-interaction">11.16</a>.</p>
<p>In this case, the “baseline for comparison” group for the categorical variable <code>condition</code> are the condition 1 houses, since “1” comes first alphanumerically. Thus, the <code>intercept</code> and <code>log10_size</code> values are the intercept and slope for <code>log10_size</code> for this baseline group. Next, the <code>condition2</code> through <code>condition5</code> terms are the <em>offsets</em> in intercepts relative to the condition 1 intercept. Finally, the <code>log10_size:condition2</code> through <code>log10_size:condition5</code> are the <em>offsets</em> in slopes for <code>log10_size</code> relative to the condition 1 slope for <code>log10_size</code>.</p>
<p>Let’s simplify this by writing out the equation of each of the five regression lines using these 10 <code>estimate</code> values. We’ll write out each line in the following format:</p>
<p><span class="math display">\[
\widehat{\log10(\text{price})} = \hat{\beta}_0 + \hat{\beta}_{\text{size}} \cdot \log10(\text{size})
\]</span></p>
<ol style="list-style-type: decimal">
<li>Condition 1:</li>
</ol>
<p><span class="math display">\[\widehat{\log10(\text{price})} = 3.33 + 0.69 \cdot \log10(\text{size})\]</span></p>
<ol start="2" style="list-style-type: decimal">
<li>Condition 2:</li>
</ol>
<p><span class="math display">\[
\begin{aligned} 
\widehat{\log10(\text{price})} &amp;= (3.33 + 0.047) + (0.69 - 0.024) \cdot \log10(\text{size}) \\ 
                               &amp;= 3.377 + 0.666 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="3" style="list-style-type: decimal">
<li>Condition 3:</li>
</ol>
<p><span class="math display">\[
\begin{aligned} 
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.367) + (0.69 + 0.133) \cdot \log10(\text{size}) \\
                               &amp;= 2.963 + 0.823 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="4" style="list-style-type: decimal">
<li>Condition 4:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.398) + (0.69 + 0.146) \cdot \log10(\text{size}) \\
                               &amp;= 2.932 + 0.836 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<ol start="5" style="list-style-type: decimal">
<li>Condition 5:</li>
</ol>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log10(\text{price})} &amp;= (3.33 - 0.883) + (0.69 + 0.31) \cdot \log10(\text{size}) \\
                               &amp;= 2.447 + 1 \cdot \log10(\text{size})
\end{aligned}
\]</span></p>
<p>These correspond to the regression lines in the left-hand plot of Figure <a href="seattle-house-prices.html#fig:house-price-parallel-slopes">11.10</a> and the faceted plot in Figure <a href="seattle-house-prices.html#fig:house-price-interaction-2">11.11</a>. For homes of all five condition types, as the size of the house increases, the price increases. This is what most would expect. However, the rate of increase of price with size is fastest for the homes with conditions 3, 4, and 5 of 0.823, 0.836, and 1, respectively. These are the three largest slopes out of the five.</p>
</div>
<div id="house-prices-making-predictions" class="section level3">
<h3><span class="header-section-number">11.3.4</span> Making predictions</h3>
<p>Say you’re a realtor and someone calls you asking you how much their home will sell for. They tell you that it’s in condition = 5 and is sized 1900 square feet. What do you tell them? Let’s use the interaction model we fit to make predictions!</p>
<p>We first make this prediction visually in Figure <a href="seattle-house-prices.html#fig:house-price-interaction-3">11.12</a>. The predicted <code>log10_price</code> of this house is marked with a black dot. This is where the following two lines intersect:</p>
<ul>
<li>The regression line for the condition = 5 homes and</li>
<li>The vertical dashed black line at <code>log10_size</code> equals 3.28, since our predictor variable is the log10 transformed square feet of living space of <span class="math inline">\(\log10(1900) = 3.28\)</span>.</li>
</ul>
<div class="figure"><span id="fig:house-price-interaction-3"></span>
<img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/house-price-interaction-3-1.png" alt="Interaction model with prediction." width="\textwidth" />
<p class="caption">
FIGURE 11.12: Interaction model with prediction.
</p>
</div>
<p>Eyeballing it, it seems the predicted <code>log10_price</code> seems to be around 5.75. Let’s now obtain the exact numerical value for the prediction using the equation of the regression line for the condition = 5 houses, being sure to <code>log10()</code> the square footage first.</p>
<div class="sourceCode" id="cb791"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb791-1"><a href="seattle-house-prices.html#cb791-1"></a><span class="fl">2.45</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">*</span><span class="st"> </span><span class="kw">log10</span>(<span class="dv">1900</span>)</span></code></pre></div>
<pre><code>## [1] 5.73</code></pre>
<p>This value is very close to our earlier visually made prediction of 5.75. But wait! Is our prediction for the price of this house $5.75? No! Remember that we are using <code>log10_price</code> as our outcome variable! So, if we want a prediction in dollar units of <code>price</code>, we need to unlog this by taking a power of 10.</p>
<div class="sourceCode" id="cb793"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb793-1"><a href="seattle-house-prices.html#cb793-1"></a><span class="dv">10</span><span class="op">^</span>(<span class="fl">2.45</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span> <span class="op">*</span><span class="st"> </span><span class="kw">log10</span>(<span class="dv">1900</span>))</span></code></pre></div>
<pre><code>## [1] 535493</code></pre>
<p>So our predicted price for this home of condition 5 and of size 1900 square feet is $535,493.</p>
</div>
<div id="fitting-many-models-using-map" class="section level3">
<h3><span class="header-section-number">11.3.5</span> Fitting many models using <code>map()</code></h3>
<p>Much like we did with the gubernatorial forecasts in the last chapter, we can now use <code>map_*</code> functions to estimate many models using our house prices data.</p>
<p>How well do size and condition predict house prices for older houses versus newer ones? That’s difficult to visualize without using <code>map_*</code> functions. But by using <code>map()</code> and list columns, we can learn a lot we couldn’t otherwise.</p>
<p>Let’s start by <code>filter</code>ing our data to houses built before 2000 (since there is little variation in <code>condition</code> for more recently built houses) and <code>nest()</code> by <code>yr_built</code>:</p>
<div class="sourceCode" id="cb795"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb795-1"><a href="seattle-house-prices.html#cb795-1"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb795-2"><a href="seattle-house-prices.html#cb795-2"></a><span class="st">  </span><span class="kw">filter</span>(yr_built <span class="op">&lt;</span><span class="st"> </span><span class="dv">2000</span>) <span class="op">%&gt;%</span></span>
<span id="cb795-3"><a href="seattle-house-prices.html#cb795-3"></a><span class="st">  </span><span class="kw">group_by</span>(yr_built) <span class="op">%&gt;%</span></span>
<span id="cb795-4"><a href="seattle-house-prices.html#cb795-4"></a><span class="st">  </span><span class="kw">nest</span>()</span></code></pre></div>
<pre><code>## # A tibble: 100 x 2
## # Groups:   yr_built [100]
##    yr_built data               
##       &lt;int&gt; &lt;list&gt;             
##  1     1955 &lt;tibble [271 × 22]&gt;
##  2     1951 &lt;tibble [229 × 22]&gt;
##  3     1933 &lt;tibble [30 × 22]&gt; 
##  4     1965 &lt;tibble [187 × 22]&gt;
##  5     1987 &lt;tibble [294 × 22]&gt;
##  6     1995 &lt;tibble [169 × 22]&gt;
##  7     1963 &lt;tibble [256 × 22]&gt;
##  8     1960 &lt;tibble [248 × 22]&gt;
##  9     1942 &lt;tibble [223 × 22]&gt;
## 10     1927 &lt;tibble [115 × 22]&gt;
## # … with 90 more rows</code></pre>
<p>Now that we have a list column <code>data</code> consisting of our data for each <code>yr_built</code>, we can use some familiar code to run a model for each year. Let’s simplify the model to the parallel slopes model, which we can implement with the formula <code>log10_price ~ log10_size + condition.</code> This simpler model may be a better choice since we have far fewer observations per model. (In general, the smaller your data, the greater concern you should have that you are “overfitting” by including too many predictors.)</p>
<p>Let’s start by saving our model object in the list column <code>mod</code> and the <code>tid</code>ied version of that in the list column <code>reg_results</code>:</p>
<div class="sourceCode" id="cb797"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb797-1"><a href="seattle-house-prices.html#cb797-1"></a>house_prices <span class="op">%&gt;%</span></span>
<span id="cb797-2"><a href="seattle-house-prices.html#cb797-2"></a><span class="st">  </span><span class="kw">filter</span>(yr_built <span class="op">&lt;</span><span class="st"> </span><span class="dv">2000</span>) <span class="op">%&gt;%</span></span>
<span id="cb797-3"><a href="seattle-house-prices.html#cb797-3"></a><span class="st">  </span><span class="kw">group_by</span>(yr_built) <span class="op">%&gt;%</span></span>
<span id="cb797-4"><a href="seattle-house-prices.html#cb797-4"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb797-5"><a href="seattle-house-prices.html#cb797-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(log10_price <span class="op">~</span><span class="st"> </span>log10_size <span class="op">+</span><span class="st"> </span>condition, </span>
<span id="cb797-6"><a href="seattle-house-prices.html#cb797-6"></a>                        <span class="dt">data =</span> .)),</span>
<span id="cb797-7"><a href="seattle-house-prices.html#cb797-7"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(., <span class="dt">conf.int =</span> <span class="ot">TRUE</span>)))</span></code></pre></div>
<pre><code>## # A tibble: 100 x 4
## # Groups:   yr_built [100]
##    yr_built data                mod    reg_results     
##       &lt;int&gt; &lt;list&gt;              &lt;list&gt; &lt;list&gt;          
##  1     1955 &lt;tibble [271 × 22]&gt; &lt;lm&gt;   &lt;tibble [6 × 7]&gt;
##  2     1951 &lt;tibble [229 × 22]&gt; &lt;lm&gt;   &lt;tibble [5 × 7]&gt;
##  3     1933 &lt;tibble [30 × 22]&gt;  &lt;lm&gt;   &lt;tibble [6 × 7]&gt;
##  4     1965 &lt;tibble [187 × 22]&gt; &lt;lm&gt;   &lt;tibble [4 × 7]&gt;
##  5     1987 &lt;tibble [294 × 22]&gt; &lt;lm&gt;   &lt;tibble [5 × 7]&gt;
##  6     1995 &lt;tibble [169 × 22]&gt; &lt;lm&gt;   &lt;tibble [5 × 7]&gt;
##  7     1963 &lt;tibble [256 × 22]&gt; &lt;lm&gt;   &lt;tibble [5 × 7]&gt;
##  8     1960 &lt;tibble [248 × 22]&gt; &lt;lm&gt;   &lt;tibble [5 × 7]&gt;
##  9     1942 &lt;tibble [223 × 22]&gt; &lt;lm&gt;   &lt;tibble [6 × 7]&gt;
## 10     1927 &lt;tibble [115 × 22]&gt; &lt;lm&gt;   &lt;tibble [4 × 7]&gt;
## # … with 90 more rows</code></pre>
<p>Now let’s take a look at the effect of <code>log10_size_coef</code>. Note that when interpreting this coefficient that these models also include <code>condition</code>, and thus we are looking at the effect of size on price while <em>also</em> allowing the intercept to be offset by different levels of <code>condition</code>. <!-- AR: I don't love this talk of "offsets" -- conceptually, you are just estimating different intercepts for different levels of "condition" and the regression output *expresses* it in terms of offsets -- but this is how the book discusses it throughout and it would take considerable editing to change it. --></p>
<p>Here is the code to extract the coefficient on <code>log10_size_coef</code> as well as the confidence interval bounds:</p>
<div class="sourceCode" id="cb799"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb799-1"><a href="seattle-house-prices.html#cb799-1"></a>house_year_model &lt;-<span class="st"> </span>house_prices <span class="op">%&gt;%</span></span>
<span id="cb799-2"><a href="seattle-house-prices.html#cb799-2"></a><span class="st">  </span><span class="kw">filter</span>(yr_built <span class="op">&lt;</span><span class="st"> </span><span class="dv">2000</span>) <span class="op">%&gt;%</span></span>
<span id="cb799-3"><a href="seattle-house-prices.html#cb799-3"></a><span class="st">  </span><span class="kw">group_by</span>(yr_built) <span class="op">%&gt;%</span></span>
<span id="cb799-4"><a href="seattle-house-prices.html#cb799-4"></a><span class="st">  </span><span class="kw">nest</span>() <span class="op">%&gt;%</span></span>
<span id="cb799-5"><a href="seattle-house-prices.html#cb799-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mod =</span> <span class="kw">map</span>(data, <span class="op">~</span><span class="st"> </span><span class="kw">lm</span>(log10_price <span class="op">~</span><span class="st"> </span>log10_size <span class="op">+</span><span class="st"> </span>condition, </span>
<span id="cb799-6"><a href="seattle-house-prices.html#cb799-6"></a>                        <span class="dt">data =</span> .)),</span>
<span id="cb799-7"><a href="seattle-house-prices.html#cb799-7"></a>         <span class="dt">reg_results =</span> <span class="kw">map</span>(mod, <span class="op">~</span><span class="st"> </span><span class="kw">tidy</span>(., <span class="dt">conf.int =</span> <span class="ot">TRUE</span>)),</span>
<span id="cb799-8"><a href="seattle-house-prices.html#cb799-8"></a>         <span class="dt">log10_size_coef =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;log10_size&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb799-9"><a href="seattle-house-prices.html#cb799-9"></a><span class="st">                                     </span><span class="kw">pull</span>(estimate)),</span>
<span id="cb799-10"><a href="seattle-house-prices.html#cb799-10"></a>         <span class="dt">log10_size_low =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;log10_size&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb799-11"><a href="seattle-house-prices.html#cb799-11"></a><span class="st">                                     </span><span class="kw">pull</span>(conf.low)),</span>
<span id="cb799-12"><a href="seattle-house-prices.html#cb799-12"></a>         <span class="dt">log10_size_high =</span> <span class="kw">map_dbl</span>(reg_results, <span class="op">~</span><span class="st"> </span><span class="kw">filter</span>(., term <span class="op">==</span><span class="st"> &quot;log10_size&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb799-13"><a href="seattle-house-prices.html#cb799-13"></a><span class="st">                                     </span><span class="kw">pull</span>(conf.high)))</span>
<span id="cb799-14"><a href="seattle-house-prices.html#cb799-14"></a></span>
<span id="cb799-15"><a href="seattle-house-prices.html#cb799-15"></a>house_year_model</span></code></pre></div>
<pre><code>## # A tibble: 100 x 7
## # Groups:   yr_built [100]
##    yr_built data  mod   reg_results log10_size_coef log10_size_low
##       &lt;int&gt; &lt;lis&gt; &lt;lis&gt; &lt;list&gt;                &lt;dbl&gt;          &lt;dbl&gt;
##  1     1955 &lt;tib… &lt;lm&gt;  &lt;tibble [6…           0.745          0.621
##  2     1951 &lt;tib… &lt;lm&gt;  &lt;tibble [5…           0.912          0.785
##  3     1933 &lt;tib… &lt;lm&gt;  &lt;tibble [6…           1.34           1.08 
##  4     1965 &lt;tib… &lt;lm&gt;  &lt;tibble [4…           0.847          0.702
##  5     1987 &lt;tib… &lt;lm&gt;  &lt;tibble [5…           1.02           0.900
##  6     1995 &lt;tib… &lt;lm&gt;  &lt;tibble [5…           1.14           1.01 
##  7     1963 &lt;tib… &lt;lm&gt;  &lt;tibble [5…           0.986          0.837
##  8     1960 &lt;tib… &lt;lm&gt;  &lt;tibble [5…           0.919          0.789
##  9     1942 &lt;tib… &lt;lm&gt;  &lt;tibble [6…           0.622          0.483
## 10     1927 &lt;tib… &lt;lm&gt;  &lt;tibble [4…           0.818          0.657
## # … with 90 more rows, and 1 more variable: log10_size_high &lt;dbl&gt;</code></pre>
<p>The easiest way to see the results of these models is to plot the coefficients:</p>
<div class="sourceCode" id="cb801"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb801-1"><a href="seattle-house-prices.html#cb801-1"></a>house_year_model <span class="op">%&gt;%</span></span>
<span id="cb801-2"><a href="seattle-house-prices.html#cb801-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> yr_built, <span class="dt">y =</span> log10_size_coef, <span class="dt">ymin =</span> log10_size_low, <span class="dt">ymax =</span> log10_size_high)) <span class="op">+</span></span>
<span id="cb801-3"><a href="seattle-house-prices.html#cb801-3"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb801-4"><a href="seattle-house-prices.html#cb801-4"></a><span class="st">  </span><span class="kw">geom_errorbar</span>() <span class="op">+</span></span>
<span id="cb801-5"><a href="seattle-house-prices.html#cb801-5"></a><span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span></span>
<span id="cb801-6"><a href="seattle-house-prices.html#cb801-6"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Year built&quot;</span>,</span>
<span id="cb801-7"><a href="seattle-house-prices.html#cb801-7"></a>       <span class="dt">y =</span> <span class="st">&quot;Effect of log 10 size on log 10 price&quot;</span>,</span>
<span id="cb801-8"><a href="seattle-house-prices.html#cb801-8"></a>       <span class="dt">title =</span> <span class="st">&quot;Predicting house price with house size and condition&quot;</span>,</span>
<span id="cb801-9"><a href="seattle-house-prices.html#cb801-9"></a>       <span class="dt">subtitle =</span> <span class="st">&quot;Regression coefficients for house size plotted by year&quot;</span>)</span></code></pre></div>
<p><img src="Preceptor%E2%80%99s-Primer-for-Bayesian-Data-Science_files/figure-html/unnamed-chunk-471-1.png" width="\textwidth" /></p>
<p>We can learn a lot from this figure that would be hard to do if we just ran a single regression. For example, we see that the effect of house size (taking into account condition) follows no clear pattern for the first half of the twentieth century, but appears to increase throughout the second half of the twentieth century. The size of a house in Seattle is a much better predictor of its price in these models if the house was built in the 1990s than if the house was built in the 1940s.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="model3.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="other-topics.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
