<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta property="og:title" content="Chapter 8 Two Parameters | Preceptor’s Primer for Bayesian Data Science" />
<meta property="og:type" content="book" />



<meta name="github-repo" content="davidkane9/PPBDS" />

<meta name="author" content="David Kane" />

<meta name="date" content="2020-07-19" />

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS_CHTML-full" type="text/javascript"></script>

<meta name="description" content="Chapter 8 Two Parameters | Preceptor’s Primer for Bayesian Data Science">

<title>Chapter 8 Two Parameters | Preceptor’s Primer for Bayesian Data Science</title>

<link href="libs/tufte-css-2015.12.29/tufte.css" rel="stylesheet" />
<link href="libs/tufte-css-2015.12.29/envisioned.css" rel="stylesheet" />
<link href="libs/msmb-css-0/msmb.css" rel="stylesheet" />
<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);

e.style.display = ((e.style.display!='none') ? 'none' : 'block');

if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}

}
</script>
<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }

code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />

</head>

<body>



<div class="row">
<div class="col-sm-12">
<div id="TOC">
<ul class="navbar">
<li class="msmb"><p class="title">Preceptor's Primer for Bayesian Data Science<p><p class="author">David Kane</p>
<li class="dropdown" style="float:right">
<a href="javascript:void(0)" class="dropbtn">&#x25BE; Chapters</a>
<div class="dropdown-content">
<a href="index.html">Cover</a>
<a href="preamble.html">Preamble</a>
<a href="shopping-week.html">Shopping Week</a>
<a href="visualization.html"><span class="toc-section-number">1</span> Visualization</a>
<a href="tidyverse.html"><span class="toc-section-number">2</span> Tidyverse</a>
<a href="rubin-causal-model.html"><span class="toc-section-number">3</span> Rubin Causal Model</a>
<a href="functions.html"><span class="toc-section-number">4</span> Functions</a>
<a href="probability.html"><span class="toc-section-number">5</span> Probability</a>
<a href="sampling.html"><span class="toc-section-number">6</span> Sampling</a>
<a href="one-parameter.html"><span class="toc-section-number">7</span> One Parameter</a>
<a id="active-page" href="two-parameters.html"><span class="toc-section-number">8</span> Two Parameters</a><ul class="toc-sections">
<li class="toc"><a href="#eda-for-trains"> EDA for <code>trains</code></a></li>
<li class="toc"><a href="#review-of-one-parameter-estimation"> Review of One Parameter Estimation</a></li>
<li class="toc"><a href="#age-as-a-function-of-party"> <code>age</code> as a function of <code>party</code></a></li>
<li class="toc"><a href="#estimate-other-things"> Estimate other things</a></li>
<li class="toc"><a href="#estimate-trickier-things"> Estimate trickier things</a></li>
<li class="toc"><a href="#NA"> <code>att_end</code> as a function of <code>treatment</code></a></li>
<li class="toc"><a href="#two-parameter-models-which-require-the-bootstrap"> Two parameter models which require the bootstrap</a></li>
<li class="toc"><a href="#prediction-1"> Prediction</a></li>
</ul>
<a href="n-parameters.html"><span class="toc-section-number">9</span> N Parameters</a>
<a href="pitfalls.html"><span class="toc-section-number">10</span> Pitfalls</a>
<a href="continuous-response.html"><span class="toc-section-number">11</span> Continuous Response</a>
<a href="discrete-response.html"><span class="toc-section-number">12</span> Discrete Response</a>
<a href="appendices.html">Appendices</a>
<a href="tools.html">Tools</a>
<a href="shiny.html">Shiny</a>
<a href="maps.html">Maps</a>
<a href="animation.html">Animation</a>
<a href="references-1.html">References</a>
</div>
</li>
</ul>
</div>
</div>
</div>
<div class="row">
<div class="col-sm-12">
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><div id="two-parameters" class="section level1">
<h1>
<span class="header-section-number">Chapter 8</span> Two Parameters</h1>
<!-- Outline of the chapter -->
<!-- 0) Open with a question. -->
<!-- 1) EDA for trains -->
<!-- 2) Review of material from Chapter 7 -->
<!-- 3) age by party (modeling for prediction). finished with residuals parameter uncertainty No prediction -->
<!-- 4) att_end by treatment (modeling for causation). No use of bootstrap. -->
<!-- 5) Simple regression model with intercept and coefficient. Steal from chapter 9. -->
<!-- 6) MAYBE NOT Models requiring the bootstrap. Ratio of average age of democrats versus republicans. -->
<!-- 7) Prediction. Use the models to answer your question. -->
<p>We have now introduced almost all of the key themes in the book. The last five chapters are about increasing the complexity of the models we use. In this chapter, we estimate models which involve two parameters.</p>
<div id="eda-for-trains" class="section level2">
<h2>
<span class="header-section-number">8.1</span> EDA for <code>trains</code>
</h2>
<!-- DK: Still need to standardize the method we use for providing references. -->
<p>Let’s do some exploratory data analysis (EDA) of the <code>trains</code> data set from the <strong>PPBDS.data</strong> package. Recall the discussion from Chapter <a href="rubin-causal-model.html#rubin-causal-model">3</a>. Enos (2014) randomly placed Spanish-speaking confederates on nine train platforms around Boston, Massachusetts. Exposure to Spanish-speakers – the <code>treatment</code> – influenced attitudes toward immigration. These reactions were measured through changes in answers to three survey questions. Let’s load the libraries we will need in this chapter and look at the data.</p>
<div class="sourceCode" id="cb665"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb665-1"><a href="two-parameters.html#cb665-1"></a>knitr<span class="op">::</span>opts_chunk<span class="op">$</span><span class="kw">set</span>(<span class="dt">echo =</span> <span class="ot">TRUE</span>, <span class="dt">tidy =</span> <span class="ot">FALSE</span>, <span class="dt">cache.extra =</span> <span class="kw">packageVersion</span>(<span class="st">'tufte'</span>))</span>
<span id="cb665-2"><a href="two-parameters.html#cb665-2"></a></span>
<span id="cb665-3"><a href="two-parameters.html#cb665-3"></a><span class="kw">library</span>(PPBDS.data)</span>
<span id="cb665-4"><a href="two-parameters.html#cb665-4"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb665-5"><a href="two-parameters.html#cb665-5"></a><span class="kw">library</span>(broom)</span>
<span id="cb665-6"><a href="two-parameters.html#cb665-6"></a><span class="kw">library</span>(rsample)</span>
<span id="cb665-7"><a href="two-parameters.html#cb665-7"></a><span class="kw">library</span>(skimr)</span>
<span id="cb665-8"><a href="two-parameters.html#cb665-8"></a><span class="kw">library</span>(gt)</span>
<span id="cb665-9"><a href="two-parameters.html#cb665-9"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb665-10"><a href="two-parameters.html#cb665-10"></a><span class="kw">library</span>(tufte)</span></code></pre></div>
<div class="sourceCode" id="cb666"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb666-1"><a href="two-parameters.html#cb666-1"></a><span class="kw">glimpse</span>(trains)</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 8
## $ gender    &lt;chr&gt; "Female", "Female", "Male", "Male", "Male", "Female", "Fema…
## $ liberal   &lt;lgl&gt; FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE…
## $ party     &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", "Democrat…
## $ age       &lt;dbl&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24, 40, 53,…
## $ income    &lt;dbl&gt; 135000, 105000, 135000, 300000, 135000, 87500, 87500, 13500…
## $ att_start &lt;dbl&gt; 11, 9, 3, 11, 8, 13, 13, 10, 12, 9, 10, 11, 13, 6, 8, 13, 7…
## $ treatment &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treated, Contr…
## $ att_end   &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7, 8, 13, 8…</code></pre>
<p>Here, we can see variables that indicate each respondent’s gender, political affiliations, age, and income. Additionally, we have variables that indicate whether a subject was in the control or treatment group, and the their attitudes toward immigration both before or after the treatment. You can type <code>?trains</code> to read the help page for more information about each variable. Let’s restrict attention to a subset of the variables.</p>
<div class="sourceCode" id="cb668"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb668-1"><a href="two-parameters.html#cb668-1"></a>ch8 &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb668-2"><a href="two-parameters.html#cb668-2"></a><span class="st">  </span><span class="kw">select</span>(age, att_end, party, treatment)</span></code></pre></div>
<p>It is always smart to look at a some random samples of the data:</p>
<div class="sourceCode" id="cb669"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb669-1"><a href="two-parameters.html#cb669-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb669-2"><a href="two-parameters.html#cb669-2"></a><span class="st">  </span><span class="kw">sample_n</span>(<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 4
##     age att_end party      treatment
##   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;fct&gt;    
## 1    56      11 Democrat   Treated  
## 2    45      11 Democrat   Control  
## 3    47       8 Republican Control  
## 4    63       5 Democrat   Treated  
## 5    61       9 Democrat   Control</code></pre>
<p><code>att_end</code> is a measure of person’s attitude toward immigration, a higher number means to a more conservative, i.e., a more exclusionary stance on immigration into the United States. Running <code>glimpse()</code> is another way of exploring a data set.</p>
<div class="sourceCode" id="cb671"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb671-1"><a href="two-parameters.html#cb671-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb671-2"><a href="two-parameters.html#cb671-2"></a><span class="st">  </span><span class="kw">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 115
## Columns: 4
## $ age       &lt;dbl&gt; 31, 34, 63, 45, 55, 37, 53, 36, 54, 42, 33, 50, 24, 40, 53,…
## $ att_end   &lt;dbl&gt; 11, 10, 5, 11, 5, 13, 13, 11, 12, 10, 9, 9, 13, 7, 8, 13, 8…
## $ party     &lt;chr&gt; "Democrat", "Republican", "Democrat", "Democrat", "Democrat…
## $ treatment &lt;fct&gt; Treated, Treated, Treated, Treated, Control, Treated, Contr…</code></pre>
<p>Pay attention to the variable “type.” Do they make sense? Perhaps. But there are certainly grounds for suspicion. Why are <code>age</code> and <code>att_end</code> doubles rather than integers? Why is <code>party</code> a character variable and <code>treament</code> a factor variable? It could be that these are intentional choices made by the creator of the tibble, i.e., us. These could be mistakes. Or, most likely, these choices are a mixture of sensible and arbitrary. Regardless, it is your responsibility to notice them. You can’t make a good model without looking closely at the data which you are using.</p>
<p><code>skim</code> from the <strong>skimr</strong> package is the best way to get an overview of a tibble.</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb673-1"><a href="two-parameters.html#cb673-1"></a>ch8 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb673-2"><a href="two-parameters.html#cb673-2"></a><span class="st">  </span><span class="kw">skim</span>()</span></code></pre></div>
<table style="width: auto;" class="table table-condensed">
<caption>
<span id="tab:unnamed-chunk-461">TABLE 8.1: </span>Data summary
</caption>
<thead><tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
Piped data
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
115
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
factor
</td>
<td style="text-align:left;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead><tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:left;">
party
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr></tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<thead><tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:left;">
ordered
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:left;">
top_counts
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:left;">
treatment
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
FALSE
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Con: 64, Tre: 51
</td>
</tr></tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead><tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
42.4
</td>
<td style="text-align:right;">
12.2
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:right;">
68
</td>
<td style="text-align:left;">
▆▇▇▇▃
</td>
</tr>
<tr>
<td style="text-align:left;">
att_end
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.1
</td>
<td style="text-align:right;">
2.9
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
▂▃▇▃▃
</td>
</tr>
</tbody>
</table>
<p><code>skim()</code> shows us what the different values of <code>treatment</code> are because it is a factor. Unfortunately, it does not do the same for character variables like <code>party</code>. The ranges for <code>age</code> and <code>att_end</code> seem reasonable. Recall that participants were asked three questions about immigration issues, each of which allowed for an answer which was a strength of agreement between 1 and 5, with higher values indicating more agreement with conservative viewpoints. So, the most liberal possible value is 3 and the most conservative is 15.</p>
<p>Plotting some variables from the dataset is another important practice in exploratory data analysis:</p>
<div class="sourceCode" id="cb674"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb674-1"><a href="two-parameters.html#cb674-1"></a>ch8 <span class="op">%&gt;%</span></span>
<span id="cb674-2"><a href="two-parameters.html#cb674-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> party, <span class="dt">y =</span> age)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb674-3"><a href="two-parameters.html#cb674-3"></a><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">width =</span> <span class="fl">0.1</span>, <span class="dt">height =</span> <span class="dv">0</span>) <span class="op">+</span><span class="st"> </span></span>
<span id="cb674-4"><a href="two-parameters.html#cb674-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"Party"</span>,</span>
<span id="cb674-5"><a href="two-parameters.html#cb674-5"></a>       <span class="dt">y =</span> <span class="st">"Age"</span>,</span>
<span id="cb674-6"><a href="two-parameters.html#cb674-6"></a>       <span class="dt">title =</span> <span class="st">"Age by Party Affiliation in Trains Dataset"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-462-1.png" width="672"></p>
<p>From this plot, we can gather that there are many more Democrats in this dataset than Republicans. Democrats also span a wider range of ages than Republicans. The mode age for Democrats appears to be 50.</p>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb675-1"><a href="two-parameters.html#cb675-1"></a>ch8 <span class="op">%&gt;%</span></span>
<span id="cb675-2"><a href="two-parameters.html#cb675-2"></a><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> treatment, <span class="dt">y =</span> att_end)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb675-3"><a href="two-parameters.html#cb675-3"></a><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb675-4"><a href="two-parameters.html#cb675-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb675-5"><a href="two-parameters.html#cb675-5"></a>       <span class="dt">y =</span> <span class="st">"Attitude End"</span>,</span>
<span id="cb675-6"><a href="two-parameters.html#cb675-6"></a>       <span class="dt">title =</span> <span class="st">"Attitude End by Treatment in Trains Dataset"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-463-1.png" width="672"></p>
<p>On a boxplot, the top and bottom borders of the box denotes the 75th and 25th percentiles, respectively. The line inside the box denotes the mean of the data. Treated individuals have a higher mean att_end than the control group, and a higher distribution in general, with its 25th percentile lining up with the mean of the control group. The control group has an outlier, while the treatment group does not.</p>
</div>
<div id="review-of-one-parameter-estimation" class="section level2">
<h2>
<span class="header-section-number">8.2</span> Review of One Parameter Estimation</h2>
<!--  Speak with Cass about adding a Preceptor Table here. -->
<p>Recall how we constructed bootstrap distributions for a parameter by sampling with replacement in Chapter <a href="one-parameter.html#one-parameter">7</a>. Through this bootstrapping process, we were able to construct <em>confidence intervals</em> for a parameter. Remember, confidence intervals are a tool to help us identify <em>parameter uncertainty</em>, which is the degree to which we are confident in these estimates of the <em>unknown</em> (and often unknowable) numbers.</p>
<p>We will once again be using the <code>bootstraps()</code> function from the <strong>rsample</strong> package. You might think that since we’re shifting to calculating two parameters, we might need to conduct the entire bootstrapping process twice, once for each parameter. However, it’s much, much easier than that. We can actually calculate as many parameters as we need to for each bootstrap sample instead of doing a separate bootstrap for each parameter we want to estimate.</p>
<p>Let’s review the material from Chapter <a href="one-parameter.html#one-parameter">7</a> by calculating the confidence interval for both the mean and the 90th percentile of age for Boston commuters. We will build up the code section by section.</p>
<p>First, we select out the only variable we need, with is <code>age</code>, and then create an objects of class <code>bootstraps</code>.</p>
<div class="sourceCode" id="cb676"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb676-1"><a href="two-parameters.html#cb676-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb676-2"><a href="two-parameters.html#cb676-2"></a><span class="st">  </span><span class="kw">select</span>(age) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb676-3"><a href="two-parameters.html#cb676-3"></a><span class="st">  </span><span class="kw">bootstraps</span>(<span class="dv">1000</span>)</span></code></pre></div>
<pre><code>## # Bootstrap sampling 
## # A tibble: 1,000 x 2
##    splits           id           
##    &lt;list&gt;           &lt;chr&gt;        
##  1 &lt;split [115/47]&gt; Bootstrap0001
##  2 &lt;split [115/42]&gt; Bootstrap0002
##  3 &lt;split [115/39]&gt; Bootstrap0003
##  4 &lt;split [115/44]&gt; Bootstrap0004
##  5 &lt;split [115/40]&gt; Bootstrap0005
##  6 &lt;split [115/36]&gt; Bootstrap0006
##  7 &lt;split [115/44]&gt; Bootstrap0007
##  8 &lt;split [115/41]&gt; Bootstrap0008
##  9 &lt;split [115/37]&gt; Bootstrap0009
## 10 &lt;split [115/41]&gt; Bootstrap0010
## # … with 990 more rows</code></pre>
<p>We discussed these objects in Chapter <a href="one-parameter.html#one-parameter">7</a>. The key trick in working with them is the use of <code>analysis()</code> from the <strong>rsample</strong> package to pull out the underlying data.</p>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb678-1"><a href="two-parameters.html#cb678-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb678-2"><a href="two-parameters.html#cb678-2"></a><span class="st">  </span><span class="kw">select</span>(age) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb678-3"><a href="two-parameters.html#cb678-3"></a><span class="st">  </span><span class="kw">bootstraps</span>(<span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb678-4"><a href="two-parameters.html#cb678-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">boot =</span> <span class="kw">map</span>(splits, <span class="op">~</span><span class="st"> </span><span class="kw">analysis</span>(.)))</span></code></pre></div>
<pre><code>## # Bootstrap sampling 
## # A tibble: 1,000 x 3
##    splits           id            boot              
##  * &lt;list&gt;           &lt;chr&gt;         &lt;list&gt;            
##  1 &lt;split [115/40]&gt; Bootstrap0001 &lt;tibble [115 × 1]&gt;
##  2 &lt;split [115/40]&gt; Bootstrap0002 &lt;tibble [115 × 1]&gt;
##  3 &lt;split [115/44]&gt; Bootstrap0003 &lt;tibble [115 × 1]&gt;
##  4 &lt;split [115/46]&gt; Bootstrap0004 &lt;tibble [115 × 1]&gt;
##  5 &lt;split [115/47]&gt; Bootstrap0005 &lt;tibble [115 × 1]&gt;
##  6 &lt;split [115/43]&gt; Bootstrap0006 &lt;tibble [115 × 1]&gt;
##  7 &lt;split [115/40]&gt; Bootstrap0007 &lt;tibble [115 × 1]&gt;
##  8 &lt;split [115/36]&gt; Bootstrap0008 &lt;tibble [115 × 1]&gt;
##  9 &lt;split [115/36]&gt; Bootstrap0009 &lt;tibble [115 × 1]&gt;
## 10 &lt;split [115/40]&gt; Bootstrap0010 &lt;tibble [115 × 1]&gt;
## # … with 990 more rows</code></pre>
<p><code>boot</code> is now a list-column in the tibble. This workflow — keep adding new columns to the tibble created after the initial call to <code>bootstraps()</code> — is common. Let’s add three more columns.</p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb680-1"><a href="two-parameters.html#cb680-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-2"><a href="two-parameters.html#cb680-2"></a><span class="st">  </span><span class="kw">select</span>(age) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-3"><a href="two-parameters.html#cb680-3"></a><span class="st">  </span><span class="kw">bootstraps</span>(<span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-4"><a href="two-parameters.html#cb680-4"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">boot =</span> <span class="kw">map</span>(splits, <span class="op">~</span><span class="st"> </span><span class="kw">analysis</span>(.))) <span class="op">%&gt;%</span></span>
<span id="cb680-5"><a href="two-parameters.html#cb680-5"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ages =</span> <span class="kw">map</span>(boot, <span class="op">~</span><span class="st"> </span><span class="kw">pull</span>(., age))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-6"><a href="two-parameters.html#cb680-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_mean =</span> <span class="kw">map_dbl</span>(ages, <span class="op">~</span><span class="st"> </span><span class="kw">mean</span>(.))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb680-7"><a href="two-parameters.html#cb680-7"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_90th =</span> <span class="kw">map_dbl</span>(ages, <span class="op">~</span><span class="st"> </span><span class="kw">quantile</span>(., <span class="dt">probs =</span> <span class="fl">0.9</span>)))</span></code></pre></div>
<pre><code>## # Bootstrap sampling 
## # A tibble: 1,000 x 6
##    splits           id            boot              ages       age_mean age_90th
##  * &lt;list&gt;           &lt;chr&gt;         &lt;list&gt;            &lt;list&gt;        &lt;dbl&gt;    &lt;dbl&gt;
##  1 &lt;split [115/40]&gt; Bootstrap0001 &lt;tibble [115 × 1… &lt;dbl [115…     43.2     59.6
##  2 &lt;split [115/43]&gt; Bootstrap0002 &lt;tibble [115 × 1… &lt;dbl [115…     41.8     56  
##  3 &lt;split [115/47]&gt; Bootstrap0003 &lt;tibble [115 × 1… &lt;dbl [115…     40.7     58.8
##  4 &lt;split [115/43]&gt; Bootstrap0004 &lt;tibble [115 × 1… &lt;dbl [115…     42.3     57  
##  5 &lt;split [115/44]&gt; Bootstrap0005 &lt;tibble [115 × 1… &lt;dbl [115…     43.5     60  
##  6 &lt;split [115/44]&gt; Bootstrap0006 &lt;tibble [115 × 1… &lt;dbl [115…     42.1     57  
##  7 &lt;split [115/42]&gt; Bootstrap0007 &lt;tibble [115 × 1… &lt;dbl [115…     43.8     58.2
##  8 &lt;split [115/44]&gt; Bootstrap0008 &lt;tibble [115 × 1… &lt;dbl [115…     42.8     57  
##  9 &lt;split [115/39]&gt; Bootstrap0009 &lt;tibble [115 × 1… &lt;dbl [115…     41.4     58.2
## 10 &lt;split [115/46]&gt; Bootstrap0010 &lt;tibble [115 × 1… &lt;dbl [115…     39.8     55  
## # … with 990 more rows</code></pre>
<p>We could simplify this code by combining all the <code>mutate()</code> steps into a single line, create one function which does the <code>analyst()</code>, <code>pull()</code>, <code>mean()</code> and <code>quantile()</code> steps together. However, when building up an analysis like this, we prefer to go line-by-line, at least until everything is working. We could also “feed” this pipe directly into a call to <code>ggplot()</code>. However, it is better practice to save the needed results in an object and then use that object for plotting, especially if creating the data takes some time. For replication purposes, we use <code>set.seed()</code>. We only keep the variables we need.</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb682-1"><a href="two-parameters.html#cb682-1"></a><span class="kw">set.seed</span>(<span class="dv">9</span>)</span>
<span id="cb682-2"><a href="two-parameters.html#cb682-2"></a></span>
<span id="cb682-3"><a href="two-parameters.html#cb682-3"></a>boot_results &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-4"><a href="two-parameters.html#cb682-4"></a><span class="st">  </span><span class="kw">select</span>(age) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-5"><a href="two-parameters.html#cb682-5"></a><span class="st">  </span><span class="kw">bootstraps</span>(<span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-6"><a href="two-parameters.html#cb682-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ages =</span> <span class="kw">map</span>(splits, <span class="op">~</span><span class="st"> </span><span class="kw">analysis</span>(.) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-7"><a href="two-parameters.html#cb682-7"></a><span class="st">                              </span><span class="kw">pull</span>(., age))) <span class="op">%&gt;%</span></span>
<span id="cb682-8"><a href="two-parameters.html#cb682-8"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_mean =</span> <span class="kw">map_dbl</span>(ages, <span class="op">~</span><span class="st"> </span><span class="kw">mean</span>(.))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-9"><a href="two-parameters.html#cb682-9"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">age_90th =</span> <span class="kw">map_dbl</span>(ages, <span class="op">~</span><span class="st"> </span><span class="kw">quantile</span>(., <span class="dt">probs =</span> <span class="fl">0.9</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb682-10"><a href="two-parameters.html#cb682-10"></a><span class="st">  </span><span class="kw">select</span>(age_mean, age_90th)</span></code></pre></div>
<p>We no longer need to re-run this code each time we adjust the plot.</p>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb683-1"><a href="two-parameters.html#cb683-1"></a>boot_results <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb683-2"><a href="two-parameters.html#cb683-2"></a><span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span></span>
<span id="cb683-3"><a href="two-parameters.html#cb683-3"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age_mean), <span class="dt">binwidth =</span> <span class="fl">.1</span>, <span class="dt">fill =</span> <span class="st">"red"</span>) <span class="op">+</span></span>
<span id="cb683-4"><a href="two-parameters.html#cb683-4"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> age_90th), <span class="dt">binwidth =</span> <span class="fl">.1</span>, <span class="dt">fill =</span> <span class="st">"blue"</span>) <span class="op">+</span></span>
<span id="cb683-5"><a href="two-parameters.html#cb683-5"></a><span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"Estimate in Years"</span>,</span>
<span id="cb683-6"><a href="two-parameters.html#cb683-6"></a>        <span class="dt">title =</span> <span class="st">"Posterior Distribution for the Mean and the 90th Percentile of </span></span>
<span id="cb683-7"><a href="two-parameters.html#cb683-7"></a><span class="st">         Age for Boston Commuters"</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-468-1.png" width="672"></p>
<p>Remember that some parameters, like the mean, are easy to calculate with built in functions like <code>lm()</code> while others require the use of the bootstrap. Note how similar the <code>lm()</code> solution is:</p>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb684-1"><a href="two-parameters.html#cb684-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb684-2"><a href="two-parameters.html#cb684-2"></a><span class="st">  </span><span class="kw">lm</span>(age <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> .) <span class="op">%&gt;%</span></span>
<span id="cb684-3"><a href="two-parameters.html#cb684-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb684-4"><a href="two-parameters.html#cb684-4"></a><span class="st">  </span><span class="kw">select</span>(conf.low, estimate, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   conf.low estimate conf.high
##      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1     40.1     42.4      44.6</code></pre>
<p>The 95% confidence interval calculated via <code>lm()</code> is, more or less, the same as the one we calculate “by hand” using the bootstrap: 40.03, 44.57. Of course, there is no built-in function for calculating the confidence interval for the 90th percentile, so there is nothing against which to compare the bootstrap calculation of 54.6, 60. Note, however, how the most likely value for the 90th percentile, 60, is also at the end of the confidence interval.</p>
<div id="prediction" class="section level3">
<h3>
<span class="header-section-number">8.2.1</span> Prediction</h3>
<p>Before considering the questions we want to answer with our model of mean height, let’s step back and look at the big picture. All modeling problems look the same:</p>
<p><span class="math display">\[outcome = model + stuff\]</span>
There is an outcome we care about. In this case, it is heights. But it could be anything. This is the thing that we are trying to understand. In order to understand it, we build a model. That takes time and trouble, so much so that we will sometimes forget that no model explains every outcome. There will always be other “stuff” which affects outcomes, influences that our model does not account for, <em>unmodeled variation</em>. Consider a sample from our dataset, augmented with other variables:</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb686-1"><a href="two-parameters.html#cb686-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb686-2"><a href="two-parameters.html#cb686-2"></a><span class="st">  </span><span class="kw">lm</span>(age <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> .) <span class="op">%&gt;%</span></span>
<span id="cb686-3"><a href="two-parameters.html#cb686-3"></a><span class="st">  </span><span class="kw">augment</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb686-4"><a href="two-parameters.html#cb686-4"></a><span class="st">  </span><span class="kw">select</span>(age, .fitted, .resid)</span></code></pre></div>
<pre><code>## # A tibble: 115 x 3
##      age .fitted  .resid
##    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
##  1    31    42.4 -11.4  
##  2    34    42.4  -8.37 
##  3    63    42.4  20.6  
##  4    45    42.4   2.63 
##  5    55    42.4  12.6  
##  6    37    42.4  -5.37 
##  7    53    42.4  10.6  
##  8    36    42.4  -6.37 
##  9    54    42.4  11.6  
## 10    42    42.4  -0.365
## # … with 105 more rows</code></pre>
<p>These three columns capture the three key components of any approach: the outcome (<code>age</code>), the model (<code>.fitted</code>) and the stuff (<code>.resid</code>). The residual is often referred to as the error term, although calling everything we don’t understand an “error” is the height of hubris, as if the fault might in the world, rather than in our own ignorance.</p>
<p>Graphically, we have:</p>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb688-1"><a href="two-parameters.html#cb688-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-2"><a href="two-parameters.html#cb688-2"></a><span class="st">  </span><span class="kw">lm</span>(age <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> .) <span class="op">%&gt;%</span></span>
<span id="cb688-3"><a href="two-parameters.html#cb688-3"></a><span class="st">  </span><span class="kw">augment</span>() <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-4"><a href="two-parameters.html#cb688-4"></a><span class="st">  </span><span class="kw">select</span>(age, .fitted, .resid) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-5"><a href="two-parameters.html#cb688-5"></a><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> <span class="kw">everything</span>()) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-6"><a href="two-parameters.html#cb688-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">panels =</span> <span class="kw">factor</span>(name, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">"age"</span>, <span class="st">".fitted"</span>, <span class="st">".resid"</span>))) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb688-7"><a href="two-parameters.html#cb688-7"></a><span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span></span>
<span id="cb688-8"><a href="two-parameters.html#cb688-8"></a><span class="st">    </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> value), <span class="dt">bins =</span> <span class="dv">30</span>) <span class="op">+</span></span>
<span id="cb688-9"><a href="two-parameters.html#cb688-9"></a><span class="st">    </span><span class="kw">facet_grid</span>(<span class="dt">cols =</span> <span class="kw">vars</span>(panels))</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-471-1.png" width="672"></p>
<!-- DK: Clean up this plot and make it much prettier. Add labels to connect with both the outcome, model, stuff formulation above and with the $y$, $\hat{u}$, $\epsilon$ notation. Should also add a nice caption explaining it all again.  -->
<p>In order to answer questions with this model, we need to use the <code>simulate()</code> function.</p>
<div class="sourceCode" id="cb689"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb689-1"><a href="two-parameters.html#cb689-1"></a>lm.obj &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb689-2"><a href="two-parameters.html#cb689-2"></a><span class="st">  </span><span class="kw">lm</span>(age <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> .) </span>
<span id="cb689-3"><a href="two-parameters.html#cb689-3"></a></span>
<span id="cb689-4"><a href="two-parameters.html#cb689-4"></a><span class="kw">simulate</span>(lm.obj, <span class="dt">seed =</span> <span class="dv">9</span>)</span></code></pre></div>
<pre><code>##     sim_1
## 1      33
## 2      32
## 3      41
## 4      39
## 5      48
## 6      28
## 7      57
## 8      42
## 9      39
## 10     38
## 11     58
## 12     37
## 13     43
## 14     39
## 15     65
## 16     32
## 17     41
## 18     10
## 19     53
## 20     34
## 21     64
## 22     45
## 23     39
## 24     54
## 25     34
## 26     75
## 27     45
## 28     34
## 29     47
## 30     47
## 31     31
## 32     38
## 33     55
## 34     44
## 35     43
## 36     30
## 37     47
## 38     32
## 39     47
## 40     44
## 41     33
## 42     18
## 43     33
## 44     47
## 45     63
## 46     40
## 47     30
## 48     26
## 49     30
## 50     35
## 51     64
## 52     36
## 53     32
## 54     43
## 55     40
## 56     29
## 57     45
## 58     47
## 59     70
## 60     57
## 61     46
## 62     28
## 63     48
## 64     47
## 65     35
## 66     32
## 67     39
## 68     61
## 69     49
## 70     61
## 71     45
## 72     18
## 73     32
## 74     36
## 75     46
## 76     39
## 77     60
## 78     53
## 79     31
## 80     42
## 81     44
## 82     30
## 83     44
## 84     58
## 85     28
## 86     45
## 87     52
## 88     33
## 89     23
## 90     53
## 91     38
## 92     34
## 93     31
## 94     51
## 95     37
## 96     39
## 97     34
## 98     52
## 99     24
## 100    48
## 101    54
## 102    39
## 103    50
## 104    28
## 105    50
## 106    33
## 107    43
## 108    22
## 109    32
## 110    46
## 111    44
## 112    44
## 113    49
## 114    41
## 115    54</code></pre>
<!-- DK: Should also add a "validity" or "representativeness" discussion about what population this estimate applies to. All people? All people in Boston? All Boston commuters? Do we need to get into prediction stuff? Discuss the weird appearance of the plot for the 90th percentile? -->
</div>
</div>
<div id="age-as-a-function-of-party" class="section level2">
<h2>
<span class="header-section-number">8.3</span> <code>age</code> as a function of <code>party</code>
</h2>
<p>But what if, instead of having no other information about our sample beyond their ages, we also knew their political party? How would we make a model which included this other information? This is a model for prediction, rather than a model for causal inference, because <code>age</code> can not be changed regardless what happens to <code>party</code>. That is, someone’s age is the same regardless of the party of which they are a member.</p>
<p>The simplest model would be to guess that a person’s age, conditional on their party membership, is equal to the mean age of people in that party.</p>
<div class="sourceCode" id="cb691"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb691-1"><a href="two-parameters.html#cb691-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb691-2"><a href="two-parameters.html#cb691-2"></a><span class="st">  </span><span class="kw">group_by</span>(party) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb691-3"><a href="two-parameters.html#cb691-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">age_average =</span> <span class="kw">mean</span>(age))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   party      age_average
##   &lt;chr&gt;            &lt;dbl&gt;
## 1 Democrat          42.6
## 2 Republican        41.2</code></pre>
<p>If a new Boston commuter named Jake showed up at the station, what would be a good guess as to their age? If you don’t know anything else about this person, then guessing the mean age of the sample, 42.4 makes sense, as we learned in Chapter <a href="one-parameter.html#one-parameter">7</a>. But, if we know that the person is a Republican, than this guess would be (slightly) too high. Among the population of Boston commuters, (it seems that) Republican’s are younger than average. So, conditional on knowing that Jake is a Republican, we should guess that his age is 41.2.</p>
<p>However, instead of calculating these averages by hand, it is more convenient to use <code>lm()</code>, a function for creating linear statistical models. Start by estimating a simple model:</p>
<div class="sourceCode" id="cb694"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb694-1"><a href="two-parameters.html#cb694-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb694-2"><a href="two-parameters.html#cb694-2"></a><span class="st">  </span><span class="kw">lm</span>(<span class="dt">data =</span> ., age <span class="op">~</span><span class="st"> </span>party <span class="op">-</span><span class="st"> </span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = age ~ party - 1, data = .)
## 
## Coefficients:
##   partyDemocrat  partyRepublican  
##            42.6             41.2</code></pre>
<p>Our predictive model’s estimates are the same as the averages we calculated because that’s most helpful number in estimating the age of an individual in the dataset knowing only their party, at least with our current set of tools.</p>
<div id="model-structure-1" class="section level3">
<h3>
<span class="header-section-number">8.3.1</span> Model Structure</h3>
<p>The initials “lm” stand for “linear model.” We are creating a model in which age is a function of party. The “-1” term causes the model to provide us with the mean for each group. The coefficient estimates are the same as the mean values for age within each party.</p>
<p>There are three parts of understanding any model structure: whether it is causal or predictive, the mathematical formula, and realism. This model is predictive and has nothing to do with causality. Rather than modelling how the explanatory variable will change the outcome variable, we are using the explanatory variable (party) to simply predict the outcome variable (age). The difference between these two model types becomes clear when we construct a Preceptor Table:</p>
<!-- MB: The table is centered here but not in the html ... -->
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#mwnldxeqiq .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#mwnldxeqiq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwnldxeqiq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#mwnldxeqiq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#mwnldxeqiq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwnldxeqiq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#mwnldxeqiq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#mwnldxeqiq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#mwnldxeqiq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#mwnldxeqiq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#mwnldxeqiq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#mwnldxeqiq .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#mwnldxeqiq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#mwnldxeqiq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#mwnldxeqiq .gt_from_md > :first-child {
  margin-top: 0;
}

#mwnldxeqiq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#mwnldxeqiq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#mwnldxeqiq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#mwnldxeqiq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwnldxeqiq .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#mwnldxeqiq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#mwnldxeqiq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#mwnldxeqiq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#mwnldxeqiq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwnldxeqiq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#mwnldxeqiq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#mwnldxeqiq .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#mwnldxeqiq .gt_left {
  text-align: left;
}

#mwnldxeqiq .gt_center {
  text-align: center;
}

#mwnldxeqiq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#mwnldxeqiq .gt_font_normal {
  font-weight: normal;
}

#mwnldxeqiq .gt_font_bold {
  font-weight: bold;
}

#mwnldxeqiq .gt_font_italic {
  font-style: italic;
}

#mwnldxeqiq .gt_super {
  font-size: 65%;
}

#mwnldxeqiq .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="mwnldxeqiq" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Preceptor Table of age ~ party</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>ID</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Age</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Party</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>34</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Republican</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>2</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>55</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>36</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>204</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>44</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>205</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>1,627</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>50</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Republican</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>N</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
</tbody>
</table></div>
<p>The purpose of a Preceptor Table is to capture all of the data such that if the question marks were filled out, one wouldn’t need to construct a model. The rows in this Preceptor Table represent the N commuters on which our model is extrapolating, with N being the population of commuters using Boston public transportation. Only 115 of these commuters had their data recorded in the experiment, which is why most observations lack data.</p>
<p>This table is very simple, which is the point. There is no causal effect as we are simply trying to predict the immutable variable of age. Rather than representing unknown causal effects as they may in other Preceptor Tables, the question marks in this table simply denote missing data.</p>
<p>This mathematical formula will also help us better understand the model:</p>
<p><span class="math display">\[ y_i = b_1 x_r + b_2 x_d \]</span></p>
<p>You couldn’t know the true value of our parameters (<span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_2\)</span>) unless you surveyed every single commuter in the station. This is why we use models to give us estimates. A hat denotes a number that is constant and no longer variable. Because we have estimates for our parameters, <span class="math inline">\(\hat{b_1}\)</span> and <span class="math inline">\(\hat{b_1}\)</span> are denoted by hats. With these numbers plugged in, you determine a singular y value (age) for each observation, thus the denotation <span class="math inline">\(\hat{y_i}\)</span>. This is called the <em>fitted value</em>.</p>
<p><span class="math display">\[ \hat{y_i} = \hat{b_1} x_r + \hat{b_2} x_d  \]</span>
<span class="math display">\[ \hat{y_i} = 41.16 x_r + 42.6x_d \]</span>
When the individual is a Republican (<span class="math inline">\(x_r\)</span>=1 and <span class="math inline">\(x_d\)</span>=0), their fitted value is 41.16. When the individual is a Democrat (<span class="math inline">\(x_r\)</span>=0 and <span class="math inline">\(x_d\)</span>=1), their fiited value is 42.6.</p>
<p>The equation is not finished yet!</p>
<p><span class="math display">\[\epsilon_i = y_i - \hat{y_i}\]</span>
In order to calculate each observation’s residual, you subtract the observation’s age by their fitted value.</p>
<p><span class="math display">\[ y_i = \hat{b_1}x_r + \hat{b_2} x_d + \epsilon_i \]</span>
Once you do this, you have a complete equation.</p>
<p>To continue our discussion of these values, we’ll bring back our table. We’ll display a few specific observations (all of which had their data recorded) rather than representing all N commuters.</p>
<p>This time, we’ll include each individual’s fitted value for age from our model. We’ll also include their residual. Remember that the actual age of each observation, <span class="math inline">\(y_i\)</span>, is the addition of the model’s prediction (the fitted value) and real-world noise (the residual).</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wuzhuiuqvw .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wuzhuiuqvw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wuzhuiuqvw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wuzhuiuqvw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wuzhuiuqvw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wuzhuiuqvw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wuzhuiuqvw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wuzhuiuqvw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wuzhuiuqvw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wuzhuiuqvw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wuzhuiuqvw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wuzhuiuqvw .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wuzhuiuqvw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wuzhuiuqvw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wuzhuiuqvw .gt_from_md > :first-child {
  margin-top: 0;
}

#wuzhuiuqvw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wuzhuiuqvw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wuzhuiuqvw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#wuzhuiuqvw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wuzhuiuqvw .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#wuzhuiuqvw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wuzhuiuqvw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wuzhuiuqvw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wuzhuiuqvw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wuzhuiuqvw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#wuzhuiuqvw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wuzhuiuqvw .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#wuzhuiuqvw .gt_left {
  text-align: left;
}

#wuzhuiuqvw .gt_center {
  text-align: center;
}

#wuzhuiuqvw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wuzhuiuqvw .gt_font_normal {
  font-weight: normal;
}

#wuzhuiuqvw .gt_font_bold {
  font-weight: bold;
}

#wuzhuiuqvw .gt_font_italic {
  font-style: italic;
}

#wuzhuiuqvw .gt_super {
  font-size: 65%;
}

#wuzhuiuqvw .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="wuzhuiuqvw" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="5" class="gt_heading gt_title gt_font_normal" style>8 Observations from Trains Dataset</th>
    </tr>
<tr>
<th colspan="5" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>ID</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Party</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$y_i$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>fitted</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>residual</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>4</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>31</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>42.6</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>11.6</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>5,051</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Republican</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>34</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>41.1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>7.1</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>76</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>63</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>42.6</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>-20.4</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>80,050</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>45</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>42.6</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>-2.4</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>578</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Republican</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>55</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>41.1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>-13.9</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>23</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>53</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>42.6</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>-10.4</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>9,088</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Republican</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>24</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>41.1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>17.1</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>888</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>Democrat</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>45</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>42.6</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>-2.4</p>
</div></td>
    </tr>
</tbody>
</table></div>
<p>The fitted values are the same for all Republicans and for all Democrats, as the fitted value is one of the two estimates output by our model. However, almost all of the residuals are different due to each observation’s own variation from the fitted value estimate. The only observations with the same residual are 80,050 and 888. This is because they are both Democrats that are the same age: with the same <span class="math inline">\(y_i\)</span> and <span class="math inline">\(\hat{y_i}\)</span>, the calculation of their epsilon values are identical. This table shows how just a sample of 8 individuals captures a wide range of residuals, making it difficult to predict the age of a new individual who walks in the room even using our model.</p>
<p>The final aspect of model structure is realism. Ask yourself, does this model reflect the real world accurately? What are its advantages and disadvantages?</p>
</div>
<div id="parameter-uncertainty-1" class="section level3">
<h3>
<span class="header-section-number">8.3.2</span> Parameter Uncertainty</h3>
<p>How uncertain are our estimates for age? Again, we use the same tools we have used before:</p>
<div class="sourceCode" id="cb696"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb696-1"><a href="two-parameters.html#cb696-1"></a>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb696-2"><a href="two-parameters.html#cb696-2"></a><span class="st">  </span><span class="kw">lm</span>(<span class="dt">data =</span> ., age <span class="op">~</span><span class="st"> </span>party <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb696-3"><a href="two-parameters.html#cb696-3"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb696-4"><a href="two-parameters.html#cb696-4"></a><span class="st">  </span><span class="kw">select</span>(term, conf.low, estimate, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   term            conf.low estimate conf.high
##   &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 partyDemocrat       40.1     42.6      45.1
## 2 partyRepublican     35.6     41.2      46.7</code></pre>
<p>The confidence intervals that we’ve generated display the upper and lower bounds of the mean age of Democrat and Republican commuters on this train platform. This touches on the idea of <strong>parameter uncertainty</strong>: even if a model is constructed in a logical way, we are unable to know our parameters exactly, the parameters in this case being the mean ages of the two parties. Confidence intervals are one way to capture this uncertainty, so that we don’t over-confidently put forward one value rather than a range.</p>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb698-1"><a href="two-parameters.html#cb698-1"></a>trains <span class="op">%&gt;%</span></span>
<span id="cb698-2"><a href="two-parameters.html#cb698-2"></a><span class="st">  </span><span class="kw">group_by</span>(party) <span class="op">%&gt;%</span></span>
<span id="cb698-3"><a href="two-parameters.html#cb698-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">n</span>())</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   party      `n()`
##   &lt;chr&gt;      &lt;int&gt;
## 1 Democrat      96
## 2 Republican    19</code></pre>
<p>You may notice how the range of the confidence interval for Republicans is larger. This may be because far fewer Republicans were surveyed than Democrats – 19 to 96. Parameter estimates are always exclusively based on the data that the model is fed, so factors like sample size can impact our parameter uncertainty. With more data to work with, we can more accurately capture the true mean age of the Democrat commuters.</p>
</div>
<div id="unmodeled-variation-1" class="section level3">
<h3>
<span class="header-section-number">8.3.3</span> Unmodeled Variation</h3>
<p>If a new Democrat entered the train station, how easy would it be to guess their age with our model? Could you confidently say that they would be within the Democrat interval bounds of 40 and 45?</p>
<p><span class="math display">\[ y_i = b_0 + b_1 x_i + \epsilon_i \]</span></p>
<p>One shouldn’t be too confident in that prediction. As discussed, the new Democrat’s age comes in two parts: the beta (determined by their political party) and their residual (how much noise there is in this observation that offsets it from the beta prediction). While the beta values have been determined by our model, the epsilon value represents <em>unmodeled variation</em> that could likely put the value outside of these bounds. Our previous example showed us how just a randomly selected handful can have greatly varying residuals due to the real-world variation that is not captured by the model.</p>
<!-- DK: I went fast above, but that is all the key material. Still need to add a Rubin Table example, highlighting that this is modeling for prediction. There is only one column for Y because it is impossible to change someone's age, whatever manipulations you make to party. -->
<!-- DK: Is the below text from previous versions worth keeping? -->
<!-- In the original dataset — and therefore, most likely for the majority of the bootstrapped samples — the number of democratic subjects vastly outnumber the number of republican subjects. Why does this lead to wider confidence intervals? -->
<!-- Intuitively, we can think about the matter like this: since we have more data to work with for the democratic party, we are more confident that the mean income measurement from each bootstrapped sample is representative of the *true mean income of that sample* — remember, this "true value" is what we're trying to approximate through the bootstrapping process. This idea is more obvious on an extreme scale: if we were given one billion individuals' incomes, we'd feel more comfortable approximating the world's average income from that dataset than if we only had two individual's incomes to work with. These two individuals could be impoverished, or they could be billionaires, and we wouldn't reliably make any conclusions regarding world income based on those two individuals alone. Because there are far more democrats in the original sample than there are republicans, we are therefore more confident that the democrats' true average income is represented by the democratic subset of the data than we are of the republicans' true average income being accurately represented by the republican subset. -->
<!-- The math behind the confidence INTERVALS specifically is a little more complex, but the premise behind it is simple. First, recall that bootstrapping with replacement creates different assortments of the data due to the possibility of data points being omitted from each sample, or values being included more than once. If I was sampling with replacement from the list of 1, 2, 3, 4, 5, One replicate might include "1" three times, while another might include "1" zero times. -->
<!-- It is because of this possibility for omission/duplicate inclusion that subsets with small sample sizes are at the mercy of being misrepresented by sampling with replacement. In small sample sizes, individual points carry significant weight. As a result, we are more likely to get extreme values — values that are unreasonably small or large — the smaller the size of the subset. -->
<!-- As it relates to the `trains` dataset, the subset with the larger sample size, the democrat contingent, is less susceptible from this because each data point carries far less weight — each one gets drowned out by the many other democrats in the dataset, and removing or duplicating a single or even a few data points won't drastically shift measurements, such as mean and median, for most of the bootstrap samples. However, for the smaller republican subset, even a single omission or double inclusion of a data point through bootstrapping with replacement could generate extreme values for these measurements. -->
<!-- In short: If we have fewer data points, bootstrap parameter calculations are more likely to be further from the true values, and our confidence intervals will be wider as a result. It's important to understand the mechanics behind these relationships as we continue our work with confidence intervals going forward. -->
</div>
</div>
<div id="estimate-other-things" class="section level2">
<h2>
<span class="header-section-number">8.4</span> Estimate other things</h2>
<!-- Often functions of these parameters, which are, after all, just functions of the bootstrap samples. Consider the difference in income between treated and control. Again, this is a case in which we know every number. There is no missing data. So, we can calculate exactly the average income for control and the average income for treated, as we did above. With those two parameters estimated, we can calculate the average difference between the two --- or the difference between the averages, which is the same thing because all this is linear. But what about the uncertainty of that difference? Again, the bootstrap comes to our rescue. What does the 95% confidence interval of the difference look like? Does it include zero? Would we expect it to? How does randomization of treatment/control figure in? -->
</div>
<div id="estimate-trickier-things" class="section level2">
<h2>
<span class="header-section-number">8.5</span> Estimate trickier things</h2>
<!-- Explain how the above is a bit of a cheat since linear functions are special: the average difference is the same as the difference between the averages. This is an important point. But there are lots of things which are not like that! Consider the income ratio between the median treated and median control. This is something which, a priori, I might be as interested in as the difference in means. But the ratio of the medians is not the same thing as the median of the ratios! This is a key point. In order to calculate this, we need to, again, take the bootstrap and, in each bootstrap sample, calculate the median income of the treated, the median income of the controls, and record that ratio. We then save that ratio and look at its bootstrap distribution at the end of the exercise. -->
<!-- EM: I feel like having "Estimate other things" and "Estimate trickier things" are redundant as chapter sections because they are mostly addressed through the sections that sandwich them.  -->
<div id="validity" class="section level4">
<h4>
<span class="header-section-number">8.5.0.1</span> Validity</h4>
<p>We just spent a ton of time analyzing the relationship between party and income in Enos’ study. Although we have already accounted for parameter uncertainty (the confidence intervals) and unmodeled variation uncertainty (the prediction intervals), we have not accounted for the <em>validity</em> of his model — that is, whether the ideas he wishes to capture are truly represented by the data he collects.</p>
<p>For example, take the <code>income</code> variable. How do you answer this question if you, having made a fortune years ago, are currently earning an income of zero? How do you answer it if you are one-half of a married couple — is it both your incomes combined, your incomes divided by two, or some other calculation? Enos really means to distinguish between poorer and richer subjects through this measure, but the ambiguity in the question “what is your income” makes us doubt whether the income figures truly help us distinguish between these two types of people.</p>
<p>Another variable which, troublingly, raises concerns regarding validity is the <code>att_end</code> variable. Through this variable, Enos hopes to measure how people’s political attitudes change, and the implications this could have for the political landscape of the United States— however, what he is truly measuring is how people respond to his specific survey questions, which required responses on a scale of 1-5 and were aggregated and scaled to a total out of 15. What if he asked people to respond on a scale of 1-3, or a scale of 1-30? We do not mean to say that his choices were unreasonable — rather, we think it is important to note that he would have gotten very different answers using different reasonable choices. <strong>If you’re running Trump’s 2020 campaign, you don’t care about how people filled out Enos’ specific survey. You care about the statistics that data claims to represent</strong>.</p>
<p>It is always important to keep the problem of validity in the back of our minds as we investigate data sets and how the data within these sets are collected. Given the many factors — those we are aware of and those we are not aware of — that go into any kind of data collection, there is no way to guarantee 100 percent validity.</p>
</div>
<div id="unknown-unknowns-1" class="section level4">
<h4>
<span class="header-section-number">8.5.0.2</span> Unknown unknowns</h4>
<p>Yet another area of uncertainty that might not be immediately obvious is the possibiity of unknown unknowns — that is, all the things that might change with time. How do we know that our model — which relies heavily on figures like income and party affiliation — will still be able to draw conclusions about America 50 years from now? Mass migrations, political revolutions, and world wars are just a few of the things that could render all the conclusions we draw from the <code>trains</code> dataset moot. And, other than expanding our confidence intervals to the point of uselessness, there’s no way to account for the unknown unknowns.</p>
<p>In short, <em>while we can accept the model as representative of the United States at or around 2012 (the year in which Enos conducted his study), we cannot reasonably extrapolate that to the far future</em>.</p>
<p>It is always important to keep the problem of validity in the back of our minds as we investigate data sets and how the data within these sets are collected. Given the many factors — those we are aware of and those we are not aware of — that go into any kind of data collection, there is no way to guarantee 100 percent validity.</p>
</div>
</div>
<div id="att_end-as-a-function-of-treatment" class="section level2">
<h2>
<span class="header-section-number">8.6</span> <code>att_end</code> as a function of <code>treatment</code>
</h2>
<p>Let’s establish the two types of models we’ve studied thus far. What we explored above was a predictive model: with someone’s party affiliation, we can make a better guess as to what their age is. In this example, we’ll explore a causal model, looking for the casual effect of randomly assigned treatments on att_end.</p>
<p>Here’s the model using lm():</p>
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb701-1"><a href="two-parameters.html#cb701-1"></a><span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>, )</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = att_end ~ treatment - 1, data = trains)
## 
## Coefficients:
## treatmentTreated  treatmentControl  
##            10.00              8.45</code></pre>
<p>The <em>fitted value</em> of att_end is 8.45 for the control group and 10 for the treated group. Because a higher att_end means more conservative towards stances on immigration, it seems that treated individuals had more conservative stances on this issue than the control group by the end of the study.</p>
<div id="model-structure-2" class="section level3">
<h3>
<span class="header-section-number">8.6.1</span> Model Structure</h3>
<p>Our predictive model helped us make guesses as to what an individual’s age is. However, that’s just about all we can do with this relationship. Recall that the trains dataset was originally introduced in the context of the Rubin Causal Model back in Chapter <a href="rubin-causal-model.html#rubin-causal-model">3</a>. That model cannot be applied to the relationship between party and income because these values were independently decided outside the experiment — although we were able to identify correlations between those two variables, the combinations of party and income were predetermined and not randomly assigned in a way that allows us to establish a causal relationship. If an individual suddenly decided to change party affiliations, we wouldn’t suddenly expect his or her income to spike or plummet.</p>
<p>In conclusion, while we can explore correlations or trends between party and income, we cannot label these correlations or trends as causal. However, <code>treatment</code> was a variable that was randomly assigned to subjects, and we have a variable that was measured after this random assignment, <code>att_end</code>. With this setup, we can calculate the Average Treatment Effect, or the average difference in <code>att_end</code> for treated subjects and control subjects.</p>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb703-1"><a href="two-parameters.html#cb703-1"></a>mean_ends &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb703-2"><a href="two-parameters.html#cb703-2"></a><span class="st">  </span><span class="kw">group_by</span>(treatment) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb703-3"><a href="two-parameters.html#cb703-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_att_end =</span> <span class="kw">mean</span>(att_end))</span></code></pre></div>
<div class="sourceCode" id="cb704"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb704-1"><a href="two-parameters.html#cb704-1"></a>ATE &lt;-<span class="st"> </span>mean_ends<span class="op">$</span>mean_att_end[<span class="dv">2</span>] <span class="op">-</span><span class="st"> </span>mean_ends<span class="op">$</span>mean_att_end[<span class="dv">1</span>]</span></code></pre></div>
<p>Now, let’s make a Preceptor Table for this data:</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#xqtbywsmes .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#xqtbywsmes .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqtbywsmes .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#xqtbywsmes .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#xqtbywsmes .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqtbywsmes .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#xqtbywsmes .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#xqtbywsmes .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#xqtbywsmes .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#xqtbywsmes .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#xqtbywsmes .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#xqtbywsmes .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#xqtbywsmes .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#xqtbywsmes .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#xqtbywsmes .gt_from_md > :first-child {
  margin-top: 0;
}

#xqtbywsmes .gt_from_md > :last-child {
  margin-bottom: 0;
}

#xqtbywsmes .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#xqtbywsmes .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#xqtbywsmes .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqtbywsmes .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#xqtbywsmes .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#xqtbywsmes .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#xqtbywsmes .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#xqtbywsmes .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqtbywsmes .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#xqtbywsmes .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#xqtbywsmes .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#xqtbywsmes .gt_left {
  text-align: left;
}

#xqtbywsmes .gt_center {
  text-align: center;
}

#xqtbywsmes .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#xqtbywsmes .gt_font_normal {
  font-weight: normal;
}

#xqtbywsmes .gt_font_bold {
  font-weight: bold;
}

#xqtbywsmes .gt_font_italic {
  font-style: italic;
}

#xqtbywsmes .gt_super {
  font-size: 65%;
}

#xqtbywsmes .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="xqtbywsmes" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Preceptor Table of att_end ~ treatment</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>ID</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>treatment</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>att_end</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>1</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>treated</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>11</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>2</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>75</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>control</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>5</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>564</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>control</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>13</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>565</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>10,627</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>treated</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>11</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>...</p>
</div></td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;"><div class="gt_from_md">
<p>N</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
      <td class="gt_row gt_center"><div class="gt_from_md">
<p>?</p>
</div></td>
    </tr>
</tbody>
</table></div>
<p>Preceptor Tables aim to capture all of the data such that if the question marks were filled out, one wouldn’t need to construct a model. The rows in this Preceptor Table represent the N commuters on which our model is extrapolating, with N being the population of commuters using Boston public transportation. However, we’re going to need a different kind of table if we want to display the causal effect of being treated – more with this soon.</p>
<p>Next, the second part of model structure, the formula.</p>
<p><span class="math display">\[ y_i = b_1 x_t + b_2 x_c\]</span>
Once again, we start here. We can make our parameters constants, <span class="math inline">\(\hat{b_1}\)</span> and <span class="math inline">\(\hat{b_1}\)</span>, by assigning them to the estimates of the model. Plugging in these numbers outputs an estimated att_end for the observation, or our <em>fitted value</em> <span class="math inline">\(\hat{y_i}\)</span>.</p>
<p><span class="math display">\[ \hat{y_i} = \hat{b_1} x_t + \hat{b_2} x_c  \]</span>
<span class="math display">\[ \hat{y_i} = 8.45x_t + 10x_c \]</span>
When the individual is treated (<span class="math inline">\(x_t\)</span>=1 and <span class="math inline">\(x_c\)</span>=0), their fitted value is 8.45. When the individual is a control (<span class="math inline">\(x_t\)</span>=0 and <span class="math inline">\(x_c\)</span>=1), their fiited value is 42.6.</p>
<p>Subtract the recorded att_end by fitted value for the epsilon value…
<span class="math display">\[\epsilon_i = y_i - \hat{y_i}\]</span>
…And you can now complete your equation.
<span class="math display">\[ y_i = \hat{b_1}x_r + \hat{b_2} x_d + \epsilon_i \]</span>
Note that the math for both the predictive model we worked on earlier and this model is <em>identical</em>. It is not the calculations for the residual, fitted value, or parameter estimates that differ between these two model types; rather, it is how one uses and interprets these numbers. While predictive models are simply used for predicting another variable’s value (in the previous case, age), we can use these numbers to calculate the effect of one variable (treatment) on another (att_end) for each individual observation.</p>
<p>Now, we’ll create a Rubin Causal Model table of possible outcomes, as we did back in ch3. We’ll do this using 7 random observations from the trains dataset.</p>
<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb705-1"><a href="two-parameters.html#cb705-1"></a><span class="co">#Adding question marks where necessary</span></span>
<span id="cb705-2"><a href="two-parameters.html#cb705-2"></a></span>
<span id="cb705-3"><a href="two-parameters.html#cb705-3"></a>trains_RCM &lt;-<span class="st"> </span>trains <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb705-4"><a href="two-parameters.html#cb705-4"></a><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> treatment, <span class="dt">values_from =</span> att_end) <span class="op">%&gt;%</span></span>
<span id="cb705-5"><a href="two-parameters.html#cb705-5"></a><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">7</span>) <span class="op">%&gt;%</span></span>
<span id="cb705-6"><a href="two-parameters.html#cb705-6"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">subject =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">7</span>) <span class="op">%&gt;%</span></span>
<span id="cb705-7"><a href="two-parameters.html#cb705-7"></a><span class="st">  </span><span class="kw">replace_na</span>(<span class="kw">list</span>(<span class="dt">Treated =</span> <span class="st">"?"</span>, <span class="dt">Control =</span> <span class="st">"?"</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb705-8"><a href="two-parameters.html#cb705-8"></a><span class="st">  </span><span class="kw">select</span>(subject, Control, Treated)</span>
<span id="cb705-9"><a href="two-parameters.html#cb705-9"></a></span>
<span id="cb705-10"><a href="two-parameters.html#cb705-10"></a>trains_RCM<span class="op">$</span>subject &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">"7"</span>, <span class="st">"6,041"</span>, <span class="st">"67"</span>, <span class="st">"40,080"</span>, <span class="st">"758"</span>, <span class="st">"32"</span>, <span class="st">"8,809"</span>)</span>
<span id="cb705-11"><a href="two-parameters.html#cb705-11"></a></span>
<span id="cb705-12"><a href="two-parameters.html#cb705-12"></a><span class="co">#Mathematical notation</span></span>
<span id="cb705-13"><a href="two-parameters.html#cb705-13"></a></span>
<span id="cb705-14"><a href="two-parameters.html#cb705-14"></a>trains_RCM <span class="op">%&gt;%</span></span>
<span id="cb705-15"><a href="two-parameters.html#cb705-15"></a><span class="st">  </span><span class="kw">gt</span>() <span class="op">%&gt;%</span></span>
<span id="cb705-16"><a href="two-parameters.html#cb705-16"></a><span class="st">  </span><span class="kw">cols_label</span>(<span class="dt">subject =</span> <span class="kw">md</span>(<span class="st">"**Subject**"</span>),</span>
<span id="cb705-17"><a href="two-parameters.html#cb705-17"></a>                <span class="dt">Control =</span> <span class="kw">md</span>(<span class="st">"**$$Y_c(u)$$**"</span>),</span>
<span id="cb705-18"><a href="two-parameters.html#cb705-18"></a>                <span class="dt">Treated =</span> <span class="kw">md</span>(<span class="st">"**$$Y_t(u)$$**"</span>)) <span class="op">%&gt;%</span></span>
<span id="cb705-19"><a href="two-parameters.html#cb705-19"></a><span class="st">  </span><span class="kw">tab_style</span>(<span class="kw">cell_borders</span>(<span class="dt">sides =</span> <span class="st">"right"</span>),</span>
<span id="cb705-20"><a href="two-parameters.html#cb705-20"></a>            <span class="dt">location =</span> <span class="kw">cells_body</span>(<span class="dt">columns =</span> <span class="kw">vars</span>(subject))) <span class="op">%&gt;%</span></span>
<span id="cb705-21"><a href="two-parameters.html#cb705-21"></a><span class="st">  </span><span class="kw">cols_align</span>(<span class="dt">align =</span> <span class="st">"center"</span>, <span class="dt">columns =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb705-22"><a href="two-parameters.html#cb705-22"></a><span class="st">  </span><span class="kw">tab_header</span>(<span class="dt">title =</span> <span class="st">"Ending Attitudes on Immigration of 7 Random Respondents"</span>)</span></code></pre></div>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#jcjpwfnqom .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jcjpwfnqom .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jcjpwfnqom .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jcjpwfnqom .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jcjpwfnqom .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jcjpwfnqom .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jcjpwfnqom .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jcjpwfnqom .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jcjpwfnqom .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jcjpwfnqom .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jcjpwfnqom .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jcjpwfnqom .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#jcjpwfnqom .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jcjpwfnqom .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jcjpwfnqom .gt_from_md > :first-child {
  margin-top: 0;
}

#jcjpwfnqom .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jcjpwfnqom .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jcjpwfnqom .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#jcjpwfnqom .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jcjpwfnqom .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#jcjpwfnqom .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jcjpwfnqom .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jcjpwfnqom .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jcjpwfnqom .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jcjpwfnqom .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#jcjpwfnqom .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jcjpwfnqom .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#jcjpwfnqom .gt_left {
  text-align: left;
}

#jcjpwfnqom .gt_center {
  text-align: center;
}

#jcjpwfnqom .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jcjpwfnqom .gt_font_normal {
  font-weight: normal;
}

#jcjpwfnqom .gt_font_bold {
  font-weight: bold;
}

#jcjpwfnqom .gt_font_italic {
  font-style: italic;
}

#jcjpwfnqom .gt_super {
  font-size: 65%;
}

#jcjpwfnqom .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="jcjpwfnqom" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">?</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">?</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">?</td>
    </tr>
</tbody>
</table></div>
<p>Recall that the Rubin Causal Model centers on filling in the unknowns, which are indicated by the “?”s in the table. There’s one way we could fill in the missing values — we could use our approximations we generated with our <code>lm()</code> model: that is, for each unknown Treated value, we use 10, and for each unknown Control value, we use 8.45.</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#ypsouxzuce .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ypsouxzuce .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ypsouxzuce .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ypsouxzuce .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ypsouxzuce .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ypsouxzuce .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ypsouxzuce .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ypsouxzuce .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ypsouxzuce .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ypsouxzuce .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ypsouxzuce .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ypsouxzuce .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#ypsouxzuce .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ypsouxzuce .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ypsouxzuce .gt_from_md > :first-child {
  margin-top: 0;
}

#ypsouxzuce .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ypsouxzuce .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ypsouxzuce .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#ypsouxzuce .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypsouxzuce .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#ypsouxzuce .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ypsouxzuce .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ypsouxzuce .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ypsouxzuce .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ypsouxzuce .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#ypsouxzuce .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ypsouxzuce .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#ypsouxzuce .gt_left {
  text-align: left;
}

#ypsouxzuce .gt_center {
  text-align: center;
}

#ypsouxzuce .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ypsouxzuce .gt_font_normal {
  font-weight: normal;
}

#ypsouxzuce .gt_font_bold {
  font-weight: bold;
}

#ypsouxzuce .gt_font_italic {
  font-style: italic;
}

#ypsouxzuce .gt_super {
  font-size: 65%;
}

#ypsouxzuce .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="ypsouxzuce" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">10</td>
    </tr>
</tbody>
</table></div>
<p>This table looks a bit funky: take a look at subject 67. According to this model, subject 67’s attitude under control would be HIGHER than his/her attitude under treatment, which corresponds to a negative treatment effect. This would mean that he/she would become more LIBERAL after undergoing treatment, which flies in the face of the ATE we calculated earlier. Another example of this can be seen with subject 32, whose predicted <code>att_end</code> under treatment is lower than his/her <code>att_end</code> under control (also signifying a shift towards liberal attitudes regarding immigration).</p>
<p>Clearly, using the same control and treatment values to fill in the unknowns doesn’t capture the entire picture as it does with a predictive model. While using <code>lm()</code> to fill in the <code>att_end</code> unknowns towards the center of the distribution, it makes less sense for values towards the outskirts of the dataset. So, how can we predict outcomes in a way that equally addresses data towards the center of the distribution, and data that isn’t?</p>
<p>One such way is by attaching the ATE, which we previously calculated to be -1.55, in the appropriate direction to fill in the unknowns:</p>
<pre><code>## # A tibble: 2 x 4
##   term             estimate conf.low conf.high
##   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)          8.45    7.77       9.14
## 2 treatmentTreated     1.55    0.514      2.58</code></pre>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#zcscnhzelg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zcscnhzelg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zcscnhzelg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zcscnhzelg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zcscnhzelg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zcscnhzelg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zcscnhzelg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zcscnhzelg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zcscnhzelg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zcscnhzelg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zcscnhzelg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zcscnhzelg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#zcscnhzelg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zcscnhzelg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zcscnhzelg .gt_from_md > :first-child {
  margin-top: 0;
}

#zcscnhzelg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zcscnhzelg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zcscnhzelg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#zcscnhzelg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zcscnhzelg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#zcscnhzelg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zcscnhzelg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zcscnhzelg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zcscnhzelg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zcscnhzelg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#zcscnhzelg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zcscnhzelg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#zcscnhzelg .gt_left {
  text-align: left;
}

#zcscnhzelg .gt_center {
  text-align: center;
}

#zcscnhzelg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zcscnhzelg .gt_font_normal {
  font-weight: normal;
}

#zcscnhzelg .gt_font_bold {
  font-weight: bold;
}

#zcscnhzelg .gt_font_italic {
  font-style: italic;
}

#zcscnhzelg .gt_super {
  font-size: 65%;
}

#zcscnhzelg .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="zcscnhzelg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">9.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">3.45</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">9.45</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">6.55</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">11.45</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">14.55</td>
    </tr>
</tbody>
</table></div>
<p>The usage of this table shows how a causal model is used differently than a predictive model. Unlike before, it wasn’t enough to fill in our unknowns with the parameter estimates. This is because we aren’t merely predicting their att_end, a variable that, unlike age, could be changed by exposure to a treatment variable. By using the ATE, we were able to make a more informed prediction on any individual’s att_end had they been placed in the other group.</p>
</div>
<div id="parameter-uncertainty-2" class="section level3">
<h3>
<span class="header-section-number">8.6.2</span> Parameter Uncertainty</h3>
<p>Here, we see that the average treatment effect is -1.55; this is the average change in att_end caused by treatment (if this statistic looks unfamiliar, refer back to chapter 3 for a refresher on ATE). But how confident are we in this ATE? We can use <code>lm()</code> again to generate confidence intervals for our parameters and for this value:</p>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb707-1"><a href="two-parameters.html#cb707-1"></a><span class="co">#This is necessary so we can see the offset as caused by treatmentTreated, not treatmentControl.</span></span>
<span id="cb707-2"><a href="two-parameters.html#cb707-2"></a></span>
<span id="cb707-3"><a href="two-parameters.html#cb707-3"></a>trains<span class="op">$</span>treatment &lt;-<span class="kw">fct_relevel</span>(trains<span class="op">$</span>treatment, <span class="st">"Control"</span>, <span class="st">"Treated"</span>)</span>
<span id="cb707-4"><a href="two-parameters.html#cb707-4"></a></span>
<span id="cb707-5"><a href="two-parameters.html#cb707-5"></a><span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb707-6"><a href="two-parameters.html#cb707-6"></a><span class="st">  </span><span class="kw">tidy</span>(<span class="dt">conf.int =</span> <span class="ot">TRUE</span>) <span class="op">%&gt;%</span></span>
<span id="cb707-7"><a href="two-parameters.html#cb707-7"></a><span class="st">  </span><span class="kw">select</span>(term, estimate, conf.low, conf.high)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   term             estimate conf.low conf.high
##   &lt;chr&gt;               &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 treatmentControl     8.45     7.77      9.14
## 2 treatmentTreated    10.       9.23     10.8</code></pre>
<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb709-1"><a href="two-parameters.html#cb709-1"></a><span class="kw">summary</span>(<span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment <span class="op">-</span><span class="st"> </span><span class="dv">1</span>))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = att_end ~ treatment - 1, data = trains)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -6.00  -2.00   0.00   2.00   6.55 
## 
## Coefficients:
##                  Estimate Std. Error t value Pr(&gt;|t|)    
## treatmentControl    8.453      0.347    24.4   &lt;2e-16 ***
## treatmentTreated   10.000      0.389    25.7   &lt;2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 2.8 on 113 degrees of freedom
## Multiple R-squared:  0.917,  Adjusted R-squared:  0.916 
## F-statistic:  627 on 2 and 113 DF,  p-value: &lt;2e-16</code></pre>
<!-- MB: Is this true  -->
<p>Our measure of confidence for the ATE is known as the residual standard error, which in this case is 2.78. The residual standard error show our confidence in the average treatment effect of the <code>trains</code> dataset being representative of the true average treatment effect on Boston commuters.</p>
</div>
<div id="uncertainties" class="section level3">
<h3>
<span class="header-section-number">8.6.3</span> Uncertainties</h3>
<p>There are various sources of uncertainties and problems that have addressed in previous chapters and again in this chapter. It’s important that you always have these in the back of your mind when working with data:</p>
<ol style="list-style-type: decimal">
<li><p><em>Validity</em>. At the surface level, parameter names might not invoke too much thought — but once you really sit down and think about the story the numbers are trying to tell, it’s not always the case that the numbers deserve to tell that story. In our earlier discussion regarding <code>income</code> and <code>att_end</code>, the conclusions we draw from these data might be misleading just because the way they were collected or computed inevitably change these conclusions. Even when there’s nothing WRONG with a setup, we need to keep in mind that the smallest differences</p></li>
<li><p>When we dive deeper into the data, we run into the issue of <em>parameter uncertainty</em>, which is the uncertainty associated with our analysis of summary parameters, such as mean, median, and range. In our above analysis with the <code>trains</code> dataset, we account for parameter uncertainty using confidence intervals.</p></li>
<li><p>As great as confidence intervals are, they don’t capture the uncertainty of using summary statistics to predict parameter values of random individuals. We are more sure, for example, about the range of possible incomes for the mean income of American democrats than we are about the range of possible incomes for a single American democrat, whose income could stray far from the mean democrat income. This <em>unmodeled variation</em>, or variation between data points that is not fully captured by bootstrapping, deserves much consideration when dealing with data.</p></li>
<li><p><em>Unknown unknowns</em> are an especially unavoidable source of uncertainty. The world is changing, and people 50 years from now might act differently and have vastly different lifestyles and characteristics; in the case of the <code>trains</code> dataset, it wouldn’t be unreasonable to expect completely different combinations of income and party affiliation. That would render our mean income, median ratio, and prediction intervals for both those measures useless.</p></li>
</ol>
</div>
</div>
<div id="two-parameter-models-which-require-the-bootstrap" class="section level2">
<h2>
<span class="header-section-number">8.7</span> Two parameter models which require the bootstrap</h2>
</div>
<div id="prediction-1" class="section level2">
<h2>
<span class="header-section-number">8.8</span> Prediction</h2>
<!-- How do we connect this to the probability chapter? I am still thinking about this. Basic idea is that, what would we estimate would happen with a new experiment, which might include one or 10 or 1,000 new people? Just like coin-tossing from chapter 5. We need to make this connection very explicit. Read through chapter 5 and discuss.  Posterior distribution, given the data we have, of an unknown parameter.  -->
<!-- Should we make an explicit connection to the probability chapter by adding another dimension to that work? We have two coins, each with their own p. Build the joint distribution for them, with one on the x-axis and one on the y-axis. You need a near graphic for each value of the H number of heads total that you get from flipping them each N times. Then, you run the experiment, and you select the correct graphic. That shows you the best guess joint distribution. This is confusing!  -->
<!-- Do we want to play the prediction game? If so, how? -->
<p>We will introduce a new function here, <code>predict()</code>, which takes in a model as input and, given a specified parameter, will predict the value and confidence intervals of any given data point:</p>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb711-1"><a href="two-parameters.html#cb711-1"></a>trains.lm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> trains, income <span class="op">~</span><span class="st"> </span>party)</span>
<span id="cb711-2"><a href="two-parameters.html#cb711-2"></a>newdata &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">party =</span> <span class="kw">c</span>(<span class="st">"Republican"</span>, <span class="st">"Democrat"</span>))</span>
<span id="cb711-3"><a href="two-parameters.html#cb711-3"></a></span>
<span id="cb711-4"><a href="two-parameters.html#cb711-4"></a><span class="kw">predict</span>(trains.lm, newdata, <span class="dt">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div>
<pre><code>##      fit    lwr    upr
## 1 167368  17113 317624
## 2 136755 -10456 283967</code></pre>
<p>Note that for both Democrats and Republicans, the prediction interval is significantly wider than the confidence interval. This discrepancy illustrates the <em>unmodeled variation</em> of the dataset: while the mean values, as indicated by the “fit” column, are still the best guess you can make for any given subject, we are less confident in the value range of that individual subject than we are of the value range of the mean. <em>The unmodeled variation widens the prediction intervals relative to the confidence intervals.</em></p>
<p>Recall our discussion regarding the wider confidence intervals for Republican subjects than Democrat subjects (<em>would like to attach a link here that takes reader up to that part of the chapter</em>). Although the Republican and Democrat average incomes had vastly different confidence intervals — the Republican convidence intervals were much wider — they have very similar prediction intervals. Although the <em>parameter uncertainty</em> of these two parameters were very different, the <em>unmodeled variation</em> for both parameters was roughly the same. Even though the data points were equally spread out for both Democrat and Republican income, were were able to more confidently pinpoint a true value for democrat income because we had more data to work with.</p>
<p>In many cases, the most important use of a model is for prediction. We use them to make predictions about data which we have not yet seen.</p>
<p>Recall our earlier conversation regarding the difference between confidence intervals. An argument could be made that, taking individual variation into account, prediction intervals would be more accurate indicators of uncertainty than confidence intervals. We can construct the above table using prediction intervals instead, generated using the <code>predict()</code> function:</p>
<div class="sourceCode" id="cb713"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb713-1"><a href="two-parameters.html#cb713-1"></a><span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment) <span class="op">%&gt;%</span></span>
<span id="cb713-2"><a href="two-parameters.html#cb713-2"></a><span class="kw">predict</span>(<span class="kw">tibble</span>(<span class="dt">treatment =</span> <span class="kw">c</span>(<span class="st">"Treated"</span>, <span class="st">"Control"</span>)), </span>
<span id="cb713-3"><a href="two-parameters.html#cb713-3"></a>        <span class="dt">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div>
<pre><code>##    fit lwr upr
## 1 10.0 4.4  16
## 2  8.5 2.9  14</code></pre>
<p>And we can reconstruct the table by filling in the unknowns with the predictions (note that these are unchanged) and their associated levels of uncertainty (which HAVE changed to accomodate for individual variation within the data):</p>
<div class="sourceCode" id="cb715"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb715-1"><a href="two-parameters.html#cb715-1"></a>trains.lm &lt;-<span class="st"> </span><span class="kw">lm</span>(<span class="dt">data =</span> trains, att_end <span class="op">~</span><span class="st"> </span>treatment)</span>
<span id="cb715-2"><a href="two-parameters.html#cb715-2"></a>newdata &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">treatment =</span> <span class="kw">c</span>(<span class="st">"Treated"</span>, <span class="st">"Control"</span>))</span>
<span id="cb715-3"><a href="two-parameters.html#cb715-3"></a></span>
<span id="cb715-4"><a href="two-parameters.html#cb715-4"></a><span class="kw">predict</span>(trains.lm, newdata, <span class="dt">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div>
<pre><code>##    fit lwr upr
## 1 10.0 4.4  16
## 2  8.5 2.9  14</code></pre>
<p>And we can reconstruct the table by filling in the unknowns with the predictions (note that these are unchanged) and their associated levels of uncertainty (which HAVE changed to accomodate for individual variation within the data):</p>
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#gsvkbcpodj .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#gsvkbcpodj .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gsvkbcpodj .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#gsvkbcpodj .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#gsvkbcpodj .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gsvkbcpodj .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#gsvkbcpodj .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#gsvkbcpodj .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#gsvkbcpodj .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#gsvkbcpodj .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#gsvkbcpodj .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#gsvkbcpodj .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#gsvkbcpodj .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#gsvkbcpodj .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#gsvkbcpodj .gt_from_md > :first-child {
  margin-top: 0;
}

#gsvkbcpodj .gt_from_md > :last-child {
  margin-bottom: 0;
}

#gsvkbcpodj .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#gsvkbcpodj .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#gsvkbcpodj .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gsvkbcpodj .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#gsvkbcpodj .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#gsvkbcpodj .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#gsvkbcpodj .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#gsvkbcpodj .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gsvkbcpodj .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#gsvkbcpodj .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#gsvkbcpodj .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#gsvkbcpodj .gt_left {
  text-align: left;
}

#gsvkbcpodj .gt_center {
  text-align: center;
}

#gsvkbcpodj .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#gsvkbcpodj .gt_font_normal {
  font-weight: normal;
}

#gsvkbcpodj .gt_font_bold {
  font-weight: bold;
}

#gsvkbcpodj .gt_font_italic {
  font-style: italic;
}

#gsvkbcpodj .gt_super {
  font-size: 65%;
}

#gsvkbcpodj .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>
<div id="gsvkbcpodj" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;"><table class="gt_table">
<thead class="gt_header">
<tr>
<th colspan="3" class="gt_heading gt_title gt_font_normal" style>Ending Attitudes on Immigration of 7 Random Respondents</th>
    </tr>
<tr>
<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style></th>
    </tr>
</thead>
<thead class="gt_col_headings"><tr>
<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>Subject</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_c(u)$$</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1"><strong>$$Y_t(u)$$</strong></th>
    </tr></thead>
<tbody class="gt_table_body">
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">7</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">6,041</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">10</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">67</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">5</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">40,080</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">11</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">758</td>
      <td class="gt_row gt_center">5</td>
      <td class="gt_row gt_center">10 (4.4-15.6)</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">32</td>
      <td class="gt_row gt_center">8.45 (2.9-14.0)</td>
      <td class="gt_row gt_center">13</td>
    </tr>
<tr>
<td class="gt_row gt_center" style="border-right-width: 1px; border-right-style: solid; border-right-color: #000000;">8,809</td>
      <td class="gt_row gt_center">13</td>
      <td class="gt_row gt_center">10 (4.4-15.6)</td>
    </tr>
</tbody>
</table></div>

</div>
</div></body></html>

<p style="text-align: center;">
<a href="one-parameter.html"><button class="btn btn-default">Previous</button></a>
<a href="n-parameters.html"><button class="btn btn-default">Next</button></a>
</p>
<p class="build-date">Page built: 
2020-07-19
</p>
</div>
</div>



</body>
</html>
